#!/bin/tcsh -f

xattr -d com.apple.TextEncoding *
xattr -d com.apple.TextEncoding */*
xattr -d com.apple.TextEncoding */*/*
xattr -d com.apple.FinderInfo */*.*c* */*.h* */*.gif
xattr -d com.apple.ResourceFork */*.*c* */*.h* */*.gif
xattr -d com.apple.quarantine *
xattr -d com.apple.quarantine */*
xattr -d com.apple.quarantine */*/*


