.TH "/Users/bernard/b20/bsoft/eer Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBitmap\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBitmap\&.h\fP"
.br
.ti -1c
.RI "file \fBDefectMaskingEER\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDefectMaskingEER\&.h\fP"
.br
.ti -1c
.RI "file \fBEerFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEerFile\&.h\fP"
.br
.ti -1c
.RI "file \fBEerFrame\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEerFrame\&.h\fP"
.br
.ti -1c
.RI "file \fBElectronCountedFramesDecompressor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBElectronCountedFramesDecompressor\&.h\fP"
.br
.ti -1c
.RI "file \fBFeiBitStreamer\&.h\fP"
.br
.ti -1c
.RI "file \fBGainDefectCorrect\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGainDefectCorrect\&.h\fP"
.br
.in -1c
