.TH "/Users/bernard/b20/bsoft/tcltk Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbrun_panel\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow\&.cpp\fP"
.br
.RI "A shared object to load Bsoft image files in TCL/Tk\&. "
.ti -1c
.RI "file \fBbshow_boxes\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_ctf\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_diffraction\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_filament\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_file\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_getinfo\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_graph\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_helix\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_histogram\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_image\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_magnify\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_misc\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_model\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_param\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_scales\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_select\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_tomo\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_tools\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_voxels\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbshow_xtal\&.tcl\fP"
.br
.ti -1c
.RI "file \fBbsoft_tcl\&.cpp\fP"
.br
.RI "A stub function to interface the Bsoft library within TCL/Tk\&. "
.ti -1c
.RI "file \fBbtext\&.tcl\fP"
.br
.ti -1c
.RI "file \fBtcltk_bbox\&.cpp\fP"
.br
.RI "A shared object to manage micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bbox\&.h\fP"
.br
.ti -1c
.RI "file \fBtcltk_bfil\&.cpp\fP"
.br
.RI "A shared object to manage micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bfil\&.h\fP"
.br
.ti -1c
.RI "file \fBtcltk_bhelix\&.cpp\fP"
.br
.RI "A shared object to manage micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bhelix\&.h\fP"
.br
.ti -1c
.RI "file \fBtcltk_bimage\&.cpp\fP"
.br
.RI "A shared object to load Bsoft image files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bimage\&.h\fP"
.br
.RI "A shared object to load Bsoft image files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bmarker\&.cpp\fP"
.br
.RI "A shared object to manage markers in micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bmarker\&.h\fP"
.br
.RI "A shared object to manage markers in micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bmg\&.cpp\fP"
.br
.RI "A shared object to manage micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bmg\&.h\fP"
.br
.RI "A shared object to manage boxes in micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bmodel\&.cpp\fP"
.br
.RI "A shared object to load Bsoft model files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bmodel\&.h\fP"
.br
.RI "A shared object to manage model parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bxtal\&.cpp\fP"
.br
.RI "A shared object to manage micrograph parameter files in TCL/Tk\&. "
.ti -1c
.RI "file \fBtcltk_bxtal\&.h\fP"
.br
.in -1c
