.TH "/Users/bernard/b20/bsoft/src/rwmodel Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwmodel Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrwmodel\&.cpp\fP"
.br
.RI "Library routines to read and write atomic model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_bild\&.cpp\fP"
.br
.RI "Library routines to read and write Chimera BILD model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_cmm\&.cpp\fP"
.br
.RI "Library routines to read and write Chimera marker model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_mol\&.cpp\fP"
.br
.RI "Library routines to read and write atomic model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_param\&.cpp\fP"
.br
.RI "Library routines to read and write model dynamics parameters in STAR format\&. "
.ti -1c
.RI "file \fBrwmodel_star\&.cpp\fP"
.br
.RI "Library routines to read and write STAR model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_vega\&.cpp\fP"
.br
.RI "Library routines to read and write Vega model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_xml\&.cpp\fP"
.br
.RI "Library routines to read and write XML model parameters\&. "
.in -1c
