.TH "/Users/bernard/b20/bsoft/src/mol Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/mol Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmol_alpha\&.cpp\fP"
.br
.RI "Functions to make and analyze alpha helices\&. "
.ti -1c
.RI "file \fBmol_bonds\&.cpp\fP"
.br
.RI "Functions for molecular dynamics\&. "
.ti -1c
.RI "file \fBmol_compare\&.cpp\fP"
.br
.RI "Library routines used to compare sets of atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_edit\&.cpp\fP"
.br
.RI "Library routines used for atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_map_energy\&.cpp\fP"
.br
.RI "Functions to calculate estimates of the fitting of molecules to maps\&. "
.ti -1c
.RI "file \fBmol_md\&.cpp\fP"
.br
.RI "Functions for molecular dynamics\&. "
.ti -1c
.RI "file \fBmol_monte\&.cpp\fP"
.br
.RI "Functions for a monte carlo metroplis algorithm to energy minimize molecular positions\&. "
.ti -1c
.RI "file \fBmol_param\&.cpp\fP"
.br
.RI "Functions to extract parameters from coordinate files\&. "
.ti -1c
.RI "file \fBmol_select\&.cpp\fP"
.br
.RI "Library routines to select atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_symmetry\&.cpp\fP"
.br
.RI "Library routines used for symmetry operations on atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_transform\&.cpp\fP"
.br
.RI "Library routines used for atomic coordinate transformations\&. "
.ti -1c
.RI "file \fBmol_util\&.cpp\fP"
.br
.RI "Library routines used for atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_water\&.cpp\fP"
.br
.RI "Generating and managing water\&. "
.ti -1c
.RI "file \fBmolecule_to_map\&.cpp\fP"
.br
.RI "Functions to calculate a 3D map from atomic coordinates\&. "
.ti -1c
.RI "file \fBseq_align\&.cpp\fP"
.br
.RI "Library routines to generate and analyze dot plots\&. "
.ti -1c
.RI "file \fBseq_analysis\&.cpp\fP"
.br
.RI "Analysis of protein sequences\&. "
.ti -1c
.RI "file \fBseq_util\&.cpp\fP"
.br
.RI "Sequence utility functions\&. "
.in -1c
