.TH "/Users/bernard/b20/bsoft/src/mg Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/mg Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmg_align\&.cpp\fP"
.br
.RI "Functions to align micrographs or coordinates from micrographs and apply the resultant transformation\&. "
.ti -1c
.RI "file \fBmg_class\&.cpp\fP"
.br
.RI "Classifies raw single particle images with respect to multiple models\&. "
.ti -1c
.RI "file \fBmg_ctf\&.cpp\fP"
.br
.RI "Functions for CTF (contrast transfer function) processing\&. "
.ti -1c
.RI "file \fBmg_ctf_fit\&.cpp\fP"
.br
.RI "Functions for CTF (contrast transfer function) processing\&. "
.ti -1c
.RI "file \fBmg_ctf_sim\&.cpp\fP"
.br
.RI "Functions to simulate tilted micrographs\&. "
.ti -1c
.RI "file \fBmg_extract\&.cpp\fP"
.br
.RI "Functions to extract particles from micrographs\&. "
.ti -1c
.RI "file \fBmg_hand\&.cpp\fP"
.br
.RI "Functions for comparing projections of two oppositely handed reconstructions to images of tilted specimens\&. "
.ti -1c
.RI "file \fBmg_helix\&.cpp\fP"
.br
.RI "Functions to process helical data\&. "
.ti -1c
.RI "file \fBmg_img_proc\&.cpp\fP"
.br
.RI "Functions for image processing from micrograph structures\&. "
.ti -1c
.RI "file \fBmg_marker\&.cpp\fP"
.br
.RI "Functions for dealing with markers and linkers\&. "
.ti -1c
.RI "file \fBmg_merge\&.cpp\fP"
.br
.RI "Library functions to merge images\&. "
.ti -1c
.RI "file \fBmg_multiple\&.cpp\fP"
.br
.RI "Selection of single particle parameters from multiple files for classification\&. "
.ti -1c
.RI "file \fBmg_multislice\&.cpp\fP"
.br
.RI "Generates and manipulates projects for multislice calculations\&. "
.ti -1c
.RI "file \fBmg_orient\&.cpp\fP"
.br
.RI "Determines orientation angles and x,y origins of single particle images\&. "
.ti -1c
.RI "file \fBmg_particle_select\&.cpp\fP"
.br
.RI "Select particles\&. "
.ti -1c
.RI "file \fBmg_particles\&.cpp\fP"
.br
.RI "Calculates centers of single particle images\&. "
.ti -1c
.RI "file \fBmg_pick\&.cpp\fP"
.br
.RI "Functions for picking single particle images from a micrograph\&. "
.ti -1c
.RI "file \fBmg_processing\&.cpp\fP"
.br
.RI "Functions for micrograph processing\&. "
.ti -1c
.RI "file \fBmg_random\&.cpp\fP"
.br
.RI "Functions for applying some randomization to parameters\&. "
.ti -1c
.RI "file \fBmg_reconstruct\&.cpp\fP"
.br
.RI "Functions for reconstruction\&. "
.ti -1c
.RI "file \fBmg_refine\&.cpp\fP"
.br
.RI "Reciprocal space refinement of orientation parameters of particle images\&. "
.ti -1c
.RI "file \fBmg_select\&.cpp\fP"
.br
.RI "Functions for micrograph processing\&. "
.ti -1c
.RI "file \fBmg_subtomo\&.cpp\fP"
.br
.RI "Functions to find particles (subtomograms) in a tomographic reconstruction\&. "
.ti -1c
.RI "file \fBmg_tomo_rec\&.cpp\fP"
.br
.RI "Functions to do a tomographic reconstruction\&. "
.ti -1c
.RI "file \fBmg_tomo_resol\&.cpp\fP"
.br
.RI "Functions to assess the resoltion of a tomographic tilt series\&. "
.ti -1c
.RI "file \fBmg_tomo_track\&.cpp\fP"
.br
.RI "Functions to track fiducial markers in a tomographic series of images\&. "
.ti -1c
.RI "file \fBmg_tomography\&.cpp\fP"
.br
.RI "Functions to manage tomographic series of images\&. "
.ti -1c
.RI "file \fBmg_xtal\&.cpp\fP"
.br
.RI "Functions to process crystallographic data\&. "
.in -1c
