.TH "/Users/bernard/b20/bsoft/radon Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/radon Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfft_tool\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfft_tool\&.h\fP"
.br
.ti -1c
.RI "file \fBgal_ricoI\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgal_ricoI\&.h\fP"
.br
.ti -1c
.RI "file \fBimg_radon\&.cpp\fP"
.br
.RI "Radon transform functions\&. "
.ti -1c
.RI "file \fBimg_radon\&.h\fP"
.br
.ti -1c
.RI "file \fBkernlut\&.cpp\fP"
.br
.ti -1c
.RI "file \fBkernlut\&.h\fP"
.br
.ti -1c
.RI "file \fBpocs_tool\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpocs_tool\&.h\fP"
.br
.ti -1c
.RI "file \fBproj_tool\&.cpp\fP"
.br
.ti -1c
.RI "file \fBproj_tool\&.h\fP"
.br
.ti -1c
.RI "file \fBradon_util\&.cpp\fP"
.br
.ti -1c
.RI "file \fBradon_util\&.h\fP"
.br
.ti -1c
.RI "file \fBsin_gal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsin_gal\&.h\fP"
.br
.in -1c
