.TH "/Users/bernard/b20/bsoft/src/balpha.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/balpha.cpp \- Program to make and analyze alpha helices\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmolecule\&.h'\fP
.br
\fC#include 'mol_alpha\&.h'\fP
.br
\fC#include 'mol_util\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to make and analyze alpha helices\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20050315 
.PP
Modified: 20050322 
.RE
.PP

.PP
Definition in file \fBbalpha\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 39 of file balpha\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: balpha [options] [input\&.pdb] output\&.pdb",
"----------------------------------------------",
"Creates and manipulates alpha helices\&.",
" ",
"Actions:",
"-create 12               Create an alpha helix of a given length\&.",
"-helix 213,236           Set residues to a helix (all molecules)\&.",
"-find                    Find a helix center and orientation (only for a single helix)\&.",
"-set                     Set a helix to the standard orientation (only for a single helix)\&.",
"-consolidate             Consolidate a set of helices to eliminate redundancy\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file balpha\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
