.TH "Bangletype" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bangletype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBangletype\fP ()"
.br
.ti -1c
.RI "\fBBangletype\fP (string &id1, string &id2, string &id3)"
.br
.ti -1c
.RI "void \fBidentifier\fP (string s, int i)"
.br
.ti -1c
.RI "string & \fBidentifier\fP (int i)"
.br
.ti -1c
.RI "void \fBangle\fP (double d)"
.br
.ti -1c
.RI "double \fBangle\fP ()"
.br
.ti -1c
.RI "void \fBKangle\fP (double d)"
.br
.ti -1c
.RI "double \fBKangle\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 236 of file rwmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bangletype::Bangletype ()\fC [inline]\fP"

.PP
Definition at line 250 of file rwmodel\&.h\&.
.SS "Bangletype::Bangletype (string & id1, string & id2, string & id3)\fC [inline]\fP"

.PP
Definition at line 251 of file rwmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double Bangletype::angle ()\fC [inline]\fP"

.PP
Definition at line 260 of file rwmodel\&.h\&.
.SS "void Bangletype::angle (double d)\fC [inline]\fP"

.PP
Definition at line 259 of file rwmodel\&.h\&.
.SS "double Bangletype::FOM ()\fC [inline]\fP"

.PP
Definition at line 264 of file rwmodel\&.h\&.
.SS "void Bangletype::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 263 of file rwmodel\&.h\&.
.SS "string& Bangletype::identifier (int i)\fC [inline]\fP"

.PP
Definition at line 258 of file rwmodel\&.h\&.
.SS "void Bangletype::identifier (string s, int i)\fC [inline]\fP"

.PP
Definition at line 257 of file rwmodel\&.h\&.
.SS "double Bangletype::Kangle ()\fC [inline]\fP"

.PP
Definition at line 262 of file rwmodel\&.h\&.
.SS "void Bangletype::Kangle (double d)\fC [inline]\fP"

.PP
Definition at line 261 of file rwmodel\&.h\&.
.SS "long Bangletype::select ()\fC [inline]\fP"

.PP
Definition at line 266 of file rwmodel\&.h\&.
.SS "void Bangletype::select (long i)\fC [inline]\fP"

.PP
Definition at line 265 of file rwmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
