.TH "/Users/bernard/b20/bsoft/src/bar.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bar.cpp \- Program to do simple arithmetic on images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXOP\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to do simple arithmetic on images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20040727 
.PP
Modified: 20110730 
.RE
.PP

.PP
Definition in file \fBbar\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXOP   16"

.PP
Definition at line 17 of file bar\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 39 of file bar\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bar [options] input\&.img output\&.img",
"-----------------------------------------",
"Does simple arithmetic on images\&.",
"Operations are done in the order given on the command line\&.",
" ",
"Actions:",
"-add -5\&.78               Add a constant to each voxel\&.",
"-multiply 6\&.123          Multiply each voxel with a constant\&.",
"-power 0\&.75              Raise to the power (must be positive)\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bar\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
