.TH "Batom" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Batom
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmolecule\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBatom\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "char \fBel\fP [4]"
.br
.ti -1c
.RI "char \fBtype\fP [8]"
.br
.ti -1c
.RI "int \fBtnum\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBcoord\fP"
.br
.ti -1c
.RI "double \fBq\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBmass\fP"
.br
.ti -1c
.RI "double \fBchrg\fP"
.br
.ti -1c
.RI "int \fBsel\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBvel\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file rwmolecule\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Batom::b"

.PP
Definition at line 31 of file rwmolecule\&.h\&.
.SS "double Batom::chrg"

.PP
Definition at line 33 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Batom::coord"

.PP
Definition at line 30 of file rwmolecule\&.h\&.
.SS "char Batom::el[4]"

.PP
Definition at line 27 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Batom::F"

.PP
Definition at line 36 of file rwmolecule\&.h\&.
.SS "double Batom::mass"

.PP
Definition at line 32 of file rwmolecule\&.h\&.
.SS "\fBBatom\fP* Batom::next"

.PP
Definition at line 25 of file rwmolecule\&.h\&.
.SS "int Batom::num"

.PP
Definition at line 26 of file rwmolecule\&.h\&.
.SS "double Batom::q"

.PP
Definition at line 31 of file rwmolecule\&.h\&.
.SS "int Batom::sel"

.PP
Definition at line 34 of file rwmolecule\&.h\&.
.SS "int Batom::tnum"

.PP
Definition at line 29 of file rwmolecule\&.h\&.
.SS "char Batom::type[8]"

.PP
Definition at line 28 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Batom::vel"

.PP
Definition at line 35 of file rwmolecule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
