.TH "Batomtype" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Batomtype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwatomprop\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBatomtype\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "char \fBel\fP [4]"
.br
.ti -1c
.RI "char \fBname\fP [8]"
.br
.ti -1c
.RI "float \fBmass\fP"
.br
.ti -1c
.RI "float \fBoxid\fP"
.br
.ti -1c
.RI "float \fBbond\fP"
.br
.ti -1c
.RI "float \fBvdw\fP"
.br
.ti -1c
.RI "unsigned char \fBcolor\fP [4]"
.br
.ti -1c
.RI "float \fBsfa\fP [5]"
.br
.ti -1c
.RI "float \fBsfb\fP [5]"
.br
.ti -1c
.RI "float \fBsfc\fP"
.br
.ti -1c
.RI "long \fBnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file rwatomprop\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Batomtype::bond"

.PP
Definition at line 26 of file rwatomprop\&.h\&.
.SS "unsigned char Batomtype::color[4]"

.PP
Definition at line 28 of file rwatomprop\&.h\&.
.SS "char Batomtype::el[4]"

.PP
Definition at line 22 of file rwatomprop\&.h\&.
.SS "float Batomtype::mass"

.PP
Definition at line 24 of file rwatomprop\&.h\&.
.SS "char Batomtype::name[8]"

.PP
Definition at line 23 of file rwatomprop\&.h\&.
.SS "\fBBatomtype\fP* Batomtype::next"

.PP
Definition at line 20 of file rwatomprop\&.h\&.
.SS "long Batomtype::number"

.PP
Definition at line 32 of file rwatomprop\&.h\&.
.SS "float Batomtype::oxid"

.PP
Definition at line 25 of file rwatomprop\&.h\&.
.SS "float Batomtype::sfa[5]"

.PP
Definition at line 29 of file rwatomprop\&.h\&.
.SS "float Batomtype::sfb[5]"

.PP
Definition at line 30 of file rwatomprop\&.h\&.
.SS "float Batomtype::sfc"

.PP
Definition at line 31 of file rwatomprop\&.h\&.
.SS "float Batomtype::vdw"

.PP
Definition at line 27 of file rwatomprop\&.h\&.
.SS "int Batomtype::z"

.PP
Definition at line 21 of file rwatomprop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
