.TH "/Users/bernard/b20/bsoft/src/bbif.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bbif.cpp \- Program to denoise images by bilateral filtering\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to denoise images by bilateral filtering\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann and Giovanni Cardone 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20070301 
.PP
Modified: 20150802 
.RE
.PP

.PP
Definition in file \fBbbif\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 42 of file bbif\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bbif [options] input\&.img output\&.img",
"------------------------------------------",
"Denoises by bilateral filtering\&.",
" ",
"Actions:",
"-rescale -0\&.1,5\&.2        Rescale data to average and standard deviation after filtering\&.",
"-kernel gaussian         Kernel used for for the intensity space:",
"                           1=gaussian (default)",
"                           2=lorentz ",
"                           3=tukey",
"-size 5                  kernel size (odd number, default 6*spacesigma)",
"-spacesigma 1\&.5          Standard deviation of spatial filter (pixels, default 1)\&.",
"-rangesigma 23\&.8         Standard deviation of range filter (default image standard deviation)\&.",
" ",
"Parameters:",
"-verbose 1               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (A/pixel; default from input file; a single value can be given)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 18 of file bbif\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
