.TH "Bbondtype" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bbondtype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBbondtype\fP * \fBnext\fP"
.br
.ti -1c
.RI "char \fBtype1\fP [8]"
.br
.ti -1c
.RI "char \fBtype2\fP [8]"
.br
.ti -1c
.RI "float \fBcovlength\fP"
.br
.ti -1c
.RI "float \fBvdwdist\fP"
.br
.ti -1c
.RI "long \fBnumber\fP"
.br
.ti -1c
.RI "float \fBstd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file rwmd\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Bbondtype::covlength"

.PP
Definition at line 25 of file rwmd\&.h\&.
.SS "\fBBbondtype\fP* Bbondtype::next"

.PP
Definition at line 22 of file rwmd\&.h\&.
.SS "long Bbondtype::number"

.PP
Definition at line 27 of file rwmd\&.h\&.
.SS "float Bbondtype::std"

.PP
Definition at line 28 of file rwmd\&.h\&.
.SS "char Bbondtype::type1[8]"

.PP
Definition at line 23 of file rwmd\&.h\&.
.SS "char Bbondtype::type2[8]"

.PP
Definition at line 24 of file rwmd\&.h\&.
.SS "float Bbondtype::vdwdist"

.PP
Definition at line 26 of file rwmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
