.TH "Bbond" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bbond
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmolecule\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBbond\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBatom\fP * \fBatom1\fP"
.br
.ti -1c
.RI "\fBBatom\fP * \fBatom2\fP"
.br
.ti -1c
.RI "double \fBl\fP"
.br
.ti -1c
.RI "double \fBk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 134 of file rwmolecule\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBatom\fP* Bbond::atom1"

.PP
Definition at line 136 of file rwmolecule\&.h\&.
.SS "\fBBatom\fP* Bbond::atom2"

.PP
Definition at line 137 of file rwmolecule\&.h\&.
.SS "double Bbond::k"

.PP
Definition at line 139 of file rwmolecule\&.h\&.
.SS "double Bbond::l"

.PP
Definition at line 138 of file rwmolecule\&.h\&.
.SS "\fBBbond\fP* Bbond::next"

.PP
Definition at line 135 of file rwmolecule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
