.TH "Bcolumn" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bcolumn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bplot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBcolumn\fP ()"
.br
.ti -1c
.RI "\fBBcolumn\fP (\fBBstring\fP &s)"
.br
.ti -1c
.RI "\fBBcolumn\fP (long i, \fBBstring\fP &s)"
.br
.ti -1c
.RI "long \fBnumber\fP ()"
.br
.ti -1c
.RI "void \fBnumber\fP (long i)"
.br
.ti -1c
.RI "\fBBstring\fP & \fBlabel\fP ()"
.br
.ti -1c
.RI "void \fBlabel\fP (const \fBBstring\fP &s)"
.br
.ti -1c
.RI "void \fBlabel\fP (const char *s)"
.br
.ti -1c
.RI "long \fBtype\fP ()"
.br
.ti -1c
.RI "void \fBtype\fP (long v)"
.br
.ti -1c
.RI "long \fBaxis\fP ()"
.br
.ti -1c
.RI "void \fBaxis\fP (long v)"
.br
.ti -1c
.RI "double \fBmin\fP ()"
.br
.ti -1c
.RI "void \fBmin\fP (double v)"
.br
.ti -1c
.RI "double \fBmax\fP ()"
.br
.ti -1c
.RI "void \fBmax\fP (double v)"
.br
.ti -1c
.RI "double \fBelement_size\fP ()"
.br
.ti -1c
.RI "void \fBelement_size\fP (double v)"
.br
.ti -1c
.RI "double * \fBcolor\fP ()"
.br
.ti -1c
.RI "void \fBcolor\fP (double r, double g, double b)"
.br
.ti -1c
.RI "double \fBred\fP ()"
.br
.ti -1c
.RI "double \fBgreen\fP ()"
.br
.ti -1c
.RI "double \fBblue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file Bplot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bcolumn::Bcolumn ()\fC [inline]\fP"

.PP
Definition at line 58 of file Bplot\&.h\&.
.SS "Bcolumn::Bcolumn (\fBBstring\fP & s)\fC [inline]\fP"

.PP
Definition at line 59 of file Bplot\&.h\&.
.SS "Bcolumn::Bcolumn (long i, \fBBstring\fP & s)\fC [inline]\fP"

.PP
Definition at line 60 of file Bplot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "long Bcolumn::axis ()\fC [inline]\fP"

.PP
Definition at line 68 of file Bplot\&.h\&.
.SS "void Bcolumn::axis (long v)\fC [inline]\fP"

.PP
Definition at line 69 of file Bplot\&.h\&.
.SS "double Bcolumn::blue ()\fC [inline]\fP"

.PP
Definition at line 80 of file Bplot\&.h\&.
.SS "double* Bcolumn::color ()\fC [inline]\fP"

.PP
Definition at line 76 of file Bplot\&.h\&.
.SS "void Bcolumn::color (double r, double g, double b)\fC [inline]\fP"

.PP
Definition at line 77 of file Bplot\&.h\&.
.SS "double Bcolumn::element_size ()\fC [inline]\fP"

.PP
Definition at line 74 of file Bplot\&.h\&.
.SS "void Bcolumn::element_size (double v)\fC [inline]\fP"

.PP
Definition at line 75 of file Bplot\&.h\&.
.SS "double Bcolumn::green ()\fC [inline]\fP"

.PP
Definition at line 79 of file Bplot\&.h\&.
.SS "\fBBstring\fP& Bcolumn::label ()\fC [inline]\fP"

.PP
Definition at line 63 of file Bplot\&.h\&.
.SS "void Bcolumn::label (const \fBBstring\fP & s)\fC [inline]\fP"

.PP
Definition at line 64 of file Bplot\&.h\&.
.SS "void Bcolumn::label (const char * s)\fC [inline]\fP"

.PP
Definition at line 65 of file Bplot\&.h\&.
.SS "double Bcolumn::max ()\fC [inline]\fP"

.PP
Definition at line 72 of file Bplot\&.h\&.
.SS "void Bcolumn::max (double v)\fC [inline]\fP"

.PP
Definition at line 73 of file Bplot\&.h\&.
.SS "double Bcolumn::min ()\fC [inline]\fP"

.PP
Definition at line 70 of file Bplot\&.h\&.
.SS "void Bcolumn::min (double v)\fC [inline]\fP"

.PP
Definition at line 71 of file Bplot\&.h\&.
.SS "long Bcolumn::number ()\fC [inline]\fP"

.PP
Definition at line 61 of file Bplot\&.h\&.
.SS "void Bcolumn::number (long i)\fC [inline]\fP"

.PP
Definition at line 62 of file Bplot\&.h\&.
.SS "double Bcolumn::red ()\fC [inline]\fP"

.PP
Definition at line 78 of file Bplot\&.h\&.
.SS "long Bcolumn::type ()\fC [inline]\fP"

.PP
Definition at line 66 of file Bplot\&.h\&.
.SS "void Bcolumn::type (long v)\fC [inline]\fP"

.PP
Definition at line 67 of file Bplot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
