.TH "Bcomponent" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bcomponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBcomponent\fP ()"
.br
.ti -1c
.RI "\fBBcomponent\fP (string s)"
.br
.ti -1c
.RI "\fBBcomponent\fP (long i)"
.br
.ti -1c
.RI "\fBBcomponent\fP (\fBBcomponent\fP *c)"
.br
.ti -1c
.RI "void \fBidentifier\fP (string s)"
.br
.ti -1c
.RI "void \fBidentifier\fP (\fBBstring\fP s)"
.br
.ti -1c
.RI "string & \fBidentifier\fP ()"
.br
.ti -1c
.RI "void \fBtype\fP (\fBBcomptype\fP *t)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBtype\fP ()"
.br
.ti -1c
.RI "void \fBlocation\fP (\fBVector3\fP< double > v)"
.br
.ti -1c
.RI "\fBVector3\fP< float > & \fBlocation\fP ()"
.br
.ti -1c
.RI "void \fBshift\fP (\fBVector3\fP< double > v)"
.br
.ti -1c
.RI "void \fBscale\fP (\fBVector3\fP< double > v)"
.br
.ti -1c
.RI "void \fBscale\fP (double d)"
.br
.ti -1c
.RI "void \fBview\fP (\fBView2\fP< float > v)"
.br
.ti -1c
.RI "void \fBview\fP (\fBVector3\fP< float > v)"
.br
.ti -1c
.RI "\fBView2\fP< float > & \fBview\fP ()"
.br
.ti -1c
.RI "void \fBforce\fP (\fBVector3\fP< double > v)"
.br
.ti -1c
.RI "\fBVector3\fP< float > & \fBforce\fP ()"
.br
.ti -1c
.RI "void \fBvelocity\fP (\fBVector3\fP< double > v)"
.br
.ti -1c
.RI "\fBVector3\fP< float > & \fBvelocity\fP ()"
.br
.ti -1c
.RI "void \fBradius\fP (double r)"
.br
.ti -1c
.RI "double \fBradius\fP ()"
.br
.ti -1c
.RI "void \fBcolor\fP (\fBRGBA\fP< float > c)"
.br
.ti -1c
.RI "\fBRGBA\fP< float > & \fBcolor\fP ()"
.br
.ti -1c
.RI "void \fBdensity\fP (double d)"
.br
.ti -1c
.RI "double \fBdensity\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.ti -1c
.RI "long \fBselect_increment\fP ()"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBadd\fP (string s)"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBadd\fP (long i)"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBadd\fP (\fBBcomponent\fP *c)"
.br
.ti -1c
.RI "void \fBadd_link\fP (\fBBcomponent\fP *comp)"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBfind\fP (string s)"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBfind_or_add\fP (string s)"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBfind_closest\fP (\fBVector3\fP< double > coor)"
.br
.ti -1c
.RI "bool \fBfind_link_exists\fP (\fBBcomponent\fP *c)"
.br
.ti -1c
.RI "void \fBfind_and_add_links\fP (string s1, string s2)"
.br
.ti -1c
.RI "long \fBcount\fP ()"
.br
.ti -1c
.RI "long \fBcount_selected\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBnormal\fP ()"
.br
.ti -1c
.RI "void \fBcalculate_normals\fP ()"
.br
.ti -1c
.RI "bool \fBcheck\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBcomponent\fP * \fBnext\fP"
.br
.ti -1c
.RI "vector< \fBBcomponent\fP * > \fBlink\fP"
.br
.ti -1c
.RI "vector< \fBBcomponent\fP * > \fBneighbor\fP"
.br
.ti -1c
.RI "vector< int > \fBflag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 284 of file rwmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bcomponent::Bcomponent ()\fC [inline]\fP"

.PP
Definition at line 314 of file rwmodel\&.h\&.
.SS "Bcomponent::Bcomponent (string s)\fC [inline]\fP"

.PP
Definition at line 315 of file rwmodel\&.h\&.
.SS "Bcomponent::Bcomponent (long i)\fC [inline]\fP"

.PP
Definition at line 316 of file rwmodel\&.h\&.
.SS "Bcomponent::Bcomponent (\fBBcomponent\fP * c)\fC [inline]\fP"

.PP
Definition at line 317 of file rwmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBcomponent\fP* Bcomponent::add (\fBBcomponent\fP * c)\fC [inline]\fP"

.PP
Definition at line 369 of file rwmodel\&.h\&.
.SS "\fBBcomponent\fP* Bcomponent::add (long i)\fC [inline]\fP"

.PP
Definition at line 364 of file rwmodel\&.h\&.
.SS "\fBBcomponent\fP* Bcomponent::add (string s)\fC [inline]\fP"

.PP
Definition at line 359 of file rwmodel\&.h\&.
.SS "void Bcomponent::add_link (\fBBcomponent\fP * comp)\fC [inline]\fP"

.PP
Definition at line 374 of file rwmodel\&.h\&.
.SS "void Bcomponent::calculate_normals ()\fC [inline]\fP"

.PP
Definition at line 439 of file rwmodel\&.h\&.
.SS "bool Bcomponent::check ()\fC [inline]\fP"

.PP
Definition at line 442 of file rwmodel\&.h\&.
.SS "\fBRGBA\fP<float>& Bcomponent::color ()\fC [inline]\fP"

.PP
Definition at line 351 of file rwmodel\&.h\&.
.SS "void Bcomponent::color (\fBRGBA\fP< float > c)\fC [inline]\fP"

.PP
Definition at line 350 of file rwmodel\&.h\&.
.SS "long Bcomponent::count ()\fC [inline]\fP"

.PP
Definition at line 414 of file rwmodel\&.h\&.
.SS "long Bcomponent::count_selected ()\fC [inline]\fP"

.PP
Definition at line 419 of file rwmodel\&.h\&.
.SS "double Bcomponent::density ()\fC [inline]\fP"

.PP
Definition at line 353 of file rwmodel\&.h\&.
.SS "void Bcomponent::density (double d)\fC [inline]\fP"

.PP
Definition at line 352 of file rwmodel\&.h\&.
.SS "\fBBcomponent\fP* Bcomponent::find (string s)\fC [inline]\fP"

.PP
Definition at line 378 of file rwmodel\&.h\&.
.SS "void Bcomponent::find_and_add_links (string s1, string s2)\fC [inline]\fP"

.PP
Definition at line 406 of file rwmodel\&.h\&.
.SS "\fBBcomponent\fP* Bcomponent::find_closest (\fBVector3\fP< double > coor)\fC [inline]\fP"

.PP
Definition at line 388 of file rwmodel\&.h\&.
.SS "bool Bcomponent::find_link_exists (\fBBcomponent\fP * c)\fC [inline]\fP"

.PP
Definition at line 401 of file rwmodel\&.h\&.
.SS "\fBBcomponent\fP* Bcomponent::find_or_add (string s)\fC [inline]\fP"

.PP
Definition at line 383 of file rwmodel\&.h\&.
.SS "double Bcomponent::FOM ()\fC [inline]\fP"

.PP
Definition at line 355 of file rwmodel\&.h\&.
.SS "void Bcomponent::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 354 of file rwmodel\&.h\&.
.SS "\fBVector3\fP<float>& Bcomponent::force ()\fC [inline]\fP"

.PP
Definition at line 345 of file rwmodel\&.h\&.
.SS "void Bcomponent::force (\fBVector3\fP< double > v)\fC [inline]\fP"

.PP
Definition at line 344 of file rwmodel\&.h\&.
.SS "string& Bcomponent::identifier ()\fC [inline]\fP"

.PP
Definition at line 333 of file rwmodel\&.h\&.
.SS "void Bcomponent::identifier (\fBBstring\fP s)\fC [inline]\fP"

.PP
Definition at line 332 of file rwmodel\&.h\&.
.SS "void Bcomponent::identifier (string s)\fC [inline]\fP"

.PP
Definition at line 331 of file rwmodel\&.h\&.
.SS "\fBVector3\fP<float>& Bcomponent::location ()\fC [inline]\fP"

.PP
Definition at line 337 of file rwmodel\&.h\&.
.SS "void Bcomponent::location (\fBVector3\fP< double > v)\fC [inline]\fP"

.PP
Definition at line 336 of file rwmodel\&.h\&.
.SS "\fBVector3\fP<double> Bcomponent::normal ()\fC [inline]\fP"

.PP
Definition at line 424 of file rwmodel\&.h\&.
.SS "double Bcomponent::radius ()\fC [inline]\fP"

.PP
Definition at line 349 of file rwmodel\&.h\&.
.SS "void Bcomponent::radius (double r)\fC [inline]\fP"

.PP
Definition at line 348 of file rwmodel\&.h\&.
.SS "void Bcomponent::scale (double d)\fC [inline]\fP"

.PP
Definition at line 340 of file rwmodel\&.h\&.
.SS "void Bcomponent::scale (\fBVector3\fP< double > v)\fC [inline]\fP"

.PP
Definition at line 339 of file rwmodel\&.h\&.
.SS "long Bcomponent::select ()\fC [inline]\fP"

.PP
Definition at line 357 of file rwmodel\&.h\&.
.SS "void Bcomponent::select (long i)\fC [inline]\fP"

.PP
Definition at line 356 of file rwmodel\&.h\&.
.SS "long Bcomponent::select_increment ()\fC [inline]\fP"

.PP
Definition at line 358 of file rwmodel\&.h\&.
.SS "void Bcomponent::shift (\fBVector3\fP< double > v)\fC [inline]\fP"

.PP
Definition at line 338 of file rwmodel\&.h\&.
.SS "\fBBcomptype\fP* Bcomponent::type ()\fC [inline]\fP"

.PP
Definition at line 335 of file rwmodel\&.h\&.
.SS "void Bcomponent::type (\fBBcomptype\fP * t)\fC [inline]\fP"

.PP
Definition at line 334 of file rwmodel\&.h\&.
.SS "\fBVector3\fP<float>& Bcomponent::velocity ()\fC [inline]\fP"

.PP
Definition at line 347 of file rwmodel\&.h\&.
.SS "void Bcomponent::velocity (\fBVector3\fP< double > v)\fC [inline]\fP"

.PP
Definition at line 346 of file rwmodel\&.h\&.
.SS "\fBView2\fP<float>& Bcomponent::view ()\fC [inline]\fP"

.PP
Definition at line 343 of file rwmodel\&.h\&.
.SS "void Bcomponent::view (\fBVector3\fP< float > v)\fC [inline]\fP"

.PP
Definition at line 342 of file rwmodel\&.h\&.
.SS "void Bcomponent::view (\fBView2\fP< float > v)\fC [inline]\fP"

.PP
Definition at line 341 of file rwmodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<int> Bcomponent::flag"

.PP
Definition at line 313 of file rwmodel\&.h\&.
.SS "vector<\fBBcomponent\fP*> Bcomponent::link"

.PP
Definition at line 311 of file rwmodel\&.h\&.
.SS "vector<\fBBcomponent\fP*> Bcomponent::neighbor"

.PP
Definition at line 312 of file rwmodel\&.h\&.
.SS "\fBBcomponent\fP* Bcomponent::next"

.PP
Definition at line 297 of file rwmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
