.TH "/Users/bernard/b20/bsoft/src/bcrystal.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bcrystal.cpp \- Calculates coordinates for multiple unit cells\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmolecule\&.h'\fP
.br
\fC#include 'mol_symmetry\&.h'\fP
.br
\fC#include 'mol_transform\&.h'\fP
.br
\fC#include 'mol_util\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Calculates coordinates for multiple unit cells\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20001015 
.PP
Modified: 20080225 
.RE
.PP

.PP
Definition in file \fBbcrystal\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 43 of file bcrystal\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bcrystal [options] in\&.pdb out\&.pdb",
"----------------------------------------",
"Calculates coordinates for multiple unit cells\&.",
" ",
"Actions:",
"-translate 0,-50,22      Translate (angstrom)",
"-cells 2,5,3             Number of unit cells in each lattice direction",
" ",
"Parameters:",
"-verbose 7               Verbose output",
"-rename D                Rename molecules from the given letter\&.",
"-symmetry 1              Space group",
"-unitcell 50,50,50,90,90,90 Unit cell parameters (angstrom & degrees)",
" ",
"Input:",
"-parameters parm\&.star    Atomic properties parameter file (default atom_prop\&.star)",
" ",
NULL
}
.fi
.PP
Definition at line 21 of file bcrystal\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
