.TH "/Users/bernard/b20/bsoft/src/bdelta.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bdelta.cpp \- Generating a deltagraph with minimal input parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br
\fC#include 'model_poly\&.h'\fP
.br
\fC#include 'model_poly_delta\&.h'\fP
.br
\fC#include 'model_transform\&.h'\fP
.br
\fC#include 'model_links\&.h'\fP
.br
\fC#include 'model_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generating a deltagraph with minimal input parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20080103 
.PP
Modified: 20180327 
.RE
.PP

.PP
Definition in file \fBbdelta\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 54 of file bdelta\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bdelta [options] in\&.star [in2\&.star \&.\&.\&.]",
"----------------------------------------------",
"Generates and analyzes deltagraphs\&.",
"The creation options are mutually exclusive\&.",
" ",
"Actions:",
"-pentagonal              Create a pentagonal deltagraph\&.",
"-hexagonal               Create a hexagonal deltagraph\&.",
"-tube 8,3                Create a tubular deltagraph with the given lattice parameters\&.",
"-caps 2                  Add 1 or 2 caps\&.",
"-dual                    Calculate the dual of a polyhedron\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-componentradius 0\&.5     Component display radius\&.",
"-linkradius 0\&.5          Link display radius\&.",
"-linklength 150          Link length (default 1)\&.",
"-radius 3                Radius in integer units (default 1)\&.",
"-height 5                Height in integer units (default 1)\&.",
" ",
"Input:",
"-parameters param\&.star   Input parameter file\&.",
" ",
"Output:",
"-output file\&.star        Output model parameter file\&.",
" ",
NULL
}
.fi
.PP
Definition at line 23 of file bdelta\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
