.TH "/Users/bernard/b20/bsoft/src/bedge.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bedge.cpp \- A program to float an image in a uniform background\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A program to float an image in a uniform background\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19980520 
.PP
Modified: 20150717 
.RE
.PP

.PP
Definition in file \fBbedge\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 40 of file bedge\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bedge [options] infile\&.mrc outfile\&.mrc",
"---------------------------------------------",
"Smooths the edge of an image to a uniform background\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-truncate -0\&.5,1\&.2       Truncate data to minimum and maximum before edge operation\&.",
"-size 4000,4000,10       Size of region inside edge (default 90% of image size)\&.",

"-start 2500,1500,5       Start of edge (default 5% from image origin)\&.",

"-width 8                 Gaussian width (default 0\&.1, sharp edge, <0 inverts selection)\&.",

"-shape oval              Edge shape: rectangular (default), oval, cylindrical\&.",
"-fill 150                Fill value for background: average (default), background, or value\&.",
" ",
NULL
}
.fi
.PP
Definition at line 18 of file bedge\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
