.TH "Bfield" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bfield
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBfield\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBfield\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBid\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBorigin\fP"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBmatrix\fP"
.br
.ti -1c
.RI "long \fBselect\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "\fBBmicrograph\fP * \fBmg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 385 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bfield::Bfield ()\fC [inline]\fP"

.PP
Definition at line 403 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Bfield::fom"

.PP
Definition at line 401 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bfield::id"

.PP
Definition at line 397 of file mg_processing\&.h\&.
.SS "\fBMatrix3\fP Bfield::matrix"

.PP
Definition at line 399 of file mg_processing\&.h\&.
.SS "\fBBmicrograph\fP* Bfield::mg"

.PP
Definition at line 402 of file mg_processing\&.h\&.
.SS "\fBBfield\fP* Bfield::next"

.PP
Definition at line 396 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bfield::origin"

.PP
Definition at line 398 of file mg_processing\&.h\&.
.SS "long Bfield::select"

.PP
Definition at line 400 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
