.TH "Bfilament" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bfilament
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBfilament\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBfilament\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBffil\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBBfilnode\fP * \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 165 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bfilament::Bfilament ()\fC [inline]\fP"

.PP
Definition at line 178 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBstring\fP Bfilament::ffil"

.PP
Definition at line 175 of file mg_processing\&.h\&.
.SS "int Bfilament::id"

.PP
Definition at line 176 of file mg_processing\&.h\&.
.SS "\fBBfilament\fP* Bfilament::next"

.PP
Definition at line 174 of file mg_processing\&.h\&.
.SS "\fBBfilnode\fP* Bfilament::node"

.PP
Definition at line 177 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
