.TH "/Users/bernard/b20/bsoft/src/bfind.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bfind.cpp \- Searches orientation space for the best fit of a 3D map to a template\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_particle_select\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'symmetry\&.h'\fP
.br
\fC#include 'ps_views\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "vector< \fBBimage\fP * > \fBsetup_images\fP (\fBBstring\fP &map_file, \fBBstring\fP &template_file, \fBBstring\fP &rs_mask, \fBBstring\fP &fs_mask, int read_img_num, \fBVector3\fP< long > &bin, \fBVector3\fP< double > sam, int set_origin, \fBVector3\fP< double > &origin, \fBVector3\fP< double > &part_ori)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Searches orientation space for the best fit of a 3D map to a template\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20021027 
.PP
Modified: 20200401 
.RE
.PP

.PP
Definition in file \fBbfind\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 103 of file bfind\&.cpp\&.
.SS "vector< \fBBimage\fP * > setup_images (\fBBstring\fP & map_file, \fBBstring\fP & template_file, \fBBstring\fP & rs_mask, \fBBstring\fP & fs_mask, int read_img_num, \fBVector3\fP< long > & bin, \fBVector3\fP< double > sam, int set_origin, \fBVector3\fP< double > & origin, \fBVector3\fP< double > & part_ori)"

.PP
Definition at line 582 of file bfind\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 34 of file bfind\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
