.TH "/Users/bernard/b20/bsoft/src/bgradient.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bgradient.cpp \- Calculating image gradients\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBimage\fP * \fBimg_aniso_average\fP (\fBBimage\fP *p, long iter, long ksize, double w)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Calculating image gradients\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20201224 
.PP
Modified: 20210302 
.RE
.PP

.PP
Definition in file \fBbgradient\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBimage\fP * img_aniso_average (\fBBimage\fP * p, long iter, long ksize, double w)"

.PP
Definition at line 134 of file bgradient\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 42 of file bgradient\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bgradient [options] input\&.img output\&.img",
"-----------------------------------------------",
"Calculates image gradients\&.",
" ",
"Actions:",
"-gaussian 2\&.4,5\&.1,20\&.4   Anisotropic gaussian filter (one value sets all)\&.",
"-gradient 3x3            Gradient type: cd, 3x3, freq\&.",
"-magnitude               Convert gradient vectors to lengths\&.",
"-anisotropic 10,0\&.5      Anisotropic gradient smoothing: iterations and weight\&.",
" ",
"Parameters:",
"-verbose 1               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (A/pixel; a single value can be given)\&.",
"-origin 110,50,44        Origin for the mask (default from input image)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 21 of file bgradient\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
