.TH "/Users/bernard/b20/bsoft/src/bhisto.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bhisto.cpp \- Image histograms\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image histograms\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990321 
.PP
Modified: 20210202 
.RE
.PP

.PP
Definition in file \fBbhisto\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 46 of file bhisto\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bhisto [options] input\&.img output\&.img",
"--------------------------------------------",
"Calculates the histogram of an image and associated statistics\&.",
" ",
"Actions:",
"-bins 256                Calculate histogram over a number of bins\&.",
"-counts                  Calculate a counts histogram and adjust the image\&.",
"-fit gauss,2             Do a fit to the histogram (gaussian, poisson, counts)\&.",
"                         Second argument indicates number of gaussians\&.",
"                         Counts option will convert the image to discrete counts\&.",
"-otsu                    Calculate the Otsu inter-set variance\&.",
"-multi 5                 Calculate multiple thresholds for the given number of clusters\&.",
"-percentiles             Calculate the percentiles for an image\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-select 1                Select an image (default all)\&.",
"-sampling 2,3\&.5,1        Sampling (angstrom/voxel, a single value sets all three)\&.",
" ",
"Output:",
"-Postscript histo\&.ps     Postscript output file name\&.",
" ",
NULL
}
.fi
.PP
Definition at line 18 of file bhisto\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
