.TH "/Users/bernard/b20/bsoft/src/img/Bimage_polar.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_polar.cpp \- Library routines for polar and spherical transformations and calculations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'simplex\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'Matrix\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBradial_R\fP (\fBBsimplex\fP &simp)"
.br
.ti -1c
.RI "double \fBradius_wrt_sym_axes\fP (\fBVector3\fP< double > coor, vector< \fBVector3\fP< double >> vs)"
.br
.RI "Calculates the radius relative to the closest symmetry axis\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines for polar and spherical transformations and calculations\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990904 
.PP
Modified: 20200509 
.RE
.PP

.PP
Definition in file \fBBimage_polar\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "double radial_R (\fBBsimplex\fP & simp)"

.PP
Definition at line 278 of file Bimage_polar\&.cpp\&.
.SS "double radius_wrt_sym_axes (\fBVector3\fP< double > coor, vector< \fBVector3\fP< double >> vs)"

.PP
Calculates the radius relative to the closest symmetry axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIcoor\fP coordinates in an image (voxels)\&. 
.br
\fIvs\fP symmetry axes\&. 
.RE
.PP
\fBReturns\fP
.RS 4
double symmetry-adjusted radial distance\&. 
.PP
.nf
The scalar production of the coordinate vector and each symmetry axis is calculated.
The maximal value is returned as the symmetry-adjusted radial distance.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 994 of file Bimage_polar\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
