.TH "/Users/bernard/b20/bsoft/src/img/Bimage_filter.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_filter.cpp \- Library routines used for filtering images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'matrix_linear\&.h'\fP
.br
\fC#include 'math_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBkmin\fP (long i, long hk)"
.br
.ti -1c
.RI "long \fBkmax\fP (long i, long km, long m)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines used for filtering images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990321 
.PP
Modified: 20160510 
.RE
.PP

.PP
Definition in file \fBBimage_filter\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "long kmax (long i, long km, long m)"

.PP
Definition at line 22 of file Bimage_filter\&.cpp\&.
.SS "long kmin (long i, long hk)"

.PP
Definition at line 17 of file Bimage_filter\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
