.TH "/Users/bernard/b20/bsoft/src/img/Bimage_resolution.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_resolution.cpp \- Library routines to estimate resolution\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLORESLIM\fP   200"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to estimate resolution\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000611 
.PP
Modified: 20171122 
.RE
.PP

.PP
Definition in file \fBBimage_resolution\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LORESLIM   200"

.PP
Definition at line 12 of file Bimage_resolution\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
