.TH "/Users/bernard/b20/bsoft/src/img/Bimage_edit.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_edit.cpp \- Library routines used for editing image contents\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'matrix_linear\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBrectangle_edge\fP (\fBVector3\fP< double > d, \fBVector3\fP< double > hr)"
.br
.ti -1c
.RI "double \fBoval_edge\fP (\fBVector3\fP< double > d, \fBVector3\fP< double > hr)"
.br
.ti -1c
.RI "double \fBcylinder_edge\fP (\fBVector3\fP< double > d, \fBVector3\fP< double > hr)"
.br
.ti -1c
.RI "double \fBshell_edge\fP (\fBVector3\fP< double > d, double mind, double maxd)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines used for editing image contents\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19980520 
.PP
Modified: 20210105 
.RE
.PP

.PP
Definition in file \fBBimage_edit\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "double cylinder_edge (\fBVector3\fP< double > d, \fBVector3\fP< double > hr)"

.PP
Definition at line 44 of file Bimage_edit\&.cpp\&.
.SS "double oval_edge (\fBVector3\fP< double > d, \fBVector3\fP< double > hr)"

.PP
Definition at line 27 of file Bimage_edit\&.cpp\&.
.SS "double rectangle_edge (\fBVector3\fP< double > d, \fBVector3\fP< double > hr)"

.PP
Definition at line 17 of file Bimage_edit\&.cpp\&.
.SS "double shell_edge (\fBVector3\fP< double > d, double mind, double maxd)"

.PP
Definition at line 65 of file Bimage_edit\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
