.TH "/Users/bernard/b20/bsoft/src/img/Bimage_extract.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_extract.cpp \- Library routines to extract parts of images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'spline\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBfind_optimal_tiling\fP (long target, long tile_size, double fraction=0\&.2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to extract parts of images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990321 
.PP
Modified: 20210609 
.RE
.PP

.PP
Definition in file \fBBimage_extract\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "long find_optimal_tiling (long target, long tile_size, double fraction = \fC0\&.2\fP)"

.PP
Definition at line 479 of file Bimage_extract\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
