.TH "/Users/bernard/b20/bsoft/src/img/Bimage_powerspectrum.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_powerspectrum.cpp \- Functions for calculating and using power spectra in electron micrographs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'simplex\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBset_tile_size\fP (\fBVector3\fP< long > &tile_size, \fBVector3\fP< long > img_size)"
.br
.ti -1c
.RI "double \fBisotropy_R\fP (\fBBsimplex\fP &simp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for calculating and using power spectra in electron micrographs\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000426 
.PP
Modified: 20210817 
.RE
.PP

.PP
Definition in file \fBBimage_powerspectrum\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "double isotropy_R (\fBBsimplex\fP & simp)"

.PP
Definition at line 404 of file Bimage_powerspectrum\&.cpp\&.
.SS "int set_tile_size (\fBVector3\fP< long > & tile_size, \fBVector3\fP< long > img_size)"

.PP
Definition at line 16 of file Bimage_powerspectrum\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
