.TH "/Users/bernard/b20/bsoft/src/img/Bimage_nad.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_nad.cpp \- Denoising by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'Matrix\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Denoising by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&. 


.PP
\fBAuthor\fP
.RS 4
Achilleas Frangakis 
.PP
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20020803 
.PP
Modified: 20161210 (BH) 
.RE
.PP

.PP
Definition in file \fBBimage_nad\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
