.TH "/Users/bernard/b20/bsoft/src/img/Bimage_segment.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_segment.cpp \- Methods for segmentation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBimg_update_segment\fP (long i, \fBBimage\fP *p, \fBBimage\fP *pmask, vector< long > vstep, double colorweight, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "int \fBimg_assign_pixel\fP (long i, \fBBimage\fP *p, \fBBimage\fP *pmask, double wd, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "int \fBimg_assign_segments\fP (\fBBimage\fP *p, \fBBimage\fP *pmask, vector< long > vstep, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "int \fBimg_impose_segments\fP (\fBBimage\fP *p, \fBBimage\fP *pmask, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "long \fBsegment_lowest_neighbor\fP (vector< \fBBsuperpixel\fP > &seg, long i, long cc)"
.br
.ti -1c
.RI "int \fBimg_impose_lowest_neighbor\fP (\fBBimage\fP *p, \fBBimage\fP *pmask, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "long \fBsegment_highest_neighbor\fP (vector< \fBBsuperpixel\fP > &seg, long i, long cc)"
.br
.ti -1c
.RI "int \fBimg_impose_highest_neighbor\fP (\fBBimage\fP *p, \fBBimage\fP *pmask, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "int \fBimg_impose_difference_from_highest_neighbor\fP (\fBBimage\fP *p, \fBBimage\fP *pmask, vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "long \fBsegment_setup_neighbors\fP (long i, vector< \fBBsuperpixel\fP > &seg, double dmax)"
.br
.ti -1c
.RI "long \fBsegments_setup_neighbors\fP (vector< \fBBsuperpixel\fP > &seg, long step)"
.br
.ti -1c
.RI "\fBBimage\fP * \fBimg_unbin_update\fP (\fBBimage\fP *p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Methods for segmentation\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann and Samuel Payne 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010516 
.PP
Modified: 20210118 (BH) 
.RE
.PP

.PP
Definition in file \fBBimage_segment\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int img_assign_pixel (long i, \fBBimage\fP * p, \fBBimage\fP * pmask, double wd, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1582 of file Bimage_segment\&.cpp\&.
.SS "int img_assign_segments (\fBBimage\fP * p, \fBBimage\fP * pmask, vector< long > vstep, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1610 of file Bimage_segment\&.cpp\&.
.SS "int img_impose_difference_from_highest_neighbor (\fBBimage\fP * p, \fBBimage\fP * pmask, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1698 of file Bimage_segment\&.cpp\&.
.SS "int img_impose_highest_neighbor (\fBBimage\fP * p, \fBBimage\fP * pmask, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1685 of file Bimage_segment\&.cpp\&.
.SS "int img_impose_lowest_neighbor (\fBBimage\fP * p, \fBBimage\fP * pmask, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1659 of file Bimage_segment\&.cpp\&.
.SS "int img_impose_segments (\fBBimage\fP * p, \fBBimage\fP * pmask, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1635 of file Bimage_segment\&.cpp\&.
.SS "\fBBimage\fP* img_unbin_update (\fBBimage\fP * p)"

.PP
Definition at line 1864 of file Bimage_segment\&.cpp\&.
.SS "int img_update_segment (long i, \fBBimage\fP * p, \fBBimage\fP * pmask, vector< long > vstep, double colorweight, vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 1502 of file Bimage_segment\&.cpp\&.
.SS "long segment_highest_neighbor (vector< \fBBsuperpixel\fP > & seg, long i, long cc)"

.PP
Definition at line 1672 of file Bimage_segment\&.cpp\&.
.SS "long segment_lowest_neighbor (vector< \fBBsuperpixel\fP > & seg, long i, long cc)"

.PP
Definition at line 1646 of file Bimage_segment\&.cpp\&.
.SS "long segment_setup_neighbors (long i, vector< \fBBsuperpixel\fP > & seg, double dmax)"

.PP
Definition at line 1713 of file Bimage_segment\&.cpp\&.
.SS "long segments_setup_neighbors (vector< \fBBsuperpixel\fP > & seg, long step)"

.PP
Definition at line 1730 of file Bimage_segment\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
