.TH "/Users/bernard/b20/bsoft/src/img/Bimage_mask.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_mask.cpp \- Methods for binary mask creation and manipulation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Methods for binary mask creation and manipulation\&. 


.PP
\fBAuthor\fP
.RS 4
Samuel Payne and Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010710 
.PP
Modified: 20200821 (BH) 
.RE
.PP

.PP
Definition in file \fBBimage_mask\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
