.TH "/Users/bernard/b20/bsoft/src/img/Bimage_symmetry.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_symmetry.cpp \- Symmetry function library for crystallography\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'rwsymop\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBVector3\fP< double > \fBvector3_closest_to_intersection\fP (\fBVector3\fP< double > origin1, \fBVector3\fP< double > origin2, \fBVector3\fP< double > axis1, \fBVector3\fP< double > axis2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Symmetry function library for crystallography\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990509 
.PP
Modified: 20191104 
.RE
.PP

.PP
Definition in file \fBBimage_symmetry\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBVector3\fP<double> vector3_closest_to_intersection (\fBVector3\fP< double > origin1, \fBVector3\fP< double > origin2, \fBVector3\fP< double > axis1, \fBVector3\fP< double > axis2)"

.PP
Definition at line 193 of file Bimage_symmetry\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
