.TH "/Users/bernard/b20/bsoft/src/bmapdist.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmapdist.cpp \- Calculates a distance criterion between a set of 2D images or 3D maps\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'mg_img_proc\&.h'\fP
.br
\fC#include 'Matrix\&.h'\fP
.br
\fC#include 'cluster\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMatrix\fP \fBimg_map_distance\fP (\fBBstring\fP *\fBfile_list\fP, int type, double *cutoff, double hires, double lores, \fBBimage\fP *pmask)"
.br
.ti -1c
.RI "int \fBproject_set_selection\fP (\fBBproject\fP *\fBproject\fP, long n, vector< long > idx)"
.br
.ti -1c
.RI "int \fBproject_rec_select\fP (\fBBproject\fP *\fBproject\fP, vector< long > idx)"
.br
.ti -1c
.RI "\fBBstring\fP * \fBproject_get_filenames\fP (\fBBproject\fP *\fBproject\fP, int flag)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Calculates a distance criterion between a set of 2D images or 3D maps\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010308 
.PP
Modified: 20210508 
.RE
.PP

.PP
Definition in file \fBbmapdist\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBMatrix\fP img_map_distance (\fBBstring\fP * file_list, int type, double * cutoff, double hires, double lores, \fBBimage\fP * pmask)"

.PP
Definition at line 200 of file bmapdist\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 83 of file bmapdist\&.cpp\&.
.SS "\fBBstring\fP* project_get_filenames (\fBBproject\fP * project, int flag)"

.PP
Definition at line 29 of file bmapdist\&.cpp\&.
.SS "int project_rec_select (\fBBproject\fP * project, vector< long > idx)"

.PP
Definition at line 449 of file bmapdist\&.cpp\&.
.SS "int project_set_selection (\fBBproject\fP * project, long n, vector< long > idx)"

.PP
Definition at line 375 of file bmapdist\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 49 of file bmapdist\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
