.TH "/Users/bernard/b20/bsoft/src/bmark.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmark.cpp \- Program to generate symmetry axes for mark group symmetries\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_tomography\&.h'\fP
.br
\fC#include 'mg_tomo_track\&.h'\fP
.br
\fC#include 'mg_marker\&.h'\fP
.br
\fC#include 'marker\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to generate symmetry axes for mark group symmetries\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20020619 
.PP
Modified: 20150212 
.RE
.PP

.PP
Definition in file \fBbmark\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 51 of file bmark\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bmark [options] in\&.star [in2\&.star\&.\&.\&.]",
"--------------------------------------------",
"Operates on sets of micrograph markers\&.",
" ",
"Actions:",
"-reconstructions         Operate on reconstruction parameters rather than micrographs\&.",
"-list                    List all micrograph and reconstruction markers\&.",
"-rotate 0\&.3,0\&.1,-0\&.5,81  Rotate around an axis by an angle\&.",
"-scale 0\&.5,3,1           Scale\&.",
"-translate 12\&.2,0\&.5,-50  Shift after rotation and scaling\&.",
"-plane                   Calculate a plane through the markers\&.",
"-fom 0\&.55                Select markers with a figure-of-merit above this cutoff\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-origin 0,22\&.5,30        Set the origin for rotation\&.",

" ",
"Output:",
"-output out\&.star         Output micrograph parameter file\&.",
" ",
NULL
}
.fi
.PP
Definition at line 25 of file bmark\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
