.TH "/Users/bernard/b20/bsoft/src/bmatch.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmatch.cpp \- Program to search an image with multiple projections and orient them\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'rwmodel\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBmodel\fP * \fBimg_match\fP (\fBBimage\fP *p, \fBBimage\fP *pref, double res_hi, double res_lo, double angle_inc, double threshold, long exclusion, double mask_rad)"
.br
.ti -1c
.RI "\fBBmodel\fP * \fBimg_match_one\fP (\fBBimage\fP *p, long img_num, \fBBimage\fP *pref, double res_hi, double res_lo, double angle_inc, double threshold, long exclusion, double mask_rad, \fBfft_plan\fP \fBplanf\fP, \fBfft_plan\fP \fBplanb\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "\fBBimage\fP * \fBimg_reference_prepare\fP (\fBBimage\fP *pref, long nn, \fBVector3\fP< long > size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to search an image with multiple projections and orient them\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20170720 
.PP
Modified: 20190821
.RE
.PP
clang++ -o bin/bmatch \fBsrc/bmatch\&.cpp\fP -I\&. -I/usr/local/include -I/Users/bernard/b20/bsoft/include -L/Users/bernard/b20/bsoft/lib -lbsoft -DHAVE_FFTW3 -std=c++11 -I/Users/bernard/b20/fftw-3\&.3\&.6-pl2/include 
.PP
Definition in file \fBbmatch\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmodel\fP * img_match (\fBBimage\fP * p, \fBBimage\fP * pref, double res_hi, double res_lo, double angle_inc, double threshold, long exclusion, double mask_rad)"

.PP
Definition at line 166 of file bmatch\&.cpp\&.
.SS "\fBBmodel\fP * img_match_one (\fBBimage\fP * p, long img_num, \fBBimage\fP * pref, double res_hi, double res_lo, double angle_inc, double threshold, long exclusion, double mask_rad, \fBfft_plan\fP planf, \fBfft_plan\fP planb)"

.PP
Definition at line 206 of file bmatch\&.cpp\&.
.SS "\fBBimage\fP* img_reference_prepare (\fBBimage\fP * pref, long nn, \fBVector3\fP< long > size)"

.PP
Definition at line 189 of file bmatch\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 56 of file bmatch\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bmatch [options] img\&.mrc cc\&.map",
"--------------------------------------",
"Searching an image with a set of 2D templates/references",
"Orientations are taken from the input projections\&.",
" ",


" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-sampling 2,3\&.5,1        Sampling before rescaling (angstrom/voxel, a single value sets all three)\&.",
"-resolution 25,200       Resolution limits (angstrom)\&.",
"-angle 2\&.5               Angular increment (default 3 degrees)\&.",
"-origin 0\&.8,-10,15\&.7     Set the origin (default from input image)\&.",
"-threshold 0\&.24          Threshold to find correlation peaks\&.",
"-exclusion 150           Minimum distance between correlation peaks\&.",
"-radius 50               Mask radius (slightly bigger than particle)\&.",
" ",
"Input:",
"-reference file\&.pif      Input reference projections file\&.",
" ",
"Output:",
"-output newmod\&.star      New model file\&.",
" ",
NULL
}
.fi
.PP
Definition at line 26 of file bmatch\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
