.TH "Bmd" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBKfriction\fP"
.br
.ti -1c
.RI "double \fBKbond\fP"
.br
.ti -1c
.RI "double \fBKangle\fP"
.br
.ti -1c
.RI "double \fBKelec\fP"
.br
.ti -1c
.RI "double \fBKvdw\fP"
.br
.ti -1c
.RI "double \fBKsep\fP"
.br
.ti -1c
.RI "double \fBKpoint\fP"
.br
.ti -1c
.RI "double \fBKmap\fP"
.br
.ti -1c
.RI "double \fBVdWcoeff1\fP"
.br
.ti -1c
.RI "double \fBVdWcoeff2\fP"
.br
.ti -1c
.RI "double \fBsepdist\fP"
.br
.ti -1c
.RI "double \fBcutoff\fP"
.br
.ti -1c
.RI "double \fBpointdecay\fP"
.br
.ti -1c
.RI "int \fBbondsteps\fP"
.br
.ti -1c
.RI "int \fBwrap\fP"
.br
.ti -1c
.RI "double \fBEbond\fP"
.br
.ti -1c
.RI "double \fBEangle\fP"
.br
.ti -1c
.RI "double \fBEelec\fP"
.br
.ti -1c
.RI "double \fBEvdw\fP"
.br
.ti -1c
.RI "double \fBEsep\fP"
.br
.ti -1c
.RI "double \fBEpoint\fP"
.br
.ti -1c
.RI "double \fBEmap\fP"
.br
.ti -1c
.RI "double \fBEkin\fP"
.br
.ti -1c
.RI "double \fBEpot\fP"
.br
.ti -1c
.RI "\fBVector3\fP< float > \fBpoint\fP"
.br
.ti -1c
.RI "\fBBatomtype\fP * \fBatom\fP"
.br
.ti -1c
.RI "\fBBbondtype\fP * \fBbond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file rwmd\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBatomtype\fP* Bmd::atom"

.PP
Definition at line 83 of file rwmd\&.h\&.
.SS "\fBBbondtype\fP* Bmd::bond"

.PP
Definition at line 84 of file rwmd\&.h\&.
.SS "int Bmd::bondsteps"

.PP
Definition at line 71 of file rwmd\&.h\&.
.SS "double Bmd::cutoff"

.PP
Definition at line 69 of file rwmd\&.h\&.
.SS "double Bmd::Eangle"

.PP
Definition at line 74 of file rwmd\&.h\&.
.SS "double Bmd::Ebond"

.PP
Definition at line 73 of file rwmd\&.h\&.
.SS "double Bmd::Eelec"

.PP
Definition at line 75 of file rwmd\&.h\&.
.SS "double Bmd::Ekin"

.PP
Definition at line 80 of file rwmd\&.h\&.
.SS "double Bmd::Emap"

.PP
Definition at line 79 of file rwmd\&.h\&.
.SS "double Bmd::Epoint"

.PP
Definition at line 78 of file rwmd\&.h\&.
.SS "double Bmd::Epot"

.PP
Definition at line 81 of file rwmd\&.h\&.
.SS "double Bmd::Esep"

.PP
Definition at line 77 of file rwmd\&.h\&.
.SS "double Bmd::Evdw"

.PP
Definition at line 76 of file rwmd\&.h\&.
.SS "double Bmd::Kangle"

.PP
Definition at line 60 of file rwmd\&.h\&.
.SS "double Bmd::Kbond"

.PP
Definition at line 59 of file rwmd\&.h\&.
.SS "double Bmd::Kelec"

.PP
Definition at line 61 of file rwmd\&.h\&.
.SS "double Bmd::Kfriction"

.PP
Definition at line 58 of file rwmd\&.h\&.
.SS "double Bmd::Kmap"

.PP
Definition at line 65 of file rwmd\&.h\&.
.SS "double Bmd::Kpoint"

.PP
Definition at line 64 of file rwmd\&.h\&.
.SS "double Bmd::Ksep"

.PP
Definition at line 63 of file rwmd\&.h\&.
.SS "double Bmd::Kvdw"

.PP
Definition at line 62 of file rwmd\&.h\&.
.SS "\fBVector3\fP<float> Bmd::point"

.PP
Definition at line 82 of file rwmd\&.h\&.
.SS "double Bmd::pointdecay"

.PP
Definition at line 70 of file rwmd\&.h\&.
.SS "double Bmd::sepdist"

.PP
Definition at line 68 of file rwmd\&.h\&.
.SS "double Bmd::timestep"

.PP
Definition at line 57 of file rwmd\&.h\&.
.SS "double Bmd::VdWcoeff1"

.PP
Definition at line 66 of file rwmd\&.h\&.
.SS "double Bmd::VdWcoeff2"

.PP
Definition at line 67 of file rwmd\&.h\&.
.SS "int Bmd::wrap"

.PP
Definition at line 72 of file rwmd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
