.TH "/Users/bernard/b20/bsoft/src/bmg2imod.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmg2imod.cpp \- Converts between \fBIMOD\fP files and a micrograph parameter file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_img_proc\&.h'\fP
.br
\fC#include 'mg_tomography\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'rwmgIMOD\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBwrite_IMOD_parameters\fP (\fBBstring\fP &imodfile, \fBBproject\fP *\fBproject\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts between \fBIMOD\fP files and a micrograph parameter file\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20070501 
.PP
Modified: 20180322 
.RE
.PP

.PP
Definition in file \fBbmg2imod\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 48 of file bmg2imod\&.cpp\&.
.SS "int write_IMOD_parameters (\fBBstring\fP & imodfile, \fBBproject\fP * project)"

.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bmg2imod [options] input\&.mrc input\&.xf input\&.tlt input\&.xyz",
"----------------------------------------------------------------",
"Converts between IMOD files and a micrograph parameter file\&.",
" ",
"Actions:",
"-topif                   Flag to convert the image file to multi-image PIF (default not)\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-sampling 1\&.5            Sampling (A/pixel)\&.",
" ",
"Output:",
"-output file\&.star        Output micrograph parameter file\&.",
"-imod file\&.xf            Output IMOD parameter files\&.",
" ",
NULL
}
.fi
.PP
Definition at line 27 of file bmg2imod\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
