.TH "/Users/bernard/b20/bsoft/src/bmgtransfer.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmgtransfer.cpp \- Transfer pieces of information between micrograph paramater files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'mg_ctf\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBproject_replace_parameters\fP (\fBBproject\fP *\fBproject\fP, \fBBproject\fP *proj_source, \fBBstring\fP &which)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "long \fBmg_replace_parameters\fP (\fBBmicrograph\fP *mg, \fBBmicrograph\fP *mg_source, \fBBstring\fP &which, \fBVector3\fP< double > origin)"
.br
.ti -1c
.RI "long \fBfield_replace_parameters\fP (\fBBfield\fP *field, \fBBfield\fP *field_source, \fBBstring\fP &which)"
.br
.ti -1c
.RI "long \fBrec_replace_parameters\fP (\fBBreconstruction\fP *rec, \fBBreconstruction\fP *rec_source, \fBBstring\fP &which)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Transfer pieces of information between micrograph paramater files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20140701 
.PP
Modified: 20140703 
.RE
.PP

.PP
Definition in file \fBbmgtransfer\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "long field_replace_parameters (\fBBfield\fP * field, \fBBfield\fP * field_source, \fBBstring\fP & which)"

.PP
Definition at line 177 of file bmgtransfer\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 54 of file bmgtransfer\&.cpp\&.
.SS "long mg_replace_parameters (\fBBmicrograph\fP * mg, \fBBmicrograph\fP * mg_source, \fBBstring\fP & which, \fBVector3\fP< double > origin)"

.PP
Definition at line 145 of file bmgtransfer\&.cpp\&.
.SS "long project_replace_parameters (\fBBproject\fP * project, \fBBproject\fP * proj_source, \fBBstring\fP & which)"

.PP
Definition at line 228 of file bmgtransfer\&.cpp\&.
.SS "long rec_replace_parameters (\fBBreconstruction\fP * rec, \fBBreconstruction\fP * rec_source, \fBBstring\fP & which)"

.PP
Definition at line 201 of file bmgtransfer\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 22 of file bmgtransfer\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
