.TH "Bmicrograph" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmicrograph
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBmicrograph\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBmicrograph\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBid\fP"
.br
.ti -1c
.RI "long \fBselect\fP"
.br
.ti -1c
.RI "int \fBblock\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfmg\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfframe\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfpart\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBffil\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfft\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfps\fP"
.br
.ti -1c
.RI "int \fBimg_num\fP"
.br
.ti -1c
.RI "double \fBmagnification\fP"
.br
.ti -1c
.RI "double \fBsampling\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBframe_pixel_size\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBpixel_size\fP"
.br
.ti -1c
.RI "double \fBexposure\fP"
.br
.ti -1c
.RI "double \fBdose\fP"
.br
.ti -1c
.RI "double \fBintensity\fP"
.br
.ti -1c
.RI "double \fBwri\fP"
.br
.ti -1c
.RI "double \fBtilt_axis\fP"
.br
.ti -1c
.RI "double \fBtilt_angle\fP"
.br
.ti -1c
.RI "double \fBlevel_angle\fP"
.br
.ti -1c
.RI "double \fBrot_angle\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBorigin\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBscale\fP"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBmatrix\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBhvec\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBkvec\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBlvec\fP"
.br
.ti -1c
.RI "double \fBhelix_axis\fP"
.br
.ti -1c
.RI "double \fBhelix_rise\fP"
.br
.ti -1c
.RI "double \fBhelix_angle\fP"
.br
.ti -1c
.RI "double \fBhelix_radius\fP"
.br
.ti -1c
.RI "\fBVector3\fP< long > \fBbox_size\fP"
.br
.ti -1c
.RI "double \fBfilament_width\fP"
.br
.ti -1c
.RI "double \fBfil_node_radius\fP"
.br
.ti -1c
.RI "double \fBbad_radius\fP"
.br
.ti -1c
.RI "double \fBsf_radius\fP"
.br
.ti -1c
.RI "double \fBmark_radius\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "\fBBframe\fP * \fBframe\fP"
.br
.ti -1c
.RI "\fBCTFparam\fP * \fBctf\fP"
.br
.ti -1c
.RI "\fBBparticle\fP * \fBpart\fP"
.br
.ti -1c
.RI "\fBBfilament\fP * \fBfil\fP"
.br
.ti -1c
.RI "\fBBbadarea\fP * \fBbad\fP"
.br
.ti -1c
.RI "\fBBmarker\fP * \fBmark\fP"
.br
.ti -1c
.RI "\fBBstrucfac\fP * \fBsf\fP"
.br
.ti -1c
.RI "\fBBlayerline\fP * \fBlayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 278 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bmicrograph::Bmicrograph ()\fC [inline]\fP"

.PP
Definition at line 372 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBbadarea\fP* Bmicrograph::bad"

.PP
Definition at line 368 of file mg_processing\&.h\&.
.SS "double Bmicrograph::bad_radius"

.PP
Definition at line 360 of file mg_processing\&.h\&.
.SS "int Bmicrograph::block"

.PP
Definition at line 327 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<long> Bmicrograph::box_size"

.PP
Definition at line 357 of file mg_processing\&.h\&.
.SS "\fBCTFparam\fP* Bmicrograph::ctf"

.PP
Definition at line 365 of file mg_processing\&.h\&.
.SS "double Bmicrograph::dose"

.PP
Definition at line 340 of file mg_processing\&.h\&.
.SS "double Bmicrograph::exposure"

.PP
Definition at line 339 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::ffil"

.PP
Definition at line 331 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::fframe"

.PP
Definition at line 329 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::fft"

.PP
Definition at line 332 of file mg_processing\&.h\&.
.SS "\fBBfilament\fP* Bmicrograph::fil"

.PP
Definition at line 367 of file mg_processing\&.h\&.
.SS "double Bmicrograph::fil_node_radius"

.PP
Definition at line 359 of file mg_processing\&.h\&.
.SS "double Bmicrograph::filament_width"

.PP
Definition at line 358 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::fmg"

.PP
Definition at line 328 of file mg_processing\&.h\&.
.SS "double Bmicrograph::fom"

.PP
Definition at line 363 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::fpart"

.PP
Definition at line 330 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::fps"

.PP
Definition at line 333 of file mg_processing\&.h\&.
.SS "\fBBframe\fP* Bmicrograph::frame"

.PP
Definition at line 364 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::frame_pixel_size"

.PP
Definition at line 337 of file mg_processing\&.h\&.
.SS "double Bmicrograph::helix_angle"

.PP
Definition at line 355 of file mg_processing\&.h\&.
.SS "double Bmicrograph::helix_axis"

.PP
Definition at line 353 of file mg_processing\&.h\&.
.SS "double Bmicrograph::helix_radius"

.PP
Definition at line 356 of file mg_processing\&.h\&.
.SS "double Bmicrograph::helix_rise"

.PP
Definition at line 354 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::hvec"

.PP
Definition at line 350 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bmicrograph::id"

.PP
Definition at line 325 of file mg_processing\&.h\&.
.SS "int Bmicrograph::img_num"

.PP
Definition at line 334 of file mg_processing\&.h\&.
.SS "double Bmicrograph::intensity"

.PP
Definition at line 341 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::kvec"

.PP
Definition at line 351 of file mg_processing\&.h\&.
.SS "\fBBlayerline\fP* Bmicrograph::layer"

.PP
Definition at line 371 of file mg_processing\&.h\&.
.SS "double Bmicrograph::level_angle"

.PP
Definition at line 345 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::lvec"

.PP
Definition at line 352 of file mg_processing\&.h\&.
.SS "double Bmicrograph::magnification"

.PP
Definition at line 335 of file mg_processing\&.h\&.
.SS "\fBBmarker\fP* Bmicrograph::mark"

.PP
Definition at line 369 of file mg_processing\&.h\&.
.SS "double Bmicrograph::mark_radius"

.PP
Definition at line 362 of file mg_processing\&.h\&.
.SS "\fBMatrix3\fP Bmicrograph::matrix"

.PP
Definition at line 349 of file mg_processing\&.h\&.
.SS "\fBBmicrograph\fP* Bmicrograph::next"

.PP
Definition at line 324 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::origin"

.PP
Definition at line 347 of file mg_processing\&.h\&.
.SS "\fBBparticle\fP* Bmicrograph::part"

.PP
Definition at line 366 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::pixel_size"

.PP
Definition at line 338 of file mg_processing\&.h\&.
.SS "double Bmicrograph::rot_angle"

.PP
Definition at line 346 of file mg_processing\&.h\&.
.SS "double Bmicrograph::sampling"

.PP
Definition at line 336 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bmicrograph::scale"

.PP
Definition at line 348 of file mg_processing\&.h\&.
.SS "long Bmicrograph::select"

.PP
Definition at line 326 of file mg_processing\&.h\&.
.SS "\fBBstrucfac\fP* Bmicrograph::sf"

.PP
Definition at line 370 of file mg_processing\&.h\&.
.SS "double Bmicrograph::sf_radius"

.PP
Definition at line 361 of file mg_processing\&.h\&.
.SS "double Bmicrograph::tilt_angle"

.PP
Definition at line 344 of file mg_processing\&.h\&.
.SS "double Bmicrograph::tilt_axis"

.PP
Definition at line 343 of file mg_processing\&.h\&.
.SS "double Bmicrograph::wri"

.PP
Definition at line 342 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
