.TH "/Users/bernard/b20/bsoft/src/bmodcomp.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmodcomp.cpp \- A tool to compare polyhedra\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br
\fC#include 'model_select\&.h'\fP
.br
\fC#include 'model_poly\&.h'\fP
.br
\fC#include 'model_compare\&.h'\fP
.br
\fC#include 'model_util\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A tool to compare polyhedra\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20080102 
.PP
Modified: 20190125 
.RE
.PP

.PP
Definition in file \fBbmodcomp\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 52 of file bmodcomp\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bmodcomp [options] in\&.star",
"---------------------------------",
"Compares models internally or to reference models\&.",
" ",
"Actions:",
"-all                     Select all models for comparison\&.",
"-distance                Calculate a distance matrix\&.",
"-unknown                 Select unknown models for comparison\&.",
"-closed order,3          Select based on valency (valency,<n>) or polygon order (order,<n>)\&.",
"-consensus 12\&.5          Calculate a consensus model: components are considered the same if within the given distance\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
" ",
"Input:",
"-parameters parm\&.star    Molecular parameter file (default atom_prop\&.star)\&.",
"-reference ref\&.star      File with reference models\&.",
" ",
"Output:",
"-output new\&.star         Output model file\&.",
"-writereference ref\&.star Reference output model file\&.",
"-matrix file\&.mat         Distance matrix\&.",
"-image file\&.map          Distance matrix as an image\&.",
" ",
NULL
}
.fi
.PP
Definition at line 23 of file bmodcomp\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
