.TH "Bmodparam" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmodparam
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel_param\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBmodparam\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBcomment\fP"
.br
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBKfriction\fP"
.br
.ti -1c
.RI "double \fBKdistance\fP"
.br
.ti -1c
.RI "double \fBKelec\fP"
.br
.ti -1c
.RI "double \fBKlink\fP"
.br
.ti -1c
.RI "double \fBKangle\fP"
.br
.ti -1c
.RI "double \fBKpolyangle\fP"
.br
.ti -1c
.RI "double \fBKpolygon\fP"
.br
.ti -1c
.RI "double \fBKpolyplane\fP"
.br
.ti -1c
.RI "double \fBKpoint\fP"
.br
.ti -1c
.RI "double \fBKradial\fP"
.br
.ti -1c
.RI "double \fBKplane\fP"
.br
.ti -1c
.RI "double \fBKguide\fP"
.br
.ti -1c
.RI "double \fBKmap\fP"
.br
.ti -1c
.RI "double \fBsepdist\fP"
.br
.ti -1c
.RI "double \fBcutoff\fP"
.br
.ti -1c
.RI "double \fBpointdecay\fP"
.br
.ti -1c
.RI "double \fBradius\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBpoint\fP"
.br
.ti -1c
.RI "\fBBmodel\fP * \fBguide\fP"
.br
.ti -1c
.RI "int \fBlinksteps\fP"
.br
.ti -1c
.RI "int \fBwrap\fP"
.br
.ti -1c
.RI "double \fBsigma\fP"
.br
.ti -1c
.RI "double \fBEdistance\fP"
.br
.ti -1c
.RI "double \fBEelec\fP"
.br
.ti -1c
.RI "double \fBElink\fP"
.br
.ti -1c
.RI "double \fBEangle\fP"
.br
.ti -1c
.RI "double \fBEpolyangle\fP"
.br
.ti -1c
.RI "double \fBEpolygon\fP"
.br
.ti -1c
.RI "double \fBEpolyplane\fP"
.br
.ti -1c
.RI "double \fBEpoint\fP"
.br
.ti -1c
.RI "double \fBEradial\fP"
.br
.ti -1c
.RI "double \fBEplane\fP"
.br
.ti -1c
.RI "double \fBEguide\fP"
.br
.ti -1c
.RI "double \fBEmap\fP"
.br
.ti -1c
.RI "double \fBEkin\fP"
.br
.ti -1c
.RI "double \fBEpot\fP"
.br
.ti -1c
.RI "map< string, \fBBcomptype\fP > \fBcomptype\fP"
.br
.ti -1c
.RI "vector< vector< \fBBlinktype\fP > > \fBlinktype\fP"
.br
.ti -1c
.RI "vector< vector< vector< \fBBangletype\fP > > > \fBangletype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file rwmodel_param\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bmodparam::Bmodparam ()\fC [inline]\fP"

.PP
Definition at line 104 of file rwmodel_param\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<vector<vector<\fBBangletype\fP> > > Bmodparam::angletype"

.PP
Definition at line 77 of file rwmodel_param\&.h\&.
.SS "string Bmodparam::comment"

.PP
Definition at line 37 of file rwmodel_param\&.h\&.
.SS "map<string,\fBBcomptype\fP> Bmodparam::comptype"

.PP
Definition at line 75 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::cutoff"

.PP
Definition at line 53 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Eangle"

.PP
Definition at line 64 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Edistance"

.PP
Definition at line 61 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Eelec"

.PP
Definition at line 62 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Eguide"

.PP
Definition at line 71 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Ekin"

.PP
Definition at line 73 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Elink"

.PP
Definition at line 63 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Emap"

.PP
Definition at line 72 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Eplane"

.PP
Definition at line 70 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Epoint"

.PP
Definition at line 68 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Epolyangle"

.PP
Definition at line 65 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Epolygon"

.PP
Definition at line 66 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Epolyplane"

.PP
Definition at line 67 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Epot"

.PP
Definition at line 74 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Eradial"

.PP
Definition at line 69 of file rwmodel_param\&.h\&.
.SS "\fBBmodel\fP* Bmodparam::guide"

.PP
Definition at line 57 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kangle"

.PP
Definition at line 43 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kdistance"

.PP
Definition at line 40 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kelec"

.PP
Definition at line 41 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kfriction"

.PP
Definition at line 39 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kguide"

.PP
Definition at line 50 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Klink"

.PP
Definition at line 42 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kmap"

.PP
Definition at line 51 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kplane"

.PP
Definition at line 49 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kpoint"

.PP
Definition at line 47 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kpolyangle"

.PP
Definition at line 44 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kpolygon"

.PP
Definition at line 45 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kpolyplane"

.PP
Definition at line 46 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::Kradial"

.PP
Definition at line 48 of file rwmodel_param\&.h\&.
.SS "int Bmodparam::linksteps"

.PP
Definition at line 58 of file rwmodel_param\&.h\&.
.SS "vector<vector<\fBBlinktype\fP> > Bmodparam::linktype"

.PP
Definition at line 76 of file rwmodel_param\&.h\&.
.SS "\fBVector3\fP<double> Bmodparam::point"

.PP
Definition at line 56 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::pointdecay"

.PP
Definition at line 54 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::radius"

.PP
Definition at line 55 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::sepdist"

.PP
Definition at line 52 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::sigma"

.PP
Definition at line 60 of file rwmodel_param\&.h\&.
.SS "double Bmodparam::timestep"

.PP
Definition at line 38 of file rwmodel_param\&.h\&.
.SS "int Bmodparam::wrap"

.PP
Definition at line 59 of file rwmodel_param\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
