.TH "/Users/bernard/b20/bsoft/src/bmultifit.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmultifit.cpp \- Searching for a template in a map and returning multiple hits in a model\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'model_multifit\&.h'\fP
.br
\fC#include 'ps_views\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Searching for a template in a map and returning multiple hits in a model\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20021027 
.PP
Modified: 20160604 
.RE
.PP

.PP
Definition in file \fBbmultifit\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 61 of file bmultifit\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 22 of file bmultifit\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
