.TH "Bnode" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bnode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwtree\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBnode\fP * \fBone\fP"
.br
.ti -1c
.RI "\fBBnode\fP * \fBtwo\fP"
.br
.ti -1c
.RI "\fBBnode\fP * \fBthree\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "char \fBlabel\fP [100]"
.br
.ti -1c
.RI "float \fBlength\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file rwtree\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Bnode::angle"

.PP
Definition at line 29 of file rwtree\&.h\&.
.SS "char Bnode::label[100]"

.PP
Definition at line 27 of file rwtree\&.h\&.
.SS "float Bnode::length"

.PP
Definition at line 28 of file rwtree\&.h\&.
.SS "int Bnode::number"

.PP
Definition at line 26 of file rwtree\&.h\&.
.SS "\fBBnode\fP* Bnode::one"

.PP
Definition at line 25 of file rwtree\&.h\&.
.SS "\fBBnode\fP * Bnode::three"

.PP
Definition at line 25 of file rwtree\&.h\&.
.SS "\fBBnode\fP * Bnode::two"

.PP
Definition at line 25 of file rwtree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
