.TH "Bparticle" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bparticle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBparticle\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBparticle\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfpart\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBgroup\fP"
.br
.ti -1c
.RI "double \fBmag\fP"
.br
.ti -1c
.RI "double \fBdef\fP"
.br
.ti -1c
.RI "double \fBdev\fP"
.br
.ti -1c
.RI "double \fBast\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBpixel_size\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBloc\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBori\fP"
.br
.ti -1c
.RI "\fBView\fP \fBview\fP"
.br
.ti -1c
.RI "double \fBfom\fP [\fBNFOM\fP]"
.br
.ti -1c
.RI "long \fBsel\fP"
.br
.ti -1c
.RI "\fBBmicrograph\fP * \fBmg\fP"
.br
.ti -1c
.RI "\fBBreconstruction\fP * \fBrec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bparticle::Bparticle ()\fC [inline]\fP"

.PP
Definition at line 135 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Bparticle::ast"

.PP
Definition at line 126 of file mg_processing\&.h\&.
.SS "double Bparticle::def"

.PP
Definition at line 124 of file mg_processing\&.h\&.
.SS "double Bparticle::dev"

.PP
Definition at line 125 of file mg_processing\&.h\&.
.SS "double Bparticle::fom[\fBNFOM\fP]"

.PP
Definition at line 131 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bparticle::fpart"

.PP
Definition at line 120 of file mg_processing\&.h\&.
.SS "int Bparticle::group"

.PP
Definition at line 122 of file mg_processing\&.h\&.
.SS "int Bparticle::id"

.PP
Definition at line 121 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bparticle::loc"

.PP
Definition at line 128 of file mg_processing\&.h\&.
.SS "double Bparticle::mag"

.PP
Definition at line 123 of file mg_processing\&.h\&.
.SS "\fBBmicrograph\fP* Bparticle::mg"

.PP
Definition at line 133 of file mg_processing\&.h\&.
.SS "\fBBparticle\fP* Bparticle::next"

.PP
Definition at line 119 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bparticle::ori"

.PP
Definition at line 129 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bparticle::pixel_size"

.PP
Definition at line 127 of file mg_processing\&.h\&.
.SS "\fBBreconstruction\fP* Bparticle::rec"

.PP
Definition at line 134 of file mg_processing\&.h\&.
.SS "long Bparticle::sel"

.PP
Definition at line 132 of file mg_processing\&.h\&.
.SS "\fBView\fP Bparticle::view"

.PP
Definition at line 130 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
