.TH "/Users/bernard/b20/bsoft/src/bphase.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bphase.cpp \- A program to examine phase differences between image pairs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A program to examine phase differences between image pairs\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20020217 
.PP
Modified: 20151006 
.RE
.PP

.PP
Definition in file \fBbphase\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 39 of file bphase\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bphase [options] file1\&.img file2\&.img outfile\&.img",
"-------------------------------------------------------",
"Calculates the phase difference between two images\&.",
" ",
"Actions:",
"-cosine                  Calculate the cosine of the phase angle difference\&.",
"-amplitude               Weight the phase difference with the amplitude product\&.",
"-center                  Center phase difference map and output it\&.",
"-flip                    Flip phases based on phase difference map and modify second image\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype short          Force writing of a new data type (default float)\&.",
"-origin 0\&.8,-10,15\&.7     Set the origin of both images (default from input images)\&.",
"-resolution 4\&.5,130      Resolution (default 0 - 10000 angstrom)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 18 of file bphase\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
