.TH "Bplot" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bplot
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bplot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBplot\fP ()"
.br
.ti -1c
.RI "\fBBplot\fP (long npage, long nrow, long ncol)"
.br
.ti -1c
.RI "\fBBplot\fP (\fBBstring\fP &filename)"
.br
.ti -1c
.RI "\fB~Bplot\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (long npage, long nrow, long ncol)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (long i)"
.br
.ti -1c
.RI "\fBBstring\fP & \fBtitle\fP ()"
.br
.ti -1c
.RI "void \fBtitle\fP (const \fBBstring\fP &t)"
.br
.ti -1c
.RI "void \fBtitle\fP (const char *t)"
.br
.ti -1c
.RI "void \fBpage_size\fP (long w, long h)"
.br
.ti -1c
.RI "long \fBpage_width\fP ()"
.br
.ti -1c
.RI "long \fBpage_height\fP ()"
.br
.ti -1c
.RI "void \fBsize\fP (long w, long h)"
.br
.ti -1c
.RI "long \fBwidth\fP ()"
.br
.ti -1c
.RI "long \fBheight\fP ()"
.br
.ti -1c
.RI "void \fBorigin\fP (long l, long b)"
.br
.ti -1c
.RI "long \fBleft\fP ()"
.br
.ti -1c
.RI "long \fBbottom\fP ()"
.br
.ti -1c
.RI "void \fBpages\fP (long n)"
.br
.ti -1c
.RI "long \fBpages\fP ()"
.br
.ti -1c
.RI "void \fBrows\fP (long n)"
.br
.ti -1c
.RI "long \fBrows\fP ()"
.br
.ti -1c
.RI "void \fBcolumns\fP (long n)"
.br
.ti -1c
.RI "long \fBcolumns\fP ()"
.br
.ti -1c
.RI "\fBBpage\fP & \fBpage\fP (long i)"
.br
.ti -1c
.RI "double * \fBdata_pointer\fP ()"
.br
.ti -1c
.RI "void \fBlimits\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBBplot\fP *p, long start=0)"
.br
.ti -1c
.RI "void \fBmultiply\fP (double d)"
.br
.ti -1c
.RI "double \fBcut\fP (long icol, double threshold, int dir=1)"
.br
.ti -1c
.RI "void \fBwrite_tsv\fP (\fBBstring\fP &filename)"
.br
.ti -1c
.RI "void \fBresolution_display\fP (double *fsccut=NULL, double *dprcut=NULL)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file Bplot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bplot::Bplot ()\fC [inline]\fP"

.PP
Definition at line 174 of file Bplot\&.h\&.
.SS "Bplot::Bplot (long npage, long nrow, long ncol)\fC [inline]\fP"

.PP
Definition at line 175 of file Bplot\&.h\&.
.SS "Bplot::Bplot (\fBBstring\fP & filename)"

.PP
Definition at line 30 of file Bplot\&.cpp\&.
.SS "Bplot::~Bplot ()\fC [inline]\fP"

.PP
Definition at line 179 of file Bplot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Bplot::add (\fBBplot\fP * p, long start = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 245 of file Bplot\&.h\&.
.SS "long Bplot::bottom ()\fC [inline]\fP"

.PP
Definition at line 205 of file Bplot\&.h\&.
.SS "long Bplot::columns ()\fC [inline]\fP"

.PP
Definition at line 215 of file Bplot\&.h\&.
.SS "void Bplot::columns (long n)\fC [inline]\fP"

.PP
Definition at line 214 of file Bplot\&.h\&.
.SS "double Bplot::cut (long icol, double threshold, int dir = \fC1\fP)\fC [inline]\fP"

.PP
Definition at line 251 of file Bplot\&.h\&.
.SS "double* Bplot::data_pointer ()\fC [inline]\fP"

.PP
Definition at line 223 of file Bplot\&.h\&.
.SS "long Bplot::height ()\fC [inline]\fP"

.PP
Definition at line 202 of file Bplot\&.h\&.
.SS "long Bplot::left ()\fC [inline]\fP"

.PP
Definition at line 204 of file Bplot\&.h\&.
.SS "void Bplot::limits ()\fC [inline]\fP"

.PP
Definition at line 224 of file Bplot\&.h\&.
.SS "void Bplot::multiply (double d)\fC [inline]\fP"

.PP
Definition at line 248 of file Bplot\&.h\&.
.SS "double& Bplot::operator[] (long i)\fC [inline]\fP"

.PP
Definition at line 189 of file Bplot\&.h\&.
.SS "void Bplot::origin (long l, long b)\fC [inline]\fP"

.PP
Definition at line 203 of file Bplot\&.h\&.
.SS "\fBBpage\fP& Bplot::page (long i)\fC [inline]\fP"

.PP
Definition at line 216 of file Bplot\&.h\&.
.SS "long Bplot::page_height ()\fC [inline]\fP"

.PP
Definition at line 199 of file Bplot\&.h\&.
.SS "void Bplot::page_size (long w, long h)\fC [inline]\fP"

.PP
Definition at line 197 of file Bplot\&.h\&.
.SS "long Bplot::page_width ()\fC [inline]\fP"

.PP
Definition at line 198 of file Bplot\&.h\&.
.SS "long Bplot::pages ()\fC [inline]\fP"

.PP
Definition at line 211 of file Bplot\&.h\&.
.SS "void Bplot::pages (long n)\fC [inline]\fP"

.PP
Definition at line 206 of file Bplot\&.h\&.
.SS "void Bplot::reset (long npage, long nrow, long ncol)\fC [inline]\fP"

.PP
Definition at line 184 of file Bplot\&.h\&.
.SS "void Bplot::resolution_display (double * fsccut = \fCNULL\fP, double * dprcut = \fCNULL\fP)"

.PP
Definition at line 114 of file Bplot\&.cpp\&.
.SS "long Bplot::rows ()\fC [inline]\fP"

.PP
Definition at line 213 of file Bplot\&.h\&.
.SS "void Bplot::rows (long n)\fC [inline]\fP"

.PP
Definition at line 212 of file Bplot\&.h\&.
.SS "void Bplot::size (long w, long h)\fC [inline]\fP"

.PP
Definition at line 200 of file Bplot\&.h\&.
.SS "\fBBstring\fP& Bplot::title ()\fC [inline]\fP"

.PP
Definition at line 194 of file Bplot\&.h\&.
.SS "void Bplot::title (const \fBBstring\fP & t)\fC [inline]\fP"

.PP
Definition at line 195 of file Bplot\&.h\&.
.SS "void Bplot::title (const char * t)\fC [inline]\fP"

.PP
Definition at line 196 of file Bplot\&.h\&.
.SS "long Bplot::width ()\fC [inline]\fP"

.PP
Definition at line 201 of file Bplot\&.h\&.
.SS "void Bplot::write_tsv (\fBBstring\fP & filename)\fC [inline]\fP"

.PP
Definition at line 272 of file Bplot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
