.TH "/Users/bernard/b20/bsoft/src/bradsec.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bradsec.cpp \- Generates radial sections from 3D images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBplot\fP * \fBimg_plot_radial\fP (\fBBimage\fP *p, \fBBstring\fP &title)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates radial sections from 3D images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000620 
.PP
Modified: 20200509 
.RE
.PP

.PP
Definition in file \fBbradsec\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBplot\fP * img_plot_radial (\fBBimage\fP * p, \fBBstring\fP & title)"

.PP
Definition at line 142 of file bradsec\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 44 of file bradsec\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bradsec [options] input\&.img output\&.img",
"---------------------------------------------",
"Generates symmetry-adjusted radial sections from 3D images\&.",
"The symmetry for O must be either O-3 or O-4\&.",
"The symmetry for I must be either I-3 or I-5\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (default from image; a single value can be given)\&.",
"-origin 0,-10,30         Set the origin for radial profile (default image origin)\&.",
"-radii 14,123,2\&.68       Start, end and step size for radial shell calculation (default from input)\&.",
"-symmetry C5             Point group symmetry\&.",
"-fraction 0\&.3            Spherical fraction (1=spherical shells, 0=symmetry-related shells)\&.",
"-fill 127                Fill value for excluded region: average (default), background, or value\&.",
" ",
"Output:",
"-Postscript radsec\&.ps    Symmetry-adjusted profile\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bradsec\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
