.TH "/Users/bernard/b20/bsoft/src/brandom.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/brandom.cpp \- Program to generate random images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'random_numbers\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to generate random images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990703 
.PP
Modified: 20150725 
.RE
.PP

.PP
Definition in file \fBbrandom\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 47 of file brandom\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: brandom [options] [input\&.img] output\&.img",
"-----------------------------------------------",
"Generates random content images\&.",
"If an input image is not found a random output image is generated\&.",
"The default output data type is floating point\&.",
" ",
"Actions:",
"-type gauss              Distribution type (default: uniform, ",
"                         others: gaussian, poisson, logistical, spectral)\&.",
"-rescale -0\&.1,5\&.2        Rescale output data to average and standard deviation\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Data type (default: byte)\&.",
"-images 12               Number of images (default: 1)\&.",
"-size 10,50,8            Size (default: 256,256,1)\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (default: 1,1,1; a single value can be given)\&.",
"-origin 0,-10,30         Set the origin (default image origin)\&.",
"-minmax -1\&.2,5\&.6         Set minimum and maximum of input and uniform random image (default: -1\&.732,1\&.732)\&.",
"-avgstd 0\&.5,2\&.3          Set average and standard deviation of input and non-uniform random image (default: 0,1)\&.",
"-alpha 2                 Spectral noise decay (default: white=0, pink=1, red/brown=2, blue=-1, violet=-2)\&.",
"-snr 1\&.4,63              Signal-to-noise ratio and foreground radius (default: 1)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 19 of file brandom\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
