.TH "Breconstruction" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Breconstruction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBreconstruction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBreconstruction\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBid\fP"
.br
.ti -1c
.RI "long \fBselect\fP"
.br
.ti -1c
.RI "int \fBblock\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBsymmetry\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfrec\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfpart\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBffil\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfft\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfps\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBvoxel_size\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBorigin\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBscale\fP"
.br
.ti -1c
.RI "\fBView\fP \fBview\fP"
.br
.ti -1c
.RI "\fBVector3\fP< long > \fBbox_size\fP"
.br
.ti -1c
.RI "double \fBfilament_width\fP"
.br
.ti -1c
.RI "double \fBfil_node_radius\fP"
.br
.ti -1c
.RI "double \fBbad_radius\fP"
.br
.ti -1c
.RI "double \fBsf_radius\fP"
.br
.ti -1c
.RI "double \fBmark_radius\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "\fBCTFparam\fP * \fBctf\fP"
.br
.ti -1c
.RI "\fBBparticle\fP * \fBpart\fP"
.br
.ti -1c
.RI "\fBBfilament\fP * \fBfil\fP"
.br
.ti -1c
.RI "\fBBbadarea\fP * \fBbad\fP"
.br
.ti -1c
.RI "\fBBmarker\fP * \fBmark\fP"
.br
.ti -1c
.RI "\fBBstrucfac\fP * \fBsf\fP"
.br
.ti -1c
.RI "\fBBstring\fP * \fBmodel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 419 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Breconstruction::Breconstruction ()\fC [inline]\fP"

.PP
Definition at line 480 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBbadarea\fP* Breconstruction::bad"

.PP
Definition at line 476 of file mg_processing\&.h\&.
.SS "double Breconstruction::bad_radius"

.PP
Definition at line 469 of file mg_processing\&.h\&.
.SS "int Breconstruction::block"

.PP
Definition at line 454 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<long> Breconstruction::box_size"

.PP
Definition at line 466 of file mg_processing\&.h\&.
.SS "\fBCTFparam\fP* Breconstruction::ctf"

.PP
Definition at line 473 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::ffil"

.PP
Definition at line 459 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::fft"

.PP
Definition at line 460 of file mg_processing\&.h\&.
.SS "\fBBfilament\fP* Breconstruction::fil"

.PP
Definition at line 475 of file mg_processing\&.h\&.
.SS "double Breconstruction::fil_node_radius"

.PP
Definition at line 468 of file mg_processing\&.h\&.
.SS "double Breconstruction::filament_width"

.PP
Definition at line 467 of file mg_processing\&.h\&.
.SS "double Breconstruction::fom"

.PP
Definition at line 472 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::fpart"

.PP
Definition at line 458 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::fps"

.PP
Definition at line 461 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::frec"

.PP
Definition at line 457 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::id"

.PP
Definition at line 452 of file mg_processing\&.h\&.
.SS "\fBBmarker\fP* Breconstruction::mark"

.PP
Definition at line 477 of file mg_processing\&.h\&.
.SS "double Breconstruction::mark_radius"

.PP
Definition at line 471 of file mg_processing\&.h\&.
.SS "\fBBstring\fP* Breconstruction::model"

.PP
Definition at line 479 of file mg_processing\&.h\&.
.SS "\fBBreconstruction\fP* Breconstruction::next"

.PP
Definition at line 451 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Breconstruction::origin"

.PP
Definition at line 463 of file mg_processing\&.h\&.
.SS "\fBBparticle\fP* Breconstruction::part"

.PP
Definition at line 474 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Breconstruction::scale"

.PP
Definition at line 464 of file mg_processing\&.h\&.
.SS "long Breconstruction::select"

.PP
Definition at line 453 of file mg_processing\&.h\&.
.SS "\fBBstrucfac\fP* Breconstruction::sf"

.PP
Definition at line 478 of file mg_processing\&.h\&.
.SS "double Breconstruction::sf_radius"

.PP
Definition at line 470 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Breconstruction::symmetry"

.PP
Definition at line 456 of file mg_processing\&.h\&.
.SS "int Breconstruction::type"

.PP
Definition at line 455 of file mg_processing\&.h\&.
.SS "\fBView\fP Breconstruction::view"

.PP
Definition at line 465 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Breconstruction::voxel_size"

.PP
Definition at line 462 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
