.TH "/Users/bernard/b20/bsoft/src/bscale.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bscale.cpp \- Program to find the scaling of map with respect to a reference\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to find the scaling of map with respect to a reference\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20160317 
.PP
Modified: 20170106 
.RE
.PP

.PP
Definition in file \fBbscale\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 45 of file bscale\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bscale [options] input\&.pif output\&.map",
"--------------------------------------------",
"Scales a map with respect to a reference\&.",
" ",
"Actions:",
"-bin 3                   Bin the images before comparison\&.",
"-average 7               Averaging/smoothing filter: kernel size\&.",
"-symmetry C5             Find point group symmetry equivalent\&.",
"-fit                     Fit the map to the reference\&.",
"-rescale -0\&.1,5\&.2        Rescale data to average and standard deviation\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-origin 0\&.8,-10,15\&.7     Set the origin (default from input image)\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Dimension scaling (default 1,1,1 A/pixel)\&.",
"-range 0\&.95,1\&.08,0\&.01    Scaling range and step size (default 0\&.99,1\&.01,0\&.01)\&.",
" ",
"Input:",
"-reference temp\&.map      Reference map to scale to\&.",
"-mask mask\&.mrc           Mask (must be the same size as the reference)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 18 of file bscale\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
