.TH "/Users/bernard/b20/bsoft/src/bseq.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bseq.cpp \- A program to manipulate DNA and protein sequences\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmolecule\&.h'\fP
.br
\fC#include 'rwgencode\&.h'\fP
.br
\fC#include 'seq_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A program to manipulate DNA and protein sequences\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000808 
.PP
Modified: 20190613 
.RE
.PP

.PP
Definition in file \fBbseq\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 50 of file bseq\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bseq [options] input\&.seq output\&.seq",
"------------------------------------------",
"Manipulates DNA and protein sequences\&.",
" ",
"Actions:",
"-show                    Show all DNA and protein sequences after other operations\&.",
"-Mass                    Show the calculated mass for each sequence\&.",
"-complement              Complement all DNA sequences before other operations\&.",
"-translate 1             Translate all DNA sequences with this frame (0,1,2)\&.",
"-finddna ggattcga        DNA sequence to look for in DNA sequences\&.",
"-findprotein fghwereaas  Protein sequence to look for in protein sequences\&.",
"-findcoding aklsdrtv     Coding sequence to look for in DNA sequences\&.",
"                         Can be a file name with a protein sequence\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-nogaps                  Strip gaps from input sequences\&.",
"-length 1100,1500        Sequence length range to select for\&.",
"-number 10,14            Number of residues on either side to include in output\&.",
"-threshold 50            Threshold percentage to report hits (default only best hit)\&.",
" ",
"Input:",
"-geneticcode file\&.star   Genetic code file (default = internal values)\&.",
"-elements prop\&.star      Calculate elemental composition\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bseq\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
