.TH "/Users/bernard/b20/bsoft/tcltk/bshow.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/bshow.cpp \- A shared object to load Bsoft image files in TCL/Tk\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br
\fC#include 'tcltk_bimage\&.h'\fP
.br
\fC#include 'tcltk_bmg\&.h'\fP
.br
\fC#include 'tcltk_bmodel\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBshow_Init\fP (Tcl_Interp *interp)"
.br
.ti -1c
.RI "int \fBBshow_SafeInit\fP (Tcl_Interp *interp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "string \fBcommand\fP"
.br
.ti -1c
.RI "\fBBimage\fP * \fBimglist\fP = NULL"
.br
.ti -1c
.RI "\fBBproject\fP * \fBproject\fP = NULL"
.br
.ti -1c
.RI "\fBBmodel\fP * \fBmodel\fP = NULL"
.br
.ti -1c
.RI "\fBBimage\fP * \fBimgtemp\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
A shared object to load Bsoft image files in TCL/Tk\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010210 
.PP
Modified: 20200514 
.RE
.PP

.PP
Definition in file \fBbshow\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int Bshow_Init (Tcl_Interp * interp)"

.PP
Definition at line 39 of file bshow\&.cpp\&.
.SS "int Bshow_SafeInit (Tcl_Interp * interp)"

.PP
Definition at line 51 of file bshow\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "string command\fC [extern]\fP"

.PP
Definition at line 20 of file utilities\&.cpp\&.
.SS "\fBBimage\fP* imglist = NULL"

.PP
Definition at line 32 of file bshow\&.cpp\&.
.SS "\fBBimage\fP* imgtemp = NULL"

.PP
Definition at line 36 of file bshow\&.cpp\&.
.SS "\fBBmodel\fP* model = NULL"

.PP
Definition at line 34 of file bshow\&.cpp\&.
.SS "\fBBproject\fP* project = NULL"

.PP
Definition at line 33 of file bshow\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
