.TH "/Users/bernard/b20/bsoft/src/bsim.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bsim.cpp \- A tool to generate a project with random orientations for a molecule and to simulate TEM images from given orientations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_multislice\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'rwmolecule\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A tool to generate a project with random orientations for a molecule and to simulate TEM images from given orientations\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20030805 
.PP
Modified: 20041021 
.RE
.PP

.PP
Definition in file \fBbsim\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 87 of file bsim\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 21 of file bsim\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
