.TH "/Users/bernard/b20/bsoft/tcltk/bsoft_tcl.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/bsoft_tcl.cpp \- A stub function to interface the Bsoft library within TCL/Tk\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBsoft_tcl_Init\fP (Tcl_Interp *interp)"
.br
.ti -1c
.RI "int \fBBsoft_tcl_SafeInit\fP (Tcl_Interp *interp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A stub function to interface the Bsoft library within TCL/Tk\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010210 
.PP
Modified: 20010302 
.RE
.PP

.PP
Definition in file \fBbsoft_tcl\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int Bsoft_tcl_Init (Tcl_Interp * interp)"

.PP
Definition at line 13 of file bsoft_tcl\&.cpp\&.
.SS "int Bsoft_tcl_SafeInit (Tcl_Interp * interp)"

.PP
Definition at line 18 of file bsoft_tcl\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
