.TH "/Users/bernard/b20/bsoft/src/bsplit.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bsplit.cpp \- Program to seperate a multi-image file into individual image files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'Bstring\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to seperate a multi-image file into individual image files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20001026 
.PP
Modified: 20110804 
.RE
.PP

.PP
Definition in file \fBbsplit\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 42 of file bsplit\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bsplit [options] input\&.img output\&.img",
"--------------------------------------------",
"Splits multi-image files of the following formats:",
"Digital Instruments (di), Imagic (img), Image Magick (miff), PIF (pif)", 
"SPIDER (spi), TIFF (tif), RAW (raw)\&.",
"Files of single image 3D image formats can be split with the -images option\&.",
" ",
"Actions:",
"-images                  Interpret slices of a single 3D image as 2D images\&.",
"-invert                  Invert density in the image\&.","-reslice -z+xy           Reslice = switch axes (default xyz)\&.",
"-select 1,5-13,122       Sub-images to select (first image = 0, default all)\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-first 5                 Number given to the first file (default 0)\&.",
"-digits 3                Number of digits inserted before the last period in the output file name\&.",
" ",
NULL
}
.fi
.PP
Definition at line 19 of file bsplit\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
