.TH "BstarLoop" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BstarLoop \- Structure for a table of entries in a STAR database block\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <star\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBstarLoop\fP ()"
.br
.ti -1c
.RI "\fBBstarLoop\fP (ifstream &fstar)"
.br
.ti -1c
.RI "int \fBwrite\fP (ofstream &fstar)"
.br
.ti -1c
.RI "map< string, int > & \fBtags\fP ()"
.br
.ti -1c
.RI "void \fBtags\fP (map< string, int > &t)"
.br
.ti -1c
.RI "vector< vector< string > > & \fBdata\fP ()"
.br
.ti -1c
.RI "long \fBtag\fP (const string &t)"
.br
.ti -1c
.RI "long \fBfind\fP (const string &t)"
.br
.ti -1c
.RI "long \fBcolumns\fP ()"
.br
.ti -1c
.RI "long \fBrows\fP ()"
.br
.ti -1c
.RI "void \fBadd_row\fP (vector< string > vs)"
.br
.ti -1c
.RI "vector< string > & \fBadd_row\fP (long i)"
.br
.ti -1c
.RI "vector< string > & \fBoperator[]\fP (long i)"
.br
.ti -1c
.RI "string \fBvalue\fP (long i, const string &t)"
.br
.ti -1c
.RI "long \fBinteger\fP (long i, const string &t)"
.br
.ti -1c
.RI "long \fBinteger\fP (long i, long j)"
.br
.ti -1c
.RI "double \fBreal\fP (long i, const string &t)"
.br
.ti -1c
.RI "double \fBreal\fP (long i, long j)"
.br
.ti -1c
.RI "void \fBerase\fP (const string &t)"
.br
.ti -1c
.RI "void \fBreplace_tag\fP (string oldtag, string newtag)"
.br
.ti -1c
.RI "void \fBshow_tags\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for a table of entries in a STAR database block\&. 


.PP
.nf
Each item consists of a string or a zero-delimited sequence of strings.
The tag map values indicate the order of the row elements and must be set up properly.

.fi
.PP
 
.PP
Definition at line 30 of file star\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BstarLoop::BstarLoop ()\fC [inline]\fP"

.PP
Definition at line 35 of file star\&.h\&.
.SS "BstarLoop::BstarLoop (ifstream & fstar)\fC [inline]\fP"

.PP
Definition at line 36 of file star\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "vector<string>& BstarLoop::add_row (long i)\fC [inline]\fP"

.PP
Definition at line 91 of file star\&.h\&.
.SS "void BstarLoop::add_row (vector< string > vs)\fC [inline]\fP"

.PP
Definition at line 90 of file star\&.h\&.
.SS "long BstarLoop::columns ()\fC [inline]\fP"

.PP
Definition at line 88 of file star\&.h\&.
.SS "vector< vector<string> >& BstarLoop::data ()\fC [inline]\fP"

.PP
Definition at line 81 of file star\&.h\&.
.SS "void BstarLoop::erase (const string & t)\fC [inline]\fP"

.PP
Definition at line 113 of file star\&.h\&.
.SS "long BstarLoop::find (const string & t)\fC [inline]\fP"

.PP
Definition at line 83 of file star\&.h\&.
.SS "long BstarLoop::integer (long i, const string & t)\fC [inline]\fP"

.PP
Definition at line 97 of file star\&.h\&.
.SS "long BstarLoop::integer (long i, long j)\fC [inline]\fP"

.PP
Definition at line 101 of file star\&.h\&.
.SS "vector<string>& BstarLoop::operator[] (long i)\fC [inline]\fP"

.PP
Definition at line 92 of file star\&.h\&.
.SS "double BstarLoop::real (long i, const string & t)\fC [inline]\fP"

.PP
Definition at line 105 of file star\&.h\&.
.SS "double BstarLoop::real (long i, long j)\fC [inline]\fP"

.PP
Definition at line 109 of file star\&.h\&.
.SS "void BstarLoop::replace_tag (string oldtag, string newtag)\fC [inline]\fP"

.PP
Definition at line 118 of file star\&.h\&.
.SS "long BstarLoop::rows ()\fC [inline]\fP"

.PP
Definition at line 89 of file star\&.h\&.
.SS "void BstarLoop::show_tags ()\fC [inline]\fP"

.PP
Definition at line 124 of file star\&.h\&.
.SS "long BstarLoop::tag (const string & t)\fC [inline]\fP"

.PP
Definition at line 82 of file star\&.h\&.
.SS "map<string, int>& BstarLoop::tags ()\fC [inline]\fP"

.PP
Definition at line 79 of file star\&.h\&.
.SS "void BstarLoop::tags (map< string, int > & t)\fC [inline]\fP"

.PP
Definition at line 80 of file star\&.h\&.
.SS "string BstarLoop::value (long i, const string & t)\fC [inline]\fP"

.PP
Definition at line 93 of file star\&.h\&.
.SS "int BstarLoop::write (ofstream & fstar)\fC [inline]\fP"

.PP
Definition at line 56 of file star\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
