.TH "Bstar2" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bstar2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <star\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBstar2\fP ()"
.br
.ti -1c
.RI "\fBBstar2\fP (string filename)"
.br
.ti -1c
.RI "int \fBread\fP (string filename)"
.br
.RI "Reads paramaters and data into a STAR data base from a file\&. "
.ti -1c
.RI "int \fBwrite\fP (string filename)"
.br
.RI "Writes a STAR data base to a STAR format file\&. "
.ti -1c
.RI "int \fBwrite\fP (string filename, int \fBsplit\fP)"
.br
.ti -1c
.RI "void \fBline_length\fP (long i)"
.br
.ti -1c
.RI "long \fBline_length\fP ()"
.br
.ti -1c
.RI "void \fBcomment\fP (const string &s)"
.br
.ti -1c
.RI "string & \fBcomment\fP ()"
.br
.ti -1c
.RI "long \fBlist_comments\fP (long len)"
.br
.ti -1c
.RI "vector< \fBBstarBlock\fP > & \fBblocks\fP ()"
.br
.ti -1c
.RI "bool \fBexists\fP (string t)"
.br
.ti -1c
.RI "\fBBstarBlock\fP & \fBblock\fP (long i)"
.br
.ti -1c
.RI "\fBBstarBlock\fP & \fBfind\fP (string t)"
.br
.ti -1c
.RI "\fBBstarBlock\fP & \fBadd_block\fP (const string &s)"
.br
.ti -1c
.RI "long \fBnumber_of_blocks\fP (string t)"
.br
.ti -1c
.RI "void \fBreplace_tag\fP (string oldtag, string newtag)"
.br
.ti -1c
.RI "void \fBerase\fP (const string &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 301 of file star\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bstar2::Bstar2 ()\fC [inline]\fP"

.PP
Definition at line 307 of file star\&.h\&.
.SS "Bstar2::Bstar2 (string filename)\fC [inline]\fP"

.PP
Definition at line 308 of file star\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBstarBlock\fP& Bstar2::add_block (const string & s)\fC [inline]\fP"

.PP
Definition at line 437 of file star\&.h\&.
.SS "\fBBstarBlock\fP& Bstar2::block (long i)\fC [inline]\fP"

.PP
Definition at line 426 of file star\&.h\&.
.SS "vector<\fBBstarBlock\fP>& Bstar2::blocks ()\fC [inline]\fP"

.PP
Definition at line 420 of file star\&.h\&.
.SS "string& Bstar2::comment ()\fC [inline]\fP"

.PP
Definition at line 406 of file star\&.h\&.
.SS "void Bstar2::comment (const string & s)\fC [inline]\fP"

.PP
Definition at line 405 of file star\&.h\&.
.SS "void Bstar2::erase (const string & s)\fC [inline]\fP"

.PP
Definition at line 450 of file star\&.h\&.
.SS "bool Bstar2::exists (string t)\fC [inline]\fP"

.PP
Definition at line 421 of file star\&.h\&.
.SS "\fBBstarBlock\fP& Bstar2::find (string t)\fC [inline]\fP"

.PP
Definition at line 432 of file star\&.h\&.
.SS "long Bstar2::line_length ()\fC [inline]\fP"

.PP
Definition at line 404 of file star\&.h\&.
.SS "void Bstar2::line_length (long i)\fC [inline]\fP"

.PP
Definition at line 403 of file star\&.h\&.
.SS "long Bstar2::list_comments (long len)\fC [inline]\fP"

.PP
Definition at line 407 of file star\&.h\&.
.SS "long Bstar2::number_of_blocks (string t)\fC [inline]\fP"

.PP
Definition at line 441 of file star\&.h\&.
.SS "int Bstar2::read (string filename)\fC [inline]\fP"

.PP
Reads paramaters and data into a STAR data base from a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP a file name\&. 
.PP
.nf
Every data block is read separately and comments are preserved as far 
as possible.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 317 of file star\&.h\&.
.SS "void Bstar2::replace_tag (string oldtag, string newtag)\fC [inline]\fP"

.PP
Definition at line 447 of file star\&.h\&.
.SS "int Bstar2::write (string filename)\fC [inline]\fP"

.PP
Writes a STAR data base to a STAR format file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 355 of file star\&.h\&.
.SS "int Bstar2::write (string filename, int split)\fC [inline]\fP"

.PP
Definition at line 378 of file star\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
