.TH "BstarBlock" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BstarBlock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <star\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBstarBlock\fP ()"
.br
.ti -1c
.RI "\fBBstarBlock\fP (const string &s)"
.br
.ti -1c
.RI "string \fBread\fP (ifstream &fstar)"
.br
.ti -1c
.RI "int \fBwrite\fP (ofstream &fstar)"
.br
.ti -1c
.RI "int \fBwrite\fP (string filename)"
.br
.ti -1c
.RI "string \fBtag\fP ()"
.br
.ti -1c
.RI "void \fBfile_name\fP (string s)"
.br
.ti -1c
.RI "string \fBfile_name\fP ()"
.br
.ti -1c
.RI "string & \fBoperator[]\fP (const string &t)"
.br
.ti -1c
.RI "bool \fBexists\fP (const string &t)"
.br
.ti -1c
.RI "bool \fBexists_loop\fP (const string &t)"
.br
.ti -1c
.RI "string \fBat\fP (const string &t)"
.br
.ti -1c
.RI "long \fBinteger\fP (const string &t)"
.br
.ti -1c
.RI "double \fBreal\fP (const string &t)"
.br
.ti -1c
.RI "map< string, string > & \fBitems\fP ()"
.br
.ti -1c
.RI "void \fBerase\fP (const string &t)"
.br
.ti -1c
.RI "vector< \fBBstarLoop\fP > & \fBloops\fP ()"
.br
.ti -1c
.RI "\fBBstarLoop\fP & \fBloop\fP (long i)"
.br
.ti -1c
.RI "\fBBstarLoop\fP & \fBadd_loop\fP ()"
.br
.ti -1c
.RI "void \fBreplace_tag\fP (string oldtag, string newtag)"
.br
.ti -1c
.RI "void \fBshow_tags\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file star\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BstarBlock::BstarBlock ()\fC [inline]\fP"

.PP
Definition at line 147 of file star\&.h\&.
.SS "BstarBlock::BstarBlock (const string & s)\fC [inline]\fP"

.PP
Definition at line 148 of file star\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBstarLoop\fP& BstarBlock::add_loop ()\fC [inline]\fP"

.PP
Definition at line 270 of file star\&.h\&.
.SS "string BstarBlock::at (const string & t)\fC [inline]\fP"

.PP
Definition at line 242 of file star\&.h\&.
.SS "void BstarBlock::erase (const string & t)\fC [inline]\fP"

.PP
Definition at line 260 of file star\&.h\&.
.SS "bool BstarBlock::exists (const string & t)\fC [inline]\fP"

.PP
Definition at line 233 of file star\&.h\&.
.SS "bool BstarBlock::exists_loop (const string & t)\fC [inline]\fP"

.PP
Definition at line 237 of file star\&.h\&.
.SS "string BstarBlock::file_name ()\fC [inline]\fP"

.PP
Definition at line 231 of file star\&.h\&.
.SS "void BstarBlock::file_name (string s)\fC [inline]\fP"

.PP
Definition at line 230 of file star\&.h\&.
.SS "long BstarBlock::integer (const string & t)\fC [inline]\fP"

.PP
Definition at line 247 of file star\&.h\&.
.SS "map<string,string>& BstarBlock::items ()\fC [inline]\fP"

.PP
Definition at line 259 of file star\&.h\&.
.SS "\fBBstarLoop\fP& BstarBlock::loop (long i)\fC [inline]\fP"

.PP
Definition at line 264 of file star\&.h\&.
.SS "vector<\fBBstarLoop\fP>& BstarBlock::loops ()\fC [inline]\fP"

.PP
Definition at line 263 of file star\&.h\&.
.SS "string& BstarBlock::operator[] (const string & t)\fC [inline]\fP"

.PP
Definition at line 232 of file star\&.h\&.
.SS "string BstarBlock::read (ifstream & fstar)\fC [inline]\fP"

.PP
Definition at line 153 of file star\&.h\&.
.SS "double BstarBlock::real (const string & t)\fC [inline]\fP"

.PP
Definition at line 252 of file star\&.h\&.
.SS "void BstarBlock::replace_tag (string oldtag, string newtag)\fC [inline]\fP"

.PP
Definition at line 274 of file star\&.h\&.
.SS "void BstarBlock::show_tags ()\fC [inline]\fP"

.PP
Definition at line 282 of file star\&.h\&.
.SS "string BstarBlock::tag ()\fC [inline]\fP"

.PP
Definition at line 229 of file star\&.h\&.
.SS "int BstarBlock::write (ofstream & fstar)\fC [inline]\fP"

.PP
Definition at line 183 of file star\&.h\&.
.SS "int BstarBlock::write (string filename)\fC [inline]\fP"

.PP
Definition at line 208 of file star\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
