.TH "Bstrucfac" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bstrucfac
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBstrucfac\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBstrucfac\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBloc\fP"
.br
.ti -1c
.RI "\fBVector3\fP< int > \fBindex\fP"
.br
.ti -1c
.RI "double \fBamp\fP"
.br
.ti -1c
.RI "double \fBsigamp\fP"
.br
.ti -1c
.RI "double \fBphi\fP"
.br
.ti -1c
.RI "double \fBsigphi\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "long \fBsel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bstrucfac::Bstrucfac ()\fC [inline]\fP"

.PP
Definition at line 229 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Bstrucfac::amp"

.PP
Definition at line 223 of file mg_processing\&.h\&.
.SS "double Bstrucfac::fom"

.PP
Definition at line 227 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<int> Bstrucfac::index"

.PP
Definition at line 222 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bstrucfac::loc"

.PP
Definition at line 221 of file mg_processing\&.h\&.
.SS "\fBBstrucfac\fP* Bstrucfac::next"

.PP
Definition at line 220 of file mg_processing\&.h\&.
.SS "double Bstrucfac::phi"

.PP
Definition at line 225 of file mg_processing\&.h\&.
.SS "long Bstrucfac::sel"

.PP
Definition at line 228 of file mg_processing\&.h\&.
.SS "double Bstrucfac::sigamp"

.PP
Definition at line 224 of file mg_processing\&.h\&.
.SS "double Bstrucfac::sigphi"

.PP
Definition at line 226 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
