.TH "Bsub_image" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bsub_image \- General sub-image parameter class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bimage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBsub_image\fP ()"
.br
.RI "Initializes a sub-image\&. "
.ti -1c
.RI "double \fBminimum\fP ()"
.br
.ti -1c
.RI "double \fBmaximum\fP ()"
.br
.ti -1c
.RI "double \fBaverage\fP ()"
.br
.ti -1c
.RI "double \fBstandard_deviation\fP ()"
.br
.ti -1c
.RI "double \fBvariance\fP ()"
.br
.ti -1c
.RI "void \fBminimum\fP (double d)"
.br
.ti -1c
.RI "void \fBmaximum\fP (double d)"
.br
.ti -1c
.RI "void \fBaverage\fP (double d)"
.br
.ti -1c
.RI "void \fBstandard_deviation\fP (double d)"
.br
.ti -1c
.RI "double \fBbackground\fP ()"
.br
.ti -1c
.RI "void \fBbackground\fP (double d)"
.br
.ti -1c
.RI "void \fBsampling\fP (double x, double y, double z)"
.br
.ti -1c
.RI "void \fBsampling\fP (\fBVector3\fP< double > vec)"
.br
.ti -1c
.RI "void \fBsampling\fP (vector< double > vec)"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBsampling\fP ()"
.br
.ti -1c
.RI "void \fBorigin\fP (double x, double y, double z)"
.br
.ti -1c
.RI "void \fBorigin\fP (\fBVector3\fP< double > vec)"
.br
.ti -1c
.RI "void \fBorigin\fP (vector< double > vec)"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBorigin\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBreal_coordinates\fP (long ix, long iy, long iz)"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBreal_coordinates\fP (\fBVector3\fP< long > ic)"
.br
.ti -1c
.RI "\fBVector3\fP< long > \fBimage_coordinates\fP (double xx, double yy, double zz)"
.br
.ti -1c
.RI "\fBVector3\fP< long > \fBimage_coordinates\fP (\fBVector3\fP< double > rc)"
.br
.ti -1c
.RI "void \fBview\fP (double x, double y, double z, double a)"
.br
.ti -1c
.RI "void \fBview\fP (\fBView\fP vw)"
.br
.ti -1c
.RI "void \fBview\fP (vector< double > vw)"
.br
.ti -1c
.RI "\fBView\fP \fBview\fP ()"
.br
.ti -1c
.RI "void \fBview_angle\fP (double d)"
.br
.ti -1c
.RI "double \fBview_angle\fP ()"
.br
.ti -1c
.RI "double \fBmagnification\fP ()"
.br
.ti -1c
.RI "void \fBmagnification\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
General sub-image parameter class\&. 


.PP
.nf
This contains all the information pertinent to a single image in a
multi-image file.

.fi
.PP
 
.PP
Definition at line 72 of file Bimage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bsub_image::Bsub_image ()"

.PP
Initializes a sub-image\&. 
.PP
.nf
All values are set to zero except mag and fom, set to one.

.fi
.PP
 
.PP
Definition at line 24 of file Bimage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double Bsub_image::average ()\fC [inline]\fP"

.PP
Definition at line 102 of file Bimage\&.h\&.
.SS "void Bsub_image::average (double d)\fC [inline]\fP"

.PP
Definition at line 107 of file Bimage\&.h\&.
.SS "double Bsub_image::background ()\fC [inline]\fP"

.PP
Definition at line 109 of file Bimage\&.h\&.
.SS "void Bsub_image::background (double d)\fC [inline]\fP"

.PP
Definition at line 110 of file Bimage\&.h\&.
.SS "double Bsub_image::FOM ()\fC [inline]\fP"

.PP
Definition at line 149 of file Bimage\&.h\&.
.SS "void Bsub_image::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 150 of file Bimage\&.h\&.
.SS "\fBVector3\fP<long> Bsub_image::image_coordinates (double xx, double yy, double zz)\fC [inline]\fP"

.PP
Definition at line 135 of file Bimage\&.h\&.
.SS "\fBVector3\fP<long> Bsub_image::image_coordinates (\fBVector3\fP< double > rc)\fC [inline]\fP"

.PP
Definition at line 138 of file Bimage\&.h\&.
.SS "double Bsub_image::magnification ()\fC [inline]\fP"

.PP
Definition at line 147 of file Bimage\&.h\&.
.SS "void Bsub_image::magnification (double d)\fC [inline]\fP"

.PP
Definition at line 148 of file Bimage\&.h\&.
.SS "double Bsub_image::maximum ()\fC [inline]\fP"

.PP
Definition at line 101 of file Bimage\&.h\&.
.SS "void Bsub_image::maximum (double d)\fC [inline]\fP"

.PP
Definition at line 106 of file Bimage\&.h\&.
.SS "double Bsub_image::minimum ()\fC [inline]\fP"

.PP
Definition at line 100 of file Bimage\&.h\&.
.SS "void Bsub_image::minimum (double d)\fC [inline]\fP"

.PP
Definition at line 105 of file Bimage\&.h\&.
.SS "\fBVector3\fP<double> Bsub_image::origin ()\fC [inline]\fP"

.PP
Definition at line 128 of file Bimage\&.h\&.
.SS "void Bsub_image::origin (double x, double y, double z)\fC [inline]\fP"

.PP
Definition at line 120 of file Bimage\&.h\&.
.SS "void Bsub_image::origin (\fBVector3\fP< double > vec)\fC [inline]\fP"

.PP
Definition at line 121 of file Bimage\&.h\&.
.SS "void Bsub_image::origin (vector< double > vec)\fC [inline]\fP"

.PP
Definition at line 122 of file Bimage\&.h\&.
.SS "\fBVector3\fP<double> Bsub_image::real_coordinates (long ix, long iy, long iz)\fC [inline]\fP"

.PP
Definition at line 129 of file Bimage\&.h\&.
.SS "\fBVector3\fP<double> Bsub_image::real_coordinates (\fBVector3\fP< long > ic)\fC [inline]\fP"

.PP
Definition at line 132 of file Bimage\&.h\&.
.SS "\fBVector3\fP<double> Bsub_image::sampling ()\fC [inline]\fP"

.PP
Definition at line 119 of file Bimage\&.h\&.
.SS "void Bsub_image::sampling (double x, double y, double z)\fC [inline]\fP"

.PP
Definition at line 111 of file Bimage\&.h\&.
.SS "void Bsub_image::sampling (\fBVector3\fP< double > vec)\fC [inline]\fP"

.PP
Definition at line 112 of file Bimage\&.h\&.
.SS "void Bsub_image::sampling (vector< double > vec)\fC [inline]\fP"

.PP
Definition at line 113 of file Bimage\&.h\&.
.SS "long Bsub_image::select ()\fC [inline]\fP"

.PP
Definition at line 151 of file Bimage\&.h\&.
.SS "void Bsub_image::select (long i)\fC [inline]\fP"

.PP
Definition at line 152 of file Bimage\&.h\&.
.SS "double Bsub_image::standard_deviation ()\fC [inline]\fP"

.PP
Definition at line 103 of file Bimage\&.h\&.
.SS "void Bsub_image::standard_deviation (double d)\fC [inline]\fP"

.PP
Definition at line 108 of file Bimage\&.h\&.
.SS "double Bsub_image::variance ()\fC [inline]\fP"

.PP
Definition at line 104 of file Bimage\&.h\&.
.SS "\fBView\fP Bsub_image::view ()\fC [inline]\fP"

.PP
Definition at line 144 of file Bimage\&.h\&.
.SS "void Bsub_image::view (double x, double y, double z, double a)\fC [inline]\fP"

.PP
Definition at line 141 of file Bimage\&.h\&.
.SS "void Bsub_image::view (vector< double > vw)\fC [inline]\fP"

.PP
Definition at line 143 of file Bimage\&.h\&.
.SS "void Bsub_image::view (\fBView\fP vw)\fC [inline]\fP"

.PP
Definition at line 142 of file Bimage\&.h\&.
.SS "double Bsub_image::view_angle ()\fC [inline]\fP"

.PP
Definition at line 146 of file Bimage\&.h\&.
.SS "void Bsub_image::view_angle (double d)\fC [inline]\fP"

.PP
Definition at line 145 of file Bimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
