.TH "/Users/bernard/b20/bsoft/src/bsupix.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bsupix.cpp \- Segment images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "vector< \fBBsuperpixel\fP > \fBsuperpixel_from_json\fP (\fBJSvalue\fP &root)"
.br
.ti -1c
.RI "\fBJSvalue\fP \fBjson_from_superpixel\fP (vector< \fBBsuperpixel\fP > &seg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "\fBJSvalue\fP \fBjsvalue_from_neighbors\fP (\fBBsuperpixel\fP &sp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Segment images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20160320 
.PP
Modified: 20210303 
.RE
.PP

.PP
Definition in file \fBbsupix\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBJSvalue\fP json_from_superpixel (vector< \fBBsuperpixel\fP > & seg)"

.PP
Definition at line 269 of file bsupix\&.cpp\&.
.SS "\fBJSvalue\fP jsvalue_from_neighbors (\fBBsuperpixel\fP & sp)"

.PP
Definition at line 258 of file bsupix\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 65 of file bsupix\&.cpp\&.
.SS "vector< \fBBsuperpixel\fP > superpixel_from_json (\fBJSvalue\fP & root)"

.PP
Definition at line 228 of file bsupix\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 22 of file bsupix\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
