.TH "Bsuperpixel" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bsuperpixel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bsuperpixel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBsuperpixel\fP ()"
.br
.ti -1c
.RI "void \fBindex\fP (long i)"
.br
.ti -1c
.RI "long \fBindex\fP ()"
.br
.ti -1c
.RI "void \fBcount\fP (long i)"
.br
.ti -1c
.RI "long \fBcount\fP ()"
.br
.ti -1c
.RI "void \fBcoordinates\fP (vector< double > &c)"
.br
.ti -1c
.RI "vector< double > & \fBcoordinates\fP ()"
.br
.ti -1c
.RI "void \fBchannels\fP (long nc)"
.br
.ti -1c
.RI "void \fBchannels\fP (vector< double > &v)"
.br
.ti -1c
.RI "void \fBvariances\fP (vector< double > &v)"
.br
.ti -1c
.RI "vector< double > & \fBchannels\fP ()"
.br
.ti -1c
.RI "vector< double > & \fBvariances\fP ()"
.br
.ti -1c
.RI "double \fBchannel\fP (long i)"
.br
.ti -1c
.RI "double \fBvariance\fP (long i)"
.br
.ti -1c
.RI "void \fBweight\fP (double w)"
.br
.ti -1c
.RI "double \fBweight\fP ()"
.br
.ti -1c
.RI "void \fBneighbor\fP (long i, long j)"
.br
.ti -1c
.RI "long \fBneighbor\fP (long i)"
.br
.ti -1c
.RI "void \fBneighbors\fP (vector< long > &v)"
.br
.ti -1c
.RI "void \fBadd_neighbor\fP (long i)"
.br
.ti -1c
.RI "void \fBclear_neighbors\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (long cx, long cy, long cz, vector< double > v)"
.br
.ti -1c
.RI "void \fBadd\fP (vector< long > c, vector< double > v)"
.br
.ti -1c
.RI "void \fBaverage\fP ()"
.br
.ti -1c
.RI "double \fBdifference2\fP (vector< double > v)"
.br
.ti -1c
.RI "void \fBscale\fP (double s)"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Bsuperpixel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bsuperpixel::Bsuperpixel ()\fC [inline]\fP"

.PP
Definition at line 25 of file Bsuperpixel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Bsuperpixel::add (long cx, long cy, long cz, vector< double > v)\fC [inline]\fP"

.PP
Definition at line 84 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::add (vector< long > c, vector< double > v)\fC [inline]\fP"

.PP
Definition at line 94 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::add_neighbor (long i)\fC [inline]\fP"

.PP
Definition at line 64 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::average ()\fC [inline]\fP"

.PP
Definition at line 97 of file Bsuperpixel\&.h\&.
.SS "double Bsuperpixel::channel (long i)\fC [inline]\fP"

.PP
Definition at line 55 of file Bsuperpixel\&.h\&.
.SS "vector<double>& Bsuperpixel::channels ()\fC [inline]\fP"

.PP
Definition at line 53 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::channels (long nc)\fC [inline]\fP"

.PP
Definition at line 35 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::channels (vector< double > & v)\fC [inline]\fP"

.PP
Definition at line 39 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::clear ()\fC [inline]\fP"

.PP
Definition at line 77 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::clear_neighbors ()\fC [inline]\fP"

.PP
Definition at line 73 of file Bsuperpixel\&.h\&.
.SS "vector<double>& Bsuperpixel::coordinates ()\fC [inline]\fP"

.PP
Definition at line 34 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::coordinates (vector< double > & c)\fC [inline]\fP"

.PP
Definition at line 33 of file Bsuperpixel\&.h\&.
.SS "long Bsuperpixel::count ()\fC [inline]\fP"

.PP
Definition at line 32 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::count (long i)\fC [inline]\fP"

.PP
Definition at line 31 of file Bsuperpixel\&.h\&.
.SS "double Bsuperpixel::difference2 (vector< double > v)\fC [inline]\fP"

.PP
Definition at line 107 of file Bsuperpixel\&.h\&.
.SS "long Bsuperpixel::index ()\fC [inline]\fP"

.PP
Definition at line 30 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::index (long i)\fC [inline]\fP"

.PP
Definition at line 29 of file Bsuperpixel\&.h\&.
.SS "long Bsuperpixel::neighbor (long i)\fC [inline]\fP"

.PP
Definition at line 60 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::neighbor (long i, long j)\fC [inline]\fP"

.PP
Definition at line 59 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::neighbors (vector< long > & v)\fC [inline]\fP"

.PP
Definition at line 61 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::scale (double s)\fC [inline]\fP"

.PP
Definition at line 113 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::show ()\fC [inline]\fP"

.PP
Definition at line 117 of file Bsuperpixel\&.h\&.
.SS "double Bsuperpixel::variance (long i)\fC [inline]\fP"

.PP
Definition at line 56 of file Bsuperpixel\&.h\&.
.SS "vector<double>& Bsuperpixel::variances ()\fC [inline]\fP"

.PP
Definition at line 54 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::variances (vector< double > & v)\fC [inline]\fP"

.PP
Definition at line 46 of file Bsuperpixel\&.h\&.
.SS "double Bsuperpixel::weight ()\fC [inline]\fP"

.PP
Definition at line 58 of file Bsuperpixel\&.h\&.
.SS "void Bsuperpixel::weight (double w)\fC [inline]\fP"

.PP
Definition at line 57 of file Bsuperpixel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
