.TH "/Users/bernard/b20/bsoft/src/bsymcomp.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bsymcomp.cpp \- Finds the best orientation that fits a symmetrized template\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Finds the best orientation that fits a symmetrized template\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20070516 
.PP
Modified: 20150806 
.RE
.PP

.PP
Definition in file \fBbsymcomp\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 42 of file bsymcomp\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bsymcomp [options] input\&.img output\&.img",
"----------------------------------------------",
"Finds the best orientation that fits a symmetrized template\&.",
"The output is the rotated input image\&.",
" ",
"Parameters:",
"-verbose 1               Verbosity of output",
"-datatype u              Force writing of a new data type\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (A/pixel; default from input file; a single value can be given)\&.",
"-origin 110,50,44        Origin for rotations of the template (default taken from template image)\&.",
"-angles 8\&.8,2\&.5,5\&.2      Step size for alpha, theta and phi, one value sets all (default 45 degrees)\&.",
"-shift 0\&.5,3,-2\&.3        Shift to apply before symmetrization\&.",
"-symmetry C5             Point group symmetry\&.",
"-fill 0\&.02               Fill value (default image background)\&.",
" ",
"Input:",
"-Template image\&.map      Template with symmetry to search for\&.",
" ",
NULL
}
.fi
.PP
Definition at line 18 of file bsymcomp\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
