.TH "/Users/bernard/b20/bsoft/src/btomo.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/btomo.cpp \- Program to process tomographic series of images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_img_proc\&.h'\fP
.br
\fC#include 'mg_tomography\&.h'\fP
.br
\fC#include 'mg_align\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'rwmgIMOD\&.h'\fP
.br
\fC#include 'matrix_linear\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'qsort_functions\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'random_numbers\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBread_imod_tlt\fP (\fBBstring\fP &filename, \fBBproject\fP *\fBproject\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to process tomographic series of images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20020416 
.PP
Modified: 20210311 
.RE
.PP

.PP
Definition in file \fBbtomo\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 75 of file btomo\&.cpp\&.
.SS "int read_imod_tlt (\fBBstring\fP & filename, \fBBproject\fP * project)"

.PP
Definition at line 48 of file rwmgIMOD\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 32 of file btomo\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
