.TH "ChunkEntry" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkEntry\fP ()"
.br
.ti -1c
.RI "\fBChunkEntry\fP (string t, long p, long l)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtag\fP"
.br
.ti -1c
.RI "long \fBpos\fP"
.br
.ti -1c
.RI "long \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file rwND2\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChunkEntry::ChunkEntry ()\fC [inline]\fP"

.PP
Definition at line 35 of file rwND2\&.cpp\&.
.SS "ChunkEntry::ChunkEntry (string t, long p, long l)\fC [inline]\fP"

.PP
Definition at line 36 of file rwND2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "long ChunkEntry::len"

.PP
Definition at line 34 of file rwND2\&.cpp\&.
.SS "long ChunkEntry::pos"

.PP
Definition at line 33 of file rwND2\&.cpp\&.
.SS "string ChunkEntry::tag"

.PP
Definition at line 32 of file rwND2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
