.TH "CMYK< Type >" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMYK< Type >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Color\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMYK\fP ()"
.br
.ti -1c
.RI "\fBCMYK\fP (const \fBCMYK\fP &col)"
.br
.ti -1c
.RI "\fBCMYK\fP (const double d[4])"
.br
.ti -1c
.RI "\fBCMYK\fP (const vector< double > &d)"
.br
.ti -1c
.RI "\fBCMYK\fP (const double cc, const double mm, const double yy, const double kk)"
.br
.ti -1c
.RI "\fBCMYK\fP \fBoperator=\fP (const \fBCMYK\fP &col)"
.br
.ti -1c
.RI "\fBCMYK\fP (\fBRGB\fP< Type > &rgb)"
.br
.ti -1c
.RI "Type & \fBoperator[]\fP (const unsigned int i)"
.br
.ti -1c
.RI "Type \fBc\fP ()"
.br
.ti -1c
.RI "Type \fBm\fP ()"
.br
.ti -1c
.RI "Type \fBy\fP ()"
.br
.ti -1c
.RI "Type \fBk\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Type>
.br
class CMYK< Type >"

.PP
Definition at line 264 of file Color\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Type > \fBCMYK\fP< Type >::\fBCMYK\fP ()\fC [inline]\fP"

.PP
Definition at line 268 of file Color\&.h\&.
.SS "template<typename Type > \fBCMYK\fP< Type >::\fBCMYK\fP (const \fBCMYK\fP< Type > & col)\fC [inline]\fP"

.PP
Definition at line 269 of file Color\&.h\&.
.SS "template<typename Type > \fBCMYK\fP< Type >::\fBCMYK\fP (const double d[4])\fC [inline]\fP"

.PP
Definition at line 270 of file Color\&.h\&.
.SS "template<typename Type > \fBCMYK\fP< Type >::\fBCMYK\fP (const vector< double > & d)\fC [inline]\fP"

.PP
Definition at line 271 of file Color\&.h\&.
.SS "template<typename Type > \fBCMYK\fP< Type >::\fBCMYK\fP (const double cc, const double mm, const double yy, const double kk)\fC [inline]\fP"

.PP
Definition at line 272 of file Color\&.h\&.
.SS "template<typename Type > \fBCMYK\fP< Type >::\fBCMYK\fP (\fBRGB\fP< Type > & rgb)\fC [inline]\fP"

.PP
Definition at line 278 of file Color\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Type > Type \fBCMYK\fP< Type >::c ()\fC [inline]\fP"

.PP
Definition at line 301 of file Color\&.h\&.
.SS "template<typename Type > Type \fBCMYK\fP< Type >::k ()\fC [inline]\fP"

.PP
Definition at line 304 of file Color\&.h\&.
.SS "template<typename Type > Type \fBCMYK\fP< Type >::m ()\fC [inline]\fP"

.PP
Definition at line 302 of file Color\&.h\&.
.SS "template<typename Type > \fBCMYK\fP \fBCMYK\fP< Type >::operator= (const \fBCMYK\fP< Type > & col)\fC [inline]\fP"

.PP
Definition at line 274 of file Color\&.h\&.
.SS "template<typename Type > Type& \fBCMYK\fP< Type >::operator[] (const unsigned int i)\fC [inline]\fP"

.PP
Definition at line 297 of file Color\&.h\&.
.SS "template<typename Type > Type \fBCMYK\fP< Type >::y ()\fC [inline]\fP"

.PP
Definition at line 303 of file Color\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
