.TH "/Users/bernard/b20/bsoft/include/Color.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/Color.h \- Classes for color objects\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bstring\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRGB< Type >\fP"
.br
.ti -1c
.RI "class \fBRGBA< Type >\fP"
.br
.ti -1c
.RI "class \fBCMYK< Type >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Type > ostream & \fBoperator<<\fP (ostream &output, \fBRGB\fP< Type > rgb)"
.br
.ti -1c
.RI "template<typename Type > ostream & \fBoperator<<\fP (ostream &output, \fBRGBA\fP< Type > rgba)"
.br
.ti -1c
.RI "template<typename Type > ostream & \fBoperator<<\fP (ostream &output, \fBCMYK\fP< Type > cmyk)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classes for color objects\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20050112 
.PP
Modified: 20170420 
.RE
.PP

.PP
Definition in file \fBColor\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "template<typename Type > ostream& operator<< (ostream & output, \fBCMYK\fP< Type > cmyk)"

.PP
Definition at line 308 of file Color\&.h\&.
.SS "template<typename Type > ostream& operator<< (ostream & output, \fBRGB\fP< Type > rgb)"

.PP
Definition at line 148 of file Color\&.h\&.
.SS "template<typename Type > ostream& operator<< (ostream & output, \fBRGBA\fP< Type > rgba)"

.PP
Definition at line 250 of file Color\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
