.TH "/Users/bernard/b20/bsoft/src/dcount.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/dcount.cpp \- A program to determine the occupancy of components in models\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'rwmodel\&.h'\fP
.br
\fC#include 'model_occupancy\&.h'\fP
.br
\fC#include 'model_select\&.h'\fP
.br
\fC#include 'model_util\&.h'\fP
.br
\fC#include 'ps_model\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A program to determine the occupancy of components in models\&. 


.PP
\fBAuthor\fP
.RS 4
Daniel Nemecek and Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20091202 (DN) 
.PP
Modified: 20110729 (BH) 
.PP
Updated 20110507 (DN)
.IP "\(bu" 2
determine density threshold from unmasked particles
.IP "\(bu" 2
mask particles before refinement of locations and determination of occupancy 
.PP
.RE
.PP

.PP
Definition in file \fBdcount\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 69 of file dcount\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 27 of file dcount\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
