.TH "/Users/bernard/b20/bsoft/eer/DefectMaskingEER.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/DefectMaskingEER.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <random>\fP
.br
\fC#include 'ElectronCountedFramesDecompressor\&.h'\fP
.br
\fC#include 'GainDefectCorrect\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDefectNeighborSpec\fP"
.br
.ti -1c
.RI "struct \fBCameraDefectNeighborInformation\fP"
.br
.ti -1c
.RI "struct \fBDefectElectronAdder\fP"
.br
.ti -1c
.RI "struct \fBSubpixelPositionRandomizer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBdefectNeighborInfo_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCreateDefectNeighborInfoMap\fP (const \fBCameraDefects\fP &def, const float *gainImage, \fBCameraDefectNeighborInformation\fP &camDefectNeighborInfo)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef uint8_t \fBdefectNeighborInfo_t\fP"

.PP
Definition at line 14 of file DefectMaskingEER\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void CreateDefectNeighborInfoMap (const \fBCameraDefects\fP & def, const float * gainImage, \fBCameraDefectNeighborInformation\fP & camDefectNeighborInfo)"

.PP
Definition at line 36 of file DefectMaskingEER\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
