.TH "/Users/bernard/b20/bsoft/eer/DefectMaskingEER.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/DefectMaskingEER.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DefectMaskingEER\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_addDefectNeighborInfo\fP (\fBCameraDefectNeighborInformation\fP &camDefectNeighborInfo, uint32_t idx, \fBdefectNeighborInfo_t\fP spec)"
.br
.ti -1c
.RI "void \fBCreateDefectNeighborInfoMap\fP (const \fBCameraDefects\fP &def, const float *gainImage, \fBCameraDefectNeighborInformation\fP &camDefectNeighborInfo)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectNeighborTypeMask\fP = 0xC0"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_Defect1DInterpol\fP = 0x40"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_Defect2DInterpol\fP = 0x80"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectCorner\fP = 0xC0"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectUpDown\fP = 0x20"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectBack\fP = 0x10"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectRight\fP = 0x00"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectLeft\fP = \fBbitMask_DefectBack\fP"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectDown\fP = \fBbitMask_DefectUpDown\fP"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_DefectUp\fP = \fBbitMask_DefectBack\fP | \fBbitMask_DefectUpDown\fP"
.br
.ti -1c
.RI "const \fBdefectNeighborInfo_t\fP \fBbitMask_Distance\fP = 0x0F"
.br
.ti -1c
.RI "const unsigned \fBgainImageSizeFactor\fP = \fBtotalSuperResolutionImSize\fP/\fBgainImageSize\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _addDefectNeighborInfo (\fBCameraDefectNeighborInformation\fP & camDefectNeighborInfo, uint32_t idx, \fBdefectNeighborInfo_t\fP spec)\fC [inline]\fP"

.PP
Definition at line 30 of file DefectMaskingEER\&.cpp\&.
.SS "void CreateDefectNeighborInfoMap (const \fBCameraDefects\fP & def, const float * gainImage, \fBCameraDefectNeighborInformation\fP & camDefectNeighborInfo)"

.PP
Definition at line 36 of file DefectMaskingEER\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBdefectNeighborInfo_t\fP bitMask_Defect1DInterpol = 0x40"

.PP
Definition at line 9 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_Defect2DInterpol = 0x80"

.PP
Definition at line 10 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectBack = 0x10"

.PP
Definition at line 14 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectCorner = 0xC0"

.PP
Definition at line 11 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectDown = \fBbitMask_DefectUpDown\fP"

.PP
Definition at line 17 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectLeft = \fBbitMask_DefectBack\fP"

.PP
Definition at line 16 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectNeighborTypeMask = 0xC0"

.PP
Definition at line 8 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectRight = 0x00"

.PP
Definition at line 15 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectUp = \fBbitMask_DefectBack\fP | \fBbitMask_DefectUpDown\fP"

.PP
Definition at line 18 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_DefectUpDown = 0x20"

.PP
Definition at line 13 of file DefectMaskingEER\&.cpp\&.
.SS "const \fBdefectNeighborInfo_t\fP bitMask_Distance = 0x0F"

.PP
Definition at line 21 of file DefectMaskingEER\&.cpp\&.
.SS "const unsigned gainImageSizeFactor = \fBtotalSuperResolutionImSize\fP/\fBgainImageSize\fP"

.PP
Definition at line 25 of file DefectMaskingEER\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
