.TH "DM4head" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DM4head
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwDM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "unsigned long \fBfile_length\fP"
.br
.ti -1c
.RI "int \fBendianness\fP"
.br
.ti -1c
.RI "char \fBsorted\fP"
.br
.ti -1c
.RI "char \fBopen\fP"
.br
.ti -1c
.RI "int \fBntag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file rwDM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int DM4head::endianness"

.PP
Definition at line 85 of file rwDM\&.h\&.
.SS "unsigned long DM4head::file_length"

.PP
Definition at line 84 of file rwDM\&.h\&.
.SS "int DM4head::ntag"

.PP
Definition at line 88 of file rwDM\&.h\&.
.SS "char DM4head::open"

.PP
Definition at line 87 of file rwDM\&.h\&.
.SS "char DM4head::sorted"

.PP
Definition at line 86 of file rwDM\&.h\&.
.SS "int DM4head::version"

.PP
Definition at line 83 of file rwDM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
