.TH "DMMachead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMMachead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwDM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBwidth\fP"
.br
.ti -1c
.RI "short \fBheight\fP"
.br
.ti -1c
.RI "short \fBbytes_per_pixel\fP"
.br
.ti -1c
.RI "short \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file rwDM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "short DMMachead::bytes_per_pixel"

.PP
Definition at line 34 of file rwDM\&.h\&.
.SS "short DMMachead::height"

.PP
Definition at line 33 of file rwDM\&.h\&.
.SS "short DMMachead::type"

.PP
Definition at line 35 of file rwDM\&.h\&.
.SS "short DMMachead::width"

.PP
Definition at line 32 of file rwDM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
