.TH "DSN6head" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DSN6head
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwDSN6\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBx_start\fP"
.br
.ti -1c
.RI "short \fBy_start\fP"
.br
.ti -1c
.RI "short \fBz_start\fP"
.br
.ti -1c
.RI "short \fBx_extent\fP"
.br
.ti -1c
.RI "short \fBy_extent\fP"
.br
.ti -1c
.RI "short \fBz_extent\fP"
.br
.ti -1c
.RI "short \fBx_sampling\fP"
.br
.ti -1c
.RI "short \fBy_sampling\fP"
.br
.ti -1c
.RI "short \fBz_sampling\fP"
.br
.ti -1c
.RI "short \fBa\fP"
.br
.ti -1c
.RI "short \fBb\fP"
.br
.ti -1c
.RI "short \fBc\fP"
.br
.ti -1c
.RI "short \fBalpha\fP"
.br
.ti -1c
.RI "short \fBbeta\fP"
.br
.ti -1c
.RI "short \fBgamma\fP"
.br
.ti -1c
.RI "short \fBproduct\fP"
.br
.ti -1c
.RI "short \fBplus\fP"
.br
.ti -1c
.RI "short \fBcell_scale\fP"
.br
.ti -1c
.RI "short \fBscale\fP"
.br
.ti -1c
.RI "short \fBextra\fP [237]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwDSN6\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "short DSN6head::a"

.PP
Definition at line 25 of file rwDSN6\&.h\&.
.SS "short DSN6head::alpha"

.PP
Definition at line 28 of file rwDSN6\&.h\&.
.SS "short DSN6head::b"

.PP
Definition at line 26 of file rwDSN6\&.h\&.
.SS "short DSN6head::beta"

.PP
Definition at line 29 of file rwDSN6\&.h\&.
.SS "short DSN6head::c"

.PP
Definition at line 27 of file rwDSN6\&.h\&.
.SS "short DSN6head::cell_scale"

.PP
Definition at line 33 of file rwDSN6\&.h\&.
.SS "short DSN6head::extra[237]"

.PP
Definition at line 35 of file rwDSN6\&.h\&.
.SS "short DSN6head::gamma"

.PP
Definition at line 30 of file rwDSN6\&.h\&.
.SS "short DSN6head::plus"

.PP
Definition at line 32 of file rwDSN6\&.h\&.
.SS "short DSN6head::product"

.PP
Definition at line 31 of file rwDSN6\&.h\&.
.SS "short DSN6head::scale"

.PP
Definition at line 34 of file rwDSN6\&.h\&.
.SS "short DSN6head::x_extent"

.PP
Definition at line 19 of file rwDSN6\&.h\&.
.SS "short DSN6head::x_sampling"

.PP
Definition at line 22 of file rwDSN6\&.h\&.
.SS "short DSN6head::x_start"

.PP
Definition at line 16 of file rwDSN6\&.h\&.
.SS "short DSN6head::y_extent"

.PP
Definition at line 20 of file rwDSN6\&.h\&.
.SS "short DSN6head::y_sampling"

.PP
Definition at line 23 of file rwDSN6\&.h\&.
.SS "short DSN6head::y_start"

.PP
Definition at line 17 of file rwDSN6\&.h\&.
.SS "short DSN6head::z_extent"

.PP
Definition at line 21 of file rwDSN6\&.h\&.
.SS "short DSN6head::z_sampling"

.PP
Definition at line 24 of file rwDSN6\&.h\&.
.SS "short DSN6head::z_start"

.PP
Definition at line 18 of file rwDSN6\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
