.TH "/Users/bernard/b20/bsoft/eer/ElectronCountedFramesDecompressor.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/ElectronCountedFramesDecompressor.h
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'FeiBitStreamer\&.h'\fP
.br
\fC#include 'EerFile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBElectronPos\fP"
.br
.ti -1c
.RI "class \fBElectronCountedFramesDecompressor\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned \fBnBitsRLE\fP = 7"
.br
.ti -1c
.RI "const unsigned \fBnSubPixBits\fP = 2"
.br
.ti -1c
.RI "const bool \fBno_bit_waste_on_overflow_code\fP = true"
.br
.ti -1c
.RI "const unsigned \fBnBitsPerCode\fP = \fBnBitsRLE\fP + 2*\fBnSubPixBits\fP"
.br
.ti -1c
.RI "const unsigned \fBcameraSize\fP = 4096"
.br
.ti -1c
.RI "const unsigned \fBsuperResolutionFactor\fP = (1<<\fBnSubPixBits\fP)"
.br
.ti -1c
.RI "const unsigned \fBtotalSuperResolutionImSize\fP = \fBsuperResolutionFactor\fP * \fBcameraSize\fP"
.br
.ti -1c
.RI "const unsigned \fBgainImageSize\fP = 4096"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const unsigned cameraSize = 4096"

.PP
Definition at line 19 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const unsigned gainImageSize = 4096"

.PP
Definition at line 24 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const unsigned nBitsPerCode = \fBnBitsRLE\fP + 2*\fBnSubPixBits\fP"

.PP
Definition at line 16 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const unsigned nBitsRLE = 7"

.PP
Definition at line 12 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const bool no_bit_waste_on_overflow_code = true"

.PP
Definition at line 14 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const unsigned nSubPixBits = 2"

.PP
Definition at line 13 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const unsigned superResolutionFactor = (1<<\fBnSubPixBits\fP)"

.PP
Definition at line 20 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "const unsigned totalSuperResolutionImSize = \fBsuperResolutionFactor\fP * \fBcameraSize\fP"

.PP
Definition at line 22 of file ElectronCountedFramesDecompressor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
