.TH "/Users/bernard/b20/bsoft/eer/ElectronCountedFramesDecompressor.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/ElectronCountedFramesDecompressor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'stddef\&.h'\fP
.br
\fC#include 'stdint\&.h'\fP
.br
\fC#include 'ElectronCountedFramesDecompressor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBelectronSetterDelta< upBits >\fP"
.br
.ti -1c
.RI "struct \fBelectronAdderDelta< upBits >\fP"
.br
.ti -1c
.RI "struct \fBelectronAdderBSpline< upBits >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMPRESSIONMODE\fP   6"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBfooterCheckResult\fP { \fBfooterOK\fP, \fBfooterError\fP, \fBfooterInvalid\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfooterCheckResult\fP \fBCheckFooter\fP (\fBBitStreamWordType\fP *data)"
.br
.ti -1c
.RI "template<typename T > void \fBGetWeightsSpline3\fP (T w, T weights[])"
.br
.ti -1c
.RI "void \fBcreateBSplineLUT\fP ()"
.br
.ti -1c
.RI "template<class operationFunc , typename ImType > unsigned \fBdoDecompressImage\fP (\fBBitStreamer\fP &myBitStreamer, ImType *p, unsigned w, unsigned h)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBheaderPrefix\fP ='ThermoFisherECCompr'"
.br
.ti -1c
.RI "const char \fBHWfooterStringOK\fP [] = 'ThermoFisherECComprOK000'"
.br
.ti -1c
.RI "const char \fBHWfooterStringErr\fP [] = 'ThermoFisherECComprERR00'"
.br
.ti -1c
.RI "const unsigned int \fBHWfooterLength\fP = 24"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMPRESSIONMODE   6"

.PP
Definition at line 27 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBfooterCheckResult\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIfooterOK \fP\fP
.TP
\fB\fIfooterError \fP\fP
.TP
\fB\fIfooterInvalid \fP\fP
.PP
Definition at line 38 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBfooterCheckResult\fP CheckFooter (\fBBitStreamWordType\fP * data)"

.PP
Definition at line 41 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "void createBSplineLUT ()"

.PP
Definition at line 115 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "template<class operationFunc , typename ImType > unsigned doDecompressImage (\fBBitStreamer\fP & myBitStreamer, ImType * p, unsigned w, unsigned h)"

.PP
Definition at line 168 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "template<typename T > void GetWeightsSpline3 (T w, T weights[])\fC [inline]\fP"

.PP
Definition at line 102 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* headerPrefix ='ThermoFisherECCompr'"

.PP
Definition at line 30 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "const unsigned int HWfooterLength = 24"

.PP
Definition at line 36 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "const char HWfooterStringErr[] = 'ThermoFisherECComprERR00'"

.PP
Definition at line 35 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "const char HWfooterStringOK[] = 'ThermoFisherECComprOK000'"

.PP
Definition at line 34 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
