.TH "electronAdderDelta< upBits >" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
electronAdderDelta< upBits >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBapply\fP (uint8_t *p, unsigned posX, unsigned posY, unsigned subPixX, unsigned subPixY)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const unsigned \fBwidthIn\fP = 4096"
.br
.ti -1c
.RI "static const unsigned \fBwidthOut\fP = (\fBwidthIn\fP << \fBnSubPixBits\fP) >> (\fBnSubPixBits\fP\-upBits)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int upBits>
.br
struct electronAdderDelta< upBits >"

.PP
Definition at line 81 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<int upBits> static void \fBelectronAdderDelta\fP< upBits >::apply (uint8_t * p, unsigned posX, unsigned posY, unsigned subPixX, unsigned subPixY)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 86 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<int upBits> const unsigned \fBelectronAdderDelta\fP< upBits >::widthIn = 4096\fC [static]\fP"

.PP
Definition at line 83 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "template<int upBits> const unsigned \fBelectronAdderDelta\fP< upBits >::widthOut = (\fBwidthIn\fP << \fBnSubPixBits\fP) >> (\fBnSubPixBits\fP\-upBits)\fC [static]\fP"

.PP
Definition at line 84 of file ElectronCountedFramesDecompressor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
