.TH "/Users/bernard/b20/bsoft/src/emgrand.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/emgrand.cpp \- Generate random values for micrograph parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_random\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'symmetry\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generate random values for micrograph parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Eduardo Sanz-Garcia, David Belnap and Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20051011 
.PP
Modified: 20100128 
.RE
.PP

.PP
Definition in file \fBemgrand\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 47 of file emgrand\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: emgrand [options] input\&.star [input\&.star]",
"------------------------------------------------",
"Randomizes particle parameters\&.",
" ",
"Actions:",
"-randomviews             Replace views with random orientations\&.",
"-helical                 Replace views with random orientations for a helix\&.",
"-symmetry C5             Replace views with random symmetry-related orientations\&.",
"-origins 1\&.4             Introduce random errors into origins with this standard deviation (pixels)\&.",
"-views 3\&.1               Introduce random errors into views with this standard deviation (degrees)\&.",
"-defocus 0\&.3             Introduce random errors into defocus with this standard deviation (um)\&.",
"-magnification 0\&.1       Introduce random errors into magnifications with this standard deviation (fraction)\&.",
"-setasu C5               Set the views to the asymmetric unit (must agree with -symmetry if used)\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
" ",
"Output:",
"-output file\&.star        Output parameter file name\&.",
" ",
NULL
}
.fi
.PP
Definition at line 21 of file emgrand\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
