.TH "/Users/bernard/b20/bsoft/include/Euler.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/Euler.h \- \fBEuler\fP object\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Vector3\&.h'\fP
.br
\fC#include 'Matrix3\&.h'\fP
.br
\fC#include 'Quaternion\&.h'\fP
.br
\fC#include 'View\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEuler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBEuler\fP object\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010420 
.PP
Modified: 20150106 
.RE
.PP

.PP
Definition in file \fBEuler\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
