.TH "Euler" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Euler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Euler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEuler\fP ()"
.br
.ti -1c
.RI "\fBEuler\fP (const \fBEuler\fP &e)"
.br
.ti -1c
.RI "\fBEuler\fP (const double \fBpsi\fP, const double \fBtheta\fP, const double \fBphi\fP)"
.br
.ti -1c
.RI "\fBEuler\fP (\fBView\fP &v)"
.br
.ti -1c
.RI "\fBEuler\fP (\fBMatrix3\fP &m)"
.br
.ti -1c
.RI "\fBEuler\fP \fBoperator=\fP (const \fBEuler\fP &e)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "double \fBpsi\fP ()"
.br
.ti -1c
.RI "double \fBtheta\fP ()"
.br
.ti -1c
.RI "double \fBphi\fP ()"
.br
.ti -1c
.RI "void \fBpsi\fP (const double d)"
.br
.ti -1c
.RI "void \fBtheta\fP (const double d)"
.br
.ti -1c
.RI "void \fBphi\fP (const double d)"
.br
.ti -1c
.RI "\fBView\fP \fBview\fP ()"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBmatrix\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Euler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Euler::Euler ()\fC [inline]\fP"

.PP
Definition at line 35 of file Euler\&.h\&.
.SS "Euler::Euler (const \fBEuler\fP & e)\fC [inline]\fP"

.PP
Definition at line 36 of file Euler\&.h\&.
.SS "Euler::Euler (const double psi, const double theta, const double phi)\fC [inline]\fP"

.PP
Definition at line 37 of file Euler\&.h\&.
.SS "Euler::Euler (\fBView\fP & v)\fC [inline]\fP"

.PP
Definition at line 40 of file Euler\&.h\&.
.SS "Euler::Euler (\fBMatrix3\fP & m)\fC [inline]\fP"

.PP
Definition at line 47 of file Euler\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMatrix3\fP Euler::matrix ()\fC [inline]\fP"

.PP
Definition at line 67 of file Euler\&.h\&.
.SS "\fBEuler\fP Euler::operator= (const \fBEuler\fP & e)\fC [inline]\fP"

.PP
Definition at line 51 of file Euler\&.h\&.
.SS "double& Euler::operator[] (int i)\fC [inline]\fP"

.PP
Definition at line 55 of file Euler\&.h\&.
.SS "double Euler::phi ()\fC [inline]\fP"

.PP
Definition at line 58 of file Euler\&.h\&.
.SS "void Euler::phi (const double d)\fC [inline]\fP"

.PP
Definition at line 61 of file Euler\&.h\&.
.SS "double Euler::psi ()\fC [inline]\fP"

.PP
Definition at line 56 of file Euler\&.h\&.
.SS "void Euler::psi (const double d)\fC [inline]\fP"

.PP
Definition at line 59 of file Euler\&.h\&.
.SS "double Euler::theta ()\fC [inline]\fP"

.PP
Definition at line 57 of file Euler\&.h\&.
.SS "void Euler::theta (const double d)\fC [inline]\fP"

.PP
Definition at line 60 of file Euler\&.h\&.
.SS "\fBView\fP Euler::view ()\fC [inline]\fP"

.PP
Definition at line 62 of file Euler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
