.TH "Fei::Acquisition::EerReader::Bitmap" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fei::Acquisition::EerReader::Bitmap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bitmap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitmap\fP (TIFF *tiff)"
.br
.ti -1c
.RI "uint32_t \fBGetWidth\fP () const"
.br
.ti -1c
.RI "uint32_t \fBGetLength\fP () const"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBGetImageData\fP () const"
.br
.ti -1c
.RI "int \fBGetBitsPerSample\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Bitmap\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fei::Acquisition::EerReader::Bitmap::Bitmap (TIFF * tiff)"

.PP
Definition at line 13 of file Bitmap\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int Fei::Acquisition::EerReader::Bitmap::GetBitsPerSample () const"

.PP
Definition at line 55 of file Bitmap\&.cpp\&.
.SS "std::vector< unsigned char > Fei::Acquisition::EerReader::Bitmap::GetImageData () const"

.PP
Definition at line 50 of file Bitmap\&.cpp\&.
.SS "uint32_t Fei::Acquisition::EerReader::Bitmap::GetLength () const"

.PP
Definition at line 45 of file Bitmap\&.cpp\&.
.SS "uint32_t Fei::Acquisition::EerReader::Bitmap::GetWidth () const"

.PP
Definition at line 40 of file Bitmap\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
