.TH "/Users/bernard/b20/bsoft/eer/FeiBitStreamer.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/FeiBitStreamer.h
.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'stdint\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBitStreamer\fP"
.br
.ti -1c
.RI "class \fBBitStreamWriter\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBBitType\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBMultiBitType\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBBitStreamWordType\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBBitStreamWordTypeNBits\fP = 8 * sizeof(\fBBitStreamWordType\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef uint64_t \fBBitStreamWordType\fP"

.PP
Definition at line 14 of file FeiBitStreamer\&.h\&.
.SS "typedef uint8_t \fBBitType\fP"

.PP
Definition at line 11 of file FeiBitStreamer\&.h\&.
.SS "typedef uint16_t \fBMultiBitType\fP"

.PP
Definition at line 12 of file FeiBitStreamer\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const int BitStreamWordTypeNBits = 8 * sizeof(\fBBitStreamWordType\fP)"

.PP
Definition at line 15 of file FeiBitStreamer\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
