.TH "GFslice_head" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GFslice_head
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwGOODFORD\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpad1\fP"
.br
.ti -1c
.RI "int \fBk\fP"
.br
.ti -1c
.RI "int \fBim\fP"
.br
.ti -1c
.RI "int \fBjm\fP"
.br
.ti -1c
.RI "int \fBpad2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file rwGOODFORD\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int GFslice_head::im"

.PP
Definition at line 40 of file rwGOODFORD\&.h\&.
.SS "int GFslice_head::jm"

.PP
Definition at line 41 of file rwGOODFORD\&.h\&.
.SS "int GFslice_head::k"

.PP
Definition at line 39 of file rwGOODFORD\&.h\&.
.SS "int GFslice_head::pad1"

.PP
Definition at line 38 of file rwGOODFORD\&.h\&.
.SS "int GFslice_head::pad2"

.PP
Definition at line 42 of file rwGOODFORD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
