.TH "GOODFORDhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GOODFORDhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwGOODFORD\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpad1\fP"
.br
.ti -1c
.RI "char \fBtitle\fP [72]"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "int \fBpad2\fP"
.br
.ti -1c
.RI "int \fBgrdflg\fP"
.br
.ti -1c
.RI "int \fBpad3\fP"
.br
.ti -1c
.RI "int \fBpad4\fP"
.br
.ti -1c
.RI "int \fBpad5\fP"
.br
.ti -1c
.RI "int \fBpad6\fP"
.br
.ti -1c
.RI "int \fBim\fP"
.br
.ti -1c
.RI "int \fBjm\fP"
.br
.ti -1c
.RI "int \fBkm\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBox\fP"
.br
.ti -1c
.RI "float \fBoy\fP"
.br
.ti -1c
.RI "float \fBoz\fP"
.br
.ti -1c
.RI "int \fBpad7\fP [8]"
.br
.ti -1c
.RI "int \fBpad8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file rwGOODFORD\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int GOODFORDhead::grdflg"

.PP
Definition at line 21 of file rwGOODFORD\&.h\&.
.SS "float GOODFORDhead::h"

.PP
Definition at line 29 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::im"

.PP
Definition at line 26 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::jm"

.PP
Definition at line 27 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::km"

.PP
Definition at line 28 of file rwGOODFORD\&.h\&.
.SS "float GOODFORDhead::ox"

.PP
Definition at line 30 of file rwGOODFORD\&.h\&.
.SS "float GOODFORDhead::oy"

.PP
Definition at line 31 of file rwGOODFORD\&.h\&.
.SS "float GOODFORDhead::oz"

.PP
Definition at line 32 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad1"

.PP
Definition at line 17 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad2"

.PP
Definition at line 20 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad3"

.PP
Definition at line 22 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad4"

.PP
Definition at line 23 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad5"

.PP
Definition at line 24 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad6"

.PP
Definition at line 25 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad7[8]"

.PP
Definition at line 33 of file rwGOODFORD\&.h\&.
.SS "int GOODFORDhead::pad8"

.PP
Definition at line 34 of file rwGOODFORD\&.h\&.
.SS "float GOODFORDhead::scale"

.PP
Definition at line 19 of file rwGOODFORD\&.h\&.
.SS "char GOODFORDhead::title[72]"

.PP
Definition at line 18 of file rwGOODFORD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
