.TH "GSgraph" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GSgraph \- Graph segmentation container\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bgraphseg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "vector< \fBGSvoxel\fP > & \fBvoxels\fP ()"
.br
.ti -1c
.RI "vector< \fBGSedge\fP > & \fBedges\fP ()"
.br
.ti -1c
.RI "\fBGSvoxel\fP & \fBvoxel\fP (long i)"
.br
.ti -1c
.RI "\fBGSvoxel\fP & \fBadd_voxel\fP (long index, long nj, long nv, double avg)"
.br
.ti -1c
.RI "long \fBvoxel_count\fP ()"
.br
.ti -1c
.RI "\fBGSedge\fP & \fBedge\fP (long i)"
.br
.ti -1c
.RI "\fBGSedge\fP & \fBadd_edge\fP (long u, long v, double w)"
.br
.ti -1c
.RI "long \fBedge_count\fP ()"
.br
.ti -1c
.RI "void \fBedge_sort\fP ()"
.br
.ti -1c
.RI "long \fBregion_find\fP (long i)"
.br
.ti -1c
.RI "int \fBregion_join\fP (long i, long j)"
.br
.ti -1c
.RI "long \fBregion_merging\fP (double threshold)"
.br
.ti -1c
.RI "long \fBstatistical_region_merging\fP (double threshold)"
.br
.ti -1c
.RI "long \fBregion_merge_small\fP (long nrc, long min_size)"
.br
.ti -1c
.RI "long \fBregion_number\fP ()"
.br
.ti -1c
.RI "void \fBshow_regions\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graph segmentation container\&. 
.PP
Definition at line 64 of file Bgraphseg\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGSedge\fP& GSgraph::add_edge (long u, long v, double w)\fC [inline]\fP"

.PP
Definition at line 83 of file Bgraphseg\&.h\&.
.SS "\fBGSvoxel\fP& GSgraph::add_voxel (long index, long nj, long nv, double avg)\fC [inline]\fP"

.PP
Definition at line 72 of file Bgraphseg\&.h\&.
.SS "\fBGSedge\fP& GSgraph::edge (long i)\fC [inline]\fP"

.PP
Definition at line 82 of file Bgraphseg\&.h\&.
.SS "long GSgraph::edge_count ()\fC [inline]\fP"

.PP
Definition at line 87 of file Bgraphseg\&.h\&.
.SS "void GSgraph::edge_sort ()\fC [inline]\fP"

.PP
Definition at line 88 of file Bgraphseg\&.h\&.
.SS "vector<\fBGSedge\fP>& GSgraph::edges ()\fC [inline]\fP"

.PP
Definition at line 70 of file Bgraphseg\&.h\&.
.SS "long GSgraph::region_find (long i)\fC [inline]\fP"

.PP
Definition at line 91 of file Bgraphseg\&.h\&.
.SS "int GSgraph::region_join (long i, long j)\fC [inline]\fP"

.PP
Definition at line 97 of file Bgraphseg\&.h\&.
.SS "long GSgraph::region_merge_small (long nrc, long min_size)\fC [inline]\fP"

.PP
Definition at line 153 of file Bgraphseg\&.h\&.
.SS "long GSgraph::region_merging (double threshold)\fC [inline]\fP"

.PP
Definition at line 113 of file Bgraphseg\&.h\&.
.SS "long GSgraph::region_number ()\fC [inline]\fP"

.PP
Definition at line 165 of file Bgraphseg\&.h\&.
.SS "void GSgraph::show_regions ()\fC [inline]\fP"

.PP
Definition at line 176 of file Bgraphseg\&.h\&.
.SS "long GSgraph::statistical_region_merging (double threshold)\fC [inline]\fP"

.PP
Definition at line 131 of file Bgraphseg\&.h\&.
.SS "\fBGSvoxel\fP& GSgraph::voxel (long i)\fC [inline]\fP"

.PP
Definition at line 71 of file Bgraphseg\&.h\&.
.SS "long GSgraph::voxel_count ()\fC [inline]\fP"

.PP
Definition at line 76 of file Bgraphseg\&.h\&.
.SS "vector<\fBGSvoxel\fP>& GSgraph::voxels ()\fC [inline]\fP"

.PP
Definition at line 69 of file Bgraphseg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
