.TH "GSregion" 3 "Sat Jan 16 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GSregion \- Graph segmentation region\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bgraphseg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGSregion\fP ()"
.br
.ti -1c
.RI "\fBGSregion\fP (long index, long nj, long nv, double avg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBp\fP"
.br
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBs\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graph segmentation region\&. 
.PP
Definition at line 34 of file Bgraphseg\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GSregion::GSregion ()\fC [inline]\fP"

.PP
Definition at line 40 of file Bgraphseg\&.h\&.
.SS "GSregion::GSregion (long index, long nj, long nv, double avg)\fC [inline]\fP"

.PP
Definition at line 41 of file Bgraphseg\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float GSregion::a"

.PP
Definition at line 39 of file Bgraphseg\&.h\&.
.SS "long GSregion::p"

.PP
Definition at line 36 of file Bgraphseg\&.h\&.
.SS "int GSregion::r"

.PP
Definition at line 37 of file Bgraphseg\&.h\&.
.SS "int GSregion::s"

.PP
Definition at line 38 of file Bgraphseg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
