.TH "Hand_Stats" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hand_Stats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBCountA\fP"
.br
.ti -1c
.RI "int \fBCountB\fP"
.br
.ti -1c
.RI "int \fBTie\fP"
.br
.ti -1c
.RI "double \fBAvg1A\fP"
.br
.ti -1c
.RI "double \fBAvg2A\fP"
.br
.ti -1c
.RI "double \fBAvg2B\fP"
.br
.ti -1c
.RI "double \fBStd1A\fP"
.br
.ti -1c
.RI "double \fBStd2A\fP"
.br
.ti -1c
.RI "double \fBStd2B\fP"
.br
.ti -1c
.RI "double \fBAvgAbsDiff_2Aphi\fP"
.br
.ti -1c
.RI "double \fBAvgAbsDiff_2Athe\fP"
.br
.ti -1c
.RI "double \fBAvgAbsDiff_2Apsi\fP"
.br
.ti -1c
.RI "double \fBAvgAbsDiff_2Bphi\fP"
.br
.ti -1c
.RI "double \fBAvgAbsDiff_2Bthe\fP"
.br
.ti -1c
.RI "double \fBAvgAbsDiff_2Bpsi\fP"
.br
.ti -1c
.RI "double \fBStdAbsDiff_2Aphi\fP"
.br
.ti -1c
.RI "double \fBStdAbsDiff_2Athe\fP"
.br
.ti -1c
.RI "double \fBStdAbsDiff_2Apsi\fP"
.br
.ti -1c
.RI "double \fBStdAbsDiff_2Bphi\fP"
.br
.ti -1c
.RI "double \fBStdAbsDiff_2Bthe\fP"
.br
.ti -1c
.RI "double \fBStdAbsDiff_2Bpsi\fP"
.br
.ti -1c
.RI "double \fBSum_1A\fP"
.br
.ti -1c
.RI "double \fBSum_2A\fP"
.br
.ti -1c
.RI "double \fBSum_2B\fP"
.br
.ti -1c
.RI "double \fBSum_1Asq\fP"
.br
.ti -1c
.RI "double \fBSum_2Asq\fP"
.br
.ti -1c
.RI "double \fBSum_2Bsq\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPhi2A\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffThe2A\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPsi2A\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPhi2B\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffThe2B\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPsi2B\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPhi2Asq\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffThe2Asq\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPsi2Asq\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPhi2Bsq\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffThe2Bsq\fP"
.br
.ti -1c
.RI "double \fBSum_AbsDiffPsi2Bsq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file mg_hand\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double Hand_Stats::Avg1A"

.PP
Definition at line 32 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Avg2A"

.PP
Definition at line 33 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Avg2B"

.PP
Definition at line 34 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::AvgAbsDiff_2Aphi"

.PP
Definition at line 38 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::AvgAbsDiff_2Apsi"

.PP
Definition at line 40 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::AvgAbsDiff_2Athe"

.PP
Definition at line 39 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::AvgAbsDiff_2Bphi"

.PP
Definition at line 41 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::AvgAbsDiff_2Bpsi"

.PP
Definition at line 43 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::AvgAbsDiff_2Bthe"

.PP
Definition at line 42 of file mg_hand\&.cpp\&.
.SS "int Hand_Stats::CountA"

.PP
Definition at line 29 of file mg_hand\&.cpp\&.
.SS "int Hand_Stats::CountB"

.PP
Definition at line 30 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Std1A"

.PP
Definition at line 35 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Std2A"

.PP
Definition at line 36 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Std2B"

.PP
Definition at line 37 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::StdAbsDiff_2Aphi"

.PP
Definition at line 44 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::StdAbsDiff_2Apsi"

.PP
Definition at line 46 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::StdAbsDiff_2Athe"

.PP
Definition at line 45 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::StdAbsDiff_2Bphi"

.PP
Definition at line 47 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::StdAbsDiff_2Bpsi"

.PP
Definition at line 49 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::StdAbsDiff_2Bthe"

.PP
Definition at line 48 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_1A"

.PP
Definition at line 50 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_1Asq"

.PP
Definition at line 53 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_2A"

.PP
Definition at line 51 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_2Asq"

.PP
Definition at line 54 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_2B"

.PP
Definition at line 52 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_2Bsq"

.PP
Definition at line 55 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPhi2A"

.PP
Definition at line 56 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPhi2Asq"

.PP
Definition at line 62 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPhi2B"

.PP
Definition at line 59 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPhi2Bsq"

.PP
Definition at line 65 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPsi2A"

.PP
Definition at line 58 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPsi2Asq"

.PP
Definition at line 64 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPsi2B"

.PP
Definition at line 61 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffPsi2Bsq"

.PP
Definition at line 67 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffThe2A"

.PP
Definition at line 57 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffThe2Asq"

.PP
Definition at line 63 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffThe2B"

.PP
Definition at line 60 of file mg_hand\&.cpp\&.
.SS "double Hand_Stats::Sum_AbsDiffThe2Bsq"

.PP
Definition at line 66 of file mg_hand\&.cpp\&.
.SS "int Hand_Stats::Tie"

.PP
Definition at line 31 of file mg_hand\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
