.TH "IMAGIChead_old" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMAGIChead_old
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwIMAGIC\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBimn\fP"
.br
.ti -1c
.RI "int \fBifn\fP"
.br
.ti -1c
.RI "int \fBierror\fP"
.br
.ti -1c
.RI "int \fBnhfr\fP"
.br
.ti -1c
.RI "int \fBndate\fP"
.br
.ti -1c
.RI "int \fBnmonth\fP"
.br
.ti -1c
.RI "int \fBnyear\fP"
.br
.ti -1c
.RI "int \fBnhour\fP"
.br
.ti -1c
.RI "int \fBnminut\fP"
.br
.ti -1c
.RI "int \fBnsec\fP"
.br
.ti -1c
.RI "int \fBnpix2\fP"
.br
.ti -1c
.RI "int \fBnpixel\fP"
.br
.ti -1c
.RI "int \fBixlp\fP"
.br
.ti -1c
.RI "int \fBiylp\fP"
.br
.ti -1c
.RI "char \fBtype\fP [4]"
.br
.ti -1c
.RI "int \fBixold\fP"
.br
.ti -1c
.RI "int \fBiyold\fP"
.br
.ti -1c
.RI "float \fBavdens\fP"
.br
.ti -1c
.RI "float \fBsigma\fP"
.br
.ti -1c
.RI "float \fBvarian\fP"
.br
.ti -1c
.RI "float \fBoldavd\fP"
.br
.ti -1c
.RI "float \fBdensmax\fP"
.br
.ti -1c
.RI "float \fBdensmin\fP"
.br
.ti -1c
.RI "float \fBdummy\fP [4]"
.br
.ti -1c
.RI "char \fBlastpr\fP [8]"
.br
.ti -1c
.RI "char \fBname\fP [80]"
.br
.ti -1c
.RI "float \fBextra_1\fP [8]"
.br
.ti -1c
.RI "float \fBeman_alt\fP"
.br
.ti -1c
.RI "float \fBeman_az\fP"
.br
.ti -1c
.RI "float \fBeman_phi\fP"
.br
.ti -1c
.RI "float \fBextra_2\fP [69]"
.br
.ti -1c
.RI "float \fBeuler_alpha\fP"
.br
.ti -1c
.RI "float \fBeuler_beta\fP"
.br
.ti -1c
.RI "float \fBeuler_gamma\fP"
.br
.ti -1c
.RI "float \fBproj_weight\fP"
.br
.ti -1c
.RI "float \fBextra_3\fP [66]"
.br
.ti -1c
.RI "char \fBhistory\fP [228]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file rwIMAGIC\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float IMAGIChead_old::avdens"

.PP
Definition at line 128 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::densmax"

.PP
Definition at line 132 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::densmin"

.PP
Definition at line 133 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::dummy[4]"

.PP
Definition at line 136 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::eman_alt"

.PP
Definition at line 140 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::eman_az"

.PP
Definition at line 141 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::eman_phi"

.PP
Definition at line 142 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::euler_alpha"

.PP
Definition at line 144 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::euler_beta"

.PP
Definition at line 145 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::euler_gamma"

.PP
Definition at line 146 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::extra_1[8]"

.PP
Definition at line 139 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::extra_2[69]"

.PP
Definition at line 143 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::extra_3[66]"

.PP
Definition at line 148 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead_old::history[228]"

.PP
Definition at line 149 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::ierror"

.PP
Definition at line 113 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::ifn"

.PP
Definition at line 112 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::imn"

.PP
Definition at line 111 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::ixlp"

.PP
Definition at line 123 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::ixold"

.PP
Definition at line 126 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::iylp"

.PP
Definition at line 124 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::iyold"

.PP
Definition at line 127 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead_old::lastpr[8]"

.PP
Definition at line 137 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead_old::name[80]"

.PP
Definition at line 138 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::ndate"

.PP
Definition at line 115 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::nhfr"

.PP
Definition at line 114 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::nhour"

.PP
Definition at line 118 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::nminut"

.PP
Definition at line 119 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::nmonth"

.PP
Definition at line 116 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::npix2"

.PP
Definition at line 121 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::npixel"

.PP
Definition at line 122 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::nsec"

.PP
Definition at line 120 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead_old::nyear"

.PP
Definition at line 117 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::oldavd"

.PP
Definition at line 131 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::proj_weight"

.PP
Definition at line 147 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::sigma"

.PP
Definition at line 129 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead_old::type[4]"

.PP
Definition at line 125 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead_old::varian"

.PP
Definition at line 130 of file rwIMAGIC\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
