.TH "ImageAttribute" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageAttribute
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageAttribute\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtype\fP"
.br
.ti -1c
.RI "string \fBtag\fP"
.br
.ti -1c
.RI "double \fBval\fP"
.br
.ti -1c
.RI "string \fBsval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file rwND2\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImageAttribute::ImageAttribute ()\fC [inline]\fP"

.PP
Definition at line 45 of file rwND2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "string ImageAttribute::sval"

.PP
Definition at line 44 of file rwND2\&.cpp\&.
.SS "string ImageAttribute::tag"

.PP
Definition at line 42 of file rwND2\&.cpp\&.
.SS "bool ImageAttribute::type"

.PP
Definition at line 41 of file rwND2\&.cpp\&.
.SS "double ImageAttribute::val"

.PP
Definition at line 43 of file rwND2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
