.TH "IMOD" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMOD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmgIMOD\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [128]"
.br
.ti -1c
.RI "int \fBxmax\fP"
.br
.ti -1c
.RI "int \fBymax\fP"
.br
.ti -1c
.RI "int \fBzmax\fP"
.br
.ti -1c
.RI "int \fBobjsize\fP"
.br
.ti -1c
.RI "uint \fBflags\fP"
.br
.ti -1c
.RI "int \fBdrawmode\fP"
.br
.ti -1c
.RI "int \fBmousemode\fP"
.br
.ti -1c
.RI "int \fBblacklevel\fP"
.br
.ti -1c
.RI "int \fBwhitelevel\fP"
.br
.ti -1c
.RI "float \fBxoffset\fP"
.br
.ti -1c
.RI "float \fByoffset\fP"
.br
.ti -1c
.RI "float \fBzoffset\fP"
.br
.ti -1c
.RI "float \fBxscale\fP"
.br
.ti -1c
.RI "float \fByscale\fP"
.br
.ti -1c
.RI "float \fBzscale\fP"
.br
.ti -1c
.RI "int \fBobject\fP"
.br
.ti -1c
.RI "int \fBcontour\fP"
.br
.ti -1c
.RI "int \fBpoint\fP"
.br
.ti -1c
.RI "int \fBres\fP"
.br
.ti -1c
.RI "int \fBthresh\fP"
.br
.ti -1c
.RI "float \fBpixsize\fP"
.br
.ti -1c
.RI "int \fBunits\fP"
.br
.ti -1c
.RI "int \fBcsum\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwmgIMOD\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float IMOD::alpha"

.PP
Definition at line 57 of file rwmgIMOD\&.h\&.
.SS "float IMOD::beta"

.PP
Definition at line 58 of file rwmgIMOD\&.h\&.
.SS "int IMOD::blacklevel"

.PP
Definition at line 32 of file rwmgIMOD\&.h\&.
.SS "int IMOD::contour"

.PP
Definition at line 44 of file rwmgIMOD\&.h\&.
.SS "int IMOD::csum"

.PP
Definition at line 55 of file rwmgIMOD\&.h\&.
.SS "int IMOD::drawmode"

.PP
Definition at line 29 of file rwmgIMOD\&.h\&.
.SS "uint IMOD::flags"

.PP
Definition at line 23 of file rwmgIMOD\&.h\&.
.SS "float IMOD::gamma"

.PP
Definition at line 59 of file rwmgIMOD\&.h\&.
.SS "int IMOD::mousemode"

.PP
Definition at line 30 of file rwmgIMOD\&.h\&.
.SS "char IMOD::name[128]"

.PP
Definition at line 16 of file rwmgIMOD\&.h\&.
.SS "int IMOD::object"

.PP
Definition at line 43 of file rwmgIMOD\&.h\&.
.SS "int IMOD::objsize"

.PP
Definition at line 21 of file rwmgIMOD\&.h\&.
.SS "float IMOD::pixsize"

.PP
Definition at line 51 of file rwmgIMOD\&.h\&.
.SS "int IMOD::point"

.PP
Definition at line 45 of file rwmgIMOD\&.h\&.
.SS "int IMOD::res"

.PP
Definition at line 47 of file rwmgIMOD\&.h\&.
.SS "int IMOD::thresh"

.PP
Definition at line 49 of file rwmgIMOD\&.h\&.
.SS "int IMOD::units"

.PP
Definition at line 52 of file rwmgIMOD\&.h\&.
.SS "int IMOD::whitelevel"

.PP
Definition at line 33 of file rwmgIMOD\&.h\&.
.SS "int IMOD::xmax"

.PP
Definition at line 17 of file rwmgIMOD\&.h\&.
.SS "float IMOD::xoffset"

.PP
Definition at line 35 of file rwmgIMOD\&.h\&.
.SS "float IMOD::xscale"

.PP
Definition at line 39 of file rwmgIMOD\&.h\&.
.SS "int IMOD::ymax"

.PP
Definition at line 18 of file rwmgIMOD\&.h\&.
.SS "float IMOD::yoffset"

.PP
Definition at line 36 of file rwmgIMOD\&.h\&.
.SS "float IMOD::yscale"

.PP
Definition at line 40 of file rwmgIMOD\&.h\&.
.SS "int IMOD::zmax"

.PP
Definition at line 19 of file rwmgIMOD\&.h\&.
.SS "float IMOD::zoffset"

.PP
Definition at line 37 of file rwmgIMOD\&.h\&.
.SS "float IMOD::zscale"

.PP
Definition at line 41 of file rwmgIMOD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
