.TH "int_float" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_float
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qsort_functions\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file qsort_functions\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float int_float::f"

.PP
Definition at line 12 of file qsort_functions\&.h\&.
.SS "int int_float::i"

.PP
Definition at line 12 of file qsort_functions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
