.TH "/Users/bernard/b20/bsoft/src/jpartdif.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/jpartdif.cpp \- Analysis of particle differences between two starfiles\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_multiple\&.h'\fP
.br
\fC#include 'mg_particle_select\&.h'\fP
.br
\fC#include 'Matrix\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'Vector3\&.h'\fP
.br
\fC#include 'View\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Analysis of particle differences between two starfiles\&. 


.PP
\fBAuthor\fP
.RS 4
Juha Huiskonen 
.PP
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20071214 
.PP
Modified: 20111506 
.PP
Modified: 20120106 
.PP
Modified: 20150108 (BH) - incorporated into Bsoft 
.RE
.PP

.PP
Definition in file \fBjpartdif\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 53 of file jpartdif\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: jpartdif [options] input1\&.star input2\&.star",
"-------------------------------------------------",
"Calculates the difference in the particle parameters,",
"or selects particles based on the fom difference\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-consolidate             Only consolidate particles based on distance\&.",
"-locdiff                 Calculate the difference in the locations\&.",
"-fomdiff                 Calculate the difference in the foms\&.",
"-printlocdiff            Print the difference in the locations\&.",
"-printanglediff          Print the difference in the view angle\&.",
"-printalphadiff          Print the difference in the alpha angles\&.",
"-thrlocdiff 10\&.0         Analyse only particles below threshold (pixels)\&.",
"-thranglediff 20\&.0       Analyse only particles below threshold (degrees)\&.",
"-remove                  Remove all particles with selection number 0\&.",
" ",
"Output:",
"-output file\&.star        Output parameter file\&.",

" ",
NULL
}
.fi
.PP
Definition at line 27 of file jpartdif\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
