.TH "/Users/bernard/b20/bsoft/src/util/json.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/util/json.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'json\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBJStype\fP t)"
.br
.ti -1c
.RI "int \fBindent\fP (0)"
.br
.ti -1c
.RI "void \fBindent_line\fP (ostream &output)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBJSvalue\fP &jsv)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
20160409 - 20180328 
.RE
.PP

.PP
Definition in file \fBjson\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int indent (0)"

.SS "void indent_line (ostream & output)"

.PP
Definition at line 26 of file json\&.cpp\&.
.SS "ostream& operator<< (ostream & output, \fBJStype\fP t)"

.PP
Definition at line 10 of file json\&.cpp\&.
.SS "ostream& operator<< (ostream & output, \fBJSvalue\fP & jsv)"

.PP
Definition at line 30 of file json\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
