.TH "/Users/bernard/b20/bsoft/src/jsubtomo.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/jsubtomo.cpp \- Finds particles (subtomograms) in a tomographic reconstruction and refines their origins and orientations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'mg_subtomo\&.h'\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_particle_select\&.h'\fP
.br
\fC#include 'mg_extract\&.h'\fP
.br
\fC#include 'mg_img_proc\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'ps_micrograph\&.h'\fP
.br
\fC#include 'Matrix\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Finds particles (subtomograms) in a tomographic reconstruction and refines their origins and orientations\&. 


.PP
\fBAuthor\fP
.RS 4
Juha Huiskonen (JTH) 
.PP
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20071010 
.PP
Modified: 20080630 -rescale option\&. 
.PP
Modified: 20081124 option to write star files of extracted particles 
.PP
Modified: 20081128 rescaling of the map moved to main loop, output files will be float by default 
.PP
Modified: 20100503 changes to how extract mode handles particle origins 
.PP
Modified: 20100511 target map cropped for refinement, cropped map rescaled 
.PP
Modified: 20120123 (BH) 
.PP
Modified: 20120308 
.PP
Modified: 20120316 added an option to limit shifts along view vectors 
.PP
Modified: 20120329 added functional topp and topn options 
.PP
Modified: 20131129 (BH) 
.PP
Modified: 20150108 (BH) - incorporated into Bsoft 
.PP
Modified: 20150806 (BH) 
.PP
.nf
Based on the code by Bernard Heymann (BH) (bfind.c in bsoft)

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBjsubtomo\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 122 of file jsubtomo\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 42 of file jsubtomo\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
