.TH "kernel" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernlut\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnk\fP"
.br
.ti -1c
.RI "int \fBpower\fP"
.br
.ti -1c
.RI "int \fBnkern\fP"
.br
.ti -1c
.RI "int \fBnker\fP"
.br
.ti -1c
.RI "int \fBbordo\fP"
.br
.ti -1c
.RI "float * \fBkern\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file kernlut\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int kernel::bordo"

.PP
Definition at line 19 of file kernlut\&.h\&.
.SS "float* kernel::kern"

.PP
Definition at line 20 of file kernlut\&.h\&.
.SS "int kernel::nk"

.PP
Definition at line 15 of file kernlut\&.h\&.
.SS "int kernel::nker"

.PP
Definition at line 18 of file kernlut\&.h\&.
.SS "int kernel::nkern"

.PP
Definition at line 17 of file kernlut\&.h\&.
.SS "int kernel::power"

.PP
Definition at line 16 of file kernlut\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
