.TH "LUTable" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LUTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <proj_tool\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBncol\fP"
.br
.ti -1c
.RI "int \fBsizeT\fP"
.br
.ti -1c
.RI "int ** \fBtab1\fP"
.br
.ti -1c
.RI "float ** \fBtab2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file proj_tool\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int LUTable::ncol"

.PP
Definition at line 15 of file proj_tool\&.h\&.
.SS "int LUTable::sizeT"

.PP
Definition at line 15 of file proj_tool\&.h\&.
.SS "int** LUTable::tab1"

.PP
Definition at line 16 of file proj_tool\&.h\&.
.SS "float** LUTable::tab2"

.PP
Definition at line 17 of file proj_tool\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
