.TH "/Users/bernard/b20/bsoft/include/mdoc.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/mdoc.h
.SH SYNOPSIS
.br
.PP
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'json\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMDOCparser\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_MDOC_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
20190109 
.RE
.PP

.PP
Definition in file \fBmdoc\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _MDOC_"

.PP
Definition at line 124 of file mdoc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
