.TH "MFFhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MFFhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwMFF\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpad1\fP"
.br
.ti -1c
.RI "char \fBtitle\fP [80]"
.br
.ti -1c
.RI "int \fBpad2\fP [2]"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "int \fBpad3\fP [2]"
.br
.ti -1c
.RI "float \fBstepu\fP"
.br
.ti -1c
.RI "float \fBstepv\fP"
.br
.ti -1c
.RI "float \fBstepw\fP"
.br
.ti -1c
.RI "int \fBpad4\fP [2]"
.br
.ti -1c
.RI "int \fBidiru\fP"
.br
.ti -1c
.RI "int \fBidirv\fP"
.br
.ti -1c
.RI "int \fBidirw\fP"
.br
.ti -1c
.RI "int \fBpad5\fP [2]"
.br
.ti -1c
.RI "int \fBndiva\fP"
.br
.ti -1c
.RI "int \fBndivb\fP"
.br
.ti -1c
.RI "int \fBndivc\fP"
.br
.ti -1c
.RI "int \fBpad6\fP [2]"
.br
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBpad7\fP [2]"
.br
.ti -1c
.RI "float \fBuvworg\fP [3]"
.br
.ti -1c
.RI "int \fBpad8\fP [2]"
.br
.ti -1c
.RI "float \fBuvwmat\fP [3][3]"
.br
.ti -1c
.RI "int \fBpad9\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwMFF\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float MFFhead::a"

.PP
Definition at line 19 of file rwMFF\&.h\&.
.SS "float MFFhead::alpha"

.PP
Definition at line 22 of file rwMFF\&.h\&.
.SS "float MFFhead::b"

.PP
Definition at line 20 of file rwMFF\&.h\&.
.SS "float MFFhead::beta"

.PP
Definition at line 23 of file rwMFF\&.h\&.
.SS "float MFFhead::c"

.PP
Definition at line 21 of file rwMFF\&.h\&.
.SS "float MFFhead::gamma"

.PP
Definition at line 24 of file rwMFF\&.h\&.
.SS "int MFFhead::idiru"

.PP
Definition at line 30 of file rwMFF\&.h\&.
.SS "int MFFhead::idirv"

.PP
Definition at line 31 of file rwMFF\&.h\&.
.SS "int MFFhead::idirw"

.PP
Definition at line 32 of file rwMFF\&.h\&.
.SS "int MFFhead::ndiva"

.PP
Definition at line 34 of file rwMFF\&.h\&.
.SS "int MFFhead::ndivb"

.PP
Definition at line 35 of file rwMFF\&.h\&.
.SS "int MFFhead::ndivc"

.PP
Definition at line 36 of file rwMFF\&.h\&.
.SS "int MFFhead::nx"

.PP
Definition at line 38 of file rwMFF\&.h\&.
.SS "int MFFhead::ny"

.PP
Definition at line 39 of file rwMFF\&.h\&.
.SS "int MFFhead::nz"

.PP
Definition at line 40 of file rwMFF\&.h\&.
.SS "int MFFhead::pad1"

.PP
Definition at line 16 of file rwMFF\&.h\&.
.SS "int MFFhead::pad2[2]"

.PP
Definition at line 18 of file rwMFF\&.h\&.
.SS "int MFFhead::pad3[2]"

.PP
Definition at line 25 of file rwMFF\&.h\&.
.SS "int MFFhead::pad4[2]"

.PP
Definition at line 29 of file rwMFF\&.h\&.
.SS "int MFFhead::pad5[2]"

.PP
Definition at line 33 of file rwMFF\&.h\&.
.SS "int MFFhead::pad6[2]"

.PP
Definition at line 37 of file rwMFF\&.h\&.
.SS "int MFFhead::pad7[2]"

.PP
Definition at line 41 of file rwMFF\&.h\&.
.SS "int MFFhead::pad8[2]"

.PP
Definition at line 43 of file rwMFF\&.h\&.
.SS "int MFFhead::pad9[2]"

.PP
Definition at line 45 of file rwMFF\&.h\&.
.SS "float MFFhead::stepu"

.PP
Definition at line 26 of file rwMFF\&.h\&.
.SS "float MFFhead::stepv"

.PP
Definition at line 27 of file rwMFF\&.h\&.
.SS "float MFFhead::stepw"

.PP
Definition at line 28 of file rwMFF\&.h\&.
.SS "char MFFhead::title[80]"

.PP
Definition at line 17 of file rwMFF\&.h\&.
.SS "float MFFhead::uvwmat[3][3]"

.PP
Definition at line 44 of file rwMFF\&.h\&.
.SS "float MFFhead::uvworg[3]"

.PP
Definition at line 42 of file rwMFF\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
