.TH "/Users/bernard/b20/bsoft/src/mg/mg_marker.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/mg/mg_marker.cpp \- Functions for dealing with markers and linkers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_marker\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBproject_marker_lists\fP (\fBBproject\fP *\fBproject\fP)"
.br
.RI "Lists micrograph markers\&. "
.ti -1c
.RI "long \fBproject_marker_in_particle\fP (\fBBproject\fP *\fBproject\fP)"
.br
.RI "Enumerates markers within particles\&. "
.ti -1c
.RI "long \fBproject_marker_in_particle_image\fP (\fBBproject\fP *\fBproject\fP, double marker_radius)"
.br
.RI "Enumerates markers within particles\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for dealing with markers and linkers\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20150212 
.PP
Modified: 20150212 
.RE
.PP

.PP
Definition in file \fBmg_marker\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "long project_marker_in_particle (\fBBproject\fP * project)"

.PP
Enumerates markers within particles\&. 
.PP
\fBParameters\fP
.RS 4
\fI*project\fP micrograph project\&. 
.RE
.PP
\fBReturns\fP
.RS 4
long number of markers (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 72 of file mg_marker\&.cpp\&.
.SS "long project_marker_in_particle_image (\fBBproject\fP * project, double marker_radius)"

.PP
Enumerates markers within particles\&. 
.PP
\fBParameters\fP
.RS 4
\fI*project\fP micrograph project\&. 
.br
\fImarker_radius\fP search radius to associate with marker\&. 
.RE
.PP
\fBReturns\fP
.RS 4
long number of markers (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 135 of file mg_marker\&.cpp\&.
.SS "long project_marker_lists (\fBBproject\fP * project)"

.PP
Lists micrograph markers\&. 
.PP
\fBParameters\fP
.RS 4
\fI*project\fP micrograph project\&. 
.RE
.PP
\fBReturns\fP
.RS 4
long number of markers (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 23 of file mg_marker\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
