.TH "/Users/bernard/b20/bsoft/include/mg_tags.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/mg_tags.h \- All STAR and XML file format tags for micrographs and reconstructions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMMENT\fP   'comment'"
.br
.ti -1c
.RI "#define \fBID\fP   'id'"
.br
.ti -1c
.RI "#define \fBPROJECT\fP   'project'"
.br
.ti -1c
.RI "#define \fBFIELD\fP   'field'"
.br
.ti -1c
.RI "#define \fBFIELD_ID\fP   'field\&.id'"
.br
.ti -1c
.RI "#define \fBFIELD_SELECT\fP   'field\&.select'"
.br
.ti -1c
.RI "#define \fBFIELD_FOM\fP   'field\&.fom'"
.br
.ti -1c
.RI "#define \fBMAP\fP   'map\&.3D_reconstruction'"
.br
.ti -1c
.RI "#define \fBMAP_ID\fP   'map\&.3D_reconstruction\&.id'"
.br
.ti -1c
.RI "#define \fBMAP_REFERENCE\fP   'map\&.reference\&.file_name'"
.br
.ti -1c
.RI "#define \fBMAP_RECONSTRUCTION\fP   'map\&.3D_reconstruction\&.file_name'"
.br
.ti -1c
.RI "#define \fBMAP_TRANSFORM_FILE\fP   'map\&.3D_reconstruction_fourier_transform\&.file_name'"
.br
.ti -1c
.RI "#define \fBMAP_POWERSPEC_FILE\fP   'map\&.3D_reconstruction_powerspectrum\&.file_name'"
.br
.ti -1c
.RI "#define \fBMAP_SIZE_X\fP   'map\&.3D_reconstruction\&.size_x'"
.br
.ti -1c
.RI "#define \fBMAP_SIZE_Y\fP   'map\&.3D_reconstruction\&.size_y'"
.br
.ti -1c
.RI "#define \fBMAP_SIZE_Z\fP   'map\&.3D_reconstruction\&.size_z'"
.br
.ti -1c
.RI "#define \fBMAP_ORIGIN_X\fP   'map\&.3D_reconstruction\&.origin_x'"
.br
.ti -1c
.RI "#define \fBMAP_ORIGIN_Y\fP   'map\&.3D_reconstruction\&.origin_y'"
.br
.ti -1c
.RI "#define \fBMAP_ORIGIN_Z\fP   'map\&.3D_reconstruction\&.origin_z'"
.br
.ti -1c
.RI "#define \fBMAP_SCALE_X\fP   'map\&.3D_reconstruction\&.scale_x'"
.br
.ti -1c
.RI "#define \fBMAP_SCALE_Y\fP   'map\&.3D_reconstruction\&.scale_y'"
.br
.ti -1c
.RI "#define \fBMAP_SCALE_Z\fP   'map\&.3D_reconstruction\&.scale_z'"
.br
.ti -1c
.RI "#define \fBMAP_VOXEL_SIZE\fP   'map\&.3D_reconstruction\&.voxel_size'"
.br
.ti -1c
.RI "#define \fBMAP_VOXEL_SIZE_X\fP   'map\&.3D_reconstruction\&.voxel_size_x'"
.br
.ti -1c
.RI "#define \fBMAP_VOXEL_SIZE_Y\fP   'map\&.3D_reconstruction\&.voxel_size_y'"
.br
.ti -1c
.RI "#define \fBMAP_VOXEL_SIZE_Z\fP   'map\&.3D_reconstruction\&.voxel_size_z'"
.br
.ti -1c
.RI "#define \fBMAP_SELECT\fP   'map\&.3D_reconstruction\&.select'"
.br
.ti -1c
.RI "#define \fBMAP_FOM\fP   'map\&.3D_reconstruction\&.fom'"
.br
.ti -1c
.RI "#define \fBMAP_MAGNIFICATION\fP   'map\&.magnification'"
.br
.ti -1c
.RI "#define \fBMAP_VIEW_X\fP   'map\&.view_x'"
.br
.ti -1c
.RI "#define \fBMAP_VIEW_Y\fP   'map\&.view_y'"
.br
.ti -1c
.RI "#define \fBMAP_VIEW_Z\fP   'map\&.view_z'"
.br
.ti -1c
.RI "#define \fBMAP_VIEW_ANGLE\fP   'map\&.view_angle'"
.br
.ti -1c
.RI "#define \fBMAP_BACK_RWEIGHT\fP   'map\&.back_projection\&.rweight'"
.br
.ti -1c
.RI "#define \fBMAP_MODEL\fP   'map\&.model'"
.br
.ti -1c
.RI "#define \fBMAP_SYMMETRY\fP   'map\&.symmetry'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH\fP   'micrograph'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FILE\fP   'micrograph\&.file_name'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAMES_FILE\fP   'micrograph_frames\&.file_name'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME\fP   'micrograph_frame\&.number'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_PIXEL_X\fP   'micrograph_frame\&.pixel_size_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_PIXEL_Y\fP   'micrograph_frame\&.pixel_size_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_PIXEL_Z\fP   'micrograph_frame\&.pixel_size_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_SHIFT_X\fP   'micrograph_frame\&.shift_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_SHIFT_Y\fP   'micrograph_frame\&.shift_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_SELECT\fP   'micrograph_frame\&.select'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FRAME_FOM\fP   'micrograph_frame\&.fom'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_PARTICLE_FILE\fP   'micrograph_particle\&.file_name'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FILAMENT_FILE\fP   'micrograph_filament\&.file_name'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_TRANSFORM_FILE\fP   'micrograph_fourier_transform\&.file_name'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_POWERSPEC_FILE\fP   'micrograph_powerspectrum\&.file_name'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_ID\fP   'micrograph\&.id'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FIELD_ID\fP   'micrograph\&.field_id'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_NUMBER\fP   'micrograph\&.number'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_SELECT\fP   'micrograph\&.select'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FOM\fP   'micrograph\&.fom'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MAGNIFICATION\fP   'micrograph\&.magnification'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_SAMPLING\fP   'micrograph\&.sampling'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_PIXEL\fP   'micrograph\&.pixel_size'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_PIXEL_X\fP   'micrograph\&.pixel_size_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_PIXEL_Y\fP   'micrograph\&.pixel_size_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_PIXEL_Z\fP   'micrograph\&.pixel_size_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_UNITS\fP   'micrograph\&.units'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_DOSE\fP   'micrograph\&.electron_dose'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_EXPOSURE\fP   'micrograph\&.exposure'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_INTENSITY\fP   'micrograph\&.intensity'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_WATER_RING\fP   'micrograph\&.water_ring_index'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_ORIGIN_X\fP   'micrograph\&.origin_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_ORIGIN_Y\fP   'micrograph\&.origin_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_ORIGIN_Z\fP   'micrograph\&.origin_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_SCALE_X\fP   'micrograph\&.scale_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_SCALE_Y\fP   'micrograph\&.scale_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_SCALE_Z\fP   'micrograph\&.scale_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_TILT_AXIS\fP   'micrograph\&.tilt_axis'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_TILT_ANGLE\fP   'micrograph\&.tilt_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_LEVEL_ANGLE\fP   'micrograph\&.level_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_ROT_ANGLE\fP   'micrograph\&.rotation_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_VIEW_X\fP   'micrograph\&.view_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_VIEW_Y\fP   'micrograph\&.view_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_VIEW_Z\fP   'micrograph\&.view_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_VIEW_ANGLE\fP   'micrograph\&.view_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_1_1\fP   'micrograph\&.matrix_1_1'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_1_2\fP   'micrograph\&.matrix_1_2'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_1_3\fP   'micrograph\&.matrix_1_3'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_2_1\fP   'micrograph\&.matrix_2_1'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_2_2\fP   'micrograph\&.matrix_2_2'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_2_3\fP   'micrograph\&.matrix_2_3'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_3_1\fP   'micrograph\&.matrix_3_1'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_3_2\fP   'micrograph\&.matrix_3_2'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MATRIX_3_3\fP   'micrograph\&.matrix_3_3'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HVEC_X\fP   'micrograph\&.h_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HVEC_Y\fP   'micrograph\&.h_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HVEC_Z\fP   'micrograph\&.h_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_KVEC_X\fP   'micrograph\&.k_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_KVEC_Y\fP   'micrograph\&.k_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_KVEC_Z\fP   'micrograph\&.k_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_LVEC_X\fP   'micrograph\&.l_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_LVEC_Y\fP   'micrograph\&.l_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_LVEC_Z\fP   'micrograph\&.l_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HELIX_AXIS\fP   'micrograph\&.helix_axis_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HELIX_RISE\fP   'micrograph\&.helix_subunit_rise'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HELIX_ANGLE\fP   'micrograph\&.helix_subunit_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_HELIX_RADIUS\fP   'micrograph\&.helix_radius'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_VOLTAGE\fP   'micrograph\&.voltage'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_CS\fP   'micrograph\&.ctf\&.Cs'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_CC\fP   'micrograph\&.ctf\&.Cc'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_ALPHA\fP   'micrograph\&.ctf\&.alpha'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_DE\fP   'micrograph\&.ctf\&.energy_spread'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_AMP_CONT\fP   'micrograph\&.ctf\&.amp_contrast'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_ZERO\fP   'micrograph\&.ctf\&.first_zero'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_DEF_AVG\fP   'micrograph\&.ctf\&.defocus_average'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_DEF_DEV\fP   'micrograph\&.ctf\&.defocus_deviation'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_DEF_MIN\fP   'micrograph\&.ctf\&.defocus_min'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_DEF_MAX\fP   'micrograph\&.ctf\&.defocus_max'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_AST_ANG\fP   'micrograph\&.ctf\&.astigmatism_angle'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_BASELINE\fP   'micrograph\&.ctf\&.baseline'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_CTF_ENVELOPE\fP   'micrograph\&.ctf\&.envelope'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BOX_RADIUS\fP   'micrograph\&.box_radius'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BOX_RADIUS_X\fP   'micrograph\&.box_radius_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BOX_RADIUS_Y\fP   'micrograph\&.box_radius_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BOX_RADIUS_Z\fP   'micrograph\&.box_radius_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BAD\fP   'micrograph\&.bad'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BAD_RADIUS\fP   'micrograph\&.bad_radius'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BAD_X\fP   'micrograph\&.bad_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BAD_Y\fP   'micrograph\&.bad_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_BAD_Z\fP   'micrograph\&.bad_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_RADIUS\fP   'micrograph\&.marker_radius'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_ID\fP   'micrograph\&.marker_id'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_X\fP   'micrograph\&.marker_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_Y\fP   'micrograph\&.marker_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_Z\fP   'micrograph\&.marker_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_ERROR_X\fP   'micrograph\&.marker_error_x'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_ERROR_Y\fP   'micrograph\&.marker_error_y'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_ERROR_Z\fP   'micrograph\&.marker_error_z'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_MARKER_FOM\fP   'micrograph\&.marker_fom'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FILAMENT_WIDTH\fP   'micrograph\&.filament_width'"
.br
.ti -1c
.RI "#define \fBMICROGRAPH_FILNODE_RADIUS\fP   'micrograph\&.filament_node_radius'"
.br
.ti -1c
.RI "#define \fBCTF\fP   'ctf'"
.br
.ti -1c
.RI "#define \fBCTF_VOLTAGE\fP   'ctf\&.voltage'"
.br
.ti -1c
.RI "#define \fBCTF_FOCAL\fP   'ctf\&.focal_length'"
.br
.ti -1c
.RI "#define \fBCTF_APERTURE\fP   'ctf\&.objective_aperture'"
.br
.ti -1c
.RI "#define \fBCTF_CS\fP   'ctf\&.Cs'"
.br
.ti -1c
.RI "#define \fBCTF_CC\fP   'ctf\&.Cc'"
.br
.ti -1c
.RI "#define \fBCTF_ALPHA\fP   'ctf\&.alpha'"
.br
.ti -1c
.RI "#define \fBCTF_DE\fP   'ctf\&.energy_spread'"
.br
.ti -1c
.RI "#define \fBCTF_AMP\fP   'ctf\&.amp_contrast'"
.br
.ti -1c
.RI "#define \fBCTF_AMP_SHIFT\fP   'ctf\&.amplitude_phase_shift'"
.br
.ti -1c
.RI "#define \fBCTF_ZERO\fP   'ctf\&.first_zero'"
.br
.ti -1c
.RI "#define \fBCTF_DEF_AVG\fP   'ctf\&.defocus_average'"
.br
.ti -1c
.RI "#define \fBCTF_DEF_DEV\fP   'ctf\&.defocus_deviation'"
.br
.ti -1c
.RI "#define \fBCTF_DEF_MIN\fP   'ctf\&.defocus_min'"
.br
.ti -1c
.RI "#define \fBCTF_DEF_MAX\fP   'ctf\&.defocus_max'"
.br
.ti -1c
.RI "#define \fBCTF_AST_ANG\fP   'ctf\&.astigmatism_angle'"
.br
.ti -1c
.RI "#define \fBCTF_BASELINE\fP   'ctf\&.baseline'"
.br
.ti -1c
.RI "#define \fBCTF_ENVELOPE\fP   'ctf\&.envelope'"
.br
.ti -1c
.RI "#define \fBPARTICLE\fP   'particle'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FILE\fP   'particle\&.file_name'"
.br
.ti -1c
.RI "#define \fBPARTICLE_NUMBER\fP   'particle\&.number'"
.br
.ti -1c
.RI "#define \fBPARTICLE_ID\fP   'particle\&.id'"
.br
.ti -1c
.RI "#define \fBPARTICLE_GROUP\fP   'particle\&.group_id'"
.br
.ti -1c
.RI "#define \fBPARTICLE_MG_ID\fP   'particle\&.micrograph_id'"
.br
.ti -1c
.RI "#define \fBPARTICLE_MG_X\fP   'particle\&.micrograph_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_MG_Y\fP   'particle\&.micrograph_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_MG_Z\fP   'particle\&.micrograph_z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_X\fP   'particle\&.x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_Y\fP   'particle\&.y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_Z\fP   'particle\&.z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_X_ORIGIN\fP   'particle\&.x_origin'"
.br
.ti -1c
.RI "#define \fBPARTICLE_Y_ORIGIN\fP   'particle\&.y_origin'"
.br
.ti -1c
.RI "#define \fBPARTICLE_Z_ORIGIN\fP   'particle\&.z_origin'"
.br
.ti -1c
.RI "#define \fBPARTICLE_ORIGIN_X\fP   'particle\&.origin_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_ORIGIN_Y\fP   'particle\&.origin_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_ORIGIN_Z\fP   'particle\&.origin_z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PSI\fP   'particle\&.psi'"
.br
.ti -1c
.RI "#define \fBPARTICLE_THETA\fP   'particle\&.theta'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PHI\fP   'particle\&.phi'"
.br
.ti -1c
.RI "#define \fBPARTICLE_OMEGA\fP   'particle\&.omega'"
.br
.ti -1c
.RI "#define \fBPARTICLE_VIEW_X\fP   'particle\&.view_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_VIEW_Y\fP   'particle\&.view_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_VIEW_Z\fP   'particle\&.view_z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_VIEW_ANGLE\fP   'particle\&.view_angle'"
.br
.ti -1c
.RI "#define \fBPARTICLE_MAGNIF\fP   'particle\&.magnification'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PIXEL\fP   'particle\&.pixel_size'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PIXEL_X\fP   'particle\&.pixel_size_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PIXEL_Y\fP   'particle\&.pixel_size_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PIXEL_Z\fP   'particle\&.pixel_size_z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_DEFOCUS\fP   'particle\&.defocus'"
.br
.ti -1c
.RI "#define \fBPARTICLE_DEF_DEV\fP   'particle\&.defocus_deviation'"
.br
.ti -1c
.RI "#define \fBPARTICLE_AST_ANG\fP   'particle\&.astigmatism_angle'"
.br
.ti -1c
.RI "#define \fBPARTICLE_SELECT\fP   'particle\&.select'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM\fP   'particle\&.fom'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM_CV\fP   'particle\&.fom_crossvalidation'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM_SNR\fP   'particle\&.signal_to_noise'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM_AVG\fP   'particle\&.fom_average'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM_STD\fP   'particle\&.fom_stdev'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM1\fP   'particle\&.fom1'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM2\fP   'particle\&.fom2'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM3\fP   'particle\&.fom3'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM4\fP   'particle\&.fom4'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM5\fP   'particle\&.fom5'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM6\fP   'particle\&.fom6'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM7\fP   'particle\&.fom7'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM8\fP   'particle\&.fom8'"
.br
.ti -1c
.RI "#define \fBPARTICLE_FOM9\fP   'particle\&.fom9'"
.br
.ti -1c
.RI "#define \fBPARTICLE_HANDA_FOM\fP   'particle\&.handa_fom'"
.br
.ti -1c
.RI "#define \fBPARTICLE_HANDB_FOM\fP   'particle\&.handb_fom'"
.br
.ti -1c
.RI "#define \fBPARTICLE_CC\fP   'particle\&.cc'"
.br
.ti -1c
.RI "#define \fBPARTICLE_CC_AVG\fP   'particle\&.cc_avg'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PFT_CC\fP   'particle\&.pft_cc'"
.br
.ti -1c
.RI "#define \fBPARTICLE_PRJ_CC\fP   'particle\&.prj_cc'"
.br
.ti -1c
.RI "#define \fBPARTICLE_CMP_CC\fP   'particle\&.cmp_cc'"
.br
.ti -1c
.RI "#define \fBPARTICLE_RFACTORAB\fP   'particle\&.rfactorab'"
.br
.ti -1c
.RI "#define \fBPARTICLE_COVERAGE\fP   'particle\&.coverage'"
.br
.ti -1c
.RI "#define \fBPARTICLE_DENSITY\fP   'particle\&.density'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_SIZE\fP   'particle\&.box_size'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_SIZE_X\fP   'particle\&.box_size_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_SIZE_Y\fP   'particle\&.box_size_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_SIZE_Z\fP   'particle\&.box_size_z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_RADIUS\fP   'particle\&.box_radius'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_RADIUS_X\fP   'particle\&.box_radius_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_RADIUS_Y\fP   'particle\&.box_radius_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BOX_RADIUS_Z\fP   'particle\&.box_radius_z'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BAD\fP   'particle\&.bad'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BAD_RADIUS\fP   'particle\&.bad_radius'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BAD_X\fP   'particle\&.bad_x'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BAD_Y\fP   'particle\&.bad_y'"
.br
.ti -1c
.RI "#define \fBPARTICLE_BAD_Z\fP   'particle\&.bad_z'"
.br
.ti -1c
.RI "#define \fBCLASS_AVERAGE\fP   'class_average'"
.br
.ti -1c
.RI "#define \fBFILAMENT\fP   'filament'"
.br
.ti -1c
.RI "#define \fBFILAMENT_FILE\fP   'filament\&.file_name'"
.br
.ti -1c
.RI "#define \fBFILAMENT_ID\fP   'filament\&.id'"
.br
.ti -1c
.RI "#define \fBFILAMENT_NODE\fP   'filament\&.node'"
.br
.ti -1c
.RI "#define \fBFILAMENT_NODE_ID\fP   'filament\&.node_id'"
.br
.ti -1c
.RI "#define \fBFILAMENT_NODE_X\fP   'filament\&.x'"
.br
.ti -1c
.RI "#define \fBFILAMENT_NODE_Y\fP   'filament\&.y'"
.br
.ti -1c
.RI "#define \fBFILAMENT_NODE_Z\fP   'filament\&.z'"
.br
.ti -1c
.RI "#define \fBFILAMENT_WIDTH\fP   'filament\&.width'"
.br
.ti -1c
.RI "#define \fBFILNODE_RADIUS\fP   'filament\&.node_radius'"
.br
.ti -1c
.RI "#define \fBORIENT_ID\fP   'orient\&.id'"
.br
.ti -1c
.RI "#define \fBORIENT_ORIGIN_X\fP   'orient\&.origin_x'"
.br
.ti -1c
.RI "#define \fBORIENT_ORIGIN_Y\fP   'orient\&.origin_y'"
.br
.ti -1c
.RI "#define \fBORIENT_ORIGIN_Z\fP   'orient\&.origin_z'"
.br
.ti -1c
.RI "#define \fBORIENT_VIEW_X\fP   'orient\&.view_x'"
.br
.ti -1c
.RI "#define \fBORIENT_VIEW_Y\fP   'orient\&.view_y'"
.br
.ti -1c
.RI "#define \fBORIENT_VIEW_Z\fP   'orient\&.view_z'"
.br
.ti -1c
.RI "#define \fBORIENT_VIEW_ANGLE\fP   'orient\&.view_angle'"
.br
.ti -1c
.RI "#define \fBORIENT_FOM\fP   'orient\&.fom'"
.br
.ti -1c
.RI "#define \fBORIENT_SELECT\fP   'orient\&.select'"
.br
.ti -1c
.RI "#define \fBMARKER\fP   'marker'"
.br
.ti -1c
.RI "#define \fBMARKER_RADIUS\fP   'marker\&.radius'"
.br
.ti -1c
.RI "#define \fBMARKER_ID\fP   'marker\&.id'"
.br
.ti -1c
.RI "#define \fBMARKER_X\fP   'marker\&.x'"
.br
.ti -1c
.RI "#define \fBMARKER_Y\fP   'marker\&.y'"
.br
.ti -1c
.RI "#define \fBMARKER_Z\fP   'marker\&.z'"
.br
.ti -1c
.RI "#define \fBMARKER_ERROR_X\fP   'marker\&.error_x'"
.br
.ti -1c
.RI "#define \fBMARKER_ERROR_Y\fP   'marker\&.error_y'"
.br
.ti -1c
.RI "#define \fBMARKER_ERROR_Z\fP   'marker\&.error_z'"
.br
.ti -1c
.RI "#define \fBMARKER_IMAGE\fP   'marker\&.image_number'"
.br
.ti -1c
.RI "#define \fBMARKER_RESIDUAL\fP   'marker\&.residual'"
.br
.ti -1c
.RI "#define \fBMARKER_FOM\fP   'marker\&.fom'"
.br
.ti -1c
.RI "#define \fBMARKER_SELECT\fP   'marker\&.select'"
.br
.ti -1c
.RI "#define \fBREFLEX\fP   'refln'"
.br
.ti -1c
.RI "#define \fBREFLEX_RADIUS\fP   'refln\&.radius'"
.br
.ti -1c
.RI "#define \fBREFLEX_X\fP   'refln\&.location_x'"
.br
.ti -1c
.RI "#define \fBREFLEX_Y\fP   'refln\&.location_y'"
.br
.ti -1c
.RI "#define \fBREFLEX_Z\fP   'refln\&.location_z'"
.br
.ti -1c
.RI "#define \fBREFLEX_H\fP   'refln\&.index_h'"
.br
.ti -1c
.RI "#define \fBREFLEX_K\fP   'refln\&.index_k'"
.br
.ti -1c
.RI "#define \fBREFLEX_L\fP   'refln\&.index_l'"
.br
.ti -1c
.RI "#define \fBREFLEX_AMP\fP   'refln\&.F_meas_au'"
.br
.ti -1c
.RI "#define \fBREFLEX_SIGAMP\fP   'refln\&.F_meas_sigma_au'"
.br
.ti -1c
.RI "#define \fBREFLEX_PHI\fP   'refln\&.phase_meas'"
.br
.ti -1c
.RI "#define \fBREFLEX_SIGPHI\fP   'refln\&.phase_sigma'"
.br
.ti -1c
.RI "#define \fBREFLEX_FOM\fP   'refln\&.weight'"
.br
.ti -1c
.RI "#define \fBREFLEX_STATUS\fP   'refln\&.status'"
.br
.ti -1c
.RI "#define \fBLAYERLINE\fP   'layer_line'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_NUMBER\fP   'layer_line\&.number'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_ORDER\fP   'layer_line\&.bessel_order'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_DISTANCE\fP   'layer_line\&.distance'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_FREQ\fP   'layer_line\&.frequency'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_AMP\fP   'layer_line\&.amplitude'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_FOM\fP   'layer_line\&.fom'"
.br
.ti -1c
.RI "#define \fBLAYERLINE_SELECT\fP   'layer_line\&.select'"
.br
.in -1c
.SH "Detailed Description"
.PP 
All STAR and XML file format tags for micrographs and reconstructions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000419 
.PP
Modified: 20210728 
.RE
.PP

.PP
Definition in file \fBmg_tags\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLASS_AVERAGE   'class_average'"

.PP
Definition at line 259 of file mg_tags\&.h\&.
.SS "#define COMMENT   'comment'"

.PP
Definition at line 21 of file mg_tags\&.h\&.
.SS "#define CTF   'ctf'"

.PP
Definition at line 165 of file mg_tags\&.h\&.
.SS "#define CTF_ALPHA   'ctf\&.alpha'"

.PP
Definition at line 171 of file mg_tags\&.h\&.
.SS "#define CTF_AMP   'ctf\&.amp_contrast'"

.PP
Definition at line 173 of file mg_tags\&.h\&.
.SS "#define CTF_AMP_SHIFT   'ctf\&.amplitude_phase_shift'"

.PP
Definition at line 174 of file mg_tags\&.h\&.
.SS "#define CTF_APERTURE   'ctf\&.objective_aperture'"

.PP
Definition at line 168 of file mg_tags\&.h\&.
.SS "#define CTF_AST_ANG   'ctf\&.astigmatism_angle'"

.PP
Definition at line 180 of file mg_tags\&.h\&.
.SS "#define CTF_BASELINE   'ctf\&.baseline'"

.PP
Definition at line 181 of file mg_tags\&.h\&.
.SS "#define CTF_CC   'ctf\&.Cc'"

.PP
Definition at line 170 of file mg_tags\&.h\&.
.SS "#define CTF_CS   'ctf\&.Cs'"

.PP
Definition at line 169 of file mg_tags\&.h\&.
.SS "#define CTF_DE   'ctf\&.energy_spread'"

.PP
Definition at line 172 of file mg_tags\&.h\&.
.SS "#define CTF_DEF_AVG   'ctf\&.defocus_average'"

.PP
Definition at line 176 of file mg_tags\&.h\&.
.SS "#define CTF_DEF_DEV   'ctf\&.defocus_deviation'"

.PP
Definition at line 177 of file mg_tags\&.h\&.
.SS "#define CTF_DEF_MAX   'ctf\&.defocus_max'"

.PP
Definition at line 179 of file mg_tags\&.h\&.
.SS "#define CTF_DEF_MIN   'ctf\&.defocus_min'"

.PP
Definition at line 178 of file mg_tags\&.h\&.
.SS "#define CTF_ENVELOPE   'ctf\&.envelope'"

.PP
Definition at line 182 of file mg_tags\&.h\&.
.SS "#define CTF_FOCAL   'ctf\&.focal_length'"

.PP
Definition at line 167 of file mg_tags\&.h\&.
.SS "#define CTF_VOLTAGE   'ctf\&.voltage'"

.PP
Definition at line 166 of file mg_tags\&.h\&.
.SS "#define CTF_ZERO   'ctf\&.first_zero'"

.PP
Definition at line 175 of file mg_tags\&.h\&.
.SS "#define FIELD   'field'"

.PP
Definition at line 25 of file mg_tags\&.h\&.
.SS "#define FIELD_FOM   'field\&.fom'"

.PP
Definition at line 28 of file mg_tags\&.h\&.
.SS "#define FIELD_ID   'field\&.id'"

.PP
Definition at line 26 of file mg_tags\&.h\&.
.SS "#define FIELD_SELECT   'field\&.select'"

.PP
Definition at line 27 of file mg_tags\&.h\&.
.SS "#define FILAMENT   'filament'"

.PP
Definition at line 262 of file mg_tags\&.h\&.
.SS "#define FILAMENT_FILE   'filament\&.file_name'"

.PP
Definition at line 263 of file mg_tags\&.h\&.
.SS "#define FILAMENT_ID   'filament\&.id'"

.PP
Definition at line 264 of file mg_tags\&.h\&.
.SS "#define FILAMENT_NODE   'filament\&.node'"

.PP
Definition at line 265 of file mg_tags\&.h\&.
.SS "#define FILAMENT_NODE_ID   'filament\&.node_id'"

.PP
Definition at line 266 of file mg_tags\&.h\&.
.SS "#define FILAMENT_NODE_X   'filament\&.x'"

.PP
Definition at line 267 of file mg_tags\&.h\&.
.SS "#define FILAMENT_NODE_Y   'filament\&.y'"

.PP
Definition at line 268 of file mg_tags\&.h\&.
.SS "#define FILAMENT_NODE_Z   'filament\&.z'"

.PP
Definition at line 269 of file mg_tags\&.h\&.
.SS "#define FILAMENT_WIDTH   'filament\&.width'"

.PP
Definition at line 270 of file mg_tags\&.h\&.
.SS "#define FILNODE_RADIUS   'filament\&.node_radius'"

.PP
Definition at line 271 of file mg_tags\&.h\&.
.SS "#define ID   'id'"

.PP
Definition at line 22 of file mg_tags\&.h\&.
.SS "#define LAYERLINE   'layer_line'"

.PP
Definition at line 318 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_AMP   'layer_line\&.amplitude'"

.PP
Definition at line 323 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_DISTANCE   'layer_line\&.distance'"

.PP
Definition at line 321 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_FOM   'layer_line\&.fom'"

.PP
Definition at line 324 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_FREQ   'layer_line\&.frequency'"

.PP
Definition at line 322 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_NUMBER   'layer_line\&.number'"

.PP
Definition at line 319 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_ORDER   'layer_line\&.bessel_order'"

.PP
Definition at line 320 of file mg_tags\&.h\&.
.SS "#define LAYERLINE_SELECT   'layer_line\&.select'"

.PP
Definition at line 325 of file mg_tags\&.h\&.
.SS "#define MAP   'map\&.3D_reconstruction'"

.PP
Definition at line 31 of file mg_tags\&.h\&.
.SS "#define MAP_BACK_RWEIGHT   'map\&.back_projection\&.rweight'"

.PP
Definition at line 57 of file mg_tags\&.h\&.
.SS "#define MAP_FOM   'map\&.3D_reconstruction\&.fom'"

.PP
Definition at line 51 of file mg_tags\&.h\&.
.SS "#define MAP_ID   'map\&.3D_reconstruction\&.id'"

.PP
Definition at line 32 of file mg_tags\&.h\&.
.SS "#define MAP_MAGNIFICATION   'map\&.magnification'"

.PP
Definition at line 52 of file mg_tags\&.h\&.
.SS "#define MAP_MODEL   'map\&.model'"

.PP
Definition at line 58 of file mg_tags\&.h\&.
.SS "#define MAP_ORIGIN_X   'map\&.3D_reconstruction\&.origin_x'"

.PP
Definition at line 40 of file mg_tags\&.h\&.
.SS "#define MAP_ORIGIN_Y   'map\&.3D_reconstruction\&.origin_y'"

.PP
Definition at line 41 of file mg_tags\&.h\&.
.SS "#define MAP_ORIGIN_Z   'map\&.3D_reconstruction\&.origin_z'"

.PP
Definition at line 42 of file mg_tags\&.h\&.
.SS "#define MAP_POWERSPEC_FILE   'map\&.3D_reconstruction_powerspectrum\&.file_name'"

.PP
Definition at line 36 of file mg_tags\&.h\&.
.SS "#define MAP_RECONSTRUCTION   'map\&.3D_reconstruction\&.file_name'"

.PP
Definition at line 34 of file mg_tags\&.h\&.
.SS "#define MAP_REFERENCE   'map\&.reference\&.file_name'"

.PP
Definition at line 33 of file mg_tags\&.h\&.
.SS "#define MAP_SCALE_X   'map\&.3D_reconstruction\&.scale_x'"

.PP
Definition at line 43 of file mg_tags\&.h\&.
.SS "#define MAP_SCALE_Y   'map\&.3D_reconstruction\&.scale_y'"

.PP
Definition at line 44 of file mg_tags\&.h\&.
.SS "#define MAP_SCALE_Z   'map\&.3D_reconstruction\&.scale_z'"

.PP
Definition at line 45 of file mg_tags\&.h\&.
.SS "#define MAP_SELECT   'map\&.3D_reconstruction\&.select'"

.PP
Definition at line 50 of file mg_tags\&.h\&.
.SS "#define MAP_SIZE_X   'map\&.3D_reconstruction\&.size_x'"

.PP
Definition at line 37 of file mg_tags\&.h\&.
.SS "#define MAP_SIZE_Y   'map\&.3D_reconstruction\&.size_y'"

.PP
Definition at line 38 of file mg_tags\&.h\&.
.SS "#define MAP_SIZE_Z   'map\&.3D_reconstruction\&.size_z'"

.PP
Definition at line 39 of file mg_tags\&.h\&.
.SS "#define MAP_SYMMETRY   'map\&.symmetry'"

.PP
Definition at line 59 of file mg_tags\&.h\&.
.SS "#define MAP_TRANSFORM_FILE   'map\&.3D_reconstruction_fourier_transform\&.file_name'"

.PP
Definition at line 35 of file mg_tags\&.h\&.
.SS "#define MAP_VIEW_ANGLE   'map\&.view_angle'"

.PP
Definition at line 56 of file mg_tags\&.h\&.
.SS "#define MAP_VIEW_X   'map\&.view_x'"

.PP
Definition at line 53 of file mg_tags\&.h\&.
.SS "#define MAP_VIEW_Y   'map\&.view_y'"

.PP
Definition at line 54 of file mg_tags\&.h\&.
.SS "#define MAP_VIEW_Z   'map\&.view_z'"

.PP
Definition at line 55 of file mg_tags\&.h\&.
.SS "#define MAP_VOXEL_SIZE   'map\&.3D_reconstruction\&.voxel_size'"

.PP
Definition at line 46 of file mg_tags\&.h\&.
.SS "#define MAP_VOXEL_SIZE_X   'map\&.3D_reconstruction\&.voxel_size_x'"

.PP
Definition at line 47 of file mg_tags\&.h\&.
.SS "#define MAP_VOXEL_SIZE_Y   'map\&.3D_reconstruction\&.voxel_size_y'"

.PP
Definition at line 48 of file mg_tags\&.h\&.
.SS "#define MAP_VOXEL_SIZE_Z   'map\&.3D_reconstruction\&.voxel_size_z'"

.PP
Definition at line 49 of file mg_tags\&.h\&.
.SS "#define MARKER   'marker'"

.PP
Definition at line 286 of file mg_tags\&.h\&.
.SS "#define MARKER_ERROR_X   'marker\&.error_x'"

.PP
Definition at line 292 of file mg_tags\&.h\&.
.SS "#define MARKER_ERROR_Y   'marker\&.error_y'"

.PP
Definition at line 293 of file mg_tags\&.h\&.
.SS "#define MARKER_ERROR_Z   'marker\&.error_z'"

.PP
Definition at line 294 of file mg_tags\&.h\&.
.SS "#define MARKER_FOM   'marker\&.fom'"

.PP
Definition at line 297 of file mg_tags\&.h\&.
.SS "#define MARKER_ID   'marker\&.id'"

.PP
Definition at line 288 of file mg_tags\&.h\&.
.SS "#define MARKER_IMAGE   'marker\&.image_number'"

.PP
Definition at line 295 of file mg_tags\&.h\&.
.SS "#define MARKER_RADIUS   'marker\&.radius'"

.PP
Definition at line 287 of file mg_tags\&.h\&.
.SS "#define MARKER_RESIDUAL   'marker\&.residual'"

.PP
Definition at line 296 of file mg_tags\&.h\&.
.SS "#define MARKER_SELECT   'marker\&.select'"

.PP
Definition at line 298 of file mg_tags\&.h\&.
.SS "#define MARKER_X   'marker\&.x'"

.PP
Definition at line 289 of file mg_tags\&.h\&.
.SS "#define MARKER_Y   'marker\&.y'"

.PP
Definition at line 290 of file mg_tags\&.h\&.
.SS "#define MARKER_Z   'marker\&.z'"

.PP
Definition at line 291 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH   'micrograph'"

.PP
Definition at line 62 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BAD   'micrograph\&.bad'"

.PP
Definition at line 147 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BAD_RADIUS   'micrograph\&.bad_radius'"

.PP
Definition at line 148 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BAD_X   'micrograph\&.bad_x'"

.PP
Definition at line 149 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BAD_Y   'micrograph\&.bad_y'"

.PP
Definition at line 150 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BAD_Z   'micrograph\&.bad_z'"

.PP
Definition at line 151 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BOX_RADIUS   'micrograph\&.box_radius'"

.PP
Definition at line 143 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BOX_RADIUS_X   'micrograph\&.box_radius_x'"

.PP
Definition at line 144 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BOX_RADIUS_Y   'micrograph\&.box_radius_y'"

.PP
Definition at line 145 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_BOX_RADIUS_Z   'micrograph\&.box_radius_z'"

.PP
Definition at line 146 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_ALPHA   'micrograph\&.ctf\&.alpha'"

.PP
Definition at line 132 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_AMP_CONT   'micrograph\&.ctf\&.amp_contrast'"

.PP
Definition at line 134 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_AST_ANG   'micrograph\&.ctf\&.astigmatism_angle'"

.PP
Definition at line 140 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_BASELINE   'micrograph\&.ctf\&.baseline'"

.PP
Definition at line 141 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_CC   'micrograph\&.ctf\&.Cc'"

.PP
Definition at line 131 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_CS   'micrograph\&.ctf\&.Cs'"

.PP
Definition at line 130 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_DE   'micrograph\&.ctf\&.energy_spread'"

.PP
Definition at line 133 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_DEF_AVG   'micrograph\&.ctf\&.defocus_average'"

.PP
Definition at line 136 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_DEF_DEV   'micrograph\&.ctf\&.defocus_deviation'"

.PP
Definition at line 137 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_DEF_MAX   'micrograph\&.ctf\&.defocus_max'"

.PP
Definition at line 139 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_DEF_MIN   'micrograph\&.ctf\&.defocus_min'"

.PP
Definition at line 138 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_ENVELOPE   'micrograph\&.ctf\&.envelope'"

.PP
Definition at line 142 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_CTF_ZERO   'micrograph\&.ctf\&.first_zero'"

.PP
Definition at line 135 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_DOSE   'micrograph\&.electron_dose'"

.PP
Definition at line 89 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_EXPOSURE   'micrograph\&.exposure'"

.PP
Definition at line 90 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FIELD_ID   'micrograph\&.field_id'"

.PP
Definition at line 78 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FILAMENT_FILE   'micrograph_filament\&.file_name'"

.PP
Definition at line 74 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FILAMENT_WIDTH   'micrograph\&.filament_width'"

.PP
Definition at line 161 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FILE   'micrograph\&.file_name'"

.PP
Definition at line 63 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FILNODE_RADIUS   'micrograph\&.filament_node_radius'"

.PP
Definition at line 162 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FOM   'micrograph\&.fom'"

.PP
Definition at line 81 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME   'micrograph_frame\&.number'"

.PP
Definition at line 65 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_FOM   'micrograph_frame\&.fom'"

.PP
Definition at line 72 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_PIXEL_X   'micrograph_frame\&.pixel_size_x'"

.PP
Definition at line 66 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_PIXEL_Y   'micrograph_frame\&.pixel_size_y'"

.PP
Definition at line 67 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_PIXEL_Z   'micrograph_frame\&.pixel_size_z'"

.PP
Definition at line 68 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_SELECT   'micrograph_frame\&.select'"

.PP
Definition at line 71 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_SHIFT_X   'micrograph_frame\&.shift_x'"

.PP
Definition at line 69 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAME_SHIFT_Y   'micrograph_frame\&.shift_y'"

.PP
Definition at line 70 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_FRAMES_FILE   'micrograph_frames\&.file_name'"

.PP
Definition at line 64 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HELIX_ANGLE   'micrograph\&.helix_subunit_angle'"

.PP
Definition at line 127 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HELIX_AXIS   'micrograph\&.helix_axis_angle'"

.PP
Definition at line 125 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HELIX_RADIUS   'micrograph\&.helix_radius'"

.PP
Definition at line 128 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HELIX_RISE   'micrograph\&.helix_subunit_rise'"

.PP
Definition at line 126 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HVEC_X   'micrograph\&.h_x'"

.PP
Definition at line 116 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HVEC_Y   'micrograph\&.h_y'"

.PP
Definition at line 117 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_HVEC_Z   'micrograph\&.h_z'"

.PP
Definition at line 118 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_ID   'micrograph\&.id'"

.PP
Definition at line 77 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_INTENSITY   'micrograph\&.intensity'"

.PP
Definition at line 91 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_KVEC_X   'micrograph\&.k_x'"

.PP
Definition at line 119 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_KVEC_Y   'micrograph\&.k_y'"

.PP
Definition at line 120 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_KVEC_Z   'micrograph\&.k_z'"

.PP
Definition at line 121 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_LEVEL_ANGLE   'micrograph\&.level_angle'"

.PP
Definition at line 101 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_LVEC_X   'micrograph\&.l_x'"

.PP
Definition at line 122 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_LVEC_Y   'micrograph\&.l_y'"

.PP
Definition at line 123 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_LVEC_Z   'micrograph\&.l_z'"

.PP
Definition at line 124 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MAGNIFICATION   'micrograph\&.magnification'"

.PP
Definition at line 82 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_ERROR_X   'micrograph\&.marker_error_x'"

.PP
Definition at line 157 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_ERROR_Y   'micrograph\&.marker_error_y'"

.PP
Definition at line 158 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_ERROR_Z   'micrograph\&.marker_error_z'"

.PP
Definition at line 159 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_FOM   'micrograph\&.marker_fom'"

.PP
Definition at line 160 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_ID   'micrograph\&.marker_id'"

.PP
Definition at line 153 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_RADIUS   'micrograph\&.marker_radius'"

.PP
Definition at line 152 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_X   'micrograph\&.marker_x'"

.PP
Definition at line 154 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_Y   'micrograph\&.marker_y'"

.PP
Definition at line 155 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MARKER_Z   'micrograph\&.marker_z'"

.PP
Definition at line 156 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_1_1   'micrograph\&.matrix_1_1'"

.PP
Definition at line 107 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_1_2   'micrograph\&.matrix_1_2'"

.PP
Definition at line 108 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_1_3   'micrograph\&.matrix_1_3'"

.PP
Definition at line 109 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_2_1   'micrograph\&.matrix_2_1'"

.PP
Definition at line 110 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_2_2   'micrograph\&.matrix_2_2'"

.PP
Definition at line 111 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_2_3   'micrograph\&.matrix_2_3'"

.PP
Definition at line 112 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_3_1   'micrograph\&.matrix_3_1'"

.PP
Definition at line 113 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_3_2   'micrograph\&.matrix_3_2'"

.PP
Definition at line 114 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_MATRIX_3_3   'micrograph\&.matrix_3_3'"

.PP
Definition at line 115 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_NUMBER   'micrograph\&.number'"

.PP
Definition at line 79 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_ORIGIN_X   'micrograph\&.origin_x'"

.PP
Definition at line 93 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_ORIGIN_Y   'micrograph\&.origin_y'"

.PP
Definition at line 94 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_ORIGIN_Z   'micrograph\&.origin_z'"

.PP
Definition at line 95 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_PARTICLE_FILE   'micrograph_particle\&.file_name'"

.PP
Definition at line 73 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_PIXEL   'micrograph\&.pixel_size'"

.PP
Definition at line 84 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_PIXEL_X   'micrograph\&.pixel_size_x'"

.PP
Definition at line 85 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_PIXEL_Y   'micrograph\&.pixel_size_y'"

.PP
Definition at line 86 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_PIXEL_Z   'micrograph\&.pixel_size_z'"

.PP
Definition at line 87 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_POWERSPEC_FILE   'micrograph_powerspectrum\&.file_name'"

.PP
Definition at line 76 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_ROT_ANGLE   'micrograph\&.rotation_angle'"

.PP
Definition at line 102 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_SAMPLING   'micrograph\&.sampling'"

.PP
Definition at line 83 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_SCALE_X   'micrograph\&.scale_x'"

.PP
Definition at line 96 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_SCALE_Y   'micrograph\&.scale_y'"

.PP
Definition at line 97 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_SCALE_Z   'micrograph\&.scale_z'"

.PP
Definition at line 98 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_SELECT   'micrograph\&.select'"

.PP
Definition at line 80 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_TILT_ANGLE   'micrograph\&.tilt_angle'"

.PP
Definition at line 100 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_TILT_AXIS   'micrograph\&.tilt_axis'"

.PP
Definition at line 99 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_TRANSFORM_FILE   'micrograph_fourier_transform\&.file_name'"

.PP
Definition at line 75 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_UNITS   'micrograph\&.units'"

.PP
Definition at line 88 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_VIEW_ANGLE   'micrograph\&.view_angle'"

.PP
Definition at line 106 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_VIEW_X   'micrograph\&.view_x'"

.PP
Definition at line 103 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_VIEW_Y   'micrograph\&.view_y'"

.PP
Definition at line 104 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_VIEW_Z   'micrograph\&.view_z'"

.PP
Definition at line 105 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_VOLTAGE   'micrograph\&.voltage'"

.PP
Definition at line 129 of file mg_tags\&.h\&.
.SS "#define MICROGRAPH_WATER_RING   'micrograph\&.water_ring_index'"

.PP
Definition at line 92 of file mg_tags\&.h\&.
.SS "#define ORIENT_FOM   'orient\&.fom'"

.PP
Definition at line 282 of file mg_tags\&.h\&.
.SS "#define ORIENT_ID   'orient\&.id'"

.PP
Definition at line 274 of file mg_tags\&.h\&.
.SS "#define ORIENT_ORIGIN_X   'orient\&.origin_x'"

.PP
Definition at line 275 of file mg_tags\&.h\&.
.SS "#define ORIENT_ORIGIN_Y   'orient\&.origin_y'"

.PP
Definition at line 276 of file mg_tags\&.h\&.
.SS "#define ORIENT_ORIGIN_Z   'orient\&.origin_z'"

.PP
Definition at line 277 of file mg_tags\&.h\&.
.SS "#define ORIENT_SELECT   'orient\&.select'"

.PP
Definition at line 283 of file mg_tags\&.h\&.
.SS "#define ORIENT_VIEW_ANGLE   'orient\&.view_angle'"

.PP
Definition at line 281 of file mg_tags\&.h\&.
.SS "#define ORIENT_VIEW_X   'orient\&.view_x'"

.PP
Definition at line 278 of file mg_tags\&.h\&.
.SS "#define ORIENT_VIEW_Y   'orient\&.view_y'"

.PP
Definition at line 279 of file mg_tags\&.h\&.
.SS "#define ORIENT_VIEW_Z   'orient\&.view_z'"

.PP
Definition at line 280 of file mg_tags\&.h\&.
.SS "#define PARTICLE   'particle'"

.PP
Definition at line 185 of file mg_tags\&.h\&.
.SS "#define PARTICLE_AST_ANG   'particle\&.astigmatism_angle'"

.PP
Definition at line 218 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BAD   'particle\&.bad'"

.PP
Definition at line 252 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BAD_RADIUS   'particle\&.bad_radius'"

.PP
Definition at line 253 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BAD_X   'particle\&.bad_x'"

.PP
Definition at line 254 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BAD_Y   'particle\&.bad_y'"

.PP
Definition at line 255 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BAD_Z   'particle\&.bad_z'"

.PP
Definition at line 256 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_RADIUS   'particle\&.box_radius'"

.PP
Definition at line 248 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_RADIUS_X   'particle\&.box_radius_x'"

.PP
Definition at line 249 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_RADIUS_Y   'particle\&.box_radius_y'"

.PP
Definition at line 250 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_RADIUS_Z   'particle\&.box_radius_z'"

.PP
Definition at line 251 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_SIZE   'particle\&.box_size'"

.PP
Definition at line 244 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_SIZE_X   'particle\&.box_size_x'"

.PP
Definition at line 245 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_SIZE_Y   'particle\&.box_size_y'"

.PP
Definition at line 246 of file mg_tags\&.h\&.
.SS "#define PARTICLE_BOX_SIZE_Z   'particle\&.box_size_z'"

.PP
Definition at line 247 of file mg_tags\&.h\&.
.SS "#define PARTICLE_CC   'particle\&.cc'"

.PP
Definition at line 236 of file mg_tags\&.h\&.
.SS "#define PARTICLE_CC_AVG   'particle\&.cc_avg'"

.PP
Definition at line 237 of file mg_tags\&.h\&.
.SS "#define PARTICLE_CMP_CC   'particle\&.cmp_cc'"

.PP
Definition at line 240 of file mg_tags\&.h\&.
.SS "#define PARTICLE_COVERAGE   'particle\&.coverage'"

.PP
Definition at line 242 of file mg_tags\&.h\&.
.SS "#define PARTICLE_DEF_DEV   'particle\&.defocus_deviation'"

.PP
Definition at line 217 of file mg_tags\&.h\&.
.SS "#define PARTICLE_DEFOCUS   'particle\&.defocus'"

.PP
Definition at line 216 of file mg_tags\&.h\&.
.SS "#define PARTICLE_DENSITY   'particle\&.density'"

.PP
Definition at line 243 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FILE   'particle\&.file_name'"

.PP
Definition at line 186 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM   'particle\&.fom'"

.PP
Definition at line 220 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM1   'particle\&.fom1'"

.PP
Definition at line 225 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM2   'particle\&.fom2'"

.PP
Definition at line 226 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM3   'particle\&.fom3'"

.PP
Definition at line 227 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM4   'particle\&.fom4'"

.PP
Definition at line 228 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM5   'particle\&.fom5'"

.PP
Definition at line 229 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM6   'particle\&.fom6'"

.PP
Definition at line 230 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM7   'particle\&.fom7'"

.PP
Definition at line 231 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM8   'particle\&.fom8'"

.PP
Definition at line 232 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM9   'particle\&.fom9'"

.PP
Definition at line 233 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM_AVG   'particle\&.fom_average'"

.PP
Definition at line 223 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM_CV   'particle\&.fom_crossvalidation'"

.PP
Definition at line 221 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM_SNR   'particle\&.signal_to_noise'"

.PP
Definition at line 222 of file mg_tags\&.h\&.
.SS "#define PARTICLE_FOM_STD   'particle\&.fom_stdev'"

.PP
Definition at line 224 of file mg_tags\&.h\&.
.SS "#define PARTICLE_GROUP   'particle\&.group_id'"

.PP
Definition at line 189 of file mg_tags\&.h\&.
.SS "#define PARTICLE_HANDA_FOM   'particle\&.handa_fom'"

.PP
Definition at line 234 of file mg_tags\&.h\&.
.SS "#define PARTICLE_HANDB_FOM   'particle\&.handb_fom'"

.PP
Definition at line 235 of file mg_tags\&.h\&.
.SS "#define PARTICLE_ID   'particle\&.id'"

.PP
Definition at line 188 of file mg_tags\&.h\&.
.SS "#define PARTICLE_MAGNIF   'particle\&.magnification'"

.PP
Definition at line 211 of file mg_tags\&.h\&.
.SS "#define PARTICLE_MG_ID   'particle\&.micrograph_id'"

.PP
Definition at line 190 of file mg_tags\&.h\&.
.SS "#define PARTICLE_MG_X   'particle\&.micrograph_x'"

.PP
Definition at line 191 of file mg_tags\&.h\&.
.SS "#define PARTICLE_MG_Y   'particle\&.micrograph_y'"

.PP
Definition at line 192 of file mg_tags\&.h\&.
.SS "#define PARTICLE_MG_Z   'particle\&.micrograph_z'"

.PP
Definition at line 193 of file mg_tags\&.h\&.
.SS "#define PARTICLE_NUMBER   'particle\&.number'"

.PP
Definition at line 187 of file mg_tags\&.h\&.
.SS "#define PARTICLE_OMEGA   'particle\&.omega'"

.PP
Definition at line 206 of file mg_tags\&.h\&.
.SS "#define PARTICLE_ORIGIN_X   'particle\&.origin_x'"

.PP
Definition at line 200 of file mg_tags\&.h\&.
.SS "#define PARTICLE_ORIGIN_Y   'particle\&.origin_y'"

.PP
Definition at line 201 of file mg_tags\&.h\&.
.SS "#define PARTICLE_ORIGIN_Z   'particle\&.origin_z'"

.PP
Definition at line 202 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PFT_CC   'particle\&.pft_cc'"

.PP
Definition at line 238 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PHI   'particle\&.phi'"

.PP
Definition at line 205 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PIXEL   'particle\&.pixel_size'"

.PP
Definition at line 212 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PIXEL_X   'particle\&.pixel_size_x'"

.PP
Definition at line 213 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PIXEL_Y   'particle\&.pixel_size_y'"

.PP
Definition at line 214 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PIXEL_Z   'particle\&.pixel_size_z'"

.PP
Definition at line 215 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PRJ_CC   'particle\&.prj_cc'"

.PP
Definition at line 239 of file mg_tags\&.h\&.
.SS "#define PARTICLE_PSI   'particle\&.psi'"

.PP
Definition at line 203 of file mg_tags\&.h\&.
.SS "#define PARTICLE_RFACTORAB   'particle\&.rfactorab'"

.PP
Definition at line 241 of file mg_tags\&.h\&.
.SS "#define PARTICLE_SELECT   'particle\&.select'"

.PP
Definition at line 219 of file mg_tags\&.h\&.
.SS "#define PARTICLE_THETA   'particle\&.theta'"

.PP
Definition at line 204 of file mg_tags\&.h\&.
.SS "#define PARTICLE_VIEW_ANGLE   'particle\&.view_angle'"

.PP
Definition at line 210 of file mg_tags\&.h\&.
.SS "#define PARTICLE_VIEW_X   'particle\&.view_x'"

.PP
Definition at line 207 of file mg_tags\&.h\&.
.SS "#define PARTICLE_VIEW_Y   'particle\&.view_y'"

.PP
Definition at line 208 of file mg_tags\&.h\&.
.SS "#define PARTICLE_VIEW_Z   'particle\&.view_z'"

.PP
Definition at line 209 of file mg_tags\&.h\&.
.SS "#define PARTICLE_X   'particle\&.x'"

.PP
Definition at line 194 of file mg_tags\&.h\&.
.SS "#define PARTICLE_X_ORIGIN   'particle\&.x_origin'"

.PP
Definition at line 197 of file mg_tags\&.h\&.
.SS "#define PARTICLE_Y   'particle\&.y'"

.PP
Definition at line 195 of file mg_tags\&.h\&.
.SS "#define PARTICLE_Y_ORIGIN   'particle\&.y_origin'"

.PP
Definition at line 198 of file mg_tags\&.h\&.
.SS "#define PARTICLE_Z   'particle\&.z'"

.PP
Definition at line 196 of file mg_tags\&.h\&.
.SS "#define PARTICLE_Z_ORIGIN   'particle\&.z_origin'"

.PP
Definition at line 199 of file mg_tags\&.h\&.
.SS "#define PROJECT   'project'"

.PP
Definition at line 24 of file mg_tags\&.h\&.
.SS "#define REFLEX   'refln'"

.PP
Definition at line 301 of file mg_tags\&.h\&.
.SS "#define REFLEX_AMP   'refln\&.F_meas_au'"

.PP
Definition at line 309 of file mg_tags\&.h\&.
.SS "#define REFLEX_FOM   'refln\&.weight'"

.PP
Definition at line 314 of file mg_tags\&.h\&.
.SS "#define REFLEX_H   'refln\&.index_h'"

.PP
Definition at line 306 of file mg_tags\&.h\&.
.SS "#define REFLEX_K   'refln\&.index_k'"

.PP
Definition at line 307 of file mg_tags\&.h\&.
.SS "#define REFLEX_L   'refln\&.index_l'"

.PP
Definition at line 308 of file mg_tags\&.h\&.
.SS "#define REFLEX_PHI   'refln\&.phase_meas'"

.PP
Definition at line 312 of file mg_tags\&.h\&.
.SS "#define REFLEX_RADIUS   'refln\&.radius'"

.PP
Definition at line 302 of file mg_tags\&.h\&.
.SS "#define REFLEX_SIGAMP   'refln\&.F_meas_sigma_au'"

.PP
Definition at line 311 of file mg_tags\&.h\&.
.SS "#define REFLEX_SIGPHI   'refln\&.phase_sigma'"

.PP
Definition at line 313 of file mg_tags\&.h\&.
.SS "#define REFLEX_STATUS   'refln\&.status'"

.PP
Definition at line 315 of file mg_tags\&.h\&.
.SS "#define REFLEX_X   'refln\&.location_x'"

.PP
Definition at line 303 of file mg_tags\&.h\&.
.SS "#define REFLEX_Y   'refln\&.location_y'"

.PP
Definition at line 304 of file mg_tags\&.h\&.
.SS "#define REFLEX_Z   'refln\&.location_z'"

.PP
Definition at line 305 of file mg_tags\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
