.TH "/Users/bernard/b20/bsoft/include/mol_param.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/mol_param.h \- Header for functions to extract parameters from coordinate files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmolecule\&.h'\fP
.br
\fC#include 'rwmd\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBatomtype\fP * \fBmolgroup_get_atom_types\fP (\fBBmolgroup\fP *molgroup, int elements)"
.br
.RI "Obtains atomic types from molecule groups\&. "
.ti -1c
.RI "\fBBmd\fP * \fBmd_calculate_parameters\fP (\fBBmolgroup\fP *molgroup, int elements, int show_bond, int show_angle)"
.br
.RI "Calculates atomic parameters from molecule groups\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header for functions to extract parameters from coordinate files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20050304 
.PP
Modified: 20090226 
.RE
.PP

.PP
Definition in file \fBmol_param\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmd\fP* md_calculate_parameters (\fBBmolgroup\fP * molgroup, int elements, int show_bond, int show_angle)"

.PP
Calculates atomic parameters from molecule groups\&. 
.PP
\fBParameters\fP
.RS 4
\fI*molgroup\fP molecule group\&. 
.br
\fIelements\fP flag to take atom types from element records\&. 
.br
\fIshow_bond\fP flag to show bonds\&. 
.br
\fIshow_angle\fP flag to show angles\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmd* molecular dynamics object, NULL on failure\&. 
.RE
.PP

.PP
Definition at line 73 of file mol_param\&.cpp\&.
.SS "\fBBatomtype\fP* molgroup_get_atom_types (\fBBmolgroup\fP * molgroup, int elements)"

.PP
Obtains atomic types from molecule groups\&. 
.PP
\fBParameters\fP
.RS 4
\fI*molgroup\fP molecule group\&. 
.br
\fIelements\fP flag to take atom types from element records\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Batomtype* atom property structure, NULL on failure\&. 
.RE
.PP

.PP
Definition at line 26 of file mol_param\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
