.TH "MRChead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MRChead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwMRC\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBnxStart\fP"
.br
.ti -1c
.RI "int \fBnyStart\fP"
.br
.ti -1c
.RI "int \fBnzStart\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmy\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "int \fBmapc\fP"
.br
.ti -1c
.RI "int \fBmapr\fP"
.br
.ti -1c
.RI "int \fBmaps\fP"
.br
.ti -1c
.RI "float \fBamin\fP"
.br
.ti -1c
.RI "float \fBamax\fP"
.br
.ti -1c
.RI "float \fBamean\fP"
.br
.ti -1c
.RI "int \fBispg\fP"
.br
.ti -1c
.RI "int \fBnsymbt\fP"
.br
.ti -1c
.RI "float \fBextra1\fP [2]"
.br
.ti -1c
.RI "char \fBexttype\fP [4]"
.br
.ti -1c
.RI "int \fBnversion\fP"
.br
.ti -1c
.RI "float \fBextra2\fP [10]"
.br
.ti -1c
.RI "int \fBimodStamp\fP"
.br
.ti -1c
.RI "int \fBimodFlags\fP"
.br
.ti -1c
.RI "float \fBextra3\fP [9]"
.br
.ti -1c
.RI "float \fBxOrigin\fP"
.br
.ti -1c
.RI "float \fByOrigin\fP"
.br
.ti -1c
.RI "float \fBzOrigin\fP"
.br
.ti -1c
.RI "char \fBmap\fP [4]"
.br
.ti -1c
.RI "char \fBmachst\fP [4]"
.br
.ti -1c
.RI "float \fBarms\fP"
.br
.ti -1c
.RI "int \fBnlabl\fP"
.br
.ti -1c
.RI "char \fBlabels\fP [800]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file rwMRC\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float MRChead::a"

.PP
Definition at line 94 of file rwMRC\&.h\&.
.SS "float MRChead::alpha"

.PP
Definition at line 97 of file rwMRC\&.h\&.
.SS "float MRChead::amax"

.PP
Definition at line 104 of file rwMRC\&.h\&.
.SS "float MRChead::amean"

.PP
Definition at line 105 of file rwMRC\&.h\&.
.SS "float MRChead::amin"

.PP
Definition at line 103 of file rwMRC\&.h\&.
.SS "float MRChead::arms"

.PP
Definition at line 120 of file rwMRC\&.h\&.
.SS "float MRChead::b"

.PP
Definition at line 95 of file rwMRC\&.h\&.
.SS "float MRChead::beta"

.PP
Definition at line 98 of file rwMRC\&.h\&.
.SS "float MRChead::c"

.PP
Definition at line 96 of file rwMRC\&.h\&.
.SS "float MRChead::extra1[2]"

.PP
Definition at line 108 of file rwMRC\&.h\&.
.SS "float MRChead::extra2[10]"

.PP
Definition at line 111 of file rwMRC\&.h\&.
.SS "float MRChead::extra3[9]"

.PP
Definition at line 114 of file rwMRC\&.h\&.
.SS "char MRChead::exttype[4]"

.PP
Definition at line 109 of file rwMRC\&.h\&.
.SS "float MRChead::gamma"

.PP
Definition at line 99 of file rwMRC\&.h\&.
.SS "int MRChead::imodFlags"

.PP
Definition at line 113 of file rwMRC\&.h\&.
.SS "int MRChead::imodStamp"

.PP
Definition at line 112 of file rwMRC\&.h\&.
.SS "int MRChead::ispg"

.PP
Definition at line 106 of file rwMRC\&.h\&.
.SS "char MRChead::labels[800]"

.PP
Definition at line 122 of file rwMRC\&.h\&.
.SS "char MRChead::machst[4]"

.PP
Definition at line 119 of file rwMRC\&.h\&.
.SS "char MRChead::map[4]"

.PP
Definition at line 118 of file rwMRC\&.h\&.
.SS "int MRChead::mapc"

.PP
Definition at line 100 of file rwMRC\&.h\&.
.SS "int MRChead::mapr"

.PP
Definition at line 101 of file rwMRC\&.h\&.
.SS "int MRChead::maps"

.PP
Definition at line 102 of file rwMRC\&.h\&.
.SS "int MRChead::mode"

.PP
Definition at line 87 of file rwMRC\&.h\&.
.SS "int MRChead::mx"

.PP
Definition at line 91 of file rwMRC\&.h\&.
.SS "int MRChead::my"

.PP
Definition at line 92 of file rwMRC\&.h\&.
.SS "int MRChead::mz"

.PP
Definition at line 93 of file rwMRC\&.h\&.
.SS "int MRChead::nlabl"

.PP
Definition at line 121 of file rwMRC\&.h\&.
.SS "int MRChead::nsymbt"

.PP
Definition at line 107 of file rwMRC\&.h\&.
.SS "int MRChead::nversion"

.PP
Definition at line 110 of file rwMRC\&.h\&.
.SS "int MRChead::nx"

.PP
Definition at line 84 of file rwMRC\&.h\&.
.SS "int MRChead::nxStart"

.PP
Definition at line 88 of file rwMRC\&.h\&.
.SS "int MRChead::ny"

.PP
Definition at line 85 of file rwMRC\&.h\&.
.SS "int MRChead::nyStart"

.PP
Definition at line 89 of file rwMRC\&.h\&.
.SS "int MRChead::nz"

.PP
Definition at line 86 of file rwMRC\&.h\&.
.SS "int MRChead::nzStart"

.PP
Definition at line 90 of file rwMRC\&.h\&.
.SS "float MRChead::xOrigin"

.PP
Definition at line 115 of file rwMRC\&.h\&.
.SS "float MRChead::yOrigin"

.PP
Definition at line 116 of file rwMRC\&.h\&.
.SS "float MRChead::zOrigin"

.PP
Definition at line 117 of file rwMRC\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
