.TH "MRChead2000" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MRChead2000
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwMRC\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBnxStart\fP"
.br
.ti -1c
.RI "int \fBnyStart\fP"
.br
.ti -1c
.RI "int \fBnzStart\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmy\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "int \fBmapc\fP"
.br
.ti -1c
.RI "int \fBmapr\fP"
.br
.ti -1c
.RI "int \fBmaps\fP"
.br
.ti -1c
.RI "float \fBamin\fP"
.br
.ti -1c
.RI "float \fBamax\fP"
.br
.ti -1c
.RI "float \fBamean\fP"
.br
.ti -1c
.RI "int \fBispg\fP"
.br
.ti -1c
.RI "int \fBnsymbt\fP"
.br
.ti -1c
.RI "float \fBextra\fP [25]"
.br
.ti -1c
.RI "float \fBxOrigin\fP"
.br
.ti -1c
.RI "float \fByOrigin\fP"
.br
.ti -1c
.RI "float \fBzOrigin\fP"
.br
.ti -1c
.RI "char \fBmap\fP [4]"
.br
.ti -1c
.RI "char \fBmachst\fP [4]"
.br
.ti -1c
.RI "float \fBarms\fP"
.br
.ti -1c
.RI "int \fBnlabl\fP"
.br
.ti -1c
.RI "char \fBlabels\fP [800]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file rwMRC\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float MRChead2000::a"

.PP
Definition at line 58 of file rwMRC\&.h\&.
.SS "float MRChead2000::alpha"

.PP
Definition at line 61 of file rwMRC\&.h\&.
.SS "float MRChead2000::amax"

.PP
Definition at line 68 of file rwMRC\&.h\&.
.SS "float MRChead2000::amean"

.PP
Definition at line 69 of file rwMRC\&.h\&.
.SS "float MRChead2000::amin"

.PP
Definition at line 67 of file rwMRC\&.h\&.
.SS "float MRChead2000::arms"

.PP
Definition at line 78 of file rwMRC\&.h\&.
.SS "float MRChead2000::b"

.PP
Definition at line 59 of file rwMRC\&.h\&.
.SS "float MRChead2000::beta"

.PP
Definition at line 62 of file rwMRC\&.h\&.
.SS "float MRChead2000::c"

.PP
Definition at line 60 of file rwMRC\&.h\&.
.SS "float MRChead2000::extra[25]"

.PP
Definition at line 72 of file rwMRC\&.h\&.
.SS "float MRChead2000::gamma"

.PP
Definition at line 63 of file rwMRC\&.h\&.
.SS "int MRChead2000::ispg"

.PP
Definition at line 70 of file rwMRC\&.h\&.
.SS "char MRChead2000::labels[800]"

.PP
Definition at line 80 of file rwMRC\&.h\&.
.SS "char MRChead2000::machst[4]"

.PP
Definition at line 77 of file rwMRC\&.h\&.
.SS "char MRChead2000::map[4]"

.PP
Definition at line 76 of file rwMRC\&.h\&.
.SS "int MRChead2000::mapc"

.PP
Definition at line 64 of file rwMRC\&.h\&.
.SS "int MRChead2000::mapr"

.PP
Definition at line 65 of file rwMRC\&.h\&.
.SS "int MRChead2000::maps"

.PP
Definition at line 66 of file rwMRC\&.h\&.
.SS "int MRChead2000::mode"

.PP
Definition at line 51 of file rwMRC\&.h\&.
.SS "int MRChead2000::mx"

.PP
Definition at line 55 of file rwMRC\&.h\&.
.SS "int MRChead2000::my"

.PP
Definition at line 56 of file rwMRC\&.h\&.
.SS "int MRChead2000::mz"

.PP
Definition at line 57 of file rwMRC\&.h\&.
.SS "int MRChead2000::nlabl"

.PP
Definition at line 79 of file rwMRC\&.h\&.
.SS "int MRChead2000::nsymbt"

.PP
Definition at line 71 of file rwMRC\&.h\&.
.SS "int MRChead2000::nx"

.PP
Definition at line 48 of file rwMRC\&.h\&.
.SS "int MRChead2000::nxStart"

.PP
Definition at line 52 of file rwMRC\&.h\&.
.SS "int MRChead2000::ny"

.PP
Definition at line 49 of file rwMRC\&.h\&.
.SS "int MRChead2000::nyStart"

.PP
Definition at line 53 of file rwMRC\&.h\&.
.SS "int MRChead2000::nz"

.PP
Definition at line 50 of file rwMRC\&.h\&.
.SS "int MRChead2000::nzStart"

.PP
Definition at line 54 of file rwMRC\&.h\&.
.SS "float MRChead2000::xOrigin"

.PP
Definition at line 73 of file rwMRC\&.h\&.
.SS "float MRChead2000::yOrigin"

.PP
Definition at line 74 of file rwMRC\&.h\&.
.SS "float MRChead2000::zOrigin"

.PP
Definition at line 75 of file rwMRC\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
