.TH "MRCheadold" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MRCheadold
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwMRC\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBnxStart\fP"
.br
.ti -1c
.RI "int \fBnyStart\fP"
.br
.ti -1c
.RI "int \fBnzStart\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmy\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "int \fBmapc\fP"
.br
.ti -1c
.RI "int \fBmapr\fP"
.br
.ti -1c
.RI "int \fBmaps\fP"
.br
.ti -1c
.RI "float \fBamin\fP"
.br
.ti -1c
.RI "float \fBamax\fP"
.br
.ti -1c
.RI "float \fBamean\fP"
.br
.ti -1c
.RI "int \fBispg\fP"
.br
.ti -1c
.RI "int \fBnsymbt\fP"
.br
.ti -1c
.RI "float \fBextra\fP [29]"
.br
.ti -1c
.RI "float \fBxOrigin\fP"
.br
.ti -1c
.RI "float \fByOrigin\fP"
.br
.ti -1c
.RI "int \fBnlabl\fP"
.br
.ti -1c
.RI "char \fBlabels\fP [10][80]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwMRC\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float MRCheadold::a"

.PP
Definition at line 26 of file rwMRC\&.h\&.
.SS "float MRCheadold::alpha"

.PP
Definition at line 29 of file rwMRC\&.h\&.
.SS "float MRCheadold::amax"

.PP
Definition at line 36 of file rwMRC\&.h\&.
.SS "float MRCheadold::amean"

.PP
Definition at line 37 of file rwMRC\&.h\&.
.SS "float MRCheadold::amin"

.PP
Definition at line 35 of file rwMRC\&.h\&.
.SS "float MRCheadold::b"

.PP
Definition at line 27 of file rwMRC\&.h\&.
.SS "float MRCheadold::beta"

.PP
Definition at line 30 of file rwMRC\&.h\&.
.SS "float MRCheadold::c"

.PP
Definition at line 28 of file rwMRC\&.h\&.
.SS "float MRCheadold::extra[29]"

.PP
Definition at line 40 of file rwMRC\&.h\&.
.SS "float MRCheadold::gamma"

.PP
Definition at line 31 of file rwMRC\&.h\&.
.SS "int MRCheadold::ispg"

.PP
Definition at line 38 of file rwMRC\&.h\&.
.SS "char MRCheadold::labels[10][80]"

.PP
Definition at line 44 of file rwMRC\&.h\&.
.SS "int MRCheadold::mapc"

.PP
Definition at line 32 of file rwMRC\&.h\&.
.SS "int MRCheadold::mapr"

.PP
Definition at line 33 of file rwMRC\&.h\&.
.SS "int MRCheadold::maps"

.PP
Definition at line 34 of file rwMRC\&.h\&.
.SS "int MRCheadold::mode"

.PP
Definition at line 19 of file rwMRC\&.h\&.
.SS "int MRCheadold::mx"

.PP
Definition at line 23 of file rwMRC\&.h\&.
.SS "int MRCheadold::my"

.PP
Definition at line 24 of file rwMRC\&.h\&.
.SS "int MRCheadold::mz"

.PP
Definition at line 25 of file rwMRC\&.h\&.
.SS "int MRCheadold::nlabl"

.PP
Definition at line 43 of file rwMRC\&.h\&.
.SS "int MRCheadold::nsymbt"

.PP
Definition at line 39 of file rwMRC\&.h\&.
.SS "int MRCheadold::nx"

.PP
Definition at line 16 of file rwMRC\&.h\&.
.SS "int MRCheadold::nxStart"

.PP
Definition at line 20 of file rwMRC\&.h\&.
.SS "int MRCheadold::ny"

.PP
Definition at line 17 of file rwMRC\&.h\&.
.SS "int MRCheadold::nyStart"

.PP
Definition at line 21 of file rwMRC\&.h\&.
.SS "int MRCheadold::nz"

.PP
Definition at line 18 of file rwMRC\&.h\&.
.SS "int MRCheadold::nzStart"

.PP
Definition at line 22 of file rwMRC\&.h\&.
.SS "float MRCheadold::xOrigin"

.PP
Definition at line 41 of file rwMRC\&.h\&.
.SS "float MRCheadold::yOrigin"

.PP
Definition at line 42 of file rwMRC\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
