.TH "OBJT" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OBJT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmgIMOD\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [64]"
.br
.ti -1c
.RI "uint \fBextra\fP [16]"
.br
.ti -1c
.RI "int \fBcontsize\fP"
.br
.ti -1c
.RI "uint \fBflags\fP"
.br
.ti -1c
.RI "int \fBaxis\fP"
.br
.ti -1c
.RI "int \fBdrawmode\fP"
.br
.ti -1c
.RI "float \fBred\fP"
.br
.ti -1c
.RI "float \fBgreen\fP"
.br
.ti -1c
.RI "float \fBblue\fP"
.br
.ti -1c
.RI "int \fBpdrawsize\fP"
.br
.ti -1c
.RI "unsigned char \fBsymbol\fP"
.br
.ti -1c
.RI "unsigned char \fBsymsize\fP"
.br
.ti -1c
.RI "unsigned char \fBlinewidth2\fP"
.br
.ti -1c
.RI "unsigned char \fBlinewidth\fP"
.br
.ti -1c
.RI "unsigned char \fBlinesty\fP"
.br
.ti -1c
.RI "unsigned char \fBsymflags\fP"
.br
.ti -1c
.RI "unsigned char \fBsympad\fP"
.br
.ti -1c
.RI "unsigned char \fBtrans\fP"
.br
.ti -1c
.RI "int \fBmeshsize\fP"
.br
.ti -1c
.RI "int \fBsurfsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file rwmgIMOD\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int OBJT::axis"

.PP
Definition at line 102 of file rwmgIMOD\&.h\&.
.SS "float OBJT::blue"

.PP
Definition at line 107 of file rwmgIMOD\&.h\&.
.SS "int OBJT::contsize"

.PP
Definition at line 67 of file rwmgIMOD\&.h\&.
.SS "int OBJT::drawmode"

.PP
Definition at line 103 of file rwmgIMOD\&.h\&.
.SS "uint OBJT::extra[16]"

.PP
Definition at line 64 of file rwmgIMOD\&.h\&.
.SS "uint OBJT::flags"

.PP
Definition at line 68 of file rwmgIMOD\&.h\&.
.SS "float OBJT::green"

.PP
Definition at line 106 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::linesty"

.PP
Definition at line 117 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::linewidth"

.PP
Definition at line 116 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::linewidth2"

.PP
Definition at line 115 of file rwmgIMOD\&.h\&.
.SS "int OBJT::meshsize"

.PP
Definition at line 124 of file rwmgIMOD\&.h\&.
.SS "char OBJT::name[64]"

.PP
Definition at line 63 of file rwmgIMOD\&.h\&.
.SS "int OBJT::pdrawsize"

.PP
Definition at line 109 of file rwmgIMOD\&.h\&.
.SS "float OBJT::red"

.PP
Definition at line 105 of file rwmgIMOD\&.h\&.
.SS "int OBJT::surfsize"

.PP
Definition at line 125 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::symbol"

.PP
Definition at line 111 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::symflags"

.PP
Definition at line 118 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::sympad"

.PP
Definition at line 120 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::symsize"

.PP
Definition at line 114 of file rwmgIMOD\&.h\&.
.SS "unsigned char OBJT::trans"

.PP
Definition at line 121 of file rwmgIMOD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
