.TH "PIFhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIFhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwPIF\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfile_id\fP [8]"
.br
.ti -1c
.RI "char \fBrealscalefactor\fP [16]"
.br
.ti -1c
.RI "int \fBnumimages\fP"
.br
.ti -1c
.RI "int \fBendianness\fP"
.br
.ti -1c
.RI "char \fBgenprogram\fP [32]"
.br
.ti -1c
.RI "int \fBhtype\fP"
.br
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBeven\fP"
.br
.ti -1c
.RI "int \fBmrcX\fP"
.br
.ti -1c
.RI "int \fBmrcY\fP"
.br
.ti -1c
.RI "int \fBmrcZ\fP"
.br
.ti -1c
.RI "char \fBfloatScaleStr\fP [16]"
.br
.ti -1c
.RI "char \fBa0\fP [13]"
.br
.ti -1c
.RI "char \fBa1\fP [13]"
.br
.ti -1c
.RI "char \fBa2\fP [13]"
.br
.ti -1c
.RI "char \fBa3\fP [13]"
.br
.ti -1c
.RI "char \fBa4\fP [13]"
.br
.ti -1c
.RI "char \fBa5\fP [13]"
.br
.ti -1c
.RI "char \fBdummy\fP [62]"
.br
.ti -1c
.RI "char \fBlabel\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwPIF\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char PIFhead::a0[13]"

.PP
Definition at line 32 of file rwPIF\&.h\&.
.SS "char PIFhead::a1[13]"

.PP
Definition at line 33 of file rwPIF\&.h\&.
.SS "char PIFhead::a2[13]"

.PP
Definition at line 34 of file rwPIF\&.h\&.
.SS "char PIFhead::a3[13]"

.PP
Definition at line 35 of file rwPIF\&.h\&.
.SS "char PIFhead::a4[13]"

.PP
Definition at line 36 of file rwPIF\&.h\&.
.SS "char PIFhead::a5[13]"

.PP
Definition at line 37 of file rwPIF\&.h\&.
.SS "char PIFhead::dummy[62]"

.PP
Definition at line 38 of file rwPIF\&.h\&.
.SS "int PIFhead::endianness"

.PP
Definition at line 19 of file rwPIF\&.h\&.
.SS "int PIFhead::even"

.PP
Definition at line 27 of file rwPIF\&.h\&.
.SS "char PIFhead::file_id[8]"

.PP
Definition at line 16 of file rwPIF\&.h\&.
.SS "char PIFhead::floatScaleStr[16]"

.PP
Definition at line 31 of file rwPIF\&.h\&.
.SS "char PIFhead::genprogram[32]"

.PP
Definition at line 20 of file rwPIF\&.h\&.
.SS "int PIFhead::htype"

.PP
Definition at line 21 of file rwPIF\&.h\&.
.SS "char PIFhead::label[256]"

.PP
Definition at line 39 of file rwPIF\&.h\&.
.SS "int PIFhead::mode"

.PP
Definition at line 25 of file rwPIF\&.h\&.
.SS "int PIFhead::mrcX"

.PP
Definition at line 28 of file rwPIF\&.h\&.
.SS "int PIFhead::mrcY"

.PP
Definition at line 29 of file rwPIF\&.h\&.
.SS "int PIFhead::mrcZ"

.PP
Definition at line 30 of file rwPIF\&.h\&.
.SS "int PIFhead::numimages"

.PP
Definition at line 18 of file rwPIF\&.h\&.
.SS "int PIFhead::nx"

.PP
Definition at line 22 of file rwPIF\&.h\&.
.SS "int PIFhead::ny"

.PP
Definition at line 23 of file rwPIF\&.h\&.
.SS "int PIFhead::nz"

.PP
Definition at line 24 of file rwPIF\&.h\&.
.SS "char PIFhead::realscalefactor[16]"

.PP
Definition at line 17 of file rwPIF\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
