.TH "PIFimagehead_new" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIFimagehead_new
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwPIF\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBbkgnd\fP"
.br
.ti -1c
.RI "int \fBpackradius\fP"
.br
.ti -1c
.RI "int \fBnxstart\fP"
.br
.ti -1c
.RI "int \fBnystart\fP"
.br
.ti -1c
.RI "int \fBnzstart\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmy\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "int \fBxlength\fP"
.br
.ti -1c
.RI "int \fBylength\fP"
.br
.ti -1c
.RI "int \fBzlength\fP"
.br
.ti -1c
.RI "int \fBalpha\fP"
.br
.ti -1c
.RI "int \fBbeta\fP"
.br
.ti -1c
.RI "int \fBgamma\fP"
.br
.ti -1c
.RI "int \fBmapc\fP"
.br
.ti -1c
.RI "int \fBmapr\fP"
.br
.ti -1c
.RI "int \fBmaps\fP"
.br
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "int \fBmean\fP"
.br
.ti -1c
.RI "int \fBstddev\fP"
.br
.ti -1c
.RI "int \fBispg\fP"
.br
.ti -1c
.RI "int \fBnsymbt\fP"
.br
.ti -1c
.RI "int \fBxorigin\fP"
.br
.ti -1c
.RI "int \fByorigin\fP"
.br
.ti -1c
.RI "char \fBtitle\fP [80]"
.br
.ti -1c
.RI "char \fBtimestamp\fP [32]"
.br
.ti -1c
.RI "char \fBmicrograph\fP [16]"
.br
.ti -1c
.RI "char \fBscannumber\fP [8]"
.br
.ti -1c
.RI "int \fBaoverb\fP"
.br
.ti -1c
.RI "int \fBmap_abang\fP"
.br
.ti -1c
.RI "int \fBdela\fP"
.br
.ti -1c
.RI "int \fBdelb\fP"
.br
.ti -1c
.RI "int \fBdelc\fP"
.br
.ti -1c
.RI "int \fBt_matrix\fP [6]"
.br
.ti -1c
.RI "int \fBdthe\fP"
.br
.ti -1c
.RI "int \fBdphi_90\fP"
.br
.ti -1c
.RI "int \fBsymmetry\fP"
.br
.ti -1c
.RI "int \fBbinfactor\fP"
.br
.ti -1c
.RI "int \fBa_star\fP"
.br
.ti -1c
.RI "int \fBb_star\fP"
.br
.ti -1c
.RI "int \fBc_star\fP"
.br
.ti -1c
.RI "int \fBalp_star\fP"
.br
.ti -1c
.RI "int \fBbet_star\fP"
.br
.ti -1c
.RI "int \fBgam_star\fP"
.br
.ti -1c
.RI "int \fBpixelSize\fP"
.br
.ti -1c
.RI "int \fBpixSizUnits\fP"
.br
.ti -1c
.RI "int \fBres_out\fP"
.br
.ti -1c
.RI "int \fBctfMode\fP"
.br
.ti -1c
.RI "int \fBtempFactor\fP"
.br
.ti -1c
.RI "int \fBwiener\fP"
.br
.ti -1c
.RI "int \fBborderType\fP"
.br
.ti -1c
.RI "int \fBborderWidth\fP"
.br
.ti -1c
.RI "int \fBdatar4_min\fP"
.br
.ti -1c
.RI "int \fBdatar4_max\fP"
.br
.ti -1c
.RI "int \fBrad_lo\fP"
.br
.ti -1c
.RI "int \fBrad_hi\fP"
.br
.ti -1c
.RI "int \fBtransX\fP"
.br
.ti -1c
.RI "int \fBtransY\fP"
.br
.ti -1c
.RI "int \fBtransZ\fP"
.br
.ti -1c
.RI "int \fBisTrunc\fP"
.br
.ti -1c
.RI "int \fBorigX\fP"
.br
.ti -1c
.RI "int \fBorigY\fP"
.br
.ti -1c
.RI "int \fBorigZ\fP"
.br
.ti -1c
.RI "char \fBextra\fP [72]"
.br
.ti -1c
.RI "int \fBpixelsize_x\fP"
.br
.ti -1c
.RI "int \fBpixelsize_y\fP"
.br
.ti -1c
.RI "int \fBpixelsize_z\fP"
.br
.ti -1c
.RI "int \fBview_x\fP"
.br
.ti -1c
.RI "int \fBview_y\fP"
.br
.ti -1c
.RI "int \fBview_z\fP"
.br
.ti -1c
.RI "int \fBview_angle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file rwPIF\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int PIFimagehead_new::a_star"

.PP
Definition at line 153 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::alp_star"

.PP
Definition at line 156 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::alpha"

.PP
Definition at line 125 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::aoverb"

.PP
Definition at line 143 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::b_star"

.PP
Definition at line 154 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::bet_star"

.PP
Definition at line 157 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::beta"

.PP
Definition at line 126 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::binfactor"

.PP
Definition at line 152 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::bkgnd"

.PP
Definition at line 114 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::borderType"

.PP
Definition at line 165 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::borderWidth"

.PP
Definition at line 166 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::c_star"

.PP
Definition at line 155 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::ctfMode"

.PP
Definition at line 162 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::datar4_max"

.PP
Definition at line 168 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::datar4_min"

.PP
Definition at line 167 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::dela"

.PP
Definition at line 145 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::delb"

.PP
Definition at line 146 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::delc"

.PP
Definition at line 147 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::dphi_90"

.PP
Definition at line 150 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::dthe"

.PP
Definition at line 149 of file rwPIF\&.h\&.
.SS "char PIFimagehead_new::extra[72]"

.PP
Definition at line 178 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::gam_star"

.PP
Definition at line 158 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::gamma"

.PP
Definition at line 127 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::ispg"

.PP
Definition at line 135 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::isTrunc"

.PP
Definition at line 174 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::map_abang"

.PP
Definition at line 144 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::mapc"

.PP
Definition at line 128 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::mapr"

.PP
Definition at line 129 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::maps"

.PP
Definition at line 130 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::max"

.PP
Definition at line 132 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::mean"

.PP
Definition at line 133 of file rwPIF\&.h\&.
.SS "char PIFimagehead_new::micrograph[16]"

.PP
Definition at line 141 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::min"

.PP
Definition at line 131 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::mode"

.PP
Definition at line 113 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::mx"

.PP
Definition at line 119 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::my"

.PP
Definition at line 120 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::mz"

.PP
Definition at line 121 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::nsymbt"

.PP
Definition at line 136 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::nx"

.PP
Definition at line 110 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::nxstart"

.PP
Definition at line 116 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::ny"

.PP
Definition at line 111 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::nystart"

.PP
Definition at line 117 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::nz"

.PP
Definition at line 112 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::nzstart"

.PP
Definition at line 118 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::origX"

.PP
Definition at line 175 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::origY"

.PP
Definition at line 176 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::origZ"

.PP
Definition at line 177 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::packradius"

.PP
Definition at line 115 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::pixelSize"

.PP
Definition at line 159 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::pixelsize_x"

.PP
Definition at line 179 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::pixelsize_y"

.PP
Definition at line 180 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::pixelsize_z"

.PP
Definition at line 181 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::pixSizUnits"

.PP
Definition at line 160 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::rad_hi"

.PP
Definition at line 170 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::rad_lo"

.PP
Definition at line 169 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::res_out"

.PP
Definition at line 161 of file rwPIF\&.h\&.
.SS "char PIFimagehead_new::scannumber[8]"

.PP
Definition at line 142 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::stddev"

.PP
Definition at line 134 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::symmetry"

.PP
Definition at line 151 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::t_matrix[6]"

.PP
Definition at line 148 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::tempFactor"

.PP
Definition at line 163 of file rwPIF\&.h\&.
.SS "char PIFimagehead_new::timestamp[32]"

.PP
Definition at line 140 of file rwPIF\&.h\&.
.SS "char PIFimagehead_new::title[80]"

.PP
Definition at line 139 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::transX"

.PP
Definition at line 171 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::transY"

.PP
Definition at line 172 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::transZ"

.PP
Definition at line 173 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::view_angle"

.PP
Definition at line 185 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::view_x"

.PP
Definition at line 182 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::view_y"

.PP
Definition at line 183 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::view_z"

.PP
Definition at line 184 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::wiener"

.PP
Definition at line 164 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::xlength"

.PP
Definition at line 122 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::xorigin"

.PP
Definition at line 137 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::ylength"

.PP
Definition at line 123 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::yorigin"

.PP
Definition at line 138 of file rwPIF\&.h\&.
.SS "int PIFimagehead_new::zlength"

.PP
Definition at line 124 of file rwPIF\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
