.TH "PIFimagehead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIFimagehead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwPIF\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBbkgnd\fP"
.br
.ti -1c
.RI "int \fBpackradius\fP"
.br
.ti -1c
.RI "int \fBnxstart\fP"
.br
.ti -1c
.RI "int \fBnystart\fP"
.br
.ti -1c
.RI "int \fBnzstart\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmy\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "int \fBxlength\fP"
.br
.ti -1c
.RI "int \fBylength\fP"
.br
.ti -1c
.RI "int \fBzlength\fP"
.br
.ti -1c
.RI "int \fBalpha\fP"
.br
.ti -1c
.RI "int \fBbeta\fP"
.br
.ti -1c
.RI "int \fBgamma\fP"
.br
.ti -1c
.RI "int \fBmapc\fP"
.br
.ti -1c
.RI "int \fBmapr\fP"
.br
.ti -1c
.RI "int \fBmaps\fP"
.br
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "int \fBmean\fP"
.br
.ti -1c
.RI "int \fBstddev\fP"
.br
.ti -1c
.RI "int \fBispg\fP"
.br
.ti -1c
.RI "int \fBnsymbt\fP"
.br
.ti -1c
.RI "int \fBxorigin\fP"
.br
.ti -1c
.RI "int \fByorigin\fP"
.br
.ti -1c
.RI "char \fBtitle\fP [80]"
.br
.ti -1c
.RI "char \fBtimestamp\fP [32]"
.br
.ti -1c
.RI "char \fBmicrograph\fP [16]"
.br
.ti -1c
.RI "char \fBscannumber\fP [8]"
.br
.ti -1c
.RI "int \fBaoverb\fP"
.br
.ti -1c
.RI "int \fBmap_abang\fP"
.br
.ti -1c
.RI "int \fBdela\fP"
.br
.ti -1c
.RI "int \fBdelb\fP"
.br
.ti -1c
.RI "int \fBdelc\fP"
.br
.ti -1c
.RI "int \fBt_matrix\fP [6]"
.br
.ti -1c
.RI "int \fBdthe\fP"
.br
.ti -1c
.RI "int \fBdphi_90\fP"
.br
.ti -1c
.RI "int \fBsymmetry\fP"
.br
.ti -1c
.RI "int \fBbinfactor\fP"
.br
.ti -1c
.RI "int \fBa_star\fP"
.br
.ti -1c
.RI "int \fBb_star\fP"
.br
.ti -1c
.RI "int \fBc_star\fP"
.br
.ti -1c
.RI "int \fBalp_star\fP"
.br
.ti -1c
.RI "int \fBbet_star\fP"
.br
.ti -1c
.RI "int \fBgam_star\fP"
.br
.ti -1c
.RI "int \fBzorigin\fP"
.br
.ti -1c
.RI "int \fBpixelsize_x\fP"
.br
.ti -1c
.RI "int \fBpixelsize_y\fP"
.br
.ti -1c
.RI "int \fBpixelsize_z\fP"
.br
.ti -1c
.RI "int \fBview_x\fP"
.br
.ti -1c
.RI "int \fBview_y\fP"
.br
.ti -1c
.RI "int \fBview_z\fP"
.br
.ti -1c
.RI "int \fBview_angle\fP"
.br
.ti -1c
.RI "char \fBextra\fP [144]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file rwPIF\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int PIFimagehead::a_star"

.PP
Definition at line 92 of file rwPIF\&.h\&.
.SS "int PIFimagehead::alp_star"

.PP
Definition at line 95 of file rwPIF\&.h\&.
.SS "int PIFimagehead::alpha"

.PP
Definition at line 64 of file rwPIF\&.h\&.
.SS "int PIFimagehead::aoverb"

.PP
Definition at line 82 of file rwPIF\&.h\&.
.SS "int PIFimagehead::b_star"

.PP
Definition at line 93 of file rwPIF\&.h\&.
.SS "int PIFimagehead::bet_star"

.PP
Definition at line 96 of file rwPIF\&.h\&.
.SS "int PIFimagehead::beta"

.PP
Definition at line 65 of file rwPIF\&.h\&.
.SS "int PIFimagehead::binfactor"

.PP
Definition at line 91 of file rwPIF\&.h\&.
.SS "int PIFimagehead::bkgnd"

.PP
Definition at line 53 of file rwPIF\&.h\&.
.SS "int PIFimagehead::c_star"

.PP
Definition at line 94 of file rwPIF\&.h\&.
.SS "int PIFimagehead::dela"

.PP
Definition at line 84 of file rwPIF\&.h\&.
.SS "int PIFimagehead::delb"

.PP
Definition at line 85 of file rwPIF\&.h\&.
.SS "int PIFimagehead::delc"

.PP
Definition at line 86 of file rwPIF\&.h\&.
.SS "int PIFimagehead::dphi_90"

.PP
Definition at line 89 of file rwPIF\&.h\&.
.SS "int PIFimagehead::dthe"

.PP
Definition at line 88 of file rwPIF\&.h\&.
.SS "char PIFimagehead::extra[144]"

.PP
Definition at line 106 of file rwPIF\&.h\&.
.SS "int PIFimagehead::gam_star"

.PP
Definition at line 97 of file rwPIF\&.h\&.
.SS "int PIFimagehead::gamma"

.PP
Definition at line 66 of file rwPIF\&.h\&.
.SS "int PIFimagehead::ispg"

.PP
Definition at line 74 of file rwPIF\&.h\&.
.SS "int PIFimagehead::map_abang"

.PP
Definition at line 83 of file rwPIF\&.h\&.
.SS "int PIFimagehead::mapc"

.PP
Definition at line 67 of file rwPIF\&.h\&.
.SS "int PIFimagehead::mapr"

.PP
Definition at line 68 of file rwPIF\&.h\&.
.SS "int PIFimagehead::maps"

.PP
Definition at line 69 of file rwPIF\&.h\&.
.SS "int PIFimagehead::max"

.PP
Definition at line 71 of file rwPIF\&.h\&.
.SS "int PIFimagehead::mean"

.PP
Definition at line 72 of file rwPIF\&.h\&.
.SS "char PIFimagehead::micrograph[16]"

.PP
Definition at line 80 of file rwPIF\&.h\&.
.SS "int PIFimagehead::min"

.PP
Definition at line 70 of file rwPIF\&.h\&.
.SS "int PIFimagehead::mode"

.PP
Definition at line 52 of file rwPIF\&.h\&.
.SS "int PIFimagehead::mx"

.PP
Definition at line 58 of file rwPIF\&.h\&.
.SS "int PIFimagehead::my"

.PP
Definition at line 59 of file rwPIF\&.h\&.
.SS "int PIFimagehead::mz"

.PP
Definition at line 60 of file rwPIF\&.h\&.
.SS "int PIFimagehead::nsymbt"

.PP
Definition at line 75 of file rwPIF\&.h\&.
.SS "int PIFimagehead::nx"

.PP
Definition at line 49 of file rwPIF\&.h\&.
.SS "int PIFimagehead::nxstart"

.PP
Definition at line 55 of file rwPIF\&.h\&.
.SS "int PIFimagehead::ny"

.PP
Definition at line 50 of file rwPIF\&.h\&.
.SS "int PIFimagehead::nystart"

.PP
Definition at line 56 of file rwPIF\&.h\&.
.SS "int PIFimagehead::nz"

.PP
Definition at line 51 of file rwPIF\&.h\&.
.SS "int PIFimagehead::nzstart"

.PP
Definition at line 57 of file rwPIF\&.h\&.
.SS "int PIFimagehead::packradius"

.PP
Definition at line 54 of file rwPIF\&.h\&.
.SS "int PIFimagehead::pixelsize_x"

.PP
Definition at line 99 of file rwPIF\&.h\&.
.SS "int PIFimagehead::pixelsize_y"

.PP
Definition at line 100 of file rwPIF\&.h\&.
.SS "int PIFimagehead::pixelsize_z"

.PP
Definition at line 101 of file rwPIF\&.h\&.
.SS "char PIFimagehead::scannumber[8]"

.PP
Definition at line 81 of file rwPIF\&.h\&.
.SS "int PIFimagehead::stddev"

.PP
Definition at line 73 of file rwPIF\&.h\&.
.SS "int PIFimagehead::symmetry"

.PP
Definition at line 90 of file rwPIF\&.h\&.
.SS "int PIFimagehead::t_matrix[6]"

.PP
Definition at line 87 of file rwPIF\&.h\&.
.SS "char PIFimagehead::timestamp[32]"

.PP
Definition at line 79 of file rwPIF\&.h\&.
.SS "char PIFimagehead::title[80]"

.PP
Definition at line 78 of file rwPIF\&.h\&.
.SS "int PIFimagehead::view_angle"

.PP
Definition at line 105 of file rwPIF\&.h\&.
.SS "int PIFimagehead::view_x"

.PP
Definition at line 102 of file rwPIF\&.h\&.
.SS "int PIFimagehead::view_y"

.PP
Definition at line 103 of file rwPIF\&.h\&.
.SS "int PIFimagehead::view_z"

.PP
Definition at line 104 of file rwPIF\&.h\&.
.SS "int PIFimagehead::xlength"

.PP
Definition at line 61 of file rwPIF\&.h\&.
.SS "int PIFimagehead::xorigin"

.PP
Definition at line 76 of file rwPIF\&.h\&.
.SS "int PIFimagehead::ylength"

.PP
Definition at line 62 of file rwPIF\&.h\&.
.SS "int PIFimagehead::yorigin"

.PP
Definition at line 77 of file rwPIF\&.h\&.
.SS "int PIFimagehead::zlength"

.PP
Definition at line 63 of file rwPIF\&.h\&.
.SS "int PIFimagehead::zorigin"

.PP
Definition at line 98 of file rwPIF\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
