.TH "/Users/bernard/b20/bsoft/include/Quaternion.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/Quaternion.h \- Class for quaternions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'Vector3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuaternion\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBQuaternion\fP &q)"
.br
.ti -1c
.RI "template<typename Type > \fBVector3\fP< Type > \fBvector3_rotate\fP (\fBVector3\fP< Type > &vec, \fBVector3\fP< Type > &axis, double \fBangle\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for quaternions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20051017 
.PP
Modified: 20150115 
.RE
.PP

.PP
Definition in file \fBQuaternion\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & output, \fBQuaternion\fP & q)"

.PP
Definition at line 15 of file Quaternion\&.cpp\&.
.SS "template<typename Type > \fBVector3\fP<Type> vector3_rotate (\fBVector3\fP< Type > & vec, \fBVector3\fP< Type > & axis, double angle)\fC [inline]\fP"

.PP
Definition at line 183 of file Quaternion\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
