.TH "/Users/bernard/b20/bsoft/radon/radon_util.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/radon/radon_util.h
.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrotZ_cart\fP (double x, double y, double z, double ang, double *xx, double *yy, double *zz)"
.br
.RI "Rotates a vector of cartesian coordinates along the Z axis\&. "
.ti -1c
.RI "int \fBrotY_cart\fP (double x, double y, double z, double ang, double *xx, double *yy, double *zz)"
.br
.RI "Rotates a vector of cartesian coordinates along the Y axis\&. "
.ti -1c
.RI "int \fBrotX_cart\fP (double x, double y, double z, double ang, double *xx, double *yy, double *zz)"
.br
.RI "Rotates a vector of cartesian coordinates along the X axis\&. "
.ti -1c
.RI "double \fBang_one_two\fP (double a1, double b1, double a2, double b2)"
.br
.RI "Calculates the angle (in radians) from 2 vectors\&. "
.ti -1c
.RI "int \fBsphere\fP (\fBBimage\fP *p)"
.br
.ti -1c
.RI "int \fBmean_to_0\fP (\fBBimage\fP *p)"
.br
.RI "Set each value equal to old_value-(first image pixel) "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
P\&.L\&. Bellon, F\&. Cantele and S\&. Lanzavecchia Dip\&. Chimica Strutturale e Stereochimica Inorganica Via Venezian 21, 20133 Milano, Italy
.RE
.PP
\fBDate\fP
.RS 4
Created: 7 04 2003 
.PP
Modified: 07 07 2005 
.RE
.PP

.PP
Definition in file \fBradon_util\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "double ang_one_two (double a1, double b1, double a2, double b2)"

.PP
Calculates the angle (in radians) from 2 vectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIa1\fP first coordinate of first vector 
.br
\fIb1\fP second coordinate of first vector 
.br
\fIa2\fP first coordinate of second vector 
.br
\fIb2\fP second coordinate of second vector 
.RE
.PP
\fBReturns\fP
.RS 4
double angle 
.RE
.PP

.PP
Definition at line 89 of file radon_util\&.cpp\&.
.SS "int mean_to_0 (\fBBimage\fP * p)"

.PP
Set each value equal to old_value-(first image pixel) 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP image\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.RE
.PP

.PP
Definition at line 193 of file radon_util\&.cpp\&.
.SS "int rotX_cart (double x, double y, double z, double ang, double * xx, double * yy, double * zz)"

.PP
Rotates a vector of cartesian coordinates along the X axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP x coordinate of starting vector 
.br
\fIy\fP y coordinate of starting vector 
.br
\fIz\fP z coordinate of starting vector 
.br
\fIang\fP rotation angle (in radiants) 
.br
\fI*xx\fP x coordinate of rotated vector 
.br
\fI*yy\fP y coordinate of rotated vector 
.br
\fI*zz\fP z coordinate of rotated vector 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 
.RE
.PP

.PP
Definition at line 71 of file radon_util\&.cpp\&.
.SS "int rotY_cart (double x, double y, double z, double ang, double * xx, double * yy, double * zz)"

.PP
Rotates a vector of cartesian coordinates along the Y axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP x coordinate of starting vector 
.br
\fIy\fP y coordinate of starting vector 
.br
\fIz\fP z coordinate of starting vector 
.br
\fIang\fP rotation angle (in radiants) 
.br
\fI*xx\fP x coordinate of rotated vector 
.br
\fI*yy\fP y coordinate of rotated vector 
.br
\fI*zz\fP z coordinate of rotated vector 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 
.RE
.PP

.PP
Definition at line 50 of file radon_util\&.cpp\&.
.SS "int rotZ_cart (double x, double y, double z, double ang, double * xx, double * yy, double * zz)"

.PP
Rotates a vector of cartesian coordinates along the Z axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP x coordinate of starting vector 
.br
\fIy\fP y coordinate of starting vector 
.br
\fIz\fP z coordinate of starting vector 
.br
\fIang\fP rotation angle (in radiants) 
.br
\fI*xx\fP x coordinate of rotated vector 
.br
\fI*yy\fP y coordinate of rotated vector 
.br
\fI*zz\fP z coordinate of rotated vector 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 
.RE
.PP

.PP
Definition at line 29 of file radon_util\&.cpp\&.
.SS "int sphere (\fBBimage\fP * p)"

.PP
\fBParameters\fP
.RS 4
\fI*p\fP 
.br
 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 
.RE
.PP

.PP
Definition at line 114 of file radon_util\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
