.TH "REG" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REG
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwSUPRIM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBl\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file rwSUPRIM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float REG::f"

.PP
Definition at line 75 of file rwSUPRIM\&.h\&.
.SS "int REG::l"

.PP
Definition at line 74 of file rwSUPRIM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
