.TH "/Users/bernard/b20/bsoft/include/rwClustal.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwClustal.h \- Header file for reading and writing Clustal sequence files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmolecule\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadClustal\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Reads Clustal format sequence files\&. "
.ti -1c
.RI "int \fBwriteClustal\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Writes Clustal format sequence files\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing Clustal sequence files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20030309 
.PP
Modified: 20030309 
.PP
.nf
Format: Protein sequence file format

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwClustal\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readClustal (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Reads Clustal format sequence files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP sequence file name\&. 
.br
\fI*molgroup\fP molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules read (<0 if reading failed)\&. 
.PP
.nf
Clustal format:

NP_039940       -----MHAKMNGWAGVRL--VTHCLNTRSRTYVALNMLAFARTPRGVPSCLFNKVWVSRY
P16720          -----MHAKMNGWAGVRL--VTHCLNTRSRTYVALNMLAFARTPRGVPSCLFNKVWVSRY
DAA00163        -----MHAKMNGWAGVRL--VTHCLNTRSRTYVALNMLAFARTPRGVPSCLFNKVWVSRY

.fi
.PP
 
.RE
.PP

.PP
Definition at line 30 of file rwClustal\&.cpp\&.
.SS "int writeClustal (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Writes Clustal format sequence files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP sequence file name\&. 
.br
\fI*molgroup\fP molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules written (<0 if writing failed)\&. 
.RE
.PP

.PP
Definition at line 86 of file rwClustal\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
