.TH "/Users/bernard/b20/bsoft/src/rwimg/rwDX.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwDX.cpp \- Functions for reading and writing OpenDX files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwDX\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadDX\fP (\fBBimage\fP *p, int readdata)"
.br
.RI "Reading an OpenDX image format\&. "
.ti -1c
.RI "int \fBwriteDX\fP (\fBBimage\fP *p)"
.br
.RI "Writing a DX image format\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing OpenDX files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20150319 
.PP
Modified: 20150319 
.RE
.PP

.PP
Definition in file \fBrwDX\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readDX (\fBBimage\fP * p, int readdata)"

.PP
Reading an OpenDX image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.SH "Comments"
.PP
.RE
.PP
object 1 class gridpositions counts nx ny nz origin xmin ymin zmin delta hx 0\&.0 0\&.0 delta 0\&.0 hy 0\&.0 delta 0\&.0 0\&.0 hz object 2 class gridconnections counts nx ny nz object 3 class array type double rank 0 times n u(0,0,0) u(0,0,1) u(0,0,2) \&.\&.\&. u(0,0,nz-3) u(0,0,nz-2) u(0,0,nz-1) u(0,1,0) u(0,1,1) u(0,1,2) \&.\&.\&. u(0,1,nz-3) u(0,1,nz-2) u(0,1,nz-1) \&.\&.\&. u(0,ny-3,nz-3) u(0,ny-2,nz-2) u(0,ny-1,nz-1) u(1,0,0) u(1,0,1) u(1,0,2) \&.\&.\&. attribute 'dep' string 'positions' object 'regular positions regular connections' class field component 'positions' value 1 component 'connections' value 2 component 'data' value 3 
.PP
Definition at line 44 of file rwDX\&.cpp\&.
.SS "int writeDX (\fBBimage\fP * p)"

.PP
Writing a DX image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 112 of file rwDX\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
