.TH "/Users/bernard/b20/bsoft/include/rwFSC_XML.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwFSC_XML.h \- Library routines to read and write FSC curves\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ps_plot\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBplot\fP * \fBxml_read_fsc\fP (\fBBstring\fP &filename, \fBBstring\fP &xsdfile)"
.br
.RI "Function prototypes\&. "
.ti -1c
.RI "\fBBplot\fP * \fBxml_read_fsc\fP (\fBBstring\fP &filename)"
.br
.RI "Reads an XML file with an FSC curve\&. "
.ti -1c
.RI "void \fBxml_write_fsc\fP (\fBBstring\fP &filename, \fBBplot\fP *plot)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write FSC curves\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20121216 
.PP
Modified: 20140423 
.RE
.PP

.PP
Definition in file \fBrwFSC_XML\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBplot\fP* xml_read_fsc (\fBBstring\fP & filename)"

.PP
Reads an XML file with an FSC curve\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP input file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bplot* new plot\&. 
.PP
.nf
A new plot with two columns is generated.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 167 of file rwFSC_XML\&.cpp\&.
.SS "\fBBplot\fP* xml_read_fsc (\fBBstring\fP & filename, \fBBstring\fP & xsdfile)"

.PP
Function prototypes\&. 
.SS "void xml_write_fsc (\fBBstring\fP & filename, \fBBplot\fP * plot)"

.PP
Definition at line 218 of file rwFSC_XML\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
