.TH "/Users/bernard/b20/bsoft/src/rwparam/rwFSC_XML.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwparam/rwFSC_XML.cpp \- Library routines to read and write FSC curves\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ps_plot\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSCX\fP   'Resolution (A\-1)'"
.br
.ti -1c
.RI "#define \fBFSCY\fP   'Correlation Coefficient'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBplot\fP * \fBxml_read_fsc\fP (\fBBstring\fP &filename)"
.br
.RI "Reads an XML file with an FSC curve\&. "
.ti -1c
.RI "void \fBxml_write_fsc\fP (\fBBstring\fP &filename, \fBBplot\fP *plot)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write FSC curves\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20121216 
.PP
Modified: 20140423 
.RE
.PP

.PP
Definition in file \fBrwFSC_XML\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define FSCX   'Resolution (A\-1)'"

.PP
Definition at line 16 of file rwFSC_XML\&.cpp\&.
.SS "#define FSCY   'Correlation Coefficient'"

.PP
Definition at line 17 of file rwFSC_XML\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBBplot\fP* xml_read_fsc (\fBBstring\fP & filename)"

.PP
Reads an XML file with an FSC curve\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP input file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bplot* new plot\&. 
.PP
.nf
A new plot with two columns is generated.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 167 of file rwFSC_XML\&.cpp\&.
.SS "void xml_write_fsc (\fBBstring\fP & filename, \fBBplot\fP * plot)"

.PP
Definition at line 218 of file rwFSC_XML\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
