.TH "/Users/bernard/b20/bsoft/include/rwmatrix.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmatrix.h \- Header file for reading (and writing) matrices\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bmatrix\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Bmatrix \fBread_matrix\fP (\fBBstring\fP &filename)"
.br
.ti -1c
.RI "int \fBwrite_matrix\fP (\fBBstring\fP &filename, Bmatrix matrix)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading (and writing) matrices\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010723 
.PP
Modified: 20120211 
.RE
.PP

.PP
Definition in file \fBrwmatrix\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "Bmatrix read_matrix (\fBBstring\fP & filename)"

.SS "int write_matrix (\fBBstring\fP & filename, Bmatrix matrix)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
