.TH "/Users/bernard/b20/bsoft/include/rwMFF.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwMFF.h \- Header file for reading and writing the What If MFF files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMFFhead\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMFFSIZE\fP   268"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadMFF\fP (\fBBimage\fP *p, int readdata)"
.br
.RI "Reading a MFF image format\&. "
.ti -1c
.RI "int \fBwriteMFF\fP (\fBBimage\fP *p)"
.br
.RI "Writeing a MFF image format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing the What If MFF files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990424 
.PP
Modified: 20111217 
.PP
.nf
Format: 3D crystallographic image file format for the program WHAT IF

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwMFF\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MFFSIZE   268"

.PP
Definition at line 13 of file rwMFF\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int readMFF (\fBBimage\fP * p, int readdata)"

.PP
Reading a MFF image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. A 3D file format developed with the What If molecular dynamics package\&. Header size: 268 bytes (fixed)\&. File format extensions: \&.mff\&. Byte order determination: The third dimension must be less than 256*256\&. Data type: float\&. Special features: The MFF files are written with double integers separating different records by What If\&. 
.br
 This was solved by adding 'padding' fields in the header and adding 8 bytes to every page (= section) offset\&. The data is stored as 2D pages separated by 8 bytes\&. 
.RE
.PP

.PP
Definition at line 32 of file rwMFF\&.cpp\&.
.SS "int writeMFF (\fBBimage\fP * p)"

.PP
Writeing a MFF image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. A 3D file format developed with the What If molecular dynamics package\&. 
.RE
.PP

.PP
Definition at line 104 of file rwMFF\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
