.TH "/Users/bernard/b20/bsoft/include/rwmgEMX.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmgEMX.h \- Reads and writes micrograph exchange files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBread_project_emx\fP (\fBBstring\fP &filename, \fBBproject\fP *\fBproject\fP, \fBBstring\fP &xsdfile)"
.br
.RI "Reading micrograph parameters from XML files\&. "
.ti -1c
.RI "int \fBread_project_emx\fP (\fBBstring\fP *\fBfile_list\fP, \fBBproject\fP *\fBproject\fP, \fBBstring\fP &xsdfile)"
.br
.ti -1c
.RI "int \fBwrite_project_emx\fP (\fBBstring\fP &filename, \fBBproject\fP *\fBproject\fP, int mg_select, int rec_select)"
.br
.RI "Writing micrograph parameters to an EMX file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Reads and writes micrograph exchange files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20130201
.PP

.br
 
.PP
Modified: 20130430 
.RE
.PP

.PP
Definition in file \fBrwmgEMX\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int read_project_emx (\fBBstring\fP & filename, \fBBproject\fP * project, \fBBstring\fP & xsdfile)"

.PP
Reading micrograph parameters from XML files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI*project\fP initialized project structure\&. 
.br
\fI&xsdfile\fP XML schema to validate against (can be empty)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 241 of file rwmgEMX\&.cpp\&.
.SS "int read_project_emx (\fBBstring\fP * file_list, \fBBproject\fP * project, \fBBstring\fP & xsdfile)"

.SS "int write_project_emx (\fBBstring\fP & filename, \fBBproject\fP * project, int mg_select, int rec_select)"

.PP
Writing micrograph parameters to an EMX file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI*project\fP project structure\&. 
.br
\fImg_select\fP flag to only write selected micrographs\&. 
.br
\fIrec_select\fP flag to only convert selected reconstructions\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 317 of file rwmgEMX\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
