.TH "/Users/bernard/b20/bsoft/include/rwmgXML.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmgXML.h \- Reads and writes micrograph XML files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBread_project_xml\fP (\fBBstring\fP &filename, \fBBproject\fP *\fBproject\fP)"
.br
.RI "Reading micrograph parameters from XML files\&. "
.ti -1c
.RI "int \fBread_project_xml\fP (\fBBstring\fP *\fBfile_list\fP, \fBBproject\fP *\fBproject\fP)"
.br
.ti -1c
.RI "\fBBparticle\fP * \fBread_particle_xml\fP (\fBBstring\fP &filename, \fBBparticle\fP **partlist, \fBFOMType\fP fom_tag[\fBNFOM\fP])"
.br
.ti -1c
.RI "int \fBwrite_project_xml\fP (\fBBstring\fP &filename, \fBBproject\fP *\fBproject\fP, int mg_select, int rec_select)"
.br
.RI "Writing micrograph parameters to a XML file\&. "
.ti -1c
.RI "int \fBwrite_particle_xml\fP (\fBBstring\fP &filename, \fBBparticle\fP *part, int euler_flag, int omega_flag, \fBFOMType\fP fom_tag[\fBNFOM\fP])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads and writes micrograph XML files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20050920 
.PP
Modified: 20130827 
.RE
.PP

.PP
Definition in file \fBrwmgXML\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBparticle\fP* read_particle_xml (\fBBstring\fP & filename, \fBBparticle\fP ** partlist, \fBFOMType\fP fom_tag[NFOM])"

.SS "int read_project_xml (\fBBstring\fP & filename, \fBBproject\fP * project)"

.PP
Reading micrograph parameters from XML files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI*project\fP initialized project structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 144 of file rwmgXML\&.cpp\&.
.SS "int read_project_xml (\fBBstring\fP * file_list, \fBBproject\fP * project)"

.SS "int write_particle_xml (\fBBstring\fP & filename, \fBBparticle\fP * part, int euler_flag, int omega_flag, \fBFOMType\fP fom_tag[NFOM])"

.SS "int write_project_xml (\fBBstring\fP & filename, \fBBproject\fP * project, int mg_select, int rec_select)"

.PP
Writing micrograph parameters to a XML file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI*project\fP project structure\&. 
.br
\fImg_select\fP flag to only write selected micrographs\&. 
.br
\fIrec_select\fP flag to only convert selected reconstructions\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 258 of file rwmgXML\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
