.TH "/Users/bernard/b20/bsoft/include/rwmodel_xml.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmodel_xml.h \- Read and write models in XML format\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBmodel\fP * \fBread_model_xml\fP (\fBBstring\fP *\fBfile_list\fP)"
.br
.RI "Reads XML model parameters\&. "
.ti -1c
.RI "int \fBwrite_model_xml\fP (\fBBstring\fP &filename, \fBBmodel\fP *\fBmodel\fP)"
.br
.RI "Writes XML model parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
Read and write models in XML format\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20081029 
.PP
Modified: 20081029 
.RE
.PP

.PP
Definition in file \fBrwmodel_xml\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmodel\fP* read_model_xml (\fBBstring\fP * file_list)"

.PP
Reads XML model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI*file_list\fP list of model parameter file names\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* model parameters\&. 
.RE
.PP

.PP
Definition at line 192 of file rwmodel_xml\&.cpp\&.
.SS "int write_model_xml (\fBBstring\fP & filename, \fBBmodel\fP * model)"

.PP
Writes XML model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP model parameter file name\&. 
.br
\fI*model\fP model parameters\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0, <0 on error\&. 
.RE
.PP

.PP
Definition at line 306 of file rwmodel_xml\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
