.TH "/Users/bernard/b20/bsoft/src/rwmodel/rwmodel_cmm.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwmodel/rwmodel_cmm.cpp \- Library routines to read and write Chimera marker model parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTagValue\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTagValue\fP * \fBtag_value_parse\fP (char *string)"
.br
.ti -1c
.RI "int \fBtag_value_kill\fP (\fBTagValue\fP *tv)"
.br
.ti -1c
.RI "\fBBmodel\fP * \fBread_model_chimera\fP (\fBBstring\fP *\fBfile_list\fP)"
.br
.RI "Reads Chimera marker model parameters\&. "
.ti -1c
.RI "int \fBwrite_model_chimera\fP (\fBBstring\fP &filename, \fBBmodel\fP *\fBmodel\fP)"
.br
.RI "Writes Chimera marker model parameters\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write Chimera marker model parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20060919 
.PP
Modified: 20161004 
.RE
.PP

.PP
Definition in file \fBrwmodel_cmm\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmodel\fP* read_model_chimera (\fBBstring\fP * file_list)"

.PP
Reads Chimera marker model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI*file_list\fP list of model parameter file names\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* model parameters\&. 
.RE
.PP

.PP
Definition at line 72 of file rwmodel_cmm\&.cpp\&.
.SS "int tag_value_kill (\fBTagValue\fP * tv)"

.PP
Definition at line 52 of file rwmodel_cmm\&.cpp\&.
.SS "\fBTagValue\fP* tag_value_parse (char * string)"

.PP
Definition at line 24 of file rwmodel_cmm\&.cpp\&.
.SS "int write_model_chimera (\fBBstring\fP & filename, \fBBmodel\fP * model)"

.PP
Writes Chimera marker model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP model parameter file name\&. 
.br
\fI*model\fP model parameters\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int models written\&. 
.RE
.PP

.PP
Definition at line 202 of file rwmodel_cmm\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
