.TH "/Users/bernard/b20/bsoft/include/rwmodel_param.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmodel_param.h \- Header to read and write model dynamics parameters in STAR format\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBmodparam\fP"
.br
.ti -1c
.RI "class \fBBmaterial\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDISTMAT_COMPTYPE1\fP   'distance_matrix\&.component_type1'"
.br
.ti -1c
.RI "#define \fBDISTMAT_COMPTYPE2\fP   'distance_matrix\&.component_type2'"
.br
.ti -1c
.RI "#define \fBDISTMAT_LLEN\fP   'distance_matrix\&.link_length'"
.br
.ti -1c
.RI "#define \fBDISTMAT_DIST\fP   'distance_matrix\&.distance'"
.br
.ti -1c
.RI "#define \fBDISTMAT_KL\fP   'distance_matrix\&.link_constant'"
.br
.ti -1c
.RI "#define \fBDISTMAT_KD\fP   'distance_matrix\&.distance_constant'"
.br
.ti -1c
.RI "#define \fBDISTMAT_POTTYPE\fP   'distance_matrix\&.potential_type'"
.br
.ti -1c
.RI "#define \fBANGLEMAT_COMPTYPE1\fP   'angle_matrix\&.component_type1'"
.br
.ti -1c
.RI "#define \fBANGLEMAT_COMPTYPE2\fP   'angle_matrix\&.component_type2'"
.br
.ti -1c
.RI "#define \fBANGLEMAT_COMPTYPE3\fP   'angle_matrix\&.component_type3'"
.br
.ti -1c
.RI "#define \fBANGLEMAT_ANGLE\fP   'angle_matrix\&.angle'"
.br
.ti -1c
.RI "#define \fBANGLEMAT_KA\fP   'angle_matrix\&.angle_constant'"
.br
.ti -1c
.RI "#define \fB_Bmaterial_\fP"
.br
.ti -1c
.RI "#define \fBMATERIAL_NAME\fP   'material\&.name'"
.br
.ti -1c
.RI "#define \fBMATERIAL_DENSITY\fP   'material\&.density'"
.br
.ti -1c
.RI "#define \fBMATERIAL_DENS_UNIT\fP   'material\&.density_unit'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBmodparam\fP \fBmodel_param_generate\fP (\fBBmodel\fP *\fBmodel\fP)"
.br
.RI "Generates a model parameter file from a model\&. "
.ti -1c
.RI "int \fBmodel_param_generate\fP (\fBBmodparam\fP &md, \fBBmodel\fP *\fBmodel\fP)"
.br
.ti -1c
.RI "int \fBmodel_param_set_type_indices\fP (\fBBmodel\fP *\fBmodel\fP, \fBBmodparam\fP &mp)"
.br
.RI "Sets the component type indices from the model parameters\&. "
.ti -1c
.RI "map< string, \fBBcomptype\fP > \fBread_atom_properties\fP (\fBBstring\fP &filename)"
.br
.ti -1c
.RI "map< string, \fBBmaterial\fP > \fBread_material_properties\fP (\fBBstring\fP &filename)"
.br
.ti -1c
.RI "int \fBwrite_material_properties\fP (\fBBstring\fP &filename, map< string, \fBBmaterial\fP > material)"
.br
.ti -1c
.RI "\fBBmodparam\fP \fBread_dynamics_parameters\fP (\fBBstring\fP &filename)"
.br
.RI "Reads a model parameter file\&. "
.ti -1c
.RI "int \fBupdate_dynamics_parameters\fP (\fBBmodparam\fP &md, \fBBstring\fP &filename)"
.br
.RI "Updates model parameters from a parameter file\&. "
.ti -1c
.RI "int \fBwrite_dynamics_parameters\fP (\fBBstring\fP &filename, \fBBmodparam\fP &md)"
.br
.RI "Writes a model parameter file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header to read and write model dynamics parameters in STAR format\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20100305 
.PP
Modified: 20210224 
.RE
.PP

.PP
Definition in file \fBrwmodel_param\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _Bmaterial_"

.PP
Definition at line 109 of file rwmodel_param\&.h\&.
.SS "#define ANGLEMAT_ANGLE   'angle_matrix\&.angle'"

.PP
Definition at line 24 of file rwmodel_param\&.h\&.
.SS "#define ANGLEMAT_COMPTYPE1   'angle_matrix\&.component_type1'"

.PP
Definition at line 21 of file rwmodel_param\&.h\&.
.SS "#define ANGLEMAT_COMPTYPE2   'angle_matrix\&.component_type2'"

.PP
Definition at line 22 of file rwmodel_param\&.h\&.
.SS "#define ANGLEMAT_COMPTYPE3   'angle_matrix\&.component_type3'"

.PP
Definition at line 23 of file rwmodel_param\&.h\&.
.SS "#define ANGLEMAT_KA   'angle_matrix\&.angle_constant'"

.PP
Definition at line 25 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_COMPTYPE1   'distance_matrix\&.component_type1'"

.PP
Definition at line 13 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_COMPTYPE2   'distance_matrix\&.component_type2'"

.PP
Definition at line 14 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_DIST   'distance_matrix\&.distance'"

.PP
Definition at line 16 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_KD   'distance_matrix\&.distance_constant'"

.PP
Definition at line 18 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_KL   'distance_matrix\&.link_constant'"

.PP
Definition at line 17 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_LLEN   'distance_matrix\&.link_length'"

.PP
Definition at line 15 of file rwmodel_param\&.h\&.
.SS "#define DISTMAT_POTTYPE   'distance_matrix\&.potential_type'"

.PP
Definition at line 19 of file rwmodel_param\&.h\&.
.SS "#define MATERIAL_DENS_UNIT   'material\&.density_unit'"

.PP
Definition at line 112 of file rwmodel_param\&.h\&.
.SS "#define MATERIAL_DENSITY   'material\&.density'"

.PP
Definition at line 111 of file rwmodel_param\&.h\&.
.SS "#define MATERIAL_NAME   'material\&.name'"

.PP
Definition at line 110 of file rwmodel_param\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmodparam\fP model_param_generate (\fBBmodel\fP * model)"

.PP
Generates a model parameter file from a model\&. 
.PP
\fBParameters\fP
.RS 4
\fI*model\fP linked list of models\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodparam* new model parameter structure\&. 
.PP
.nf
All the types in a list of models are collated into a string list of
types for a new model parameter structure.
The distances between component types in the matrix is set to the
smallest such distance between components of the relevant types.
The distance constant is set to 1.
The distance potential type is set to 2 (soft sphere).

.fi
.PP
 
.RE
.PP

.PP
Definition at line 37 of file rwmodel_param\&.cpp\&.
.SS "int model_param_generate (\fBBmodparam\fP & md, \fBBmodel\fP * model)"

.PP
Definition at line 44 of file rwmodel_param\&.cpp\&.
.SS "int model_param_set_type_indices (\fBBmodel\fP * model, \fBBmodparam\fP & md)"

.PP
Sets the component type indices from the model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI*model\fP linked list of models\&. 
.br
\fI&md\fP model parameter structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.PP
.nf
The position of a type in the distance matrix type list determines
the type index within the distance matrix itself.
The indices of the component types within each model is then set
to the corresponding index for the distance matrix.
If the type is not represented in the distance matrix, its index
is set to -1.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 202 of file rwmodel_param\&.cpp\&.
.SS "map<string,\fBBcomptype\fP> read_atom_properties (\fBBstring\fP & filename)"

.PP
Definition at line 305 of file rwmodel_param\&.cpp\&.
.SS "\fBBmodparam\fP read_dynamics_parameters (\fBBstring\fP & filename)"

.PP
Reads a model parameter file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBBmodparam\fP new model parameter structure\&. 
.PP
.nf
The only format supported is a STAR format.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 540 of file rwmodel_param\&.cpp\&.
.SS "map<string,\fBBmaterial\fP> read_material_properties (\fBBstring\fP & filename)"

.PP
Definition at line 439 of file rwmodel_param\&.cpp\&.
.SS "int update_dynamics_parameters (\fBBmodparam\fP & md, \fBBstring\fP & filename)"

.PP
Updates model parameters from a parameter file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&md\fP model parameters\&. 
.br
\fI&filename\fP file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.PP
.nf
The only format supported is a STAR format.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 556 of file rwmodel_param\&.cpp\&.
.SS "int write_dynamics_parameters (\fBBstring\fP & filename, \fBBmodparam\fP & md)"

.PP
Writes a model parameter file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI&md\fP model parameter structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&.
.RE
.PP
The only format supported is a STAR format\&. 
.PP
Definition at line 726 of file rwmodel_param\&.cpp\&.
.SS "int write_material_properties (\fBBstring\fP & filename, map< string, \fBBmaterial\fP > material)"

.PP
Definition at line 514 of file rwmodel_param\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
