.TH "/Users/bernard/b20/bsoft/src/rwmodel/rwmodel_vega.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwmodel/rwmodel_vega.cpp \- Library routines to read and write Vega model parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBmodel\fP * \fBread_model_vega\fP (\fBBstring\fP *\fBfile_list\fP)"
.br
.RI "Reads Vega model parameters\&. "
.ti -1c
.RI "int \fBwrite_model_vega\fP (\fBBstring\fP &filename, \fBBmodel\fP *\fBmodel\fP)"
.br
.RI "Writes Vega model parameters\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write Vega model parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20060919 
.PP
Modified: 20120211 
.RE
.PP

.PP
Definition in file \fBrwmodel_vega\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmodel\fP* read_model_vega (\fBBstring\fP * file_list)"

.PP
Reads Vega model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI*file_list\fP list of model parameter file names\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* model parameters\&. 
.RE
.PP

.PP
Definition at line 21 of file rwmodel_vega\&.cpp\&.
.SS "int write_model_vega (\fBBstring\fP & filename, \fBBmodel\fP * model)"

.PP
Writes Vega model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP model parameter file name\&. 
.br
\fI*model\fP model parameters\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int models written\&. 
.RE
.PP

.PP
Definition at line 102 of file rwmodel_vega\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
