.TH "/Users/bernard/b20/bsoft/include/rwND2.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwND2.h \- Header file for reading Nikon ND2 files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadND2\fP (\fBBimage\fP *p, int readdata, int img_select)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading Nikon ND2 files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20210628 
.PP
Modified: 20210628 
.PP
.nf
Format: Light microscopy image format for Nikon microscopes

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwND2\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readND2 (\fBBimage\fP * p, int readdata, int img_select)"

.PP
Definition at line 180 of file rwND2\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
