.TH "/Users/bernard/b20/bsoft/src/rwimg/rwND2.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwND2.cpp \- Functions for reading Nikon ND2 files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwND2\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChunkHeader\fP"
.br
.ti -1c
.RI "class \fBChunkEntry\fP"
.br
.ti -1c
.RI "class \fBImageAttribute\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsignature\fP (180276954)"
.br
.ti -1c
.RI "string \fBmastertag\fP ('ND2 CHUNK \fBMAP\fP SIGNATURE 0000001!')"
.br
.ti -1c
.RI "string \fBread_tag\fP (ifstream &fimg)"
.br
.ti -1c
.RI "string \fBread_param\fP (ifstream &fimg)"
.br
.ti -1c
.RI "\fBChunkHeader\fP \fBread_chunk_header\fP (ifstream &fimg)"
.br
.ti -1c
.RI "\fBChunkEntry\fP \fBread_chunk_entry\fP (ifstream &fimg)"
.br
.ti -1c
.RI "\fBImageAttribute\fP \fBread_attribute\fP (ifstream &fimg)"
.br
.ti -1c
.RI "int \fBreadND2\fP (\fBBimage\fP *p, int readdata, int img_select)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading Nikon ND2 files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20210627 
.PP
Modified: 20210628 
.RE
.PP

.PP
Definition in file \fBrwND2\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "string mastertag ('ND2 CHUNK \fBMAP\fP SIGNATURE 0000001!')"

.SS "\fBImageAttribute\fP read_attribute (ifstream & fimg)"

.PP
Definition at line 117 of file rwND2\&.cpp\&.
.SS "\fBChunkEntry\fP read_chunk_entry (ifstream & fimg)"

.PP
Definition at line 105 of file rwND2\&.cpp\&.
.SS "\fBChunkHeader\fP read_chunk_header (ifstream & fimg)"

.PP
Definition at line 82 of file rwND2\&.cpp\&.
.SS "string read_param (ifstream & fimg)"

.PP
Definition at line 61 of file rwND2\&.cpp\&.
.SS "string read_tag (ifstream & fimg)"

.PP
Definition at line 48 of file rwND2\&.cpp\&.
.SS "int readND2 (\fBBimage\fP * p, int readdata, int img_select)"

.PP
Definition at line 180 of file rwND2\&.cpp\&.
.SS "int signature (180276954)"

.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
