.TH "/Users/bernard/b20/bsoft/include/rwPNM.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwPNM.h \- Header file for reading and writing PNM files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadPNM\fP (\fBBimage\fP *p, int readdata, int img_select)"
.br
.RI "Reading a PNM type file\&. A simple image format\&. PBM bit image format\&. PGM grayscale image format\&. PPM \fBRGB\fP color image format\&. File format extensions: \&.pbm, \&.pgm, \&.ppm The header contains ascii text indicating the image and element sizes\&. Data types: byte, unsigned short\&. "
.ti -1c
.RI "int \fBwritePNM\fP (\fBBimage\fP *p)"
.br
.RI "Writing a PNM type file\&. A simple image format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing PNM files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20110317 
.PP
Modified: 20111217 
.PP
.nf
Format: 2D simple image file format

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwPNM\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readPNM (\fBBimage\fP * p, int readdata, int img_select)"

.PP
Reading a PNM type file\&. A simple image format\&. PBM bit image format\&. PGM grayscale image format\&. PPM \fBRGB\fP color image format\&. File format extensions: \&.pbm, \&.pgm, \&.ppm The header contains ascii text indicating the image and element sizes\&. Data types: byte, unsigned short\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.br
\fIimg_select\fP image selection in multi-image file (-1 = all images)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0, <0 on error\&. 
.RE
.PP

.PP
Definition at line 79 of file rwPNM\&.cpp\&.
.SS "int writePNM (\fBBimage\fP * p)"

.PP
Writing a PNM type file\&. A simple image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0, <0 on error\&. 
.RE
.PP

.PP
Definition at line 182 of file rwPNM\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
