.TH "/Users/bernard/b20/bsoft/src/rwimg/rwTGA.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwTGA.cpp \- Functions for reading and writing Truevision TGA files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwTGA\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGB\fP< unsigned char > \fBTGA_to_RGB\fP (const unsigned char *pColorData, unsigned int bitsPerColor)"
.br
.ti -1c
.RI "\fBRGBA\fP< unsigned char > \fBTGA_to_RGBA\fP (const unsigned char *pColorData, unsigned int bitsPerColor)"
.br
.ti -1c
.RI "int \fBreadTGA\fP (\fBBimage\fP *p, int readdata)"
.br
.RI "Reading a Truevision TGA image file format\&. "
.ti -1c
.RI "int \fBwriteTGA\fP (\fBBimage\fP *p)"
.br
.RI "Writing a Truevision TGA map image file format\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing Truevision TGA files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20150811 
.PP
Modified: 20150815 
.RE
.PP

.PP
Definition in file \fBrwTGA\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readTGA (\fBBimage\fP * p, int readdata)"

.PP
Reading a Truevision TGA image file format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. A color image format\&. Header size: 18 bytes (fixed)\&. File format extensions: \&.tga The identifier is ???\&. Byte order: Little endian\&. Data types: 1 = byte, 2 = float, 3 = complex float 4 = 3-value vector, 5 = view 
.RE
.PP

.PP
Definition at line 134 of file rwTGA\&.cpp\&.
.SS "\fBRGB\fP<unsigned char> TGA_to_RGB (const unsigned char * pColorData, unsigned int bitsPerColor)"

.PP
Definition at line 18 of file rwTGA\&.cpp\&.
.SS "\fBRGBA\fP<unsigned char> TGA_to_RGBA (const unsigned char * pColorData, unsigned int bitsPerColor)"

.PP
Definition at line 54 of file rwTGA\&.cpp\&.
.SS "int writeTGA (\fBBimage\fP * p)"

.PP
Writing a Truevision TGA map image file format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 266 of file rwTGA\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
