.TH "/Users/bernard/b20/bsoft/include/rwXPLOR.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwXPLOR.h \- Header file for reading and writing XPLOR reflection files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadXPLOR\fP (\fBBimage\fP *p, int readdata)"
.br
.RI "Reading a XPLOR map or structure factor file format\&. A minimal implementation\&. "
.ti -1c
.RI "int \fBwriteXPLOR\fP (\fBBimage\fP *p)"
.br
.RI "Writing a XPLOR map or structure factor file format\&. A text format used in X-ray crystallography\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing XPLOR reflection files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19981229 
.PP
Modified: 20000715 
.PP
.nf
Format: 3D structure factor file format for the program XPLOR

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwXPLOR\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readXPLOR (\fBBimage\fP * p, int readdata)"

.PP
Reading a XPLOR map or structure factor file format\&. A minimal implementation\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 32 of file rwXPLOR\&.cpp\&.
.SS "int writeXPLOR (\fBBimage\fP * p)"

.PP
Writing a XPLOR map or structure factor file format\&. A text format used in X-ray crystallography\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 221 of file rwXPLOR\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
