.TH "/Users/bernard/b20/bsoft/include/simplex.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/simplex.h \- Nelder and Mead downhill simplex method for generalized parameter fitting\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBsimplex\fP"
.br
.RI "Structure used in the downhill simplex method\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_Bsimplex_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nelder and Mead downhill simplex method for generalized parameter fitting\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000426 
.PP
Modified: 20210729 
.PP
.nf
Adapted from Numerical Recipes, 2nd edition, Press et al. 1992
The function "funk" is user-defined and references the "Bsimplex" structure.
It returns the "R" value and is called as:
    double  R = (funk)(simplex_struct);

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBsimplex\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _Bsimplex_"

.PP
Definition at line 115 of file simplex\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
