.TH "SPEhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPEhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwSPE\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBpad1\fP [10]"
.br
.ti -1c
.RI "char \fBdate\fP [10]"
.br
.ti -1c
.RI "short \fBpad2\fP [6]"
.br
.ti -1c
.RI "short \fBxdim\fP"
.br
.ti -1c
.RI "short \fBpad3\fP [32]"
.br
.ti -1c
.RI "short \fBdatatype\fP"
.br
.ti -1c
.RI "short \fBpad4\fP [45]"
.br
.ti -1c
.RI "char \fBComments\fP [400]"
.br
.ti -1c
.RI "short \fBpad5\fP [28]"
.br
.ti -1c
.RI "short \fBydim\fP"
.br
.ti -1c
.RI "char \fBpad6\fP [788]"
.br
.ti -1c
.RI "short \fBNumFrames\fP"
.br
.ti -1c
.RI "float \fBMaxIntensity\fP"
.br
.ti -1c
.RI "float \fBMinIntensity\fP"
.br
.ti -1c
.RI "short \fBpad7\fP [1321]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file rwSPE\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char SPEhead::Comments[400]"

.PP
Definition at line 24 of file rwSPE\&.h\&.
.SS "short SPEhead::datatype"

.PP
Definition at line 22 of file rwSPE\&.h\&.
.SS "char SPEhead::date[10]"

.PP
Definition at line 18 of file rwSPE\&.h\&.
.SS "float SPEhead::MaxIntensity"

.PP
Definition at line 29 of file rwSPE\&.h\&.
.SS "float SPEhead::MinIntensity"

.PP
Definition at line 30 of file rwSPE\&.h\&.
.SS "short SPEhead::NumFrames"

.PP
Definition at line 28 of file rwSPE\&.h\&.
.SS "short SPEhead::pad1[10]"

.PP
Definition at line 17 of file rwSPE\&.h\&.
.SS "short SPEhead::pad2[6]"

.PP
Definition at line 19 of file rwSPE\&.h\&.
.SS "short SPEhead::pad3[32]"

.PP
Definition at line 21 of file rwSPE\&.h\&.
.SS "short SPEhead::pad4[45]"

.PP
Definition at line 23 of file rwSPE\&.h\&.
.SS "short SPEhead::pad5[28]"

.PP
Definition at line 25 of file rwSPE\&.h\&.
.SS "char SPEhead::pad6[788]"

.PP
Definition at line 27 of file rwSPE\&.h\&.
.SS "short SPEhead::pad7[1321]"

.PP
Definition at line 31 of file rwSPE\&.h\&.
.SS "short SPEhead::xdim"

.PP
Definition at line 20 of file rwSPE\&.h\&.
.SS "short SPEhead::ydim"

.PP
Definition at line 26 of file rwSPE\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
