.TH "Sphere" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sphere
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_subtomo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBA\fP"
.br
.ti -1c
.RI "double \fBB\fP"
.br
.ti -1c
.RI "double \fBC\fP"
.br
.ti -1c
.RI "double \fBR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file mg_subtomo\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Sphere::A"

.PP
Definition at line 21 of file mg_subtomo\&.h\&.
.SS "double Sphere::B"

.PP
Definition at line 21 of file mg_subtomo\&.h\&.
.SS "double Sphere::C"

.PP
Definition at line 21 of file mg_subtomo\&.h\&.
.SS "double Sphere::R"

.PP
Definition at line 22 of file mg_subtomo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
