.TH "SPIDERhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPIDERhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwSPIDER\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBnslice\fP"
.br
.ti -1c
.RI "float \fBnrow\fP"
.br
.ti -1c
.RI "float \fBirec\fP"
.br
.ti -1c
.RI "float \fBnhistrec\fP"
.br
.ti -1c
.RI "float \fBiform\fP"
.br
.ti -1c
.RI "float \fBimami\fP"
.br
.ti -1c
.RI "float \fBfmax\fP"
.br
.ti -1c
.RI "float \fBfmin\fP"
.br
.ti -1c
.RI "float \fBav\fP"
.br
.ti -1c
.RI "float \fBsig\fP"
.br
.ti -1c
.RI "float \fBihist\fP"
.br
.ti -1c
.RI "float \fBnsam\fP"
.br
.ti -1c
.RI "float \fBlabrec\fP"
.br
.ti -1c
.RI "float \fBiangle\fP"
.br
.ti -1c
.RI "float \fBphi\fP"
.br
.ti -1c
.RI "float \fBtheta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "float \fBxoff\fP"
.br
.ti -1c
.RI "float \fByoff\fP"
.br
.ti -1c
.RI "float \fBzoff\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "float \fBlabbyt\fP"
.br
.ti -1c
.RI "float \fBlenbyt\fP"
.br
.ti -1c
.RI "float \fBistack\fP"
.br
.ti -1c
.RI "float \fBinuse\fP"
.br
.ti -1c
.RI "float \fBmaxim\fP"
.br
.ti -1c
.RI "float \fBimgnum\fP"
.br
.ti -1c
.RI "float \fBunused\fP [2]"
.br
.ti -1c
.RI "float \fBkangle\fP"
.br
.ti -1c
.RI "float \fBphi1\fP"
.br
.ti -1c
.RI "float \fBtheta1\fP"
.br
.ti -1c
.RI "float \fBpsi1\fP"
.br
.ti -1c
.RI "float \fBphi2\fP"
.br
.ti -1c
.RI "float \fBtheta2\fP"
.br
.ti -1c
.RI "float \fBpsi2\fP"
.br
.ti -1c
.RI "float \fBextra\fP [175]"
.br
.ti -1c
.RI "char \fBcdat\fP [12]"
.br
.ti -1c
.RI "char \fBctim\fP [8]"
.br
.ti -1c
.RI "char \fBctit\fP [160]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwSPIDER\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float SPIDERhead::av"

.PP
Definition at line 24 of file rwSPIDER\&.h\&.
.SS "char SPIDERhead::cdat[12]"

.PP
Definition at line 52 of file rwSPIDER\&.h\&.
.SS "char SPIDERhead::ctim[8]"

.PP
Definition at line 53 of file rwSPIDER\&.h\&.
.SS "char SPIDERhead::ctit[160]"

.PP
Definition at line 54 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::extra[175]"

.PP
Definition at line 51 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::fmax"

.PP
Definition at line 22 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::fmin"

.PP
Definition at line 23 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::gamma"

.PP
Definition at line 32 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::iangle"

.PP
Definition at line 29 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::iform"

.PP
Definition at line 20 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::ihist"

.PP
Definition at line 26 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::imami"

.PP
Definition at line 21 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::imgnum"

.PP
Definition at line 42 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::inuse"

.PP
Definition at line 40 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::irec"

.PP
Definition at line 18 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::istack"

.PP
Definition at line 39 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::kangle"

.PP
Definition at line 44 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::labbyt"

.PP
Definition at line 37 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::labrec"

.PP
Definition at line 28 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::lenbyt"

.PP
Definition at line 38 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::maxim"

.PP
Definition at line 41 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::nhistrec"

.PP
Definition at line 19 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::nrow"

.PP
Definition at line 17 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::nsam"

.PP
Definition at line 27 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::nslice"

.PP
Definition at line 16 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::phi"

.PP
Definition at line 30 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::phi1"

.PP
Definition at line 45 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::phi2"

.PP
Definition at line 48 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::psi1"

.PP
Definition at line 47 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::psi2"

.PP
Definition at line 50 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::scale"

.PP
Definition at line 36 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::sig"

.PP
Definition at line 25 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::theta"

.PP
Definition at line 31 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::theta1"

.PP
Definition at line 46 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::theta2"

.PP
Definition at line 49 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::unused[2]"

.PP
Definition at line 43 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::xoff"

.PP
Definition at line 33 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::yoff"

.PP
Definition at line 34 of file rwSPIDER\&.h\&.
.SS "float SPIDERhead::zoff"

.PP
Definition at line 35 of file rwSPIDER\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
