.TH "/Users/bernard/b20/bsoft/include/star.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/star.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'string_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBstarLoop\fP"
.br
.RI "Structure for a table of entries in a STAR database block\&. "
.ti -1c
.RI "class \fBBstarBlock\fP"
.br
.ti -1c
.RI "class \fBBstar2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_STAR2_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
20151106 - 20210415 
.RE
.PP

.PP
Definition in file \fBstar\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _STAR2_"

.PP
Definition at line 459 of file star\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
