.TH "SUPRIMhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SUPRIMhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwSUPRIM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnrow\fP"
.br
.ti -1c
.RI "int \fBncol\fP"
.br
.ti -1c
.RI "int \fBformat\fP"
.br
.ti -1c
.RI "int \fBintern\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "float \fBmin\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.ti -1c
.RI "float \fBav\fP"
.br
.ti -1c
.RI "float \fBsd\fP"
.br
.ti -1c
.RI "\fBREG\fP \fBreg\fP [\fBMAXREG\fP]"
.br
.ti -1c
.RI "char \fBtrace\fP [1024]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file rwSUPRIM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float SUPRIMhead::av"

.PP
Definition at line 86 of file rwSUPRIM\&.h\&.
.SS "int SUPRIMhead::format"

.PP
Definition at line 81 of file rwSUPRIM\&.h\&.
.SS "int SUPRIMhead::intern"

.PP
Definition at line 82 of file rwSUPRIM\&.h\&.
.SS "float SUPRIMhead::max"

.PP
Definition at line 85 of file rwSUPRIM\&.h\&.
.SS "float SUPRIMhead::min"

.PP
Definition at line 84 of file rwSUPRIM\&.h\&.
.SS "int SUPRIMhead::ncol"

.PP
Definition at line 80 of file rwSUPRIM\&.h\&.
.SS "int SUPRIMhead::nrow"

.PP
Definition at line 79 of file rwSUPRIM\&.h\&.
.SS "\fBREG\fP SUPRIMhead::reg[\fBMAXREG\fP]"

.PP
Definition at line 88 of file rwSUPRIM\&.h\&.
.SS "float SUPRIMhead::sd"

.PP
Definition at line 87 of file rwSUPRIM\&.h\&.
.SS "char SUPRIMhead::trace[1024]"

.PP
Definition at line 89 of file rwSUPRIM\&.h\&.
.SS "int SUPRIMhead::type"

.PP
Definition at line 83 of file rwSUPRIM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
