.TH "/Users/bernard/b20/bsoft/include/sym_tags.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/sym_tags.h \- All STAR file format tags for symmetry parameters\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYMMETRY\fP   'symmetry'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_TYPE\fP   'symmetry\&.cell_setting'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_NUMBER\fP   'symmetry\&.Int_Tables_number'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_NAME\fP   'symmetry\&.space_group_name_H\-M'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_EQUIVID\fP   'symmetry_equiv\&.id'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_EQUIVXYZ\fP   'symmetry_equiv\&.pos_as_xyz'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_POINT_GROUP\fP   'symmetry\&.point_group'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_PG_NUMBER\fP   'symmetry\&.point_group_number'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_AXIS_ORDER\fP   'symmetry_axis\&.order'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_AXIS_X\fP   'symmetry_axis\&.x'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_AXIS_Y\fP   'symmetry_axis\&.y'"
.br
.ti -1c
.RI "#define \fBSYMMETRY_AXIS_Z\fP   'symmetry_axis\&.z'"
.br
.ti -1c
.RI "#define \fBUNIT_CELL_A\fP   'cell\&.length_a'"
.br
.ti -1c
.RI "#define \fBUNIT_CELL_B\fP   'cell\&.length_b'"
.br
.ti -1c
.RI "#define \fBUNIT_CELL_C\fP   'cell\&.length_c'"
.br
.ti -1c
.RI "#define \fBUNIT_CELL_ALPHA\fP   'cell\&.angle_alpha'"
.br
.ti -1c
.RI "#define \fBUNIT_CELL_BETA\fP   'cell\&.angle_beta'"
.br
.ti -1c
.RI "#define \fBUNIT_CELL_GAMMA\fP   'cell\&.angle_gamma'"
.br
.in -1c
.SH "Detailed Description"
.PP 
All STAR file format tags for symmetry parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000419 
.PP
Modified: 20080924 
.RE
.PP

.PP
Definition in file \fBsym_tags\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define SYMMETRY   'symmetry'"

.PP
Definition at line 13 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_AXIS_ORDER   'symmetry_axis\&.order'"

.PP
Definition at line 23 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_AXIS_X   'symmetry_axis\&.x'"

.PP
Definition at line 24 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_AXIS_Y   'symmetry_axis\&.y'"

.PP
Definition at line 25 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_AXIS_Z   'symmetry_axis\&.z'"

.PP
Definition at line 26 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_EQUIVID   'symmetry_equiv\&.id'"

.PP
Definition at line 19 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_EQUIVXYZ   'symmetry_equiv\&.pos_as_xyz'"

.PP
Definition at line 20 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_NAME   'symmetry\&.space_group_name_H\-M'"

.PP
Definition at line 18 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_NUMBER   'symmetry\&.Int_Tables_number'"

.PP
Definition at line 17 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_PG_NUMBER   'symmetry\&.point_group_number'"

.PP
Definition at line 22 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_POINT_GROUP   'symmetry\&.point_group'"

.PP
Definition at line 21 of file sym_tags\&.h\&.
.SS "#define SYMMETRY_TYPE   'symmetry\&.cell_setting'"

.PP
Definition at line 16 of file sym_tags\&.h\&.
.SS "#define UNIT_CELL_A   'cell\&.length_a'"

.PP
Definition at line 29 of file sym_tags\&.h\&.
.SS "#define UNIT_CELL_ALPHA   'cell\&.angle_alpha'"

.PP
Definition at line 32 of file sym_tags\&.h\&.
.SS "#define UNIT_CELL_B   'cell\&.length_b'"

.PP
Definition at line 30 of file sym_tags\&.h\&.
.SS "#define UNIT_CELL_BETA   'cell\&.angle_beta'"

.PP
Definition at line 33 of file sym_tags\&.h\&.
.SS "#define UNIT_CELL_C   'cell\&.length_c'"

.PP
Definition at line 31 of file sym_tags\&.h\&.
.SS "#define UNIT_CELL_GAMMA   'cell\&.angle_gamma'"

.PP
Definition at line 34 of file sym_tags\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
