.TH "TagValue" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagValue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTagValue\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file rwmodel_cmm\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTagValue\fP* TagValue::next"

.PP
Definition at line 19 of file rwmodel_cmm\&.cpp\&.
.SS "\fBBstring\fP TagValue::tag"

.PP
Definition at line 20 of file rwmodel_cmm\&.cpp\&.
.SS "\fBBstring\fP TagValue::value"

.PP
Definition at line 21 of file rwmodel_cmm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
