.TH "/Users/bernard/b20/bsoft/tcltk/tcltk_bimage.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/tcltk_bimage.h \- A shared object to load Bsoft image files in TCL/Tk\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBimage_processing\fP (Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
A shared object to load Bsoft image files in TCL/Tk\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010210 
.PP
Modified: 20130924 
.RE
.PP

.PP
Definition in file \fBtcltk_bimage\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int image_processing (Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 156 of file tcltk_bimage\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
