.TH "/Users/bernard/b20/bsoft/tcltk/tcltk_bhelix.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/tcltk_bhelix.cpp \- A shared object to manage micrograph parameter files in TCL/Tk\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br
\fC#include 'tcltk_bhelix\&.h'\fP
.br
\fC#include 'mg_helix\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Tcl_Obj * \fBlayerline_count\fP (\fBBmicrograph\fP *mg)"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_ids\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_renumber\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_distance\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_fom\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_select\fP (\fBBmicrograph\fP *mg, \fBBimage\fP *p, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_move\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_create\fP (\fBBmicrograph\fP *mg, \fBBimage\fP *p, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_delete\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_delete\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_order\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_generate\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_mask\fP (\fBBmicrograph\fP *mg, \fBBimage\fP *p, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_plot\fP (\fBBmicrograph\fP *mg, \fBBimage\fP *p, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBlayerline_bessel_function\fP (double realsizeX, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBdo_layerline\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "\fBBimage\fP * \fBimglist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A shared object to manage micrograph parameter files in TCL/Tk\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20030813 
.PP
Modified: 20130726 
.RE
.PP

.PP
Definition in file \fBtcltk_bhelix\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "Tcl_Obj* do_layerline (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 71 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_bessel_function (double realsizeX, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 546 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_count (\fBBmicrograph\fP * mg)"

.PP
Definition at line 171 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_create (\fBBmicrograph\fP * mg, \fBBimage\fP * p, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 332 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_delete (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 428 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_delete (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 363 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_distance (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 232 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_fom (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 252 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_generate (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 484 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_ids (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 186 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_mask (\fBBmicrograph\fP * mg, \fBBimage\fP * p, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 500 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_move (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 306 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_order (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 457 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_plot (\fBBmicrograph\fP * mg, \fBBimage\fP * p, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 517 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_renumber (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 206 of file tcltk_bhelix\&.cpp\&.
.SS "Tcl_Obj * layerline_select (\fBBmicrograph\fP * mg, \fBBimage\fP * p, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 272 of file tcltk_bhelix\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBBimage\fP* imglist\fC [extern]\fP"

.PP
Definition at line 32 of file bshow\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
