.TH "/Users/bernard/b20/bsoft/tcltk/tcltk_bmarker.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/tcltk_bmarker.h \- A shared object to manage markers in micrograph parameter files in TCL/Tk\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Tcl_Obj * \fBdo_tomo_thickness\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "int \fBdo_tomo_transfer_seed\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "int \fBdo_tomo_findaxis\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "int \fBdo_tomo_track\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "int \fBdo_tomo_refine\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "int \fBdo_tomo_refine_one\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBdo_marker\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
A shared object to manage markers in micrograph parameter files in TCL/Tk\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20030813 
.PP
Modified: 20200226 
.RE
.PP

.PP
Definition in file \fBtcltk_bmarker\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "Tcl_Obj* do_marker (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 279 of file tcltk_bmarker\&.cpp\&.
.SS "int do_tomo_findaxis (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 131 of file tcltk_bmarker\&.cpp\&.
.SS "int do_tomo_refine (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 179 of file tcltk_bmarker\&.cpp\&.
.SS "int do_tomo_refine_one (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 216 of file tcltk_bmarker\&.cpp\&.
.SS "Tcl_Obj* do_tomo_thickness (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 68 of file tcltk_bmarker\&.cpp\&.
.SS "int do_tomo_track (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 154 of file tcltk_bmarker\&.cpp\&.
.SS "int do_tomo_transfer_seed (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 102 of file tcltk_bmarker\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
