.TH "tk::mac" 3 "Thu Feb 13 2020" "Version 2.0.5" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tk::mac
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBShowPreferences\fP"
.br
.ti -1c
.RI "\fBShowHelp\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "tk::mac::ShowHelp"

.PP
Definition at line 1124 of file bshow_misc\&.tcl\&.
.SS "tk::mac::ShowPreferences"

.PP
Definition at line 192 of file bshow_misc\&.tcl\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
