.TH "Transform" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transform
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Transform\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransform\fP ()"
.br
.ti -1c
.RI "\fBTransform\fP (\fBQuaternion\fP &q)"
.br
.ti -1c
.RI "\fBTransform\fP (\fBMatrix3\fP &m)"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBoperator*\fP (\fBVector3\fP< double > v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransform\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBorigin\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBaxis\fP"
.br
.ti -1c
.RI "double \fBangle\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBtrans\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBscale\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file Transform\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Transform::Transform ()\fC [inline]\fP"

.PP
Definition at line 42 of file Transform\&.h\&.
.SS "Transform::Transform (\fBQuaternion\fP & q)\fC [inline]\fP"

.PP
Definition at line 44 of file Transform\&.h\&.
.SS "Transform::Transform (\fBMatrix3\fP & m)\fC [inline]\fP"

.PP
Definition at line 47 of file Transform\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBVector3\fP<double> Transform::operator* (\fBVector3\fP< double > v)\fC [inline]\fP"

.PP
Definition at line 51 of file Transform\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Transform::angle"

.PP
Definition at line 29 of file Transform\&.h\&.
.SS "\fBVector3\fP<double> Transform::axis"

.PP
Definition at line 28 of file Transform\&.h\&.
.SS "double Transform::fom"

.PP
Definition at line 32 of file Transform\&.h\&.
.SS "\fBTransform\fP* Transform::next"

.PP
Definition at line 26 of file Transform\&.h\&.
.SS "\fBVector3\fP<double> Transform::origin"

.PP
Definition at line 27 of file Transform\&.h\&.
.SS "\fBVector3\fP<double> Transform::scale"

.PP
Definition at line 31 of file Transform\&.h\&.
.SS "\fBVector3\fP<double> Transform::trans"

.PP
Definition at line 30 of file Transform\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
