.TH "TypePointer" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypePointer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bimage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBuc\fP"
.br
.ti -1c
.RI "signed char * \fBsc\fP"
.br
.ti -1c
.RI "unsigned short * \fBus\fP"
.br
.ti -1c
.RI "short * \fBss\fP"
.br
.ti -1c
.RI "unsigned int * \fBui\fP"
.br
.ti -1c
.RI "int * \fBsi\fP"
.br
.ti -1c
.RI "unsigned long * \fBul\fP"
.br
.ti -1c
.RI "long * \fBsl\fP"
.br
.ti -1c
.RI "float * \fBf\fP"
.br
.ti -1c
.RI "double * \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file Bimage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double* TypePointer::d"

.PP
Definition at line 62 of file Bimage\&.h\&.
.SS "float* TypePointer::f"

.PP
Definition at line 61 of file Bimage\&.h\&.
.SS "signed char* TypePointer::sc"

.PP
Definition at line 54 of file Bimage\&.h\&.
.SS "int* TypePointer::si"

.PP
Definition at line 58 of file Bimage\&.h\&.
.SS "long* TypePointer::sl"

.PP
Definition at line 60 of file Bimage\&.h\&.
.SS "short* TypePointer::ss"

.PP
Definition at line 56 of file Bimage\&.h\&.
.SS "unsigned char* TypePointer::uc"

.PP
Definition at line 53 of file Bimage\&.h\&.
.SS "unsigned int* TypePointer::ui"

.PP
Definition at line 57 of file Bimage\&.h\&.
.SS "unsigned long* TypePointer::ul"

.PP
Definition at line 59 of file Bimage\&.h\&.
.SS "unsigned short* TypePointer::us"

.PP
Definition at line 55 of file Bimage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
