.TH "/Users/bernard/b20/bsoft/include/View2.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/View2.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Vector3\&.h'\fP
.br
\fC#include 'Matrix3\&.h'\fP
.br
\fC#include 'Quaternion\&.h'\fP
.br
\fC#include 'random_numbers\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBView2< Type >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBView2\fP< float > v)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBView2\fP< double > v)"
.br
.ti -1c
.RI "list< \fBView2\fP< float > > \fBviews_within_limits2\fP (\fBView2\fP< float > theview, double theta_step, double phi_step, double alpha_step, double view_angle_limit, double alpha_angle_limit)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & output, \fBView2\fP< double > v)"

.PP
Definition at line 32 of file View\&.cpp\&.
.SS "ostream& operator<< (ostream & output, \fBView2\fP< float > v)"

.PP
Definition at line 26 of file View\&.cpp\&.
.SS "list<\fBView2\fP<float> > views_within_limits2 (\fBView2\fP< float > theview, double theta_step, double phi_step, double alpha_step, double view_angle_limit, double alpha_angle_limit)"

.PP
Definition at line 294 of file View\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
