>P1;VP23_HSV11
VP23_HSV11, 340 bases, 844CCB8B checksum.
 MLA-DGFETD IAIPSGISRP DAAALQRCEG RVVFLPTIRR QLTLADVAHE
 SFVSGGVSPD TLGLLLAYRR RFPAVITRVL PTRIVACPLD VGLTHAGTVN
 LRNTSP--VD LCNGDPISLV PPVFEGQATD -VRLDSLDLT LRFPVPLPSP
 LAREIVARLV ARGIRDLNPS PRNPGGLP-- DLNVLYYNGS RLSLLADVQQ
 LGPVNAELRS LVLNMVYSIT EGTTIILTLI PRLFALSAQD GYVNALLQMQ
 SVTREAAQLI HPE------- --------AP ALMQDGERRL PLYEALVAWL
 THAGQLGDTL ALAPVVRVCT FDGAAVVRSG DMAPVIRYP-*

>P1;vp23_hsv2h
vp23_hsv2h, 340 bases, AD5BFAE5 checksum.
 MIT-DCFEAD IAIPSGISRP DAAALQRCEG RVVFLPTIRR QLALADVAHE
 SFVSGGVSPD TLGLLLAYRR RFPAVITRVL PTRIVACPVD LGLTHAGTVN
 LRNTSP--VD LCNGDPVSLV PPVFEGQATD -VRLESLDLT LRFPVPLPTP
 LAREIVARLV ARGIRDLNPD PRTPGELP-- DLNVLYYNGA RLSLVADVQQ
 LASVNTELRS LVLNMVYSIT EGTTLILTLI PRLLALSAQD GYVNALLQMQ
 SVTREAAQLI HPE------- --------AP MLMQDGERRL PLYEALVAWL
 AHAGQLGDIL ALAPAVRVCT FDGAAVVQSG DMAPVIRYP-*

>P1;VP23_VZVD
VP23_VZVD, 340 bases, CF0AB5B9 checksum.
 MAM--PFEIE VLLPGELSPA ETSALQKCEG KIITFSTLRH RASLVDIALS
 SYYINGAPPD TLSLLEAYRM RFAAVITRVI PGKLLAHAIG VGTPTPG-LF
 IQNTSP--VD LCNGDYICLL PPVFG-SADS -IRLDSVGLE IVFPLTIPQT
 LMREIIAKVV ARAVERTAAG AQILPHEVLR GADVICYNGR RYELETNLQH
 RDGSDAAIRT LVLNLMFSIN EGCLLLLALI PTLLVQGAHD GYVNLLIQTA
 NCVRETGQLI NIP------- --------PM PRIQDGHRRF PIYETISSWI
 STSSRLGDTL GTRAILRVCV FDGPSTVHPG DRTAVIQV--*

>P1;VP23_HSVEB
VP23_HSVEB, 340 bases, 436EDA7 checksum.
 MAS-AAFEID ILLPSDLSPA DLSALQKCEG KLVFLTALRR RVMLSSVTLS
 SYYVNGAPPD TLSLMAAFRR RFPAIIQRVL PNKMIAAALG VAPLPPG-AF
 IQNTGP--FD LCNGDSVCAL PPILD-VEDK -LRLGSVGEE ILFPLTVPLA
 QARELIARLV ARAVQALTPN AQAQRG---- -AEVMFYNGR KYNVTPDLRH
 RDAVNGVARS LVLNMIFAMN EGSLVLLSLI PNLLTLGTQD GFVNAIIQMG
 SATREVGQLV HQQ------- --------PV PQPQDGARRF CVYDALMSWI
 SVASRLGDVV GGKPLVRICT FEGQATISRG EKAPVIQTLL*

>P1;vp23_ehv4
vp23_ehv4, 340 bases, A077FE7F checksum.
 MAS-AAFEID ILLPGDLSPS DLSALQKCEG KIVFLTALRR RVMLSSVTLA
 SYYVNGAPPD TLSLMAAFRR RFPAIIQRVL PNKMIAVALG VSVLPPG-TF
 IQNTGP--FD LTNGDSVCAL PPILD-VEDK -LRLGSVGEE ILFPLTVPLA
 QARELIARLV ARAVQALTPN AQGHRG---- -ADVMFYNGR KYNVTPDFRH
 RDAVNGVARS LVLNMIFAMN EGSLVLLSLI PNLLTLGTQD GFVNAIIQIG
 SATREVGQLI HQQ------- --------PV PQPQDGARRF CVYDALMSWI
 GVASRLGDVV GGKPLVRICT FEGPATISRG EKAPVIQTLL*

>P1;vp23_bhv1
vp23_bhv1, 340 bases, 98352485 checksum.
 MAQPEAFEVE IVLPGDLSHG DLAALQKCEG KVVFFTTLRR RVPLADVALA
 SFSVNGVAPD TLGLMAAYRC RFPAVVLRVA PGRMMAAPLG VGPMPRG-AF
 LQNTGP--FD LCNGDAVCLL PPLLG-PARA -LALASAGAE LLFPMTVPLP
 QARALVARVV ARAVEALGDR AAAARARA-- -ADVMYHNGR RYQVTPDVLC
 REGADAAART LVLNMVFNVN EGSLLLLSLI PNLLTQGLQD GVANAIVQLG
 SASREAGQLL RLE------- --------PA EPRQDGGRRF CLYGALAAWI
 SSATRLGDAV GARPLAKVCT FDGPSVVRVG EKAPIVVPL-*

>P1;vp23_ghv1
vp23_ghv1, 340 bases, D4392575 checksum.
 MAASNGTTVE IELPCGLSTC DANLLQRCEG RVLFLPSVRA RVLLKEVDYK
 SYYIAGAEPD TLSLLSTYKR RFAAVVTRAL PGRMSAVVLG MGTIPSG-LA
 LQNTGP--FD LCNGDAVCLI PPLFPNVCSR -IRLESIDTE LLFPSTVPAR
 LAREIIAKTL SRATEGIAIG GGLAPPPTSR EAESITYNGK TYTISPTLHS
 LDASESAVRT LLLNMIFAID EGNMLLYALI PTLLTLGASD GYVNALVGLQ
 TATRAVGQLI RIP------- --------RP PPLQDAWRRY PIYEALSSWI
 TMALHLGDML ALRPLLKVCT FDGPASIKVG DLCPVISNWN*

>P1;vp23_ghv2
vp23_ghv2, 340 bases, 81675852 checksum.
 MSTSNGTIVE IELPCKLSTC DANLLQRCEG RVVFLPFVRA RVLLKDVDYK
 SFYIAGTEPD TLSLLSTFKT RFACRHHSCL AWPNERCSLG NGIYSNG-LA
 LQNTGP--FD LCNGDTVCLM PPIFPNVCCR -IRLESIDTE LLFPVTVPTR
 LANEILAKTL SRAIE--AIG RGQMPPPTSR ESETIMYNGR SYTISPTLHS
 LDAAESTVRT LLLNMIFAIN EGNMILYTMI PTLLTLGASD GYINALVGLE
 TATRAVGQLI RIP------- --------NP PPLQDAWRRY PVYEALSAWI
 TMTLNLGNVL SLHPLLKVCT FDGPANIKAG DLCPVIANWY*

>P1;VP23_HCMVA
VP23_HCMVA, 340 bases, A1843EE1 checksum.
 -MAAMEANIF CTFDHKLSIA DVGKLTKLVA AVVPIPQRLH LIKHYQLGLH
 QFV--DHTRG YVRLRGLLRN MTLTLMRRVE GNQ----ILL HVPTHGLLYT
 VLNTGP--VT WEKGDALCVL PPLFHGPLAR ENLLTLGQWE LVLPWIVPMP
 LALEINQRLL IMGLFSLDRS YEE------- -VKAAVQQLQ TITFRDATFT
 IP-DPVIDQH -LLIDMKTAC LSMSMVANLA SELTMTYVRK LALEDSSMLL
 VKCQELLMRL DRERSVGEPR T------PAR P---QHVSPD DEIARLSALF
 VMLRQLDDLI REQVVFTVCD VSPDNKSATC IFKG------*

>P1;vp23_mcmv
vp23_mcmv, 340 bases, AD0C360A checksum.
 ----METTVL VTFEQRLTTG DVGKLSRLIG AVIPIPYRHH LLGSSQVGLD
 AVV-KDKTRD YSRMRARMRE MTLTIMRRVE GNQ----MIL GVPTHGQCYT
 IRNTGP--VS WEKGDVLTTL PPVFSGEVTG --LVSVSDWD LVLPWIVPMA
 LATEINQRMM MLALLSLDRS HEE------- -VRAATAQLR VVRYRDATLT
 LP-EITIDDT -VLIDMRNVC ISLSMIANLS SEVTLAYVRK LALEDSNMLL
 MKCQEILGRR MPQVGVGAGS SGDRNDPPAR SRTNYNITPT EELNKLTALF
 VMIRQITDVI SEQPAFLVCD VSPDDKSALC IYKG------*

>P1;VP23_HSV6U
VP23_HSV6U, 340 bases, F5A15083 checksum.
 ----MET-VY CTFDHKLSLS DISTLCKLMN IVIPIPAHHH LIGSGNLGLY
 PIV--SSNKD YVHVRNVLRT MVVTILQKVE GNQ----LVL RKPVTGHQYA
 IKNTGP--FP WEKGDTLTLI PPLSTHSEEK --LLKLGDWE LTVPLVVPTA
 IAAEINIRLL CIGLIAVHRE YNE------- -MQTIIDELC SIQYRDVLIK
 LP-DIVNDKQ -SMYSMKTAC ISLSMITAMA PDIVRTYIDR LTLEDHSMLL
 IKCQELLSKR TTL------- ------NTQR CGQLHATEIK DELKKVKSVL
 TMIDQINSLT NEKTYFVVCD VSADNRMATC IYKN------*

>P1;vp23_hsv6b
vp23_hsv6b, 340 bases, C4FA354 checksum.
 ----MET-VY CTFDHKLSLS DISTLCKLMN IVIPIPAHHH LIGSGNLGLY
 PIV--SSNKD YVHIRNVLRT MVVTILQKVE GNQ----LVL RKPMTGQQYA
 IKNTGP--FP WEKGDTLTLI PPLSTHSEEK --LLKLGDWE LTVPLVVPTA
 IAAEINIRLL CIGLIAVHRE YNE------- -MQTIIDELC SIQYRDVLIK
 LP-DIVNDKQ -SMYSMKTAC ISLSMITAMA PDIVRTYIDR LTLEDHSMLL
 IKCQELLSKR TTL------- ------STQR CGQLHATDIK DELKKIKSVL
 TMIDQINSLT NEKTYFVVCD VSADNRMATC IYKN------*

>P1;VP23_HSV7J
VP23_HSV7J, 340 bases, FBC558E7 checksum.
 ----MDS-IY CTFDQKLTLS DIGTLCKLTN AVIPIPSHRH LIGNTNLGLY
 TVL--STTTD YIQIRDILKT MVLTILQKVE GNQ----LIL IRPKIGHQYE
 IKNTGP--FP LEKGDQLSLL PPFLKPSQQ- --LLVLPNWE LILPLLIPTD
 VATEINVRML CISLLSIHRK YEE------- -VQIIIDELR TLQYRDVTIK
 LP-DVINDCK -STFSMKTAC ISFSMIATMA PDIVQTYIER LSLEDQSMLL
 IKCQELLAKK N--------- ------FSQE PSSFKATEIK TELQKIKTVF
 TMINQINSLT QEKTFFIVAD VSADNRLATC IFKE------*

>P1;VP23_EBV
VP23_EBV, 340 bases, C66816C3 checksum.
 ----MDLKVV VSLSSRLYTD EIAKMQQRIG CILPLASTHG TQNVQGLGLG
 QVYSLETVPD YVSMYNYLSD CTLAVLDEVS VDS----LIL TKIVPGQTYA
 IKNKYQPFFQ WHGTGSLSVM PPVFGREHAT -VKLESNDVD IVFPMVLPTP
 IAEEVLQKIL LFNVYSRVVM QAPGNA---- DMLDVHMHLG SVSYLGHHYE
 LA-LPEVPGP LGLALLDNLS LYFCIMVTLL PRASMRLVRG LIRHEHHDLL
 NLFQEMVPDE I--------- ---------A RIDLDDLSVA DDLSRMRVMM
 TYLQSLASLF NLGPRLATAA YSQETLTATC WLR-------*

>P1;vp23_kshv
vp23_kshv, 340 bases, 288629E6 checksum.
 --MALDKSIV VNFTSRLFAD ELAALQSKIG SVLPLGDCHR LQNIQALGLG
 CVCSRETSPD YIQIMQYLSK CTLAVLEEVR PDS----LRL TRMDPSDNLQ
 IKNVYAPFFQ WDSNTQLAVL PPFFSRKDST -IVLESNGFD LVFPMVVPQQ
 LGHAILQQLL VYHIYSKISA GAPDDV---- NMAELDLYTT NVSFMGRTYR
 LD-VDNTDPR TALRVLDDLS MYLCILSALV PRGCLRLLTA LVRHDRHPLT
 EVFEGVVPDE V--------- ---------T RIDLDQLSVP DDITRMRVMF
 SYLQSLSSIF NLGPRLHVYA YSAETLAASC WYSPR-----*

>P1;vp23_mmrv
vp23_mmrv, 340 bases, B0A03D60 checksum.
 --MALDKSIV VSVTSRLFAD EIANLQSKIG CILPLRDAHR LQNIQALGLG
 NLCSRDSAVD FIQAYHYLDK CTLAVLEEVG PNS----LRL TRIDPMDNYQ
 IKNAYQPAFH WDNYSELVVI PPVFGRKDAT -VSLESNGFD VVFPAVVPEP
 LAQTVLQKLL LYNIYYRVAE TTPTDV---- NLAEVTLYTT NITYMGRNYA
 LD-VDPVGSS SAMRMLDDLS IYLCVLSALI PRGCVRLLTS LVRHNKHELV
 EIFEGVVPPE V--------- ---------Q ALDLNNVSVA DDITRMGALI
 TYLRSLSSIF NLGRRFHVYA FSSDTNTASC WCAYN-----*

>P1;vp23_ahv3
vp23_ahv3, 340 bases, CAE76D68 checksum.
 --MLTDKTIT VSLTSRLFAD EIAKMQKKLG SILPLQSPHK IQSLETLGLN
 TVCSRDVFPD YVHMFSYLSK CTLAILEEVN PDR----LIL TRLDPSEIYQ
 IKNVYEPLFQ WDGFTNLTVI PPVFGRQKAT -VTLESNGFD LVFPSVVPSD
 LAQAIIGKLL LYNLYSRLVE SDP-EI---- NMEEVTMYTT NVTHMGRHYV
 LD-ITHNNPN EALKSLDELA VYTSILSALI PRACLRMLTI LMRHEQHELL
 DVFRGIVPRE V--------- ---------Y EIDASALNIG DDITRMSTFI
 TYLQSLSSIF NLGVKLRLLS YTSEALTATC WISHY-----*

>P1;VP23_HSVSA
VP23_HSVSA, 340 bases, CD3F3470 checksum.
 --MLTDKTII VSLTSRLFAD EITKLQKKIG SILPLQDPHK LQSLDTLGLN
 AVCSRDVFPD YVHMFSYLSK CTLAILEEVN PDN----LIL TRLDPSETYQ
 IKNVYEPMFQ WDGFSNLTVI PPVFGRQQAT -VTLESNGFD LVFPSVVPSD
 LAQAIIGKLL LYNLYSRLVE SDP-EI---- NIEEVNMYTT NVTHMGRHYV
 LD-INHNNPN EALKSLDDLA VYTCILSALI PRACLRVLTI LMRHDQHELL
 DVFRGIVPRE V--------- ---------Y EIDANALSIG DDITRMTTFI
 TYLQSLSSIF NLGAKLHLSS YASETQTATC WISYC-----*

>P1;vp23_ehv2
vp23_ehv2, 340 bases, C6918AE7 checksum.
 --MQVDSRIV VTLTSRLYAD EISKLQERVG SVVPLKDSHR LQNLNSVGMY
 SVYMRNVAPD FVAMFSYLSE ATLAILDEVT PDT----LVF SRLDHSQNYE
 LKNVYYPSFA WHSHTLLTVV PPVFGREAAT -VALESNGFE IVFPVVMPHA
 LAQAVLQKLM LYNIYARLSD ANVGDV---- NMDHVRFHAT TLHHMGRAYT
 LH-IDQANPG GMLGLLDNLA IYLAIISALL PNSLARLLPA IMRHEQHELL
 NIFAGVAPPD D--------- ---------- ---GGDFNIE DDMQKMESFM
 AYMQSVSSIF NLGPKLRLGQ YSSETQSGTA WLAS------*

>P1;vp23_wbhv1
vp23_wbhv1, 340 bases, E99687F0 checksum.
 --MAVDSKIV VSCTSRLFTD EVCKLQEKVG CIVPLRDSHG SQNLQTVGLK
 PALGIDLGSD YVLMCNYLST CTLAILEEVT TDS----LVL TKISRNGTYQ
 IKNKYHPFFQ WDSNIQVCVM PPLFDQESNS -VDLQSNNFT LLLPIVVPCE
 VAHEALQKVL TYNIYLRVTQ AEPNAA---- RMADVLAQTN YVTYLGNHYS
 LN-LEGMESL GALAFLDNLA TYLCIMVGLL PRACVRLLTT LLRHGENELL
 NVFRRMIPDE FNA------- ---------A AANLNADTVY PDMTKIGLLI
 TYLQTLGSIF NLSPRLQVST YTPENLSATC WYVC------*

>P1;vp23_mhv4
vp23_mhv4, 340 bases, CD4DAE67 checksum.
 --MASNRNIV ITLTSRLYAD EISALQEMVG AVICLQHYHQ VQDVTSIGLG
 HIIRPEGPVD WIAAFHYLRR CTFGILHEIN PDS----ISI IRVDPGENYQ
 IKNTSKPYVM WDEHDDLAII PPIFGVQQCT -IKLDSNDVN LVFPSVVPAG
 LAQMGIQKIL MYNLYSNLLA AERNHD---- NVNALEHYTR NISYMGRTYN
 LD-AMAQHQD GAMAVLDDVA MCTAVLAAIV PEVCNRVAMA TIREGQHPLV
 EVFADNVPML Q--------- ---------- --RGQELNVE QDIMLMGLFM
 AYTHKLGSIF NLSTRLCLGA YSHETKIGTC WL--------*

