#!/usr/bin/env sh

# Script to create the bshow link
# Bernard Heymann
# 20170511

BSOFT="/usr/local/bsoft"

cd /Applications/Bshow.app/Contents/Resources/Scripts/

rm -f AppMain.tcl

ln -s $BSOFT/tcltk/bshow AppMain.tcl

exit 0

