.TH "/Users/bernard/b20/bsoft/src/ps Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/ps Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBps_ctf_plot\&.cpp\fP"
.br
.RI "Postscript output functions for calculating CTF parameters\&. "
.ti -1c
.RI "file \fBps_marker\&.cpp\fP"
.br
.RI "Methods for postscript tools dealing with markers\&. "
.ti -1c
.RI "file \fBps_micrograph\&.cpp\fP"
.br
.RI "Postscript output for micrographs\&. "
.ti -1c
.RI "file \fBps_model\&.cpp\fP"
.br
.RI "Postscript output for models\&. "
.ti -1c
.RI "file \fBps_plot\&.cpp\fP"
.br
.RI "Postscript output functions\&. "
.ti -1c
.RI "file \fBps_sequence\&.cpp\fP"
.br
.RI "Postscript output for sequence analysis functions\&. "
.ti -1c
.RI "file \fBps_tree\&.cpp\fP"
.br
.RI "Postscript tree output functions\&. "
.ti -1c
.RI "file \fBps_views\&.cpp\fP"
.br
.RI "Postscript output for views\&. "
.in -1c
