.TH "/Users/bernard/b20/bsoft/src/img Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBimage\&.cpp\fP"
.br
.RI "Methods for the image class\&. "
.ti -1c
.RI "file \fBBimage_align\&.cpp\fP"
.br
.RI "Functions to align images\&. "
.ti -1c
.RI "file \fBBimage_background\&.cpp\fP"
.br
.RI "Library routines for manipulating image backgrounds\&. "
.ti -1c
.RI "file \fBBimage_bin\&.cpp\fP"
.br
.RI "Library routines for binning images\&. "
.ti -1c
.RI "file \fBBimage_color\&.cpp\fP"
.br
.RI "Library routines for mangaing color images\&. "
.ti -1c
.RI "file \fBBimage_combine\&.cpp\fP"
.br
.RI "Functions to combine two images in various ways\&. "
.ti -1c
.RI "file \fBBimage_complex\&.cpp\fP"
.br
.RI "Routines to convert complex data sets\&. "
.ti -1c
.RI "file \fBBimage_correlate\&.cpp\fP"
.br
.RI "Cross correlation functions\&. "
.ti -1c
.RI "file \fBBimage_edit\&.cpp\fP"
.br
.RI "Library routines used for editing image contents\&. "
.ti -1c
.RI "file \fBBimage_extract\&.cpp\fP"
.br
.RI "Library routines to extract parts of images\&. "
.ti -1c
.RI "file \fBBimage_fft\&.cpp\fP"
.br
.RI "General FFT for n-dimensional data\&. "
.ti -1c
.RI "file \fBBimage_filter\&.cpp\fP"
.br
.RI "Library routines used for filtering images\&. "
.ti -1c
.RI "file \fBBimage_fspace\&.cpp\fP"
.br
.RI "Library routines used for modifying reciprocal space amplitudes\&. "
.ti -1c
.RI "file \fBBimage_helix\&.cpp\fP"
.br
.RI "Dealing with images with helical symmetry\&. "
.ti -1c
.RI "file \fBBimage_histogram\&.cpp\fP"
.br
.RI "Library routines to calculate histograms for images\&. "
.ti -1c
.RI "file \fBBimage_mask\&.cpp\fP"
.br
.RI "Methods for binary mask creation and manipulation\&. "
.ti -1c
.RI "file \fBBimage_montage\&.cpp\fP"
.br
.RI "Functions to montage images for display\&. "
.ti -1c
.RI "file \fBBimage_nad\&.cpp\fP"
.br
.RI "Denoising by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&. "
.ti -1c
.RI "file \fBBimage_noise\&.cpp\fP"
.br
.RI "Functions for generating noise images\&. "
.ti -1c
.RI "file \fBBimage_polar\&.cpp\fP"
.br
.RI "Library routines for polar and spherical transformations and calculations\&. "
.ti -1c
.RI "file \fBBimage_powerspectrum\&.cpp\fP"
.br
.RI "Functions for calculating and using power spectra in electron micrographs\&. "
.ti -1c
.RI "file \fBBimage_project\&.cpp\fP"
.br
.RI "Functions for projections\&. "
.ti -1c
.RI "file \fBBimage_reconstruct\&.cpp\fP"
.br
.RI "2D and 3D reconstruction from single particle images "
.ti -1c
.RI "file \fBBimage_rescale\&.cpp\fP"
.br
.RI "Library routines to rescale images\&. "
.ti -1c
.RI "file \fBBimage_resize\&.cpp\fP"
.br
.RI "Library routines to resize images\&. "
.ti -1c
.RI "file \fBBimage_resolution\&.cpp\fP"
.br
.RI "Library routines to estimate resolution\&. "
.ti -1c
.RI "file \fBBimage_search\&.cpp\fP"
.br
.RI "Searches orientation space for the best fit of a 3D map to a template\&. "
.ti -1c
.RI "file \fBBimage_segment\&.cpp\fP"
.br
.RI "Methods for segmentation\&. "
.ti -1c
.RI "file \fBBimage_stats\&.cpp\fP"
.br
.RI "Functions to calculate statistics on image regions\&. "
.ti -1c
.RI "file \fBBimage_symmetry\&.cpp\fP"
.br
.RI "Symmetry function library for crystallography\&. "
.ti -1c
.RI "file \fBBimage_topo\&.cpp\fP"
.br
.RI "Functions to convert between 2D topology images to 3D surfaces\&. "
.ti -1c
.RI "file \fBBimage_transform\&.cpp\fP"
.br
.RI "Library routines for transforming images\&. "
.ti -1c
.RI "file \fBimg_combine\&.cpp\fP"
.br
.RI "Functions to combine two images in various ways\&. "
.in -1c
