.TH "/Users/bernard/b20/bsoft/src/rwmol Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwmol Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrwClustal\&.cpp\fP"
.br
.RI "Library routines to read and write Clustal sequence files\&. "
.ti -1c
.RI "file \fBrwEMBL\&.cpp\fP"
.br
.RI "Library routines to read and write EMBL sequence files\&. "
.ti -1c
.RI "file \fBrwFASTA\&.cpp\fP"
.br
.RI "Library routines to read and write FASTA sequence files\&. "
.ti -1c
.RI "file \fBrwGenBank\&.cpp\fP"
.br
.RI "Library routines to read and write GenBank sequence files\&. "
.ti -1c
.RI "file \fBrwGROMACS\&.cpp\fP"
.br
.RI "Library routines to read and write GROMACS coordinate files\&. "
.ti -1c
.RI "file \fBrwmol_star\&.cpp\fP"
.br
.RI "Library routines to read and write molecule files in STAR format\&. "
.ti -1c
.RI "file \fBrwmol_text\&.cpp\fP"
.br
.RI "Library routines to read and write molecule files in plain text\&. "
.ti -1c
.RI "file \fBrwmolecule\&.cpp\fP"
.br
.RI "Library routines to read and write molecule file, including sequences and coordinates\&. "
.ti -1c
.RI "file \fBrwPDB\&.cpp\fP"
.br
.RI "Library routines to read and write PDB coordinate files\&. "
.ti -1c
.RI "file \fBrwPhylip\&.cpp\fP"
.br
.RI "Library routines to read and write Phylip sequence files\&. "
.ti -1c
.RI "file \fBrwPIR\&.cpp\fP"
.br
.RI "Library routines to read and write PIR sequence files\&. "
.ti -1c
.RI "file \fBrwWAH\&.cpp\fP"
.br
.RI "Library routines to read and write Wayne Hendrickson coordinate files\&. "
.in -1c
