.TH "/Users/bernard/b20/bsoft/src/model Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/model Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmodel_color\&.cpp\fP"
.br
.RI "Functions to color models\&. "
.ti -1c
.RI "file \fBmodel_compare\&.cpp\fP"
.br
.RI "Functions to compare models and components\&. "
.ti -1c
.RI "file \fBmodel_create\&.cpp\fP"
.br
.RI "A tool to expand models\&. "
.ti -1c
.RI "file \fBmodel_extract_build\&.cpp\fP"
.br
.RI "Functions to extract subvolumes and build new maps\&. "
.ti -1c
.RI "file \fBmodel_links\&.cpp\fP"
.br
.RI "Library routines used for model links processing\&. "
.ti -1c
.RI "file \fBmodel_map\&.cpp\fP"
.br
.RI "Function to generate a map from a model\&. "
.ti -1c
.RI "file \fBmodel_mask\&.cpp\fP"
.br
.RI "Generating a mask from an atomic model\&. "
.ti -1c
.RI "file \fBmodel_mechanics\&.cpp\fP"
.br
.RI "Functions to do molecular mechanics\&. "
.ti -1c
.RI "file \fBmodel_multifit\&.cpp\fP"
.br
.RI "Searching for a template in a map and returning multiple hits in a model\&. "
.ti -1c
.RI "file \fBmodel_neighbors\&.cpp\fP"
.br
.RI "Functions to manipulate model component neighbors\&. "
.ti -1c
.RI "file \fBmodel_occupancy\&.cpp\fP"
.br
.RI "Library routines to count components in maps\&. "
.ti -1c
.RI "file \fBmodel_path\&.cpp\fP"
.br
.RI "Library routines used for model processing\&. "
.ti -1c
.RI "file \fBmodel_plane\&.cpp\fP"
.br
.RI "Library routines used for plane models\&. "
.ti -1c
.RI "file \fBmodel_poly\&.cpp\fP"
.br
.RI "Functions to manipulate polyhedral coordinate files\&. "
.ti -1c
.RI "file \fBmodel_poly_delta\&.cpp\fP"
.br
.RI "Functions to generate deltagraph polyhedra\&. "
.ti -1c
.RI "file \fBmodel_poly_spiral\&.cpp\fP"
.br
.RI "Functions to generate polyhedra using the spiral algorithm\&. "
.ti -1c
.RI "file \fBmodel_select\&.cpp\fP"
.br
.RI "Library routines used for model and component selection\&. "
.ti -1c
.RI "file \fBmodel_shell\&.cpp\fP"
.br
.RI "Library routines used for shell model processing\&. "
.ti -1c
.RI "file \fBmodel_symmetry\&.cpp\fP"
.br
.RI "Library routines used for model symmetry operations\&. "
.ti -1c
.RI "file \fBmodel_transform\&.cpp\fP"
.br
.RI "Library routines used for model transformation\&. "
.ti -1c
.RI "file \fBmodel_util\&.cpp\fP"
.br
.RI "Library routines used for model processing\&. "
.ti -1c
.RI "file \fBmodel_views\&.cpp\fP"
.br
.RI "Library routines used for analyzing the views of components in models\&. "
.in -1c
