.TH "/Users/bernard/b20/bsoft/src Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBimg\fP"
.br
.ti -1c
.RI "directory \fBmg\fP"
.br
.ti -1c
.RI "directory \fBmodel\fP"
.br
.ti -1c
.RI "directory \fBmol\fP"
.br
.ti -1c
.RI "directory \fBps\fP"
.br
.ti -1c
.RI "directory \fBrwimg\fP"
.br
.ti -1c
.RI "directory \fBrwmodel\fP"
.br
.ti -1c
.RI "directory \fBrwmol\fP"
.br
.ti -1c
.RI "directory \fBrwparam\fP"
.br
.ti -1c
.RI "directory \fButil\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBb3v\&.cpp\fP"
.br
.RI "Program to extract 3 orthogonal views from a map\&. "
.ti -1c
.RI "file \fBbadd\&.cpp\fP"
.br
.RI "Program to catenate image files\&. "
.ti -1c
.RI "file \fBbaddmask\&.cpp\fP"
.br
.RI "Program to catenate image files\&. "
.ti -1c
.RI "file \fBbafm\&.cpp\fP"
.br
.RI "Simulation of AFM experiments\&. "
.ti -1c
.RI "file \fBbalign\&.cpp\fP"
.br
.RI "Aligns two images\&. "
.ti -1c
.RI "file \fBbalpha\&.cpp\fP"
.br
.RI "Program to make and analyze alpha helices\&. "
.ti -1c
.RI "file \fBbampweigh\&.cpp\fP"
.br
.RI "Program to filter images\&. "
.ti -1c
.RI "file \fBbar\&.cpp\fP"
.br
.RI "Program to do simple arithmetic on images\&. "
.ti -1c
.RI "file \fBbass\&.cpp\fP"
.br
.RI "Program to assemble molecular components\&. "
.ti -1c
.RI "file \fBbbackproj\&.cpp\fP"
.br
.RI "3D reconstruction by backprojection "
.ti -1c
.RI "file \fBbbif\&.cpp\fP"
.br
.RI "Program to denoise images by bilateral filtering\&. "
.ti -1c
.RI "file \fBbbild\&.cpp\fP"
.br
.RI "Generates BILD output from a model\&. "
.ti -1c
.RI "file \fBbcat\&.cpp\fP"
.br
.RI "Program to catenate image files\&. "
.ti -1c
.RI "file \fBbcatmol\&.cpp\fP"
.br
.RI "A program to concatenate coordinates from different files\&. "
.ti -1c
.RI "file \fBbcatseq\&.cpp\fP"
.br
.RI "A program to concatenate protein sequences from different files\&. "
.ti -1c
.RI "file \fBbcc\&.cpp\fP"
.br
.RI "Program for calculating cross-correlations\&. "
.ti -1c
.RI "file \fBbclass\&.cpp\fP"
.br
.RI "Classifies raw single particle images with respect to multiple models\&. "
.ti -1c
.RI "file \fBbcolour\&.cpp\fP"
.br
.RI "Program to generate nice colour images\&. "
.ti -1c
.RI "file \fBbcomplex\&.cpp\fP"
.br
.RI "Program for handing complex images\&. "
.ti -1c
.RI "file \fBbconvert\&.cpp\fP"
.br
.RI "Program to catenate image files\&. "
.ti -1c
.RI "file \fBbcormut\&.cpp\fP"
.br
.RI "A program to analyze protein sequences for correlated mutations\&. "
.ti -1c
.RI "file \fBbcrystal\&.cpp\fP"
.br
.RI "Calculates coordinates for multiple unit cells\&. "
.ti -1c
.RI "file \fBbctf\&.cpp\fP"
.br
.RI "A program to determine and correct for the CTF (contrast transfer function) in electron micrographs\&. "
.ti -1c
.RI "file \fBbcyl\&.cpp\fP"
.br
.RI "Program to manipulate cylindrical images\&. "
.ti -1c
.RI "file \fBbdelta\&.cpp\fP"
.br
.RI "Generating a deltagraph with minimal input parameters\&. "
.ti -1c
.RI "file \fBbdens\&.cpp\fP"
.br
.RI "Program to calculate density in selected regions of a map\&. "
.ti -1c
.RI "file \fBbdif\&.cpp\fP"
.br
.RI "Analyze diffraction patterns\&. "
.ti -1c
.RI "file \fBbdual\&.cpp\fP"
.br
.RI "Program to handle dual tomographic tilt series\&. "
.ti -1c
.RI "file \fBbedge\&.cpp\fP"
.br
.RI "A program to float an image in a uniform background\&. "
.ti -1c
.RI "file \fBbeditimg\&.cpp\fP"
.br
.RI "Segment images into density regions\&. "
.ti -1c
.RI "file \fBbfcc\&.cpp\fP"
.br
.RI "Fast cross-correlation search for the best fit of a 3D map to a template\&. "
.ti -1c
.RI "file \fBbfft\&.cpp\fP"
.br
.RI "General FFT for n-dimensional data\&. "
.ti -1c
.RI "file \fBbfil\&.cpp\fP"
.br
.RI "Extract filaments from a micrograph as straightened filaments or boxed particles\&. "
.ti -1c
.RI "file \fBbfile\&.cpp\fP"
.br
.RI "Program to read file contents directly and poke single values\&. "
.ti -1c
.RI "file \fBbfilter\&.cpp\fP"
.br
.RI "Program to filter images\&. "
.ti -1c
.RI "file \fBbfilwidth\&.cpp\fP"
.br
.RI "Program to calculate moving average images\&. "
.ti -1c
.RI "file \fBbfind\&.cpp\fP"
.br
.RI "Searches orientation space for the best fit of a 3D map to a template\&. "
.ti -1c
.RI "file \fBbfix\&.cpp\fP"
.br
.RI "Program to fix end-of-line characters in ascii files\&. "
.ti -1c
.RI "file \fBbflat\&.cpp\fP"
.br
.RI "Solvent flattening\&. "
.ti -1c
.RI "file \fBbflood\&.cpp\fP"
.br
.RI "Segment images into density regions\&. "
.ti -1c
.RI "file \fBbftr\&.cpp\fP"
.br
.RI "Program for resizing an image using Fourier transformation\&. "
.ti -1c
.RI "file \fBbgex\&.cpp\fP"
.br
.RI "Calculating and comparing atomic models and maps\&. "
.ti -1c
.RI "file \fBbgradient\&.cpp\fP"
.br
.RI "Calculating image gradients\&. "
.ti -1c
.RI "file \fBbgraphseg\&.cpp\fP"
.br
.RI "Segment images into density regions using a nondirected graph\&. "
.ti -1c
.RI "file \fBbhead\&.cpp\fP"
.br
.RI "Program to modify image parameters in the header\&. "
.ti -1c
.RI "file \fBbheight\&.cpp\fP"
.br
.RI "Projecting a 3D map and calculating comparison statistics of the projections\&. "
.ti -1c
.RI "file \fBbhelcross\&.cpp\fP"
.br
.RI "Dealing with images with helical symmetry\&. "
.ti -1c
.RI "file \fBbhelix\&.cpp\fP"
.br
.RI "Dealing with images with helical symmetry\&. "
.ti -1c
.RI "file \fBbhisto\&.cpp\fP"
.br
.RI "Image histograms\&. "
.ti -1c
.RI "file \fBbico\&.cpp\fP"
.br
.RI "Program to analyze icosahedral subtomograms\&. "
.ti -1c
.RI "file \fBbimg\&.cpp\fP"
.br
.RI "General image processing program\&. "
.ti -1c
.RI "file \fBbimport\&.cpp\fP"
.br
.RI "Generate parameter files from a cisTEM hierarchy\&. "
.ti -1c
.RI "file \fBbint\&.cpp\fP"
.br
.RI "Interpolation of 2D and 3D images\&. "
.ti -1c
.RI "file \fBbkernel\&.cpp\fP"
.br
.RI "Program to calculate filter kernels\&. "
.ti -1c
.RI "file \fBblocfilt\&.cpp\fP"
.br
.RI "Local resolution analysis\&. "
.ti -1c
.RI "file \fBblocres\&.cpp\fP"
.br
.RI "Local resolution analysis\&. "
.ti -1c
.RI "file \fBbmapdist\&.cpp\fP"
.br
.RI "Calculates a distance criterion between a set of 2D images or 3D maps\&. "
.ti -1c
.RI "file \fBbmark\&.cpp\fP"
.br
.RI "Program to generate symmetry axes for mark group symmetries\&. "
.ti -1c
.RI "file \fBbmask\&.cpp\fP"
.br
.RI "Generating and manipulating masks\&. "
.ti -1c
.RI "file \fBbmatch\&.cpp\fP"
.br
.RI "Program to search an image with multiple projections and orient them\&. "
.ti -1c
.RI "file \fBbmatrix\&.cpp\fP"
.br
.RI "Program to process matrices\&. "
.ti -1c
.RI "file \fBbmaxpow\&.cpp\fP"
.br
.RI "Determining orientations by maximum power of 3D reconstruction from single particle images\&. "
.ti -1c
.RI "file \fBbmd\&.cpp\fP"
.br
.RI "Molecular dynamics - humble beginnings\&. "
.ti -1c
.RI "file \fBbmedian\&.cpp\fP"
.br
.RI "Program to filter images\&. "
.ti -1c
.RI "file \fBbmg\&.cpp\fP"
.br
.RI "Manipulating project and micrograph structures\&. "
.ti -1c
.RI "file \fBbmg2imod\&.cpp\fP"
.br
.RI "Converts between \fBIMOD\fP files and a micrograph parameter file\&. "
.ti -1c
.RI "file \fBbmgalign\&.cpp\fP"
.br
.RI "Aligns micrographs specified in parameter files\&. "
.ti -1c
.RI "file \fBbmgconvert\&.cpp\fP"
.br
.RI "Convert between micrograph parameter formats\&. "
.ti -1c
.RI "file \fBbmgft\&.cpp\fP"
.br
.RI "Disk-based 3D reconstruction for a tomography series\&. "
.ti -1c
.RI "file \fBbmgtransfer\&.cpp\fP"
.br
.RI "Transfer pieces of information between micrograph paramater files\&. "
.ti -1c
.RI "file \fBbmissing\&.cpp\fP"
.br
.RI "Generating and manipulating masks\&. "
.ti -1c
.RI "file \fBbmm\&.cpp\fP"
.br
.RI "A program to do model mechanics\&. "
.ti -1c
.RI "file \fBbmod2part\&.cpp\fP"
.br
.RI "Converting from a pseudo-atomic model to particle parameters\&. "
.ti -1c
.RI "file \fBbmodcol\&.cpp\fP"
.br
.RI "A tool to color models\&. "
.ti -1c
.RI "file \fBbmodcomp\&.cpp\fP"
.br
.RI "A tool to compare polyhedra\&. "
.ti -1c
.RI "file \fBbmodedit\&.cpp\fP"
.br
.RI "A tool to create and edit models\&. "
.ti -1c
.RI "file \fBbmodel\&.cpp\fP"
.br
.RI "Manipulates models\&. "
.ti -1c
.RI "file \fBbmodmap\&.cpp\fP"
.br
.RI "A tool to genrate a map from a model\&. "
.ti -1c
.RI "file \fBbmodmask\&.cpp\fP"
.br
.RI "Generating a mask from an atomic model\&. "
.ti -1c
.RI "file \fBbmodsel\&.cpp\fP"
.br
.RI "Manipulates selections from sets of components as solutions of fits\&. "
.ti -1c
.RI "file \fBbmodsym\&.cpp\fP"
.br
.RI "Deals with model and component symmetries\&. "
.ti -1c
.RI "file \fBbmodview\&.cpp\fP"
.br
.RI "Manipulates models\&. "
.ti -1c
.RI "file \fBbmol\&.cpp\fP"
.br
.RI "A tool to edit and analyze coordinate files\&. "
.ti -1c
.RI "file \fBbmoledit\&.cpp\fP"
.br
.RI "A tool to edit coordinate files\&. "
.ti -1c
.RI "file \fBbmolhel\&.cpp\fP"
.br
.RI "A program to perform helical symmetry operations on coordinate files\&. "
.ti -1c
.RI "file \fBbmolsym\&.cpp\fP"
.br
.RI "A tool to perform symmetry operations on coordinate files\&. "
.ti -1c
.RI "file \fBbmontage\&.cpp\fP"
.br
.RI "A program to generate a montage from a 3D image or a set of 2D images\&. "
.ti -1c
.RI "file \fBbmonte\&.cpp\fP"
.br
.RI "Program to use a monte carlo metroplis algorithm to energy minimize molecular positions\&. "
.ti -1c
.RI "file \fBbmultifit\&.cpp\fP"
.br
.RI "Searching for a template in a map and returning multiple hits in a model\&. "
.ti -1c
.RI "file \fBbmultimask\&.cpp\fP"
.br
.RI "Generating and manipulating composite masks\&. "
.ti -1c
.RI "file \fBbmultislice\&.cpp\fP"
.br
.RI "Multi-slice simulation of the electron imaging process\&. "
.ti -1c
.RI "file \fBbnad\&.cpp\fP"
.br
.RI "Image denoising by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&. "
.ti -1c
.RI "file \fBbnorm\&.cpp\fP"
.br
.RI "Program to normalize a set of images based on their histograms\&. "
.ti -1c
.RI "file \fBbop\&.cpp\fP"
.br
.RI "A program to operate on image pairs\&. "
.ti -1c
.RI "file \fBborient\&.cpp\fP"
.br
.RI "Determines orientation angles and x,y origins of single particle images\&. "
.ti -1c
.RI "file \fBbparam\&.cpp\fP"
.br
.RI "A tool to extract parameters from coordinate files\&. "
.ti -1c
.RI "file \fBbpart\&.cpp\fP"
.br
.RI "Calculates centers of single particle images\&. "
.ti -1c
.RI "file \fBbpartmulti\&.cpp\fP"
.br
.RI "Selection of single particle parameters from multiple files for classification\&. "
.ti -1c
.RI "file \fBbpartsel\&.cpp\fP"
.br
.RI "Selection of single particles for 3D reconstruction\&. "
.ti -1c
.RI "file \fBbpatch\&.cpp\fP"
.br
.RI "Program to patch tiled image files\&. "
.ti -1c
.RI "file \fBbpath\&.cpp\fP"
.br
.RI "A program to analyze paths and cycles in a model\&. "
.ti -1c
.RI "file \fBbphase\&.cpp\fP"
.br
.RI "A program to examine phase differences between image pairs\&. "
.ti -1c
.RI "file \fBbpick\&.cpp\fP"
.br
.RI "Pick particles in a micrograph given the particle coordinates, or pick particles in a focal series of micrographs with alignment of the micrographs\&. "
.ti -1c
.RI "file \fBbplane\&.cpp\fP"
.br
.RI "A tool to expand models\&. "
.ti -1c
.RI "file \fBbpoly\&.cpp\fP"
.br
.RI "A tool to manipulate polyhedral coordinate files\&. "
.ti -1c
.RI "file \fBbproject\&.cpp\fP"
.br
.RI "Projecting a 3D map and calculating comparison statistics of the projections\&. "
.ti -1c
.RI "file \fBbradial\&.cpp\fP"
.br
.RI "Polar images and radial averages\&. "
.ti -1c
.RI "file \fBbradsec\&.cpp\fP"
.br
.RI "Generates radial sections from 3D images\&. "
.ti -1c
.RI "file \fBbrandom\&.cpp\fP"
.br
.RI "Program to generate random images\&. "
.ti -1c
.RI "file \fBbrecadd\&.cpp\fP"
.br
.RI "Program to average selected reconstructions\&. "
.ti -1c
.RI "file \fBbrecmod\&.cpp\fP"
.br
.RI "A tool to merge data from micrograph reconstruction and model files\&. "
.ti -1c
.RI "file \fBbreconstruct\&.cpp\fP"
.br
.RI "3D reconstruction from single particle images "
.ti -1c
.RI "file \fBbrefine\&.cpp\fP"
.br
.RI "Reciprocal space refinement of orientation parameters of particle images\&. "
.ti -1c
.RI "file \fBbresolve\&.cpp\fP"
.br
.RI "Calculate resolution estimates and Fourier shell statistics\&. "
.ti -1c
.RI "file \fBbscale\&.cpp\fP"
.br
.RI "Program to find the scaling of map with respect to a reference\&. "
.ti -1c
.RI "file \fBbscatter\&.cpp\fP"
.br
.RI "Program to calculate scattering cross sections\&. "
.ti -1c
.RI "file \fBbsegment\&.cpp\fP"
.br
.RI "Segment images into density regions\&. "
.ti -1c
.RI "file \fBbseq\&.cpp\fP"
.br
.RI "A program to manipulate DNA and protein sequences\&. "
.ti -1c
.RI "file \fBbseqaln\&.cpp\fP"
.br
.RI "A program to analyze aligned protein sequences\&. "
.ti -1c
.RI "file \fBbseries\&.cpp\fP"
.br
.RI "Program to align and analyze series of images\&. "
.ti -1c
.RI "file \fBbsf\&.cpp\fP"
.br
.RI "Calculating structure factors from atomic models\&. "
.ti -1c
.RI "file \fBbshell\&.cpp\fP"
.br
.RI "Generates a shell point component model\&. "
.ti -1c
.RI "file \fBbsim\&.cpp\fP"
.br
.RI "A tool to generate a project with random orientations for a molecule and to simulate TEM images from given orientations\&. "
.ti -1c
.RI "file \fBbspiral\&.cpp\fP"
.br
.RI "A tool to generate polyhedra using the spiral algorithm\&. "
.ti -1c
.RI "file \fBbsplit\&.cpp\fP"
.br
.RI "Program to seperate a multi-image file into individual image files\&. "
.ti -1c
.RI "file \fBbsplitmol\&.cpp\fP"
.br
.RI "A program to concatenate coordinates from different files\&. "
.ti -1c
.RI "file \fBbspr\&.cpp\fP"
.br
.RI "3D reconstruction from single particle images "
.ti -1c
.RI "file \fBbstar\&.cpp\fP"
.br
.RI "Examines STAR format files\&. "
.ti -1c
.RI "file \fBbsupix\&.cpp\fP"
.br
.RI "Segment images\&. "
.ti -1c
.RI "file \fBbsurf\&.cpp\fP"
.br
.RI "AFM image analysis and reconstruction\&. "
.ti -1c
.RI "file \fBbsym\&.cpp\fP"
.br
.RI "Program to generate symmetry axes for point group symmetries\&. "
.ti -1c
.RI "file \fBbsymcomp\&.cpp\fP"
.br
.RI "Finds the best orientation that fits a symmetrized template\&. "
.ti -1c
.RI "file \fBbtile\&.cpp\fP"
.br
.RI "Program to split an image into overlapping tiles\&. "
.ti -1c
.RI "file \fBbtomaln\&.cpp\fP"
.br
.RI "Program to do fiducialless alignment of a tilt series\&. "
.ti -1c
.RI "file \fBbtomo\&.cpp\fP"
.br
.RI "Program to process tomographic series of images\&. "
.ti -1c
.RI "file \fBbtompart\&.cpp\fP"
.br
.RI "Program to extract single particle images from a tilt series and generate individual reconstructions\&. "
.ti -1c
.RI "file \fBbtomrec\&.cpp\fP"
.br
.RI "Disk-based 3D reconstruction for a tomography series\&. "
.ti -1c
.RI "file \fBbtomres\&.cpp\fP"
.br
.RI "Program to determine the resolution of a tilt series\&. "
.ti -1c
.RI "file \fBbtrack\&.cpp\fP"
.br
.RI "Program to track fiducial markers in a tomographic series of images\&. "
.ti -1c
.RI "file \fBbtree\&.cpp\fP"
.br
.RI "Program to process trees\&. "
.ti -1c
.RI "file \fBbtube\&.cpp\fP"
.br
.RI "Symmetrizes helical tubes with hexagonal lattices\&. "
.ti -1c
.RI "file \fBbwater\&.cpp\fP"
.br
.RI "Molecular dynamics - humble beginnings\&. "
.ti -1c
.RI "file \fBbxb\&.cpp\fP"
.br
.RI "Extracting a part of a density map and building a new map\&. "
.ti -1c
.RI "file \fBbxml\&.cpp\fP"
.br
.RI "Reads, writes and validates XML files\&. "
.ti -1c
.RI "file \fBbzfft\&.cpp\fP"
.br
.RI "Disk-based z-line transforms for big reconstructions\&. "
.ti -1c
.RI "file \fBdcount\&.cpp\fP"
.br
.RI "A program to determine the occupancy of components in models\&. "
.ti -1c
.RI "file \fBdhand\&.cpp\fP"
.br
.RI "Compare projections of two oppositely handed reconstructions to images of tilted specimens\&. "
.ti -1c
.RI "file \fBdimgstats\&.cpp\fP"
.br
.RI "Calculates statistical measures within a set of images or between sets of images\&. "
.ti -1c
.RI "file \fBdmerge\&.cpp\fP"
.br
.RI "Merge images in a defocal or other series, align images before adding together\&. "
.ti -1c
.RI "file \fBemgrand\&.cpp\fP"
.br
.RI "Generate random values for micrograph parameters\&. "
.ti -1c
.RI "file \fBjave\&.cpp\fP"
.br
.RI "Program to average files and weigh the average in Real/Fourier space\&. "
.ti -1c
.RI "file \fBjpartdif\&.cpp\fP"
.br
.RI "Analysis of particle differences between two starfiles\&. "
.ti -1c
.RI "file \fBjsubtomo\&.cpp\fP"
.br
.RI "Finds particles (subtomograms) in a tomographic reconstruction and refines their origins and orientations\&. "
.ti -1c
.RI "file \fBjviews\&.cpp\fP"
.br
.RI "Generates views covering an asymmetric unit or all symmetry related views\&. "
.ti -1c
.RI "file \fBradon\&.cpp\fP"
.br
.RI "Program to do radon transforms\&. "
.ti -1c
.RI "file \fBradonrecon\&.cpp\fP"
.br
.RI "Program to do radon transforms\&. "
.in -1c
