.TH "/Users/bernard/b20/bsoft/src/rwimg Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrwASCII\&.cpp\fP"
.br
.RI "Functions for reading and writing ASCII files\&. "
.ti -1c
.RI "file \fBrwBCR\&.cpp\fP"
.br
.RI "Functions for reading and writing AFM BCR-STM files\&. "
.ti -1c
.RI "file \fBrwBIORAD\&.cpp\fP"
.br
.RI "Functions for reading and writing BioRad confocal files\&. "
.ti -1c
.RI "file \fBrwBRIX\&.cpp\fP"
.br
.RI "Functions for reading and writing BRIX files\&. "
.ti -1c
.RI "file \fBrwBrookhavenSTEM\&.cpp\fP"
.br
.RI "Functions for reading and writing Brookhaven STEM files\&. "
.ti -1c
.RI "file \fBrwCCP4\&.cpp\fP"
.br
.RI "Functions for reading and writing CCP4 files\&. "
.ti -1c
.RI "file \fBrwDI\&.cpp\fP"
.br
.RI "Functions for reading (only) Digital Instruments files\&. "
.ti -1c
.RI "file \fBrwDM\&.cpp\fP"
.br
.RI "Functions for reading and writing Digital Micrograph files\&. "
.ti -1c
.RI "file \fBrwDSN6\&.cpp\fP"
.br
.RI "Functions for reading and writing DSN6 files\&. "
.ti -1c
.RI "file \fBrwDX\&.cpp\fP"
.br
.RI "Functions for reading and writing OpenDX files\&. "
.ti -1c
.RI "file \fBrwEER\&.cpp\fP"
.br
.RI "Reading EER files\&. "
.ti -1c
.RI "file \fBrwEM\&.cpp\fP"
.br
.RI "Functions for reading and writing EM files\&. "
.ti -1c
.RI "file \fBrwGOODFORD\&.cpp\fP"
.br
.RI "Functions for reading and writing Peter Goodford's GRID files\&. "
.ti -1c
.RI "file \fBrwGRD\&.cpp\fP"
.br
.RI "Functions for reading and writing GRD files\&. "
.ti -1c
.RI "file \fBrwHKL\&.cpp\fP"
.br
.RI "Routines to read and write HKL reflection files\&. "
.ti -1c
.RI "file \fBrwIMAGIC\&.cpp\fP"
.br
.RI "Functions for reading and writing Image Science's Imagic files\&. "
.ti -1c
.RI "file \fBrwimg\&.cpp\fP"
.br
.RI "Library for 2D and 3D image I/O\&. "
.ti -1c
.RI "file \fBrwIP\&.cpp\fP"
.br
.RI "Functions for reading and writing image plate reader files\&. "
.ti -1c
.RI "file \fBrwJPEG\&.cpp\fP"
.br
.RI "Functions for reading and writing JPEG files\&. "
.ti -1c
.RI "file \fBrwkernel\&.cpp\fP"
.br
.RI "Library routines to read and write kernel files\&. "
.ti -1c
.RI "file \fBrwMFF\&.cpp\fP"
.br
.RI "Functions for reading and writing What If MFF files\&. "
.ti -1c
.RI "file \fBrwMIFF\&.cpp\fP"
.br
.RI "Functions for reading and writing ImageMagick MIFF files\&. "
.ti -1c
.RI "file \fBrwMRC\&.cpp\fP"
.br
.RI "Functions for reading and writing MRC files\&. "
.ti -1c
.RI "file \fBrwND2\&.cpp\fP"
.br
.RI "Functions for reading Nikon ND2 files\&. "
.ti -1c
.RI "file \fBrwPIC\&.cpp\fP"
.br
.RI "Functions for reading and writing PIC BP and BQ files\&. "
.ti -1c
.RI "file \fBrwPIF\&.cpp\fP"
.br
.RI "Functions for reading and writing PIF files\&. "
.ti -1c
.RI "file \fBrwPNG\&.cpp\fP"
.br
.RI "Functions for reading and writing PNG files\&. "
.ti -1c
.RI "file \fBrwPNM\&.cpp\fP"
.br
.RI "Functions for reading and writing PBM, PGM and PPM files\&. "
.ti -1c
.RI "file \fBrwPostScript\&.cpp\fP"
.br
.RI "Functions for (reading and) writing postscript image files\&. "
.ti -1c
.RI "file \fBrwRAW\&.cpp\fP"
.br
.RI "Functions for reading and writing RAW files\&. "
.ti -1c
.RI "file \fBrwSER\&.cpp\fP"
.br
.RI "Reading FEI SER files\&. "
.ti -1c
.RI "file \fBrwSitus\&.cpp\fP"
.br
.RI "Functions for reading and writing Situs files\&. "
.ti -1c
.RI "file \fBrwSPE\&.cpp\fP"
.br
.RI "Functions for reading and writing SPE CCD files\&. "
.ti -1c
.RI "file \fBrwSPIDER\&.cpp\fP"
.br
.RI "Functions for reading and writing SPIDER files\&. "
.ti -1c
.RI "file \fBrwSUPRIM\&.cpp\fP"
.br
.RI "Functions for reading and writing SUPRIM files\&. "
.ti -1c
.RI "file \fBrwTGA\&.cpp\fP"
.br
.RI "Functions for reading and writing Truevision TGA files\&. "
.ti -1c
.RI "file \fBrwTIFF\&.cpp\fP"
.br
.RI "Functions for reading and writing TIFF files\&. "
.ti -1c
.RI "file \fBrwXPLOR\&.cpp\fP"
.br
.RI "Routines to read and write XPLOR reflection files\&. "
.in -1c
