.TH "/Users/bernard/b20/bsoft/include Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBgraphseg\&.h\fP"
.br
.RI "Graph segmentation classes\&. "
.ti -1c
.RI "file \fBBimage\&.h\fP"
.br
.RI "Header file for image class\&. "
.ti -1c
.RI "file \fBbinomial\&.h\fP"
.br
.RI "Functions to generate and fit binomials\&. "
.ti -1c
.RI "file \fBBplot\&.h\fP"
.br
.RI "Header file for postscript output functions\&. "
.ti -1c
.RI "file \fBBstring\&.h\fP"
.br
.RI "Header file for the string class\&. "
.ti -1c
.RI "file \fBBsuperpixel\&.h\fP"
.br
.RI "Super pixel segmentation\&. "
.ti -1c
.RI "file \fBcluster\&.h\fP"
.br
.RI "Header file for clustering functions\&. "
.ti -1c
.RI "file \fBColor\&.h\fP"
.br
.RI "Classes for color objects\&. "
.ti -1c
.RI "file \fBComplex\&.h\fP"
.br
.RI "Class for complex numbers\&. "
.ti -1c
.RI "file \fBctf\&.h\fP"
.br
.RI "Header file for CTF (contrast transfer function) functions\&. "
.ti -1c
.RI "file \fBctf\&.inc\fP"
.br
.ti -1c
.RI "file \fBdose\&.inc\fP"
.br
.ti -1c
.RI "file \fBdynamic_programming\&.h\fP"
.br
.RI "Library functions for dynamic programming\&. "
.ti -1c
.RI "file \fBEuler\&.h\fP"
.br
.RI "\fBEuler\fP object\&. "
.ti -1c
.RI "file \fBfft\&.h\fP"
.br
.RI "General FFT for n-dimensional data\&. "
.ti -1c
.RI "file \fBfile_util\&.h\fP"
.br
.RI "Header file for file checking functions\&. "
.ti -1c
.RI "file \fBFSI_Kernel\&.h\fP"
.br
.RI "Header file for frequency space interpolation kernel\&. "
.ti -1c
.RI "file \fBimg_combine\&.h\fP"
.br
.RI "Header file for combining two images in various ways\&. "
.ti -1c
.RI "file \fBjson\&.h\fP"
.br
.ti -1c
.RI "file \fBlinked_list\&.h\fP"
.br
.RI "Header file for generalized linked list functions\&. "
.ti -1c
.RI "file \fBmarker\&.h\fP"
.br
.RI "Header file for image parameter functions\&. "
.ti -1c
.RI "file \fBmath_util\&.h\fP"
.br
.RI "Header file for general utilities\&. "
.ti -1c
.RI "file \fBMatrix\&.h\fP"
.br
.RI "Generalized matrix class\&. "
.ti -1c
.RI "file \fBMatrix3\&.h\fP"
.br
.RI "3x3 \fBMatrix\fP manipulation functions "
.ti -1c
.RI "file \fBmatrix_linear\&.h\fP"
.br
.RI "Header file for matrix functions\&. "
.ti -1c
.RI "file \fBmatrix_util\&.h\fP"
.br
.RI "Utility functions for matrices\&. "
.ti -1c
.RI "file \fBmdoc\&.h\fP"
.br
.ti -1c
.RI "file \fBmg_align\&.h\fP"
.br
.RI "Header file for functions to align micrographs or coordinates from micrographs and apply the resultant transformation\&. "
.ti -1c
.RI "file \fBmg_class\&.h\fP"
.br
.RI "Header file for classification of raw single particle images with respect to multiple models\&. "
.ti -1c
.RI "file \fBmg_ctf\&.h\fP"
.br
.RI "Functions for CTF (contrast transfer function) processing\&. "
.ti -1c
.RI "file \fBmg_ctf_fit\&.h\fP"
.br
.RI "Header file for CTF (contrast transfer function) functions\&. "
.ti -1c
.RI "file \fBmg_ctf_sim\&.h\fP"
.br
.RI "Header file for functions to simulate tilted micrographs\&. "
.ti -1c
.RI "file \fBmg_extract\&.h\fP"
.br
.RI "Header file for functions to extract particles from micrographs\&. "
.ti -1c
.RI "file \fBmg_hand\&.h\fP"
.br
.RI "Author: David Belnap\&. "
.ti -1c
.RI "file \fBmg_helix\&.h\fP"
.br
.RI "Header file for functions to process helical data\&. "
.ti -1c
.RI "file \fBmg_img_proc\&.h\fP"
.br
.RI "Header file for image processing from micrograph structures\&. "
.ti -1c
.RI "file \fBmg_marker\&.h\fP"
.br
.RI "Header file for micrograph marker functions\&. "
.ti -1c
.RI "file \fBmg_merge\&.h\fP"
.br
.RI "Header file for functions to merge images\&. "
.ti -1c
.RI "file \fBmg_multiple\&.h\fP"
.br
.RI "Selection of single particle parameters from multiple files for classification\&. "
.ti -1c
.RI "file \fBmg_multislice\&.h\fP"
.br
.RI "Generates and manipulates projects for multislice calculations\&. "
.ti -1c
.RI "file \fBmg_orient\&.h\fP"
.br
.RI "Library routines for single particle analysis\&. "
.ti -1c
.RI "file \fBmg_particle_select\&.h\fP"
.br
.RI "Select particles\&. "
.ti -1c
.RI "file \fBmg_particles\&.h\fP"
.br
.RI "Manipulates single particle images\&. "
.ti -1c
.RI "file \fBmg_pick\&.h\fP"
.br
.RI "Header file for single particle picking functions\&. "
.ti -1c
.RI "file \fBmg_processing\&.h\fP"
.br
.RI "Header file for micrograph processing\&. "
.ti -1c
.RI "file \fBmg_random\&.h\fP"
.br
.RI "Header file for applying some randomization to parameters\&. "
.ti -1c
.RI "file \fBmg_reconstruct\&.h\fP"
.br
.RI "Functions for reconstruction\&. "
.ti -1c
.RI "file \fBmg_refine\&.h\fP"
.br
.RI "Reciprocal space refinement of orientation parameters of particle images\&. "
.ti -1c
.RI "file \fBmg_select\&.h\fP"
.br
.RI "Header file for micrograph processing\&. "
.ti -1c
.RI "file \fBmg_subtomo\&.h\fP"
.br
.RI "Header file for functions finding particles (subtomograms) in a tomogram\&. "
.ti -1c
.RI "file \fBmg_tags\&.h\fP"
.br
.RI "All STAR and XML file format tags for micrographs and reconstructions\&. "
.ti -1c
.RI "file \fBmg_tomo_rec\&.h\fP"
.br
.RI "Functions to do a tomographic reconstruction\&. "
.ti -1c
.RI "file \fBmg_tomo_resol\&.h\fP"
.br
.RI "Functions to assess the resoltion of a tomographic tilt series\&. "
.ti -1c
.RI "file \fBmg_tomo_track\&.h\fP"
.br
.RI "Functions to track fiducial markers in a tomographic series of images\&. "
.ti -1c
.RI "file \fBmg_tomography\&.h\fP"
.br
.RI "Header file for single particle image processing in Bsoft\&. "
.ti -1c
.RI "file \fBmg_xtal\&.h\fP"
.br
.RI "Header file for functions to process crystallographic data\&. "
.ti -1c
.RI "file \fBmodel_color\&.h\fP"
.br
.RI "Functions to color models\&. "
.ti -1c
.RI "file \fBmodel_compare\&.h\fP"
.br
.RI "Functions to compare models and components\&. "
.ti -1c
.RI "file \fBmodel_create\&.h\fP"
.br
.RI "Library routines used for model creation\&. "
.ti -1c
.RI "file \fBmodel_extract_build\&.h\fP"
.br
.RI "Functions to extract subvolumes and build new maps\&. "
.ti -1c
.RI "file \fBmodel_links\&.h\fP"
.br
.RI "Library routines used for model link processing\&. "
.ti -1c
.RI "file \fBmodel_map\&.h\fP"
.br
.RI "Header file for model to map conversions\&. "
.ti -1c
.RI "file \fBmodel_mask\&.h\fP"
.br
.RI "Functions to generate masks from models\&. "
.ti -1c
.RI "file \fBmodel_mechanics\&.h\fP"
.br
.RI "Functions to do molecular mechanics\&. "
.ti -1c
.RI "file \fBmodel_multifit\&.h\fP"
.br
.RI "Header file for searching for a template in a map and returning multiple hits in a model\&. "
.ti -1c
.RI "file \fBmodel_neighbors\&.h\fP"
.br
.RI "Functions to manipulate model component neighbors\&. "
.ti -1c
.RI "file \fBmodel_occupancy\&.h\fP"
.br
.RI "Library routines to count components in maps\&. "
.ti -1c
.RI "file \fBmodel_path\&.h\fP"
.br
.RI "Library routines used for model processing\&. "
.ti -1c
.RI "file \fBmodel_plane\&.h\fP"
.br
.RI "Library routines used for plane models\&. "
.ti -1c
.RI "file \fBmodel_poly\&.h\fP"
.br
.RI "Functions to manipulate polyhedral coordinate files\&. "
.ti -1c
.RI "file \fBmodel_poly_delta\&.h\fP"
.br
.RI "Functions to generate deltagraph polyhedra\&. "
.ti -1c
.RI "file \fBmodel_poly_spiral\&.h\fP"
.br
.RI "Functions to generate polyhedra using the spiral algorithm\&. "
.ti -1c
.RI "file \fBmodel_select\&.h\fP"
.br
.RI "Header file for reading and writing atomic model files\&. "
.ti -1c
.RI "file \fBmodel_shell\&.h\fP"
.br
.RI "Library routines used for shell model processing\&. "
.ti -1c
.RI "file \fBmodel_symmetry\&.h\fP"
.br
.RI "Library routines used for model symmetry operations\&. "
.ti -1c
.RI "file \fBmodel_tags\&.h\fP"
.br
.RI "All STAR and XML file format tags for models\&. "
.ti -1c
.RI "file \fBmodel_transform\&.h\fP"
.br
.RI "Library routines used for model transformation\&. "
.ti -1c
.RI "file \fBmodel_util\&.h\fP"
.br
.RI "Library routines used for model processing\&. "
.ti -1c
.RI "file \fBmodel_views\&.h\fP"
.br
.RI "Library routines used for analysing model component views\&. "
.ti -1c
.RI "file \fBmol_alpha\&.h\fP"
.br
.RI "Header for functions to make and analyze alpha helices\&. "
.ti -1c
.RI "file \fBmol_bonds\&.h\fP"
.br
.RI "Header for molecular dynamics\&. "
.ti -1c
.RI "file \fBmol_compare\&.h\fP"
.br
.RI "Library routines used to compare sets of atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_edit\&.h\fP"
.br
.RI "Library routines used for atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_map_energy\&.h\fP"
.br
.RI "Headers of functions to calculate estimates of the fitting of molecules to maps\&. "
.ti -1c
.RI "file \fBmol_md\&.h\fP"
.br
.RI "Header for molecular dynamics\&. "
.ti -1c
.RI "file \fBmol_monte\&.h\fP"
.br
.RI "Headers of functions using a monte carlo metroplis algorithm to energy minimize molecular positions\&. "
.ti -1c
.RI "file \fBmol_param\&.h\fP"
.br
.RI "Header for functions to extract parameters from coordinate files\&. "
.ti -1c
.RI "file \fBmol_select\&.h\fP"
.br
.RI "Library routines to select atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_symmetry\&.h\fP"
.br
.RI "Library routines used for symmetry operations on atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_tags\&.h\fP"
.br
.RI "All STAR file format tags for molecules and molecular parameters\&. "
.ti -1c
.RI "file \fBmol_transform\&.h\fP"
.br
.RI "Library routines used for atomic coordinate transformations\&. "
.ti -1c
.RI "file \fBmol_util\&.h\fP"
.br
.RI "Library routines used for atomic coordinates\&. "
.ti -1c
.RI "file \fBmol_water\&.h\fP"
.br
.RI "Generating and managing water\&. "
.ti -1c
.RI "file \fBmolecule_to_map\&.h\fP"
.br
.RI "Header file for functions to calculate a 3D map from atomic coordinates\&. "
.ti -1c
.RI "file \fBmoving_average\&.h\fP"
.br
.RI "Header file moving average calculations\&. "
.ti -1c
.RI "file \fBoptions\&.h\fP"
.br
.RI "Header file for option handlers\&. "
.ti -1c
.RI "file \fBps_ctf_plot\&.h\fP"
.br
.RI "Header file for postscript output functions\&. "
.ti -1c
.RI "file \fBps_marker\&.h\fP"
.br
.RI "Header file for postscript tools dealing with Bmarkers\&. "
.ti -1c
.RI "file \fBps_micrograph\&.h\fP"
.br
.RI "Header file for postscript tools dealing with micrograph particle sets\&. "
.ti -1c
.RI "file \fBps_model\&.h\fP"
.br
.RI "Header file for postscript tools dealing with models\&. "
.ti -1c
.RI "file \fBps_plot\&.h\fP"
.br
.RI "Header file for postscript output functions\&. "
.ti -1c
.RI "file \fBps_sequence\&.h\fP"
.br
.RI "Header file for postscript output for sequence analysis functions\&. "
.ti -1c
.RI "file \fBps_tree\&.h\fP"
.br
.RI "Header file for writing a tree into a postcsript file\&. "
.ti -1c
.RI "file \fBps_views\&.h\fP"
.br
.RI "Header file for postscript tools dealing with views\&. "
.ti -1c
.RI "file \fBqsort_functions\&.h\fP"
.br
.RI "Header file for utility functions for use in qsort calls\&. "
.ti -1c
.RI "file \fBQuaternion\&.h\fP"
.br
.RI "Class for quaternions\&. "
.ti -1c
.RI "file \fBrandom_numbers\&.h\fP"
.br
.RI "Header file for functions for creating random images\&. "
.ti -1c
.RI "file \fBrwASCII\&.h\fP"
.br
.RI "Header file for reading and writing ASCII files\&. "
.ti -1c
.RI "file \fBrwatomprop\&.h\fP"
.br
.RI "Header file for reading atom property files\&. "
.ti -1c
.RI "file \fBrwBCR\&.h\fP"
.br
.RI "Header file for reading and writing AFM BCR-STM files\&. "
.ti -1c
.RI "file \fBrwBIORAD\&.h\fP"
.br
.RI "Header file for reading and writing BioRad files\&. "
.ti -1c
.RI "file \fBrwBRIX\&.h\fP"
.br
.RI "Header file for reading and writing Brix files\&. "
.ti -1c
.RI "file \fBrwBrookhavenSTEM\&.h\fP"
.br
.RI "Header file for reading and writing Brookhaven STEM files\&. "
.ti -1c
.RI "file \fBrwCCP4\&.h\fP"
.br
.RI "Header file for reading and writing CCP4 files\&. "
.ti -1c
.RI "file \fBrwClustal\&.h\fP"
.br
.RI "Header file for reading and writing Clustal sequence files\&. "
.ti -1c
.RI "file \fBrwDI\&.h\fP"
.br
.RI "Header file for reading (only) Digital Instruments files\&. "
.ti -1c
.RI "file \fBrwDM\&.h\fP"
.br
.RI "Header file for reading and writing DM files\&. "
.ti -1c
.RI "file \fBrwDSN6\&.h\fP"
.br
.RI "Header file for reading and writing DSN6 files\&. "
.ti -1c
.RI "file \fBrwDX\&.h\fP"
.br
.RI "Header file for reading and writing OpenDX files\&. "
.ti -1c
.RI "file \fBrwEER\&.h\fP"
.br
.RI "Header file for reading EER files\&. "
.ti -1c
.RI "file \fBrwEM\&.h\fP"
.br
.RI "Header file for reading and writing EM files\&. "
.ti -1c
.RI "file \fBrwEMBL\&.h\fP"
.br
.RI "Header file for reading and writing EMBL sequence files\&. "
.ti -1c
.RI "file \fBrwFASTA\&.h\fP"
.br
.RI "Header file for reading and writing FASTA sequence files\&. "
.ti -1c
.RI "file \fBrwFSC_XML\&.h\fP"
.br
.RI "Library routines to read and write FSC curves\&. "
.ti -1c
.RI "file \fBrwGenBank\&.h\fP"
.br
.RI "Header file for reading and writing GenBank sequence files\&. "
.ti -1c
.RI "file \fBrwgencode\&.h\fP"
.br
.RI "Header file for reading a genetic code from a file\&. "
.ti -1c
.RI "file \fBrwGOODFORD\&.h\fP"
.br
.RI "Header file for reading and writing Peter Goodford's GRID files\&. "
.ti -1c
.RI "file \fBrwGRD\&.h\fP"
.br
.RI "Header file for reading and writing Basel GRD files\&. "
.ti -1c
.RI "file \fBrwGROMACS\&.h\fP"
.br
.RI "Header file for reading and writing GROMACS coordinate files\&. "
.ti -1c
.RI "file \fBrwHKL\&.h\fP"
.br
.RI "Header file for reading and writing HKL reflection files as images\&. "
.ti -1c
.RI "file \fBrwIMAGIC\&.h\fP"
.br
.RI "Header file for reading and writing Image Science's Imagic files\&. "
.ti -1c
.RI "file \fBrwimg\&.h\fP"
.br
.RI "Header file for 2D and 3D image I/O\&. "
.ti -1c
.RI "file \fBrwIP\&.h\fP"
.br
.RI "Header file for reading and writing image plate reader files\&. "
.ti -1c
.RI "file \fBrwJPEG\&.h\fP"
.br
.RI "Header file for reading and writing JPEG files\&. "
.ti -1c
.RI "file \fBrwkernel\&.h\fP"
.br
.RI "Header file for functions to read and write kernel files\&. "
.ti -1c
.RI "file \fBrwmatrix\&.h\fP"
.br
.RI "Header file for reading (and writing) matrices\&. "
.ti -1c
.RI "file \fBrwmd\&.h\fP"
.br
.RI "Header to read and write molecular dynamics parameters in STAR format\&. "
.ti -1c
.RI "file \fBrwMFF\&.h\fP"
.br
.RI "Header file for reading and writing the What If MFF files\&. "
.ti -1c
.RI "file \fBrwmg\&.h\fP"
.br
.RI "Header file for reading and writing micrograph parameters\&. "
.ti -1c
.RI "file \fBrwmgEMX\&.h\fP"
.br
.RI "Reads and writes micrograph exchange files\&. "
.ti -1c
.RI "file \fBrwmgIMOD\&.h\fP"
.br
.RI "Converts between \fBIMOD\fP files and a micrograph parameter file\&. "
.ti -1c
.RI "file \fBrwmgRELION\&.h\fP"
.br
.RI "Header file for reading and writing micrograph parameters from and to the RELION STAR format\&. "
.ti -1c
.RI "file \fBrwmgSerialEM\&.h\fP"
.br
.RI "Converts between SerialEM MDOC files and a micrograph parameter file\&. "
.ti -1c
.RI "file \fBrwmgSTAR\&.h\fP"
.br
.RI "Header file for reading and writing micrograph parameters from and to the STAR format\&. "
.ti -1c
.RI "file \fBrwmgXML\&.h\fP"
.br
.RI "Reads and writes micrograph XML files\&. "
.ti -1c
.RI "file \fBrwMIFF\&.h\fP"
.br
.ti -1c
.RI "file \fBrwmodel\&.h\fP"
.br
.RI "Header file for reading and writing atomic model files\&. "
.ti -1c
.RI "file \fBrwmodel_bild\&.h\fP"
.br
.RI "Header file for reading and writing Chimera BILD files\&. "
.ti -1c
.RI "file \fBrwmodel_cmm\&.h\fP"
.br
.RI "Header file for reading and writing Chimera marker model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_mol\&.h\fP"
.br
.RI "Header file for reading and writing molecular model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_param\&.h\fP"
.br
.RI "Header to read and write model dynamics parameters in STAR format\&. "
.ti -1c
.RI "file \fBrwmodel_star\&.h\fP"
.br
.RI "Header file for reading and writing STAR model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_vega\&.h\fP"
.br
.RI "Header file for reading and writing Vega model parameters\&. "
.ti -1c
.RI "file \fBrwmodel_xml\&.h\fP"
.br
.RI "Read and write models in XML format\&. "
.ti -1c
.RI "file \fBrwmol_star\&.h\fP"
.br
.RI "Read and write molecules in STAR format\&. "
.ti -1c
.RI "file \fBrwmol_text\&.h\fP"
.br
.RI "Read and write molecules in plain text\&. "
.ti -1c
.RI "file \fBrwmolecule\&.h\fP"
.br
.RI "Header file for reading reflection files\&. "
.ti -1c
.RI "file \fBrwMRC\&.h\fP"
.br
.RI "Header file for reading and writing MRC files\&. "
.ti -1c
.RI "file \fBrwND2\&.h\fP"
.br
.RI "Header file for reading Nikon ND2 files\&. "
.ti -1c
.RI "file \fBrwPDB\&.h\fP"
.br
.RI "Header file for reading and writing PDB coordinate files\&. "
.ti -1c
.RI "file \fBrwPhylip\&.h\fP"
.br
.RI "Header file for reading and writing Phylip sequence files\&. "
.ti -1c
.RI "file \fBrwPIC\&.h\fP"
.br
.RI "Header file for reading and writing PIC's BP and BQ files\&. "
.ti -1c
.RI "file \fBrwPIF\&.h\fP"
.br
.RI "Header file for reading and writing PIF files\&. "
.ti -1c
.RI "file \fBrwPIR\&.h\fP"
.br
.RI "Header file for reading and writing PIR sequence files\&. "
.ti -1c
.RI "file \fBrwPNG\&.h\fP"
.br
.RI "Header file for reading and writing PNG files\&. "
.ti -1c
.RI "file \fBrwPNM\&.h\fP"
.br
.RI "Header file for reading and writing PNM files\&. "
.ti -1c
.RI "file \fBrwPostScript\&.h\fP"
.br
.RI "Header file for (reading and) writing postscript image files\&. "
.ti -1c
.RI "file \fBrwRAW\&.h\fP"
.br
.RI "Header file for reading and writing Raw files\&. "
.ti -1c
.RI "file \fBrwresprop\&.h\fP"
.br
.RI "Header file for reading residue property files\&. "
.ti -1c
.RI "file \fBrwSER\&.h\fP"
.br
.RI "Header file for reading and writing FEI Ser files\&. "
.ti -1c
.RI "file \fBrwSitus\&.h\fP"
.br
.RI "Header file for reading and writing Situs files\&. "
.ti -1c
.RI "file \fBrwSPE\&.h\fP"
.br
.RI "Header file for reading and writing SPE files\&. "
.ti -1c
.RI "file \fBrwSPIDER\&.h\fP"
.br
.RI "Header file for reading and writing SPIDER files\&. "
.ti -1c
.RI "file \fBrwstar\&.h\fP"
.br
.RI "A header file for STAR format files\&. "
.ti -1c
.RI "file \fBrwSUPRIM\&.h\fP"
.br
.RI "Header file for reading and writing SUPRIM files\&. "
.ti -1c
.RI "file \fBrwsymop\&.h\fP"
.br
.RI "Header file for reading and writing symmetry operators\&. "
.ti -1c
.RI "file \fBrwTGA\&.h\fP"
.br
.RI "Header file for reading and writing Truevision TGA files\&. "
.ti -1c
.RI "file \fBrwTIFF\&.h\fP"
.br
.RI "Header file for reading and writing TIFF files\&. "
.ti -1c
.RI "file \fBrwtree\&.h\fP"
.br
.RI "Header file for reading (and writing) trees\&. "
.ti -1c
.RI "file \fBrwWAH\&.h\fP"
.br
.RI "Header file for reading and writing Wayne Hendrickson coordinate files\&. "
.ti -1c
.RI "file \fBrwxml\&.h\fP"
.br
.RI "Reads and writes micrograph XML files\&. "
.ti -1c
.RI "file \fBrwXPLOR\&.h\fP"
.br
.RI "Header file for reading and writing XPLOR reflection files\&. "
.ti -1c
.RI "file \fBscatter\&.h\fP"
.br
.RI "Functions for calculating electron scattering profiles\&. "
.ti -1c
.RI "file \fBseq_align\&.h\fP"
.br
.RI "Header file for functions to generate and analyze dot plots\&. "
.ti -1c
.RI "file \fBseq_analysis\&.h\fP"
.br
.RI "Header file for sequence analysis functions\&. "
.ti -1c
.RI "file \fBseq_util\&.h\fP"
.br
.RI "Header file for sequence utilities\&. "
.ti -1c
.RI "file \fBsimplex\&.h\fP"
.br
.RI "Nelder and Mead downhill simplex method for generalized parameter fitting\&. "
.ti -1c
.RI "file \fBspline\&.h\fP"
.br
.RI "Header file for spline interpolation\&. "
.ti -1c
.RI "file \fBstar\&.h\fP"
.br
.ti -1c
.RI "file \fBstring_util\&.h\fP"
.br
.ti -1c
.RI "file \fBsym_tags\&.h\fP"
.br
.RI "All STAR file format tags for symmetry parameters\&. "
.ti -1c
.RI "file \fBsymmetry\&.h\fP"
.br
.RI "Header file for general symmetry functions\&. "
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.RI "Utilities for timing functions\&. "
.ti -1c
.RI "file \fBTransform\&.h\fP"
.br
.RI "Class for a generalized transform object\&. "
.ti -1c
.RI "file \fBUnitCell\&.h\fP"
.br
.RI "Header file for unit cell functions\&. "
.ti -1c
.RI "file \fBuse_ctf\&.inc\fP"
.br
.ti -1c
.RI "file \fBuse_dose\&.inc\fP"
.br
.ti -1c
.RI "file \fButilities\&.h\fP"
.br
.RI "Header file for general utilities\&. "
.ti -1c
.RI "file \fBVector3\&.h\fP"
.br
.RI "Class for 3-value vectors\&. "
.ti -1c
.RI "file \fBversions\&.h\fP"
.br
.RI "Library functions to encode versions of all included packages\&. "
.ti -1c
.RI "file \fBView\&.h\fP"
.br
.RI "\fBView\fP object\&. "
.ti -1c
.RI "file \fBView2\&.h\fP"
.br
.in -1c
