.TH "/Users/bernard/b20/bsoft/src/util Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/util Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbinomial\&.cpp\fP"
.br
.RI "Functions to generate and fit binomials\&. "
.ti -1c
.RI "file \fBBplot\&.cpp\fP"
.br
.RI "Postscript output functions\&. "
.ti -1c
.RI "file \fBBstring\&.cpp\fP"
.br
.RI "Functions in the string class\&. "
.ti -1c
.RI "file \fBcluster\&.cpp\fP"
.br
.RI "Clustering functions\&. "
.ti -1c
.RI "file \fBctf\&.cpp\fP"
.br
.RI "Functions to manage CTF (contrast transfer function) parameters\&. "
.ti -1c
.RI "file \fBdynamic_programming\&.cpp\fP"
.br
.RI "Library functions for dynamic programming\&. "
.ti -1c
.RI "file \fBfft\&.cpp\fP"
.br
.RI "General FFT for n-dimensional data\&. "
.ti -1c
.RI "file \fBfile_util\&.cpp\fP"
.br
.RI "Library functions for file checking\&. "
.ti -1c
.RI "file \fBjson\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlinked_list\&.cpp\fP"
.br
.RI "Generalized linked list functions\&. "
.ti -1c
.RI "file \fBmarker\&.cpp\fP"
.br
.RI "Functions for dealing with markers and linkers\&. "
.ti -1c
.RI "file \fBmath_util\&.cpp\fP"
.br
.RI "Mathematics utility functions\&. "
.ti -1c
.RI "file \fBmatrix\&.cpp\fP"
.br
.RI "\fBMatrix\fP manipulation functions\&. "
.ti -1c
.RI "file \fBMatrix3\&.cpp\fP"
.br
.RI "\fBMatrix\fP manipulation functions\&. "
.ti -1c
.RI "file \fBmatrix_linear\&.cpp\fP"
.br
.RI "Solving sets of linear equations through matrix algebra\&. "
.ti -1c
.RI "file \fBmatrix_util\&.cpp\fP"
.br
.RI "Utility functions for matrices\&. "
.ti -1c
.RI "file \fBmoving_average\&.cpp\fP"
.br
.RI "Functions for moving average calculations\&. "
.ti -1c
.RI "file \fBoptions\&.cpp\fP"
.br
.RI "Functions to handle general options\&. "
.ti -1c
.RI "file \fBqsort_functions\&.cpp\fP"
.br
.RI "Library utility functions for use in qsort calls\&. "
.ti -1c
.RI "file \fBQuaternion\&.cpp\fP"
.br
.RI "\fBQuaternion\fP functions\&. "
.ti -1c
.RI "file \fBrandom_numbers\&.cpp\fP"
.br
.RI "Functions for generating random sequences\&. "
.ti -1c
.RI "file \fBscatter\&.cpp\fP"
.br
.RI "Functions for calculating electron scattering profiles\&. "
.ti -1c
.RI "file \fBsimplex\&.cpp\fP"
.br
.RI "Nelder and Mead downhill simplex method for generalized parameter fitting\&. "
.ti -1c
.RI "file \fBspline\&.cpp\fP"
.br
.RI "Functions to calculate spline curves\&. "
.ti -1c
.RI "file \fBstring_util\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsymmetry\&.cpp\fP"
.br
.RI "General symmetry functions\&. "
.ti -1c
.RI "file \fBtimer\&.cpp\fP"
.br
.RI "Utilities for timing functions\&. "
.ti -1c
.RI "file \fBTransform\&.cpp\fP"
.br
.RI "\fBTransform\fP manipulation functions\&. "
.ti -1c
.RI "file \fBUnitCell\&.cpp\fP"
.br
.RI "Unit cell functions\&. "
.ti -1c
.RI "file \fButilities\&.cpp\fP"
.br
.RI "Library functions useful in all the package\&. "
.ti -1c
.RI "file \fBView\&.cpp\fP"
.br
.RI "\fBView\fP functions\&. "
.in -1c
