.TH "/Users/bernard/b20/bsoft/src/rwparam Directory Reference" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwparam Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrwatomprop\&.cpp\fP"
.br
.RI "Library routines to read and write atom properties\&. "
.ti -1c
.RI "file \fBrwFSC_XML\&.cpp\fP"
.br
.RI "Library routines to read and write FSC curves\&. "
.ti -1c
.RI "file \fBrwgencode\&.cpp\fP"
.br
.RI "Library routines to read and write genetic codes\&. "
.ti -1c
.RI "file \fBrwmd\&.cpp\fP"
.br
.RI "Library routines to read and write molecular dynamics parameters in STAR format\&. "
.ti -1c
.RI "file \fBrwmg\&.cpp\fP"
.br
.RI "Library routines to read and write micrograph parameters\&. "
.ti -1c
.RI "file \fBrwmgEMX\&.cpp\fP"
.br
.RI "Reads and writes micrograph exchange files\&. "
.ti -1c
.RI "file \fBrwmgIMOD\&.cpp\fP"
.br
.RI "Converts between \fBIMOD\fP files and a micrograph parameter file\&. "
.ti -1c
.RI "file \fBrwmgRELION\&.cpp\fP"
.br
.RI "Library routines to read and write micrograph parameters in RELION STAR format\&. "
.ti -1c
.RI "file \fBrwmgSerialEM\&.cpp\fP"
.br
.RI "Converts between a SerialEM MDOC file and a micrograph parameter file\&. "
.ti -1c
.RI "file \fBrwmgSTAR\&.cpp\fP"
.br
.RI "Library routines to read and write micrograph parameters in STAR format\&. "
.ti -1c
.RI "file \fBrwmgSTAR2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrwmgXML\&.cpp\fP"
.br
.RI "Reads and writes micrograph XML files\&. "
.ti -1c
.RI "file \fBrwresprop\&.cpp\fP"
.br
.RI "Library routines to read and write residue properties\&. "
.ti -1c
.RI "file \fBrwstar\&.cpp\fP"
.br
.RI "Parse and interpret STAR format files\&. "
.ti -1c
.RI "file \fBrwsymop\&.cpp\fP"
.br
.RI "Library routines to read and write symmetry operators\&. "
.ti -1c
.RI "file \fBrwtree\&.cpp\fP"
.br
.RI "Functions for reading (and writing) trees\&. "
.ti -1c
.RI "file \fBrwxml\&.cpp\fP"
.br
.RI "Reads to and writes from XML structures\&. "
.in -1c
