.TH "AlphaTemplate" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlphaTemplate
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBatomtype\fP [8]"
.br
.ti -1c
.RI "double \fBcoord\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file mol_alpha\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "char AlphaTemplate::atomtype[8]"

.PP
Definition at line 38 of file mol_alpha\&.cpp\&.
.SS "double AlphaTemplate::coord[3]"

.PP
Definition at line 39 of file mol_alpha\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
