.TH "/Users/bernard/b20/bsoft/src/baddmask.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/baddmask.cpp \- Program to catenate image files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'img_combine\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBimage\fP * \fBimg_composite_mask\fP (\fBBstring\fP *\fBfile_list\fP, int mask_type)"
.br
.RI "Generates a composite of multiple masks\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to catenate image files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20091117 
.PP
Modified: 20170117 
.RE
.PP

.PP
Definition in file \fBbaddmask\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBimage\fP * img_composite_mask (\fBBstring\fP * file_list, int mask_type)"

.PP
Generates a composite of multiple masks\&. 
.PP
\fBParameters\fP
.RS 4
\fI*file_list\fP list of file names\&. 
.br
\fImask_type\fP type of mask to generate (2/3)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bimage* composite mask (4-byte integer)\&. 
.PP
.nf
The composite mask can be either a multi-bit mask (mask_type = 2),
or a multi-level mask (mask_type = 3).

.fi
.PP
 
.RE
.PP

.PP
Definition at line 147 of file baddmask\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 43 of file baddmask\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: baddmask [options] input\&.images",
"--------------------------------------",
"Adds multiple masks to generate a new composite mask\&.",
"Any number of input images may be given and may include the wild card \"*\"\&.",
" ",
"Actions:",
"-type bit                Type of composite mask: uniform/bit/level\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (A/pixel; a single value can be given)\&.",
"-origin 0\&.8,-10,15\&.7     Set the origin (default from input image)\&.",
" ",
"Output:",
"-output output\&.img       Output image (default sum\&.map)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 21 of file baddmask\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
