.TH "Baxis" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Baxis
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bplot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaxis\fP ()"
.br
.ti -1c
.RI "long \fBwhich\fP ()"
.br
.ti -1c
.RI "void \fBwhich\fP (long i)"
.br
.ti -1c
.RI "\fBBstring\fP & \fBlabel\fP ()"
.br
.ti -1c
.RI "void \fBlabel\fP (const \fBBstring\fP &s)"
.br
.ti -1c
.RI "double \fBmin\fP ()"
.br
.ti -1c
.RI "void \fBmin\fP (double v)"
.br
.ti -1c
.RI "double \fBmax\fP ()"
.br
.ti -1c
.RI "void \fBmax\fP (double v)"
.br
.ti -1c
.RI "double \fBinc\fP ()"
.br
.ti -1c
.RI "void \fBinc\fP (double v)"
.br
.ti -1c
.RI "double * \fBcolor\fP ()"
.br
.ti -1c
.RI "void \fBcolor\fP (double r, double g, double b)"
.br
.ti -1c
.RI "long \fBflags\fP ()"
.br
.ti -1c
.RI "void \fBflags\fP (long v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Bplot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Baxis::Baxis ()\fC [inline]\fP"

.PP
Definition at line 25 of file Bplot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double* Baxis::color ()\fC [inline]\fP"

.PP
Definition at line 36 of file Bplot\&.h\&.
.SS "void Baxis::color (double r, double g, double b)\fC [inline]\fP"

.PP
Definition at line 37 of file Bplot\&.h\&.
.SS "long Baxis::flags ()\fC [inline]\fP"

.PP
Definition at line 38 of file Bplot\&.h\&.
.SS "void Baxis::flags (long v)\fC [inline]\fP"

.PP
Definition at line 39 of file Bplot\&.h\&.
.SS "double Baxis::inc ()\fC [inline]\fP"

.PP
Definition at line 34 of file Bplot\&.h\&.
.SS "void Baxis::inc (double v)\fC [inline]\fP"

.PP
Definition at line 35 of file Bplot\&.h\&.
.SS "\fBBstring\fP& Baxis::label ()\fC [inline]\fP"

.PP
Definition at line 28 of file Bplot\&.h\&.
.SS "void Baxis::label (const \fBBstring\fP & s)\fC [inline]\fP"

.PP
Definition at line 29 of file Bplot\&.h\&.
.SS "double Baxis::max ()\fC [inline]\fP"

.PP
Definition at line 32 of file Bplot\&.h\&.
.SS "void Baxis::max (double v)\fC [inline]\fP"

.PP
Definition at line 33 of file Bplot\&.h\&.
.SS "double Baxis::min ()\fC [inline]\fP"

.PP
Definition at line 30 of file Bplot\&.h\&.
.SS "void Baxis::min (double v)\fC [inline]\fP"

.PP
Definition at line 31 of file Bplot\&.h\&.
.SS "long Baxis::which ()\fC [inline]\fP"

.PP
Definition at line 26 of file Bplot\&.h\&.
.SS "void Baxis::which (long i)\fC [inline]\fP"

.PP
Definition at line 27 of file Bplot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
