.TH "Bbadarea" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bbadarea
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBbadarea\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBbadarea\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bbadarea::Bbadarea ()\fC [inline]\fP"

.PP
Definition at line 198 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Bbadarea::id"

.PP
Definition at line 196 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bbadarea::loc"

.PP
Definition at line 197 of file mg_processing\&.h\&.
.SS "\fBBbadarea\fP* Bbadarea::next"

.PP
Definition at line 195 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
