.TH "Bcomptype" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bcomptype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBcomptype\fP ()"
.br
.ti -1c
.RI "\fBBcomptype\fP (string s)"
.br
.ti -1c
.RI "\fBBcomptype\fP (long i)"
.br
.ti -1c
.RI "\fBBcomptype\fP (string fn, long img_num)"
.br
.ti -1c
.RI "\fBBcomptype\fP (string s, string fn, long img_num)"
.br
.ti -1c
.RI "\fBBcomptype\fP (\fBBcomptype\fP *ct)"
.br
.ti -1c
.RI "void \fBidentifier\fP (string s)"
.br
.ti -1c
.RI "void \fBidentifier\fP (\fBBstring\fP s)"
.br
.ti -1c
.RI "string & \fBidentifier\fP ()"
.br
.ti -1c
.RI "void \fBindex\fP (long i)"
.br
.ti -1c
.RI "long \fBindex\fP ()"
.br
.ti -1c
.RI "long \fBindex\fP (string s)"
.br
.ti -1c
.RI "void \fBfile_name\fP (string s)"
.br
.ti -1c
.RI "string & \fBfile_name\fP ()"
.br
.ti -1c
.RI "void \fBimage_number\fP (long i)"
.br
.ti -1c
.RI "long \fBimage_number\fP ()"
.br
.ti -1c
.RI "void \fBmass\fP (double m)"
.br
.ti -1c
.RI "double \fBmass\fP ()"
.br
.ti -1c
.RI "void \fBcharge\fP (double c)"
.br
.ti -1c
.RI "double \fBcharge\fP ()"
.br
.ti -1c
.RI "void \fBlink_radius\fP (double r)"
.br
.ti -1c
.RI "double \fBlink_radius\fP ()"
.br
.ti -1c
.RI "void \fBradius\fP (double r)"
.br
.ti -1c
.RI "double \fBradius\fP ()"
.br
.ti -1c
.RI "template<typename T > void \fBcoefficients\fP (vector< T > c)"
.br
.ti -1c
.RI "vector< double > \fBcoefficients\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.ti -1c
.RI "long \fBselect_increment\fP ()"
.br
.ti -1c
.RI "void \fBcomponent_count\fP (float n)"
.br
.ti -1c
.RI "float \fBcomponent_count\fP ()"
.br
.ti -1c
.RI "void \fBcomponent_count_increment\fP ()"
.br
.ti -1c
.RI "void \fBcomponent_count_decrement\fP ()"
.br
.ti -1c
.RI "void \fBcomponent_count_add\fP (float n)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBadd\fP (string s)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBadd\fP (long i)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBadd\fP (string fn, long img_num)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBadd\fP (string s, string fn, long img_num)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBadd\fP (\fBBcomptype\fP *ct)"
.br
.ti -1c
.RI "\fBBcomptype\fP * \fBfind\fP (string s)"
.br
.ti -1c
.RI "long \fBcount\fP ()"
.br
.ti -1c
.RI "long \fBcount_selected\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBBcomptype\fP &ct)"
.br
.ti -1c
.RI "bool \fBcheck\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBcomptype\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file rwmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bcomptype::Bcomptype ()\fC [inline]\fP"

.PP
Definition at line 58 of file rwmodel\&.h\&.
.SS "Bcomptype::Bcomptype (string s)\fC [inline]\fP"

.PP
Definition at line 59 of file rwmodel\&.h\&.
.SS "Bcomptype::Bcomptype (long i)\fC [inline]\fP"

.PP
Definition at line 60 of file rwmodel\&.h\&.
.SS "Bcomptype::Bcomptype (string fn, long img_num)\fC [inline]\fP"

.PP
Definition at line 61 of file rwmodel\&.h\&.
.SS "Bcomptype::Bcomptype (string s, string fn, long img_num)\fC [inline]\fP"

.PP
Definition at line 62 of file rwmodel\&.h\&.
.SS "Bcomptype::Bcomptype (\fBBcomptype\fP * ct)\fC [inline]\fP"

.PP
Definition at line 63 of file rwmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBcomptype\fP* Bcomptype::add (\fBBcomptype\fP * ct)\fC [inline]\fP"

.PP
Definition at line 143 of file rwmodel\&.h\&.
.SS "\fBBcomptype\fP* Bcomptype::add (long i)\fC [inline]\fP"

.PP
Definition at line 124 of file rwmodel\&.h\&.
.SS "\fBBcomptype\fP* Bcomptype::add (string fn, long img_num)\fC [inline]\fP"

.PP
Definition at line 131 of file rwmodel\&.h\&.
.SS "\fBBcomptype\fP* Bcomptype::add (string s)\fC [inline]\fP"

.PP
Definition at line 118 of file rwmodel\&.h\&.
.SS "\fBBcomptype\fP* Bcomptype::add (string s, string fn, long img_num)\fC [inline]\fP"

.PP
Definition at line 137 of file rwmodel\&.h\&.
.SS "double Bcomptype::charge ()\fC [inline]\fP"

.PP
Definition at line 94 of file rwmodel\&.h\&.
.SS "void Bcomptype::charge (double c)\fC [inline]\fP"

.PP
Definition at line 93 of file rwmodel\&.h\&.
.SS "bool Bcomptype::check ()\fC [inline]\fP"

.PP
Definition at line 170 of file rwmodel\&.h\&.
.SS "vector<double> Bcomptype::coefficients ()\fC [inline]\fP"

.PP
Definition at line 103 of file rwmodel\&.h\&.
.SS "template<typename T > void Bcomptype::coefficients (vector< T > c)\fC [inline]\fP"

.PP
Definition at line 100 of file rwmodel\&.h\&.
.SS "float Bcomptype::component_count ()\fC [inline]\fP"

.PP
Definition at line 114 of file rwmodel\&.h\&.
.SS "void Bcomptype::component_count (float n)\fC [inline]\fP"

.PP
Definition at line 113 of file rwmodel\&.h\&.
.SS "void Bcomptype::component_count_add (float n)\fC [inline]\fP"

.PP
Definition at line 117 of file rwmodel\&.h\&.
.SS "void Bcomptype::component_count_decrement ()\fC [inline]\fP"

.PP
Definition at line 116 of file rwmodel\&.h\&.
.SS "void Bcomptype::component_count_increment ()\fC [inline]\fP"

.PP
Definition at line 115 of file rwmodel\&.h\&.
.SS "long Bcomptype::count ()\fC [inline]\fP"

.PP
Definition at line 153 of file rwmodel\&.h\&.
.SS "long Bcomptype::count_selected ()\fC [inline]\fP"

.PP
Definition at line 158 of file rwmodel\&.h\&.
.SS "string& Bcomptype::file_name ()\fC [inline]\fP"

.PP
Definition at line 88 of file rwmodel\&.h\&.
.SS "void Bcomptype::file_name (string s)\fC [inline]\fP"

.PP
Definition at line 87 of file rwmodel\&.h\&.
.SS "\fBBcomptype\fP* Bcomptype::find (string s)\fC [inline]\fP"

.PP
Definition at line 148 of file rwmodel\&.h\&.
.SS "double Bcomptype::FOM ()\fC [inline]\fP"

.PP
Definition at line 109 of file rwmodel\&.h\&.
.SS "void Bcomptype::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 108 of file rwmodel\&.h\&.
.SS "string& Bcomptype::identifier ()\fC [inline]\fP"

.PP
Definition at line 79 of file rwmodel\&.h\&.
.SS "void Bcomptype::identifier (\fBBstring\fP s)\fC [inline]\fP"

.PP
Definition at line 78 of file rwmodel\&.h\&.
.SS "void Bcomptype::identifier (string s)\fC [inline]\fP"

.PP
Definition at line 77 of file rwmodel\&.h\&.
.SS "long Bcomptype::image_number ()\fC [inline]\fP"

.PP
Definition at line 90 of file rwmodel\&.h\&.
.SS "void Bcomptype::image_number (long i)\fC [inline]\fP"

.PP
Definition at line 89 of file rwmodel\&.h\&.
.SS "long Bcomptype::index ()\fC [inline]\fP"

.PP
Definition at line 81 of file rwmodel\&.h\&.
.SS "void Bcomptype::index (long i)\fC [inline]\fP"

.PP
Definition at line 80 of file rwmodel\&.h\&.
.SS "long Bcomptype::index (string s)\fC [inline]\fP"

.PP
Definition at line 82 of file rwmodel\&.h\&.
.SS "double Bcomptype::link_radius ()\fC [inline]\fP"

.PP
Definition at line 96 of file rwmodel\&.h\&.
.SS "void Bcomptype::link_radius (double r)\fC [inline]\fP"

.PP
Definition at line 95 of file rwmodel\&.h\&.
.SS "double Bcomptype::mass ()\fC [inline]\fP"

.PP
Definition at line 92 of file rwmodel\&.h\&.
.SS "void Bcomptype::mass (double m)\fC [inline]\fP"

.PP
Definition at line 91 of file rwmodel\&.h\&.
.SS "double Bcomptype::radius ()\fC [inline]\fP"

.PP
Definition at line 98 of file rwmodel\&.h\&.
.SS "void Bcomptype::radius (double r)\fC [inline]\fP"

.PP
Definition at line 97 of file rwmodel\&.h\&.
.SS "long Bcomptype::select ()\fC [inline]\fP"

.PP
Definition at line 111 of file rwmodel\&.h\&.
.SS "void Bcomptype::select (long i)\fC [inline]\fP"

.PP
Definition at line 110 of file rwmodel\&.h\&.
.SS "long Bcomptype::select_increment ()\fC [inline]\fP"

.PP
Definition at line 112 of file rwmodel\&.h\&.
.SS "void Bcomptype::update (\fBBcomptype\fP & ct)\fC [inline]\fP"

.PP
Definition at line 163 of file rwmodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBcomptype\fP* Bcomptype::next"

.PP
Definition at line 43 of file rwmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
