.TH "/Users/bernard/b20/bsoft/src/bcormut.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bcormut.cpp \- A program to analyze protein sequences for correlated mutations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'seq_analysis\&.h'\fP
.br
\fC#include 'rwmolecule\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A program to analyze protein sequences for correlated mutations\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990123 
.PP
Modified: 20200916 
.RE
.PP

.PP
Definition in file \fBbcormut\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 51 of file bcormut\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bcormut [options] input\&.pir output\&.pir",
"---------------------------------------------",
"Analyzes for correlated mutations in aligned protein sequences\&.",
"The -cutoff option must be used to do the correlated mutation analysis\&.",
"All sequence numbers and position numbers start at 1\&.",
"Sequence numbering is according to the input, including gaps\&.",
" ",
"Actions:",
"-cutoff 0\&.3              Correlated mutations: cutoff to report\&.",
"-limit                   Limit output to reference sequence\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype b              Set the output image data type\&.",
"-reference HUMAN         Reference sequence identifier (substring)\&.",
" ",
"Input:",
"-properties file\&.star    Property file (default = internal values)\&.",
" ",
"Output:",
"-matrix file\&.mat         Correlation coefficient matrix\&.",
"-image file\&.map          Correlation coefficient matrix as an image\&.",
" ",
"Examples:",
"bcormut -verbose 7 -cutoff 0\&.4 -image coeff\&.map -datatype byte seq\&.pir",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bcormut\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
