.TH "/Users/bernard/b20/bsoft/src/bcyl.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bcyl.cpp \- Program to manipulate cylindrical images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBimg_plot_max_vs_angle\fP (\fBBimage\fP *p)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to manipulate cylindrical images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20090309 
.PP
Modified: 20160326 
.RE
.PP

.PP
Definition in file \fBbcyl\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int img_plot_max_vs_angle (\fBBimage\fP * p)"

.PP
Definition at line 149 of file bcyl\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 43 of file bcyl\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bcyl [options] input\&.img output\&.img",
"------------------------------------------",
"Unwraps an image to its cylindrical projection\&.",
" ",
"Actions:",
"-symmetrize              Symmetrizes a map cylindrically around the origin\&.",
"-unwrap 1\&.5              Unwraps an image to its cylindrical projection with the given angle\&.",
"-autocorrelate           Autocorrelates the unwrapped map and outputs the autocorrelation map\&.",
"-rescale -0\&.1,5\&.2        Rescale data to average and standard deviation (after -truncate)\&.",
"-shells                  Calculate cylindrical shells projecting along the y-axis\&.",
"-reslice yzx             Reslice (switch axes) after unwrapping\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-origin 0,-10\&.5,30       Set the origin\&.",
"-resolution 4\&.5,130      Resolution range for correlation (default 0 - 1e6 angstrom)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bcyl\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
