.TH "/Users/bernard/b20/bsoft/src/bfile.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bfile.cpp \- Program to read file contents directly and poke single values\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshow_block\fP (size_t start, size_t size, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBshow_block_hex\fP (size_t start, size_t size, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBshow_char\fP (size_t start, size_t size, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBswap_block\fP (size_t size, size_t nbytes, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBshow_table\fP (size_t start, size_t size, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBshow_structure\fP (size_t start, size_t size, int swap, char *strdef, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBshow_eer\fP (size_t start, size_t size, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBpoke_value\fP (fstream *fin, size_t loc, char typechar, double value)"
.br
.ti -1c
.RI "int \fBfind_string\fP (const char *string, size_t start, size_t size, unsigned char *buf)"
.br
.ti -1c
.RI "int \fBreplace\fP (fstream *fin, char *rstring1, char *rstring2)"
.br
.ti -1c
.RI "char * \fBstring2byte\fP (char *string)"
.br
.ti -1c
.RI "size_t \fBstring_bytes\fP (char *string)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBshow_bits\fP (unsigned long val)"
.br
.ti -1c
.RI "int \fBshow_code\fP (unsigned long code)"
.br
.ti -1c
.RI "int \fBshift_right\fP (unsigned long &bits, long n)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to read file contents directly and poke single values\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19980129 
.PP
Modified: 20210430 
.RE
.PP

.PP
Definition in file \fBbfile\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int find_string (const char * string, size_t start, size_t size, unsigned char * buf)"

.PP
Definition at line 447 of file bfile\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 66 of file bfile\&.cpp\&.
.SS "int poke_value (fstream * fin, size_t loc, char typechar, double value)"

.PP
Definition at line 465 of file bfile\&.cpp\&.
.SS "int replace (fstream * fin, char * rstring1, char * rstring2)"

.PP
Definition at line 503 of file bfile\&.cpp\&.
.SS "int shift_right (unsigned long & bits, long n)"

.PP
Definition at line 378 of file bfile\&.cpp\&.
.SS "int show_bits (unsigned long val)"

.PP
Definition at line 362 of file bfile\&.cpp\&.
.SS "int show_block (size_t start, size_t size, unsigned char * buf)"

.PP
Definition at line 200 of file bfile\&.cpp\&.
.SS "int show_block_hex (size_t start, size_t size, unsigned char * buf)"

.PP
Definition at line 218 of file bfile\&.cpp\&.
.SS "int show_char (size_t start, size_t size, unsigned char * buf)"

.PP
Definition at line 236 of file bfile\&.cpp\&.
.SS "int show_code (unsigned long code)"

.PP
Definition at line 370 of file bfile\&.cpp\&.
.SS "int show_eer (size_t start, size_t size, unsigned char * buf)"

.PP
Definition at line 391 of file bfile\&.cpp\&.
.SS "int show_structure (size_t start, size_t size, int swap, char * strdef, unsigned char * buf)"

.PP
Definition at line 298 of file bfile\&.cpp\&.
.SS "int show_table (size_t start, size_t size, unsigned char * buf)"

.PP
Definition at line 266 of file bfile\&.cpp\&.
.SS "char * string2byte (char * string)"

.PP
Definition at line 560 of file bfile\&.cpp\&.
.SS "size_t string_bytes (char * string)"

.PP
Definition at line 592 of file bfile\&.cpp\&.
.SS "int swap_block (size_t size, size_t nbytes, unsigned char * buf)"

.PP
Definition at line 252 of file bfile\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 30 of file bfile\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
