.TH "Bfilnode" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bfilnode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBfilnode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBfilnode\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 145 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bfilnode::Bfilnode ()\fC [inline]\fP"

.PP
Definition at line 155 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Bfilnode::id"

.PP
Definition at line 153 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bfilnode::loc"

.PP
Definition at line 154 of file mg_processing\&.h\&.
.SS "\fBBfilnode\fP* Bfilnode::next"

.PP
Definition at line 152 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
