.TH "/Users/bernard/b20/bsoft/src/bfix.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bfix.cpp \- Program to fix end-of-line characters in ascii files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBreplace_a_character\fP (unsigned char *buf, long size, int chin, int chout)"
.br
.ti -1c
.RI "long \fBdelete_a_character\fP (unsigned char *buf, long size, int c)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to fix end-of-line characters in ascii files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990206 
.PP
Modified: 20120306 
.RE
.PP

.PP
Definition in file \fBbfix\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "long delete_a_character (unsigned char * buf, long size, int c)"

.PP
Definition at line 170 of file bfix\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 43 of file bfix\&.cpp\&.
.SS "long replace_a_character (unsigned char * buf, long size, int chin, int chout)"

.PP
Definition at line 153 of file bfix\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bfix [options] file\&.in file\&.out",
"--------------------------------------",
"Replaces single characters in a file\&.",
"If only one file name is given, the output is sent to stdout\&.",
"If a \"\&.\" character is used for output, the input file name is used",
"(without the path)\&.",
"Note: replace and delete are mutually exclusive - the last option wins",
" ",
"Actions:",
"-n                 Replace <cr> with <nl> (To UNIX style)",
"-c                 Replace <nl> with <cr> (To MAC style)",
"-replace 9,32      Replace all character values 9 with character values 32",
"-delete 13         Delete all character values 13",
" ",
"Parameters:",
"-verbose 7         Verbosity of output",
" ",
NULL
}
.fi
.PP
Definition at line 21 of file bfix\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
