.TH "Bframe" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bframe
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBframe\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBframe\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBshift\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "long \fBsel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bframe::Bframe ()\fC [inline]\fP"

.PP
Definition at line 90 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Bframe::fom"

.PP
Definition at line 88 of file mg_processing\&.h\&.
.SS "int Bframe::id"

.PP
Definition at line 86 of file mg_processing\&.h\&.
.SS "\fBBframe\fP* Bframe::next"

.PP
Definition at line 85 of file mg_processing\&.h\&.
.SS "long Bframe::sel"

.PP
Definition at line 89 of file mg_processing\&.h\&.
.SS "\fBVector3\fP<double> Bframe::shift"

.PP
Definition at line 87 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
