.TH "/Users/bernard/b20/bsoft/include/Bgraphseg.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/Bgraphseg.h \- Graph segmentation classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'utilities\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGSedge\fP"
.br
.RI "Graph segmentation edge\&. "
.ti -1c
.RI "class \fBGSvoxel\fP"
.br
.RI "Graph segmentation region\&. "
.ti -1c
.RI "class \fBGSgraph\fP"
.br
.RI "Graph segmentation container\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GraphSeg_\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graph segmentation classes\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20110318 
.PP
Modified: 20201228 
.RE
.PP

.PP
Definition in file \fBBgraphseg\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GraphSeg_"

.PP
Definition at line 185 of file Bgraphseg\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
