.TH "/Users/bernard/b20/bsoft/src/bheight.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bheight.cpp \- Projecting a 3D map and calculating comparison statistics of the projections\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'symmetry\&.h'\fP
.br
\fC#include 'ps_views\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Projecting a 3D map and calculating comparison statistics of the projections\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20170613 
.PP
Modified: 20170613 
.RE
.PP

.PP
Definition in file \fBbheight\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 50 of file bheight\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bheight [options] input\&.img output\&.img",
"---------------------------------------------",
"Calculates 2D height images from a 3D map\&.",
" ",
"Actions:",
"-axis y                  Project down a major axis (x, y, z or 0, 1, 2)\&.",
"-View 0\&.3,-0\&.5,0\&.8,33    View to generate symmetry-related projections\&.",
"-Tilt -65,72,2\&.5,55      Tilt series of projections with angle min, max, step and axis angle\&.",
"-side 15                 Generate side view projections within the given angle from the equator\&.",
"-random 24               Generate a number of random projections\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-origin 10,-10,20        Origin for rotation (voxels, default 0,0,0)\&.",
"-sampling 2,3\&.5,1        Sampling (angstrom/voxel, a single value sets all three)\&.",
"-symmetry D6             Symmetry: Point group identifier\&.",
"-angles 8,6              Step sizes for theta and phi in the asymmetric unit, one value sets both\&.",
"-threshold 1\&.2           Density threshold to indicate boundary of object (default 0)\&.",
" ",
"Output:",
"-Plotviews plot\&.ps       Output postscript file with a plot of projection vectors\&.",
" ",
NULL
}
.fi
.PP
Definition at line 22 of file bheight\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
