.TH "/Users/bernard/b20/bsoft/src/img/Bimage_correlate.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_correlate.cpp \- Cross correlation functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'matrix_linear\&.h'\fP
.br
\fC#include 'math_util\&.h'\fP
.br
\fC#include 'qsort_functions\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cross correlation functions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19980805 
.PP
Modified: 20200218 
.PP
.nf
    Implemented using the FFTW library

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBBimage_correlate\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
