.TH "/Users/bernard/b20/bsoft/src/img/Bimage_align.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_align.cpp \- Functions to align images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'simplex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "vector< \fBVector3\fP< double > > \fBinterpolate_shifts\fP (\fBVector3\fP< double > *sh, long nimg, long window, long step)"
.br
.ti -1c
.RI "double \fBmtf_gaussian_R\fP (\fBBsimplex\fP &simp)"
.br
.ti -1c
.RI "double \fBcoincidence_loss_R\fP (\fBBsimplex\fP &simp)"
.br
.ti -1c
.RI "double \fBfit_mtf\fP (\fBBimage\fP *prad, long nimg, double &off, double &amp, double &sig)"
.br
.ti -1c
.RI "double \fBfit_coincidence_loss\fP (\fBBimage\fP *prad, long nimg, double &power, double &supr, double &pxsig)"
.br
.ti -1c
.RI "double * \fBcc_two_way\fP (long nn, double *x, double *y)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to align images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000505 
.PP
Modified: 20210809 
.RE
.PP

.PP
Definition in file \fBBimage_align\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "double* cc_two_way (long nn, double * x, double * y)"

.PP
Definition at line 1122 of file Bimage_align\&.cpp\&.
.SS "double coincidence_loss_R (\fBBsimplex\fP & simp)"

.PP
Definition at line 783 of file Bimage_align\&.cpp\&.
.SS "double fit_coincidence_loss (\fBBimage\fP * prad, long nimg, double & power, double & supr, double & pxsig)"

.PP
Definition at line 849 of file Bimage_align\&.cpp\&.
.SS "double fit_mtf (\fBBimage\fP * prad, long nimg, double & off, double & amp, double & sig)"

.PP
Definition at line 801 of file Bimage_align\&.cpp\&.
.SS "vector<\fBVector3\fP<double> > interpolate_shifts (\fBVector3\fP< double > * sh, long nimg, long window, long step)"

.PP
Definition at line 187 of file Bimage_align\&.cpp\&.
.SS "double mtf_gaussian_R (\fBBsimplex\fP & simp)"

.PP
Definition at line 764 of file Bimage_align\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
