.TH "/Users/bernard/b20/bsoft/include/Bimage.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/Bimage.h \- Header file for image class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'json\&.h'\fP
.br
\fC#include 'string_util\&.h'\fP
.br
\fC#include 'Bstring\&.h'\fP
.br
\fC#include 'Complex\&.h'\fP
.br
\fC#include 'fft\&.h'\fP
.br
\fC#include 'FSI_Kernel\&.h'\fP
.br
\fC#include 'Matrix\&.h'\fP
.br
\fC#include 'Vector3\&.h'\fP
.br
\fC#include 'View\&.h'\fP
.br
\fC#include 'Color\&.h'\fP
.br
\fC#include 'UnitCell\&.h'\fP
.br
\fC#include 'symmetry\&.h'\fP
.br
\fC#include 'ps_plot\&.h'\fP
.br
\fC#include 'Bsuperpixel\&.h'\fP
.br
\fC#include 'Bgraphseg\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <ctime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBTypePointer\fP"
.br
.ti -1c
.RI "class \fBBsub_image\fP"
.br
.RI "General sub-image parameter class\&. "
.ti -1c
.RI "class \fBBimage\fP"
.br
.RI "General image parameter class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNPOLANG\fP   720"
.br
.ti -1c
.RI "#define \fB_fouriertype_\fP"
.br
.ti -1c
.RI "#define \fB_Bimage_\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFourierType\fP { \fBNoTransform\fP = 0, \fBStandard\fP = 1, \fBCentered\fP = 2, \fBHermitian\fP = 3, \fBCentHerm\fP = 4 }"
.br
.RI "Fourier transform format specifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for image class\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990321 
.PP
Modified: 20210806 
.RE
.PP

.PP
Definition in file \fBBimage\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _Bimage_"

.PP
Definition at line 1464 of file Bimage\&.h\&.
.SS "#define _fouriertype_"

.PP
Definition at line 47 of file Bimage\&.h\&.
.SS "#define NPOLANG   720"

.PP
Definition at line 30 of file Bimage\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFourierType\fP"

.PP
Fourier transform format specifier\&. 
.PP
.nf
Transforms are classified according to where the origin is and whether
all or only the hermitian half is stored in a file.

.fi
.PP
 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINoTransform \fP\fP
.TP
\fB\fIStandard \fP\fP
.TP
\fB\fICentered \fP\fP
.TP
\fB\fIHermitian \fP\fP
.TP
\fB\fICentHerm \fP\fP
.PP
Definition at line 40 of file Bimage\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
