.TH "/Users/bernard/b20/bsoft/src/img/Bimage_fspace.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/img/Bimage_fspace.cpp \- Library routines used for modifying reciprocal space amplitudes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bimage\&.h'\fP
.br
\fC#include 'ctf\&.h'\fP
.br
\fC#include 'matrix_linear\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "vector< double > \fBcritical_exposure_curve\fP (long size, double real_size, int flag)"
.br
.ti -1c
.RI "vector< double > \fBradiation_damage_curve\fP (vector< double > dose, long size, double real_size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines used for modifying reciprocal space amplitudes\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990321 
.PP
Modified: 20210727 
.RE
.PP

.PP
Definition in file \fBBimage_fspace\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "vector<double> critical_exposure_curve (long size, double real_size, int flag)"

.PP
Definition at line 1621 of file Bimage_fspace\&.cpp\&.
.SS "vector<double> radiation_damage_curve (vector< double > dose, long size, double real_size)"

.PP
Definition at line 1653 of file Bimage_fspace\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
