.TH "BIORADhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BIORADhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwBIORAD\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBnx\fP"
.br
.ti -1c
.RI "short \fBny\fP"
.br
.ti -1c
.RI "short \fBnz\fP"
.br
.ti -1c
.RI "short \fBblack\fP"
.br
.ti -1c
.RI "short \fBwhite\fP"
.br
.ti -1c
.RI "short \fBpad1\fP [2]"
.br
.ti -1c
.RI "short \fBmode\fP"
.br
.ti -1c
.RI "short \fBpad2\fP [17]"
.br
.ti -1c
.RI "short \fBmark\fP"
.br
.ti -1c
.RI "short \fBcolor\fP"
.br
.ti -1c
.RI "short \fBmagic\fP"
.br
.ti -1c
.RI "short \fBblack2\fP"
.br
.ti -1c
.RI "short \fBwhite2\fP"
.br
.ti -1c
.RI "short \fBcolor2\fP"
.br
.ti -1c
.RI "short \fBpad3\fP"
.br
.ti -1c
.RI "short \fBlens\fP"
.br
.ti -1c
.RI "float \fBmag\fP"
.br
.ti -1c
.RI "short \fBpad4\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwBIORAD\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "short BIORADhead::black"

.PP
Definition at line 19 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::black2"

.PP
Definition at line 27 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::color"

.PP
Definition at line 25 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::color2"

.PP
Definition at line 29 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::lens"

.PP
Definition at line 31 of file rwBIORAD\&.h\&.
.SS "float BIORADhead::mag"

.PP
Definition at line 32 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::magic"

.PP
Definition at line 26 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::mark"

.PP
Definition at line 24 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::mode"

.PP
Definition at line 22 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::nx"

.PP
Definition at line 16 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::ny"

.PP
Definition at line 17 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::nz"

.PP
Definition at line 18 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::pad1[2]"

.PP
Definition at line 21 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::pad2[17]"

.PP
Definition at line 23 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::pad3"

.PP
Definition at line 30 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::pad4[3]"

.PP
Definition at line 33 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::white"

.PP
Definition at line 20 of file rwBIORAD\&.h\&.
.SS "short BIORADhead::white2"

.PP
Definition at line 28 of file rwBIORAD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
