.TH "/Users/bernard/b20/bsoft/eer/Bitmap.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/Bitmap.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <tiffio\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFei::Acquisition::EerReader::Bitmap\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFei\fP"
.br
.ti -1c
.RI " \fBFei::Acquisition\fP"
.br
.ti -1c
.RI " \fBFei::Acquisition::EerReader\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
