.TH "BitStreamer" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitStreamer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FeiBitStreamer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitStreamer\fP (\fBBitStreamWordType\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "\fBMultiBitType\fP \fBgetBits\fP (unsigned NBits)"
.br
.ti -1c
.RI "void \fBrewind\fP (unsigned NBits)"
.br
.ti -1c
.RI "uint64_t \fBnWordsRead\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBitStreamWordType\fP * \fBbuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file FeiBitStreamer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BitStreamer::BitStreamer (\fBBitStreamWordType\fP * buffer)\fC [inline]\fP"

.PP
Definition at line 22 of file FeiBitStreamer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMultiBitType\fP BitStreamer::getBits (unsigned NBits)\fC [inline]\fP"

.PP
Definition at line 29 of file FeiBitStreamer\&.h\&.
.SS "uint64_t BitStreamer::nWordsRead () const\fC [inline]\fP"

.PP
Definition at line 63 of file FeiBitStreamer\&.h\&.
.SS "void BitStreamer::rewind (unsigned NBits)\fC [inline]\fP"

.PP
Definition at line 50 of file FeiBitStreamer\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBitStreamWordType\fP* BitStreamer::buffer"

.PP
Definition at line 68 of file FeiBitStreamer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
