.TH "BitStreamWriter" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitStreamWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FeiBitStreamer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitStreamWriter\fP (\fBBitStreamWordType\fP *buf)"
.br
.ti -1c
.RI "void \fBputBits\fP (\fBMultiBitType\fP v, unsigned NBits)"
.br
.ti -1c
.RI "size_t \fBgetWordSize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file FeiBitStreamer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BitStreamWriter::BitStreamWriter (\fBBitStreamWordType\fP * buf)\fC [inline]\fP"

.PP
Definition at line 82 of file FeiBitStreamer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "size_t BitStreamWriter::getWordSize ()\fC [inline]\fP"

.PP
Definition at line 113 of file FeiBitStreamer\&.h\&.
.SS "void BitStreamWriter::putBits (\fBMultiBitType\fP v, unsigned NBits)\fC [inline]\fP"

.PP
Definition at line 90 of file FeiBitStreamer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
