.TH "/Users/bernard/b20/bsoft/src/bkernel.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bkernel.cpp \- Program to calculate filter kernels\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'FSI_Kernel\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to calculate filter kernels\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20051102 
.PP
Modified: 20150910 
.RE
.PP

.PP
Definition in file \fBbkernel\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 39 of file bkernel\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bkernel [options] output\&.krn",
"-----------------------------------",
"Calculates filter kernels\&.",
"The default kernel just calculates the mean\&.",
"The different types of kernel are mutually exclusive\&.",
" ",
"Actions:",
"-gaussian 1\&.7,8\&.4        Gaussian kernel with the indicated sigma and maximum\&.",
"-log 2\&.5,5               Laplacian of gaussian kernel with the indicated sigma and maximum\&.",
"-frequency 8,2           Frequency space kernel: width and power\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-size 5,7,9              Size of kernel (voxels)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 19 of file bkernel\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
