.TH "Blayerline" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blayerline
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlayerline\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlayerline\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "int \fBorder\fP"
.br
.ti -1c
.RI "double \fBdistance\fP"
.br
.ti -1c
.RI "double \fBfreq\fP"
.br
.ti -1c
.RI "double \fBamp\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "long \fBsel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 239 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Blayerline::Blayerline ()\fC [inline]\fP"

.PP
Definition at line 260 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Blayerline::amp"

.PP
Definition at line 257 of file mg_processing\&.h\&.
.SS "double Blayerline::distance"

.PP
Definition at line 255 of file mg_processing\&.h\&.
.SS "double Blayerline::fom"

.PP
Definition at line 258 of file mg_processing\&.h\&.
.SS "double Blayerline::freq"

.PP
Definition at line 256 of file mg_processing\&.h\&.
.SS "\fBBlayerline\fP* Blayerline::next"

.PP
Definition at line 252 of file mg_processing\&.h\&.
.SS "int Blayerline::number"

.PP
Definition at line 253 of file mg_processing\&.h\&.
.SS "int Blayerline::order"

.PP
Definition at line 254 of file mg_processing\&.h\&.
.SS "long Blayerline::sel"

.PP
Definition at line 259 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
