.TH "Blink" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blink
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlink\fP ()"
.br
.ti -1c
.RI "\fBBlink\fP (\fBBcomponent\fP *comp1, \fBBcomponent\fP *comp2)"
.br
.ti -1c
.RI "\fBBlink\fP (\fBBcomponent\fP *comp1, \fBBcomponent\fP *comp2, double d, double r)"
.br
.ti -1c
.RI "\fBBlink\fP (\fBBlink\fP *l)"
.br
.ti -1c
.RI "void \fBangle\fP (double a)"
.br
.ti -1c
.RI "double \fBangle\fP ()"
.br
.ti -1c
.RI "void \fBlength\fP (double d)"
.br
.ti -1c
.RI "double \fBlength\fP ()"
.br
.ti -1c
.RI "void \fBradius\fP (double r)"
.br
.ti -1c
.RI "double \fBradius\fP ()"
.br
.ti -1c
.RI "void \fBcolor\fP (\fBRGBA\fP< float > c)"
.br
.ti -1c
.RI "\fBRGBA\fP< float > & \fBcolor\fP ()"
.br
.ti -1c
.RI "void \fBadopt_component_color\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.ti -1c
.RI "long \fBselect_increment\fP ()"
.br
.ti -1c
.RI "\fBBlink\fP * \fBadd\fP (\fBBcomponent\fP *comp1, \fBBcomponent\fP *comp2)"
.br
.ti -1c
.RI "\fBBlink\fP * \fBadd\fP (\fBBcomponent\fP *comp1, \fBBcomponent\fP *comp2, double d, double r)"
.br
.ti -1c
.RI "\fBBlink\fP * \fBadd\fP (\fBBlink\fP *l)"
.br
.ti -1c
.RI "\fBBlink\fP * \fBfind\fP (\fBBcomponent\fP *comp1, \fBBcomponent\fP *comp2)"
.br
.ti -1c
.RI "\fBBlink\fP * \fBfind\fP (string s1, string s2)"
.br
.ti -1c
.RI "long \fBindex\fP (\fBBcomponent\fP *comp1, \fBBcomponent\fP *comp2)"
.br
.ti -1c
.RI "long \fBcount\fP ()"
.br
.ti -1c
.RI "bool \fBcheck\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlink\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBcomponent\fP * \fBcomp\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 466 of file rwmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Blink::Blink ()\fC [inline]\fP"

.PP
Definition at line 496 of file rwmodel\&.h\&.
.SS "Blink::Blink (\fBBcomponent\fP * comp1, \fBBcomponent\fP * comp2)\fC [inline]\fP"

.PP
Definition at line 497 of file rwmodel\&.h\&.
.SS "Blink::Blink (\fBBcomponent\fP * comp1, \fBBcomponent\fP * comp2, double d, double r)\fC [inline]\fP"

.PP
Definition at line 501 of file rwmodel\&.h\&.
.SS "Blink::Blink (\fBBlink\fP * l)\fC [inline]\fP"

.PP
Definition at line 507 of file rwmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBlink\fP* Blink::add (\fBBcomponent\fP * comp1, \fBBcomponent\fP * comp2)\fC [inline]\fP"

.PP
Definition at line 532 of file rwmodel\&.h\&.
.SS "\fBBlink\fP* Blink::add (\fBBcomponent\fP * comp1, \fBBcomponent\fP * comp2, double d, double r)\fC [inline]\fP"

.PP
Definition at line 537 of file rwmodel\&.h\&.
.SS "\fBBlink\fP* Blink::add (\fBBlink\fP * l)\fC [inline]\fP"

.PP
Definition at line 542 of file rwmodel\&.h\&.
.SS "void Blink::adopt_component_color ()\fC [inline]\fP"

.PP
Definition at line 524 of file rwmodel\&.h\&.
.SS "double Blink::angle ()\fC [inline]\fP"

.PP
Definition at line 517 of file rwmodel\&.h\&.
.SS "void Blink::angle (double a)\fC [inline]\fP"

.PP
Definition at line 516 of file rwmodel\&.h\&.
.SS "bool Blink::check ()\fC [inline]\fP"

.PP
Definition at line 579 of file rwmodel\&.h\&.
.SS "\fBRGBA\fP<float>& Blink::color ()\fC [inline]\fP"

.PP
Definition at line 523 of file rwmodel\&.h\&.
.SS "void Blink::color (\fBRGBA\fP< float > c)\fC [inline]\fP"

.PP
Definition at line 522 of file rwmodel\&.h\&.
.SS "long Blink::count ()\fC [inline]\fP"

.PP
Definition at line 574 of file rwmodel\&.h\&.
.SS "\fBBlink\fP* Blink::find (\fBBcomponent\fP * comp1, \fBBcomponent\fP * comp2)\fC [inline]\fP"

.PP
Definition at line 547 of file rwmodel\&.h\&.
.SS "\fBBlink\fP* Blink::find (string s1, string s2)\fC [inline]\fP"

.PP
Definition at line 556 of file rwmodel\&.h\&.
.SS "double Blink::FOM ()\fC [inline]\fP"

.PP
Definition at line 528 of file rwmodel\&.h\&.
.SS "void Blink::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 527 of file rwmodel\&.h\&.
.SS "long Blink::index (\fBBcomponent\fP * comp1, \fBBcomponent\fP * comp2)\fC [inline]\fP"

.PP
Definition at line 564 of file rwmodel\&.h\&.
.SS "double Blink::length ()\fC [inline]\fP"

.PP
Definition at line 519 of file rwmodel\&.h\&.
.SS "void Blink::length (double d)\fC [inline]\fP"

.PP
Definition at line 518 of file rwmodel\&.h\&.
.SS "double Blink::radius ()\fC [inline]\fP"

.PP
Definition at line 521 of file rwmodel\&.h\&.
.SS "void Blink::radius (double r)\fC [inline]\fP"

.PP
Definition at line 520 of file rwmodel\&.h\&.
.SS "long Blink::select ()\fC [inline]\fP"

.PP
Definition at line 530 of file rwmodel\&.h\&.
.SS "void Blink::select (long i)\fC [inline]\fP"

.PP
Definition at line 529 of file rwmodel\&.h\&.
.SS "long Blink::select_increment ()\fC [inline]\fP"

.PP
Definition at line 531 of file rwmodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBcomponent\fP* Blink::comp[2]"

.PP
Definition at line 487 of file rwmodel\&.h\&.
.SS "\fBBlink\fP* Blink::next"

.PP
Definition at line 486 of file rwmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
