.TH "Blinktype" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blinktype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlinktype\fP ()"
.br
.ti -1c
.RI "\fBBlinktype\fP (string &id1, string &id2)"
.br
.ti -1c
.RI "\fBBlinktype\fP (string &id1, string &id2, double d)"
.br
.ti -1c
.RI "void \fBidentifier\fP (string s, int i)"
.br
.ti -1c
.RI "string & \fBidentifier\fP (int i)"
.br
.ti -1c
.RI "void \fBlength\fP (double d)"
.br
.ti -1c
.RI "double \fBlength\fP ()"
.br
.ti -1c
.RI "void \fBdistance\fP (double d)"
.br
.ti -1c
.RI "double \fBdistance\fP ()"
.br
.ti -1c
.RI "void \fBKlength\fP (double d)"
.br
.ti -1c
.RI "double \fBKlength\fP ()"
.br
.ti -1c
.RI "void \fBKdistance\fP (double d)"
.br
.ti -1c
.RI "double \fBKdistance\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 185 of file rwmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Blinktype::Blinktype ()\fC [inline]\fP"

.PP
Definition at line 201 of file rwmodel\&.h\&.
.SS "Blinktype::Blinktype (string & id1, string & id2)\fC [inline]\fP"

.PP
Definition at line 202 of file rwmodel\&.h\&.
.SS "Blinktype::Blinktype (string & id1, string & id2, double d)\fC [inline]\fP"

.PP
Definition at line 207 of file rwmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double Blinktype::distance ()\fC [inline]\fP"

.PP
Definition at line 218 of file rwmodel\&.h\&.
.SS "void Blinktype::distance (double d)\fC [inline]\fP"

.PP
Definition at line 217 of file rwmodel\&.h\&.
.SS "double Blinktype::FOM ()\fC [inline]\fP"

.PP
Definition at line 224 of file rwmodel\&.h\&.
.SS "void Blinktype::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 223 of file rwmodel\&.h\&.
.SS "string& Blinktype::identifier (int i)\fC [inline]\fP"

.PP
Definition at line 214 of file rwmodel\&.h\&.
.SS "void Blinktype::identifier (string s, int i)\fC [inline]\fP"

.PP
Definition at line 213 of file rwmodel\&.h\&.
.SS "double Blinktype::Kdistance ()\fC [inline]\fP"

.PP
Definition at line 222 of file rwmodel\&.h\&.
.SS "void Blinktype::Kdistance (double d)\fC [inline]\fP"

.PP
Definition at line 221 of file rwmodel\&.h\&.
.SS "double Blinktype::Klength ()\fC [inline]\fP"

.PP
Definition at line 220 of file rwmodel\&.h\&.
.SS "void Blinktype::Klength (double d)\fC [inline]\fP"

.PP
Definition at line 219 of file rwmodel\&.h\&.
.SS "double Blinktype::length ()\fC [inline]\fP"

.PP
Definition at line 216 of file rwmodel\&.h\&.
.SS "void Blinktype::length (double d)\fC [inline]\fP"

.PP
Definition at line 215 of file rwmodel\&.h\&.
.SS "long Blinktype::select ()\fC [inline]\fP"

.PP
Definition at line 226 of file rwmodel\&.h\&.
.SS "void Blinktype::select (long i)\fC [inline]\fP"

.PP
Definition at line 225 of file rwmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
