.TH "Bmarker" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmarker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marker\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBmarker\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBimg_num\fP"
.br
.ti -1c
.RI "\fBVector3\fP< float > \fBloc\fP"
.br
.ti -1c
.RI "\fBVector3\fP< float > \fBerr\fP"
.br
.ti -1c
.RI "float \fBres\fP"
.br
.ti -1c
.RI "float \fBfom\fP"
.br
.ti -1c
.RI "int \fBsel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file marker\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVector3\fP<float> Bmarker::err"

.PP
Definition at line 26 of file marker\&.h\&.
.SS "float Bmarker::fom"

.PP
Definition at line 28 of file marker\&.h\&.
.SS "int Bmarker::id"

.PP
Definition at line 23 of file marker\&.h\&.
.SS "int Bmarker::img_num"

.PP
Definition at line 24 of file marker\&.h\&.
.SS "\fBVector3\fP<float> Bmarker::loc"

.PP
Definition at line 25 of file marker\&.h\&.
.SS "\fBBmarker\fP* Bmarker::next"

.PP
Definition at line 22 of file marker\&.h\&.
.SS "float Bmarker::res"

.PP
Definition at line 27 of file marker\&.h\&.
.SS "int Bmarker::sel"

.PP
Definition at line 29 of file marker\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
