.TH "Bmaterial" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmaterial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel_param\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBidentifier\fP (string s)"
.br
.ti -1c
.RI "string \fBidentifier\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.ti -1c
.RI "void \fBdensity\fP (double d, int u)"
.br
.ti -1c
.RI "double \fBdensity\fP (int u)"
.br
.ti -1c
.RI "double \fBgram_per_cm3\fP ()"
.br
.ti -1c
.RI "double \fBdalton_per_angstrom3\fP ()"
.br
.ti -1c
.RI "double \fBnumber_per_angstrom3\fP ()"
.br
.ti -1c
.RI "double \fBunit\fP (int u)"
.br
.ti -1c
.RI "int \fBunit\fP ()"
.br
.ti -1c
.RI "map< string, \fBBcomptype\fP > & \fBcomposition\fP ()"
.br
.ti -1c
.RI "\fBBcomptype\fP & \fBoperator[]\fP (string s)"
.br
.ti -1c
.RI "long \fBnumber\fP ()"
.br
.ti -1c
.RI "double \fBmass\fP ()"
.br
.ti -1c
.RI "void \fBmass\fP (double m)"
.br
.ti -1c
.RI "void \fBupdate_parameters\fP (map< string, \fBBcomptype\fP > &types)"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file rwmodel_param\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "map<string,\fBBcomptype\fP>& Bmaterial::composition ()\fC [inline]\fP"

.PP
Definition at line 156 of file rwmodel_param\&.h\&.
.SS "double Bmaterial::dalton_per_angstrom3 ()\fC [inline]\fP"

.PP
Definition at line 137 of file rwmodel_param\&.h\&.
.SS "void Bmaterial::density (double d, int u)\fC [inline]\fP"

.PP
Definition at line 126 of file rwmodel_param\&.h\&.
.SS "double Bmaterial::density (int u)\fC [inline]\fP"

.PP
Definition at line 127 of file rwmodel_param\&.h\&.
.SS "double Bmaterial::gram_per_cm3 ()\fC [inline]\fP"

.PP
Definition at line 132 of file rwmodel_param\&.h\&.
.SS "string Bmaterial::identifier ()\fC [inline]\fP"

.PP
Definition at line 123 of file rwmodel_param\&.h\&.
.SS "void Bmaterial::identifier (string s)\fC [inline]\fP"

.PP
Definition at line 122 of file rwmodel_param\&.h\&.
.SS "double Bmaterial::mass ()\fC [inline]\fP"

.PP
Definition at line 163 of file rwmodel_param\&.h\&.
.SS "void Bmaterial::mass (double m)\fC [inline]\fP"

.PP
Definition at line 168 of file rwmodel_param\&.h\&.
.SS "long Bmaterial::number ()\fC [inline]\fP"

.PP
Definition at line 158 of file rwmodel_param\&.h\&.
.SS "double Bmaterial::number_per_angstrom3 ()\fC [inline]\fP"

.PP
Definition at line 142 of file rwmodel_param\&.h\&.
.SS "\fBBcomptype\fP& Bmaterial::operator[] (string s)\fC [inline]\fP"

.PP
Definition at line 157 of file rwmodel_param\&.h\&.
.SS "long Bmaterial::select ()\fC [inline]\fP"

.PP
Definition at line 125 of file rwmodel_param\&.h\&.
.SS "void Bmaterial::select (long i)\fC [inline]\fP"

.PP
Definition at line 124 of file rwmodel_param\&.h\&.
.SS "void Bmaterial::show ()\fC [inline]\fP"

.PP
Definition at line 185 of file rwmodel_param\&.h\&.
.SS "int Bmaterial::unit ()\fC [inline]\fP"

.PP
Definition at line 155 of file rwmodel_param\&.h\&.
.SS "double Bmaterial::unit (int u)\fC [inline]\fP"

.PP
Definition at line 147 of file rwmodel_param\&.h\&.
.SS "void Bmaterial::update_parameters (map< string, \fBBcomptype\fP > & types)\fC [inline]\fP"

.PP
Definition at line 172 of file rwmodel_param\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
