.TH "/Users/bernard/b20/bsoft/src/bmgft.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmgft.cpp \- Disk-based 3D reconstruction for a tomography series\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_tomo_rec\&.h'\fP
.br
\fC#include 'mg_tomography\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Disk-based 3D reconstruction for a tomography series\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20060110 
.PP
Modified: 20090401 
.RE
.PP

.PP
Definition in file \fBbmgft\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 44 of file bmgft\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bmgft [options] input\&.star [input2\&.star]",
"-----------------------------------------------",
"Fourier transforms micrographs from a tomographic tilt series\&.",
" ",
"Actions:",
"-removemarkers 14        Mask out markers with this radius (pixels) before transformation\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-select 23,45,66         Micrograph selection (default all)\&.",
"-size 1024,1024,200      Intended reconstruction size (default from micrograph)\&.",
"-scale 0\&.5               Scale of intended reconstruction (default 1)\&.",
"-pad 3                   Image padding factor (default 2)\&.",
"-fill 127                Fill value for erasing/painting markers (default average)\&.",
" ",
"Output:",
"-output file\&.star        Output STAR file name\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bmgft\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
