.TH "Bmolgroup" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmolgroup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmolecule\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBmolgroup\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfilename\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBid\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBcomment\fP"
.br
.ti -1c
.RI "int \fBspacegroup\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBpointgroup\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBsgstring\fP"
.br
.ti -1c
.RI "\fBUnitCell\fP \fBunitcell\fP"
.br
.ti -1c
.RI "long \fBmaxlen\fP"
.br
.ti -1c
.RI "long \fBmaxnalen\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBmin\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBmax\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBbox\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBselect\fP"
.br
.ti -1c
.RI "int \fBsel\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "int * \fBseqflag\fP"
.br
.ti -1c
.RI "\fBBmolecule\fP * \fBmol\fP"
.br
.ti -1c
.RI "\fBBbond\fP * \fBbond\fP"
.br
.ti -1c
.RI "\fBBangle\fP * \fBangle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file rwmolecule\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBangle\fP* Bmolgroup::angle"

.PP
Definition at line 191 of file rwmolecule\&.h\&.
.SS "\fBBbond\fP* Bmolgroup::bond"

.PP
Definition at line 190 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Bmolgroup::box"

.PP
Definition at line 184 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolgroup::comment"

.PP
Definition at line 175 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolgroup::filename"

.PP
Definition at line 172 of file rwmolecule\&.h\&.
.SS "double Bmolgroup::fom"

.PP
Definition at line 187 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolgroup::id"

.PP
Definition at line 174 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Bmolgroup::max"

.PP
Definition at line 183 of file rwmolecule\&.h\&.
.SS "long Bmolgroup::maxlen"

.PP
Definition at line 180 of file rwmolecule\&.h\&.
.SS "long Bmolgroup::maxnalen"

.PP
Definition at line 181 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Bmolgroup::min"

.PP
Definition at line 182 of file rwmolecule\&.h\&.
.SS "\fBBmolecule\fP* Bmolgroup::mol"

.PP
Definition at line 189 of file rwmolecule\&.h\&.
.SS "\fBBmolgroup\fP* Bmolgroup::next"

.PP
Definition at line 171 of file rwmolecule\&.h\&.
.SS "int Bmolgroup::num"

.PP
Definition at line 173 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolgroup::pointgroup"

.PP
Definition at line 177 of file rwmolecule\&.h\&.
.SS "int Bmolgroup::sel"

.PP
Definition at line 186 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolgroup::select"

.PP
Definition at line 185 of file rwmolecule\&.h\&.
.SS "int* Bmolgroup::seqflag"

.PP
Definition at line 188 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolgroup::sgstring"

.PP
Definition at line 178 of file rwmolecule\&.h\&.
.SS "int Bmolgroup::spacegroup"

.PP
Definition at line 176 of file rwmolecule\&.h\&.
.SS "\fBUnitCell\fP Bmolgroup::unitcell"

.PP
Definition at line 179 of file rwmolecule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
