.TH "Bmolecule" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmolecule
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmolecule\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBmolecule\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBid\fP"
.br
.ti -1c
.RI "long \fBnres\fP"
.br
.ti -1c
.RI "long \fBnbase\fP"
.br
.ti -1c
.RI "long \fBfirst_codon\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBseq\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBnaseq\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBmin\fP"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBmax\fP"
.br
.ti -1c
.RI "double \fBBmin\fP"
.br
.ti -1c
.RI "double \fBBmax\fP"
.br
.ti -1c
.RI "double \fBBave\fP"
.br
.ti -1c
.RI "double \fBBstd\fP"
.br
.ti -1c
.RI "int \fBsel\fP"
.br
.ti -1c
.RI "double \fBfom\fP"
.br
.ti -1c
.RI "\fBBresidue\fP * \fBres\fP"
.br
.ti -1c
.RI "\fBBsecondary\fP * \fBsec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file rwmolecule\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Bmolecule::Bave"

.PP
Definition at line 119 of file rwmolecule\&.h\&.
.SS "double Bmolecule::Bmax"

.PP
Definition at line 118 of file rwmolecule\&.h\&.
.SS "double Bmolecule::Bmin"

.PP
Definition at line 118 of file rwmolecule\&.h\&.
.SS "double Bmolecule::Bstd"

.PP
Definition at line 119 of file rwmolecule\&.h\&.
.SS "long Bmolecule::first_codon"

.PP
Definition at line 113 of file rwmolecule\&.h\&.
.SS "double Bmolecule::fom"

.PP
Definition at line 121 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolecule::id"

.PP
Definition at line 110 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Bmolecule::max"

.PP
Definition at line 117 of file rwmolecule\&.h\&.
.SS "\fBVector3\fP<double> Bmolecule::min"

.PP
Definition at line 116 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolecule::naseq"

.PP
Definition at line 115 of file rwmolecule\&.h\&.
.SS "long Bmolecule::nbase"

.PP
Definition at line 112 of file rwmolecule\&.h\&.
.SS "\fBBmolecule\fP* Bmolecule::next"

.PP
Definition at line 108 of file rwmolecule\&.h\&.
.SS "long Bmolecule::nres"

.PP
Definition at line 111 of file rwmolecule\&.h\&.
.SS "int Bmolecule::num"

.PP
Definition at line 109 of file rwmolecule\&.h\&.
.SS "\fBBresidue\fP* Bmolecule::res"

.PP
Definition at line 122 of file rwmolecule\&.h\&.
.SS "\fBBsecondary\fP* Bmolecule::sec"

.PP
Definition at line 123 of file rwmolecule\&.h\&.
.SS "int Bmolecule::sel"

.PP
Definition at line 120 of file rwmolecule\&.h\&.
.SS "\fBBstring\fP Bmolecule::seq"

.PP
Definition at line 114 of file rwmolecule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
