.TH "Bmontage" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bmontage
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBncol\fP"
.br
.ti -1c
.RI "int \fBnrow\fP"
.br
.ti -1c
.RI "int \fBfirst\fP"
.br
.ti -1c
.RI "int \fBskip\fP"
.br
.ti -1c
.RI "int \fBpad\fP"
.br
.ti -1c
.RI "int \fBflip\fP"
.br
.ti -1c
.RI "double \fBfill\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file tcltk_bimage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double Bmontage::fill"

.PP
Definition at line 30 of file tcltk_bimage\&.cpp\&.
.SS "int Bmontage::first"

.PP
Definition at line 29 of file tcltk_bimage\&.cpp\&.
.SS "int Bmontage::flip"

.PP
Definition at line 29 of file tcltk_bimage\&.cpp\&.
.SS "int Bmontage::ncol"

.PP
Definition at line 28 of file tcltk_bimage\&.cpp\&.
.SS "int Bmontage::nrow"

.PP
Definition at line 28 of file tcltk_bimage\&.cpp\&.
.SS "int Bmontage::pad"

.PP
Definition at line 29 of file tcltk_bimage\&.cpp\&.
.SS "int Bmontage::skip"

.PP
Definition at line 29 of file tcltk_bimage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
