.TH "/Users/bernard/b20/bsoft/src/bmontage.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bmontage.cpp \- A program to generate a montage from a 3D image or a set of 2D images\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'img_combine\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
A program to generate a montage from a 3D image or a set of 2D images\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20001126 
.PP
Modified: 20170117 
.RE
.PP

.PP
Definition in file \fBbmontage\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 41 of file bmontage\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bmontage [options] input\&.img output\&.img",
"----------------------------------------------",
"Generates a montage from a 3D image or a set of 2D images",
" ",
"Actions:",
"-slices 3,4              Montage a 3D image in columns and rows (0,0: automatically calculated)\&.",
"-images 3,4              Montage 2D images in columns and rows (0,0: automatically calculated)\&.",
"-flip y                  Flip panel order on the x and/or y axis\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-first 12                First slice in 3D or first 2D image (default: 0)\&.",
"-skip 2                  Number of slices or images to skip (default: 0)\&.",
"-pad 5                   Padding to add around slices or images (default 0)\&.",
"-fill 127                Fill value for padding (default average)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 19 of file bmontage\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
