.TH "/Users/bernard/b20/bsoft/src/bnad.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bnad.cpp \- Image denoising by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image denoising by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&. 


.PP
\fBAuthor\fP
.RS 4
Achilleas Frangakis 
.PP
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20020803 
.PP
Modified: 20161210 (BH) 
.RE
.PP

.PP
Definition in file \fBbnad\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 48 of file bnad\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: bnad [options] input\&.img output\&.img",
"------------------------------------------",
"Denoises by nonlinear anisotropic diffusion: Coherence and edge enhancing diffusion\&.",
"The default is edge enhancing diffusion\&.",
"Coherence enhancing diffusion is used if the coherence parameter is specified\&.",
"Diffusion is faster for higher lambda (1e-6 to 10 have been tested)\&.",
" ",
"Actions:",
"-lambda 0\&.3              Lambda: edge enhancing diffusion (default 0\&.1)\&.",
"-coherence 0\&.002         Coherence: coherence enhancing diffusion\&.",
"-sigma 2\&.5               Initial gaussian smoothing coefficient (default no smoothing)\&.",
" ",
"Parameters:",
"-verbose 7               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-iterations 80           Iterations (default 1)\&.",
"-slabsize 20             Slab size for piece-wise processing (default z size)\&.",
"-output 5                Number of iterations between writing output maps (default 100)\&.",
" ",
"Parameters for coherence enhancing diffusion:",
"-alpha 0\&.001             Alpha (default 0\&.001)\&.",
"-rho 4                   Gaussian smoothing of structure tensor (default 6)\&.",
" ",
NULL
}
.fi
.PP
Definition at line 20 of file bnad\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
