.TH "Boption" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boption \- A class for a command line input option\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoption\fP (char *arg, char *arg1, const char *\fBuse\fP[])"
.br
.ti -1c
.RI "int \fBerrors\fP ()"
.br
.ti -1c
.RI "\fBBstring\fP \fBfilename\fP ()"
.br
.ti -1c
.RI "\fBDataType\fP \fBdatatype\fP ()"
.br
.ti -1c
.RI "long \fBinteger\fP ()"
.br
.ti -1c
.RI "double \fBreal\fP ()"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > long \fBvalues\fP (T1 &v1, T2 &v2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 > long \fBvalues\fP (T1 &v1, T2 &v2, T3 &v3)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 > long \fBvalues\fP (T1 &v1, T2 &v2, T3 &v3, T4 &v4)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > long \fBvalues\fP (T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5)"
.br
.ti -1c
.RI "double \fBfill\fP (int &fill_type)"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBvector3\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBnormalized_vector3\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< long > \fBsize\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< long > \fBsize2\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBorigin\fP ()"
.br
.ti -1c
.RI "\fBVector3\fP< double > \fBscale\fP ()"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > long \fBline\fP (\fBVector3\fP< T1 > &st, \fBVector3\fP< T2 > &en)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > long \fBbox\fP (\fBVector3\fP< T1 > &st, \fBVector3\fP< T2 > &sz)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > long \fBbox\fP (vector< T1 > &st, vector< T2 > &sz)"
.br
.ti -1c
.RI "\fBBstring\fP \fBsymmetry_string\fP ()"
.br
.ti -1c
.RI "\fBBsymmetry\fP \fBsymmetry\fP ()"
.br
.ti -1c
.RI "\fBView\fP \fBview\fP ()"
.br
.ti -1c
.RI "\fBEuler\fP \fBeuler\fP ()"
.br
.ti -1c
.RI "double \fBmass\fP ()"
.br
.ti -1c
.RI "\fBUnitCell\fP \fBunit_cell\fP ()"
.br
.ti -1c
.RI "int \fBctf_action\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBoption\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class for a command line input option\&. 


.PP
.nf
Each option is defined by a tag (i.e., the string following a hyphen)
and a value (the next string after the tag).

.fi
.PP
 
.PP
Definition at line 26 of file options\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Boption::Boption (char * arg, char * arg1, const char * use[])\fC [inline]\fP"

.PP
Definition at line 34 of file options\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 > long Boption::box (\fBVector3\fP< T1 > & st, \fBVector3\fP< T2 > & sz)\fC [inline]\fP"

.PP
Definition at line 225 of file options\&.h\&.
.SS "template<typename T1 , typename T2 > long Boption::box (vector< T1 > & st, vector< T2 > & sz)\fC [inline]\fP"

.PP
Definition at line 241 of file options\&.h\&.
.SS "int Boption::ctf_action ()\fC [inline]\fP"

.PP
Definition at line 315 of file options\&.h\&.
.SS "\fBDataType\fP Boption::datatype ()\fC [inline]\fP"

.PP
Definition at line 93 of file options\&.h\&.
.SS "int Boption::errors ()\fC [inline]\fP"

.PP
Definition at line 79 of file options\&.h\&.
.SS "\fBEuler\fP Boption::euler ()\fC [inline]\fP"

.PP
Definition at line 283 of file options\&.h\&.
.SS "\fBBstring\fP Boption::filename ()\fC [inline]\fP"

.PP
Definition at line 85 of file options\&.h\&.
.SS "double Boption::fill (int & fill_type)\fC [inline]\fP"

.PP
Definition at line 148 of file options\&.h\&.
.SS "long Boption::integer ()\fC [inline]\fP"

.PP
Definition at line 100 of file options\&.h\&.
.SS "template<typename T1 , typename T2 > long Boption::line (\fBVector3\fP< T1 > & st, \fBVector3\fP< T2 > & en)\fC [inline]\fP"

.PP
Definition at line 212 of file options\&.h\&.
.SS "double Boption::mass ()\fC [inline]\fP"

.PP
Definition at line 293 of file options\&.h\&.
.SS "\fBVector3\fP<double> Boption::normalized_vector3 ()\fC [inline]\fP"

.PP
Definition at line 168 of file options\&.h\&.
.SS "\fBVector3\fP<double> Boption::origin ()\fC [inline]\fP"

.PP
Definition at line 190 of file options\&.h\&.
.SS "double Boption::real ()\fC [inline]\fP"

.PP
Definition at line 107 of file options\&.h\&.
.SS "\fBVector3\fP<double> Boption::scale ()\fC [inline]\fP"

.PP
Definition at line 200 of file options\&.h\&.
.SS "\fBVector3\fP<long> Boption::size ()\fC [inline]\fP"

.PP
Definition at line 173 of file options\&.h\&.
.SS "\fBVector3\fP<long> Boption::size2 ()\fC [inline]\fP"

.PP
Definition at line 185 of file options\&.h\&.
.SS "\fBBsymmetry\fP Boption::symmetry ()\fC [inline]\fP"

.PP
Definition at line 264 of file options\&.h\&.
.SS "\fBBstring\fP Boption::symmetry_string ()\fC [inline]\fP"

.PP
Definition at line 256 of file options\&.h\&.
.SS "\fBUnitCell\fP Boption::unit_cell ()\fC [inline]\fP"

.PP
Definition at line 303 of file options\&.h\&.
.SS "template<typename T1 , typename T2 > long Boption::values (T1 & v1, T2 & v2)\fC [inline]\fP"

.PP
Definition at line 115 of file options\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 > long Boption::values (T1 & v1, T2 & v2, T3 & v3)\fC [inline]\fP"

.PP
Definition at line 122 of file options\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 > long Boption::values (T1 & v1, T2 & v2, T3 & v3, T4 & v4)\fC [inline]\fP"

.PP
Definition at line 130 of file options\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > long Boption::values (T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5)\fC [inline]\fP"

.PP
Definition at line 139 of file options\&.h\&.
.SS "\fBVector3\fP<double> Boption::vector3 ()\fC [inline]\fP"

.PP
Definition at line 158 of file options\&.h\&.
.SS "\fBView\fP Boption::view ()\fC [inline]\fP"

.PP
Definition at line 271 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBoption\fP* Boption::next"

.PP
Definition at line 28 of file options\&.h\&.
.SS "\fBBstring\fP Boption::tag"

.PP
Definition at line 29 of file options\&.h\&.
.SS "\fBBstring\fP Boption::value"

.PP
Definition at line 30 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
