.TH "Bpage" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bpage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bplot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBpage\fP ()"
.br
.ti -1c
.RI "\fBBpage\fP (long n, long ncol)"
.br
.ti -1c
.RI "\fBBstring\fP & \fBtitle\fP ()"
.br
.ti -1c
.RI "void \fBtitle\fP (const \fBBstring\fP &t)"
.br
.ti -1c
.RI "void \fBtitle\fP (const char *t)"
.br
.ti -1c
.RI "void \fBnumber\fP (long n)"
.br
.ti -1c
.RI "long \fBnumber\fP ()"
.br
.ti -1c
.RI "void \fBcolumns\fP (long ncol)"
.br
.ti -1c
.RI "long \fBcolumns\fP ()"
.br
.ti -1c
.RI "\fBBcolumn\fP & \fBcolumn\fP (long i)"
.br
.ti -1c
.RI "void \fBaxes\fP ()"
.br
.ti -1c
.RI "\fBBaxis\fP & \fBaxis\fP (long id)"
.br
.ti -1c
.RI "\fBBstring\fP * \fBtext\fP ()"
.br
.ti -1c
.RI "void \fBadd_text\fP (\fBBstring\fP &s)"
.br
.ti -1c
.RI "void \fBlimits\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file Bplot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bpage::Bpage ()\fC [inline]\fP"

.PP
Definition at line 97 of file Bplot\&.h\&.
.SS "Bpage::Bpage (long n, long ncol)\fC [inline]\fP"

.PP
Definition at line 98 of file Bplot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Bpage::add_text (\fBBstring\fP & s)\fC [inline]\fP"

.PP
Definition at line 122 of file Bplot\&.h\&.
.SS "void Bpage::axes ()\fC [inline]\fP"

.PP
Definition at line 116 of file Bplot\&.h\&.
.SS "\fBBaxis\fP& Bpage::axis (long id)\fC [inline]\fP"

.PP
Definition at line 117 of file Bplot\&.h\&.
.SS "\fBBcolumn\fP& Bpage::column (long i)\fC [inline]\fP"

.PP
Definition at line 110 of file Bplot\&.h\&.
.SS "long Bpage::columns ()\fC [inline]\fP"

.PP
Definition at line 109 of file Bplot\&.h\&.
.SS "void Bpage::columns (long ncol)\fC [inline]\fP"

.PP
Definition at line 105 of file Bplot\&.h\&.
.SS "void Bpage::limits ()\fC [inline]\fP"

.PP
Definition at line 123 of file Bplot\&.h\&.
.SS "long Bpage::number ()\fC [inline]\fP"

.PP
Definition at line 104 of file Bplot\&.h\&.
.SS "void Bpage::number (long n)\fC [inline]\fP"

.PP
Definition at line 103 of file Bplot\&.h\&.
.SS "\fBBstring\fP* Bpage::text ()\fC [inline]\fP"

.PP
Definition at line 121 of file Bplot\&.h\&.
.SS "\fBBstring\fP& Bpage::title ()\fC [inline]\fP"

.PP
Definition at line 100 of file Bplot\&.h\&.
.SS "void Bpage::title (const \fBBstring\fP & t)\fC [inline]\fP"

.PP
Definition at line 101 of file Bplot\&.h\&.
.SS "void Bpage::title (const char * t)\fC [inline]\fP"

.PP
Definition at line 102 of file Bplot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
