.TH "/Users/bernard/b20/bsoft/src/bpick.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/bpick.cpp \- Pick particles in a micrograph given the particle coordinates, or pick particles in a focal series of micrographs with alignment of the micrographs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_pick\&.h'\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'mg_img_proc\&.h'\fP
.br
\fC#include 'mg_extract\&.h'\fP
.br
\fC#include 'mg_particles\&.h'\fP
.br
\fC#include 'mg_particle_select\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pick particles in a micrograph given the particle coordinates, or pick particles in a focal series of micrographs with alignment of the micrographs\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann and Samuel Payne 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000505 
.PP
Modified: 20200616 (BH) 
.RE
.PP

.PP
Definition in file \fBbpick\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 89 of file bpick\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 24 of file bpick\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
