.TH "/Users/bernard/b20/bsoft/include/Bplot.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/Bplot.h \- Header file for postscript output functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bstring\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaxis\fP"
.br
.ti -1c
.RI "class \fBBcolumn\fP"
.br
.ti -1c
.RI "class \fBBpage\fP"
.br
.ti -1c
.RI "class \fBBplot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBBplot\fP *plot)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for postscript output functions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010515 
.PP
Modified: 20200723 
.RE
.PP

.PP
Definition in file \fBBplot\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & output, \fBBplot\fP * plot)"

.PP
Definition at line 15 of file Bplot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
