.TH "Bpolygon" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bpolygon
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBpolygon\fP ()"
.br
.ti -1c
.RI "\fBBpolygon\fP (\fBBpolygon\fP *p)"
.br
.ti -1c
.RI "long \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBnormal\fP (\fBVector3\fP< float > n)"
.br
.ti -1c
.RI "\fBVector3\fP< float > & \fBnormal\fP ()"
.br
.ti -1c
.RI "void \fBclosed\fP (int i)"
.br
.ti -1c
.RI "int \fBclosed\fP ()"
.br
.ti -1c
.RI "void \fBFOM\fP (double d)"
.br
.ti -1c
.RI "double \fBFOM\fP ()"
.br
.ti -1c
.RI "void \fBselect\fP (long i)"
.br
.ti -1c
.RI "long \fBselect\fP ()"
.br
.ti -1c
.RI "long \fBselect_increment\fP ()"
.br
.ti -1c
.RI "\fBBpolygon\fP * \fBadd\fP (\fBBpolygon\fP *p)"
.br
.ti -1c
.RI "long \fBcount\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBpolygon\fP * \fBnext\fP"
.br
.ti -1c
.RI "vector< \fBBcomponent\fP * > \fBcomp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 597 of file rwmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bpolygon::Bpolygon ()\fC [inline]\fP"

.PP
Definition at line 614 of file rwmodel\&.h\&.
.SS "Bpolygon::Bpolygon (\fBBpolygon\fP * p)\fC [inline]\fP"

.PP
Definition at line 615 of file rwmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBpolygon\fP* Bpolygon::add (\fBBpolygon\fP * p)\fC [inline]\fP"

.PP
Definition at line 632 of file rwmodel\&.h\&.
.SS "int Bpolygon::closed ()\fC [inline]\fP"

.PP
Definition at line 626 of file rwmodel\&.h\&.
.SS "void Bpolygon::closed (int i)\fC [inline]\fP"

.PP
Definition at line 625 of file rwmodel\&.h\&.
.SS "long Bpolygon::count ()\fC [inline]\fP"

.PP
Definition at line 637 of file rwmodel\&.h\&.
.SS "double Bpolygon::FOM ()\fC [inline]\fP"

.PP
Definition at line 628 of file rwmodel\&.h\&.
.SS "void Bpolygon::FOM (double d)\fC [inline]\fP"

.PP
Definition at line 627 of file rwmodel\&.h\&.
.SS "\fBVector3\fP<float>& Bpolygon::normal ()\fC [inline]\fP"

.PP
Definition at line 624 of file rwmodel\&.h\&.
.SS "void Bpolygon::normal (\fBVector3\fP< float > n)\fC [inline]\fP"

.PP
Definition at line 623 of file rwmodel\&.h\&.
.SS "long Bpolygon::select ()\fC [inline]\fP"

.PP
Definition at line 630 of file rwmodel\&.h\&.
.SS "void Bpolygon::select (long i)\fC [inline]\fP"

.PP
Definition at line 629 of file rwmodel\&.h\&.
.SS "long Bpolygon::select_increment ()\fC [inline]\fP"

.PP
Definition at line 631 of file rwmodel\&.h\&.
.SS "long Bpolygon::size ()\fC [inline]\fP"

.PP
Definition at line 622 of file rwmodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBBcomponent\fP*> Bpolygon::comp"

.PP
Definition at line 607 of file rwmodel\&.h\&.
.SS "\fBBpolygon\fP* Bpolygon::next"

.PP
Definition at line 606 of file rwmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
