.TH "Bproject" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bproject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mg_processing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBproject\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBproject\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfilename\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBcomment\fP"
.br
.ti -1c
.RI "int \fBsplit\fP"
.br
.ti -1c
.RI "\fBBstring\fP * \fBreference\fP"
.br
.ti -1c
.RI "int \fBselect\fP"
.br
.ti -1c
.RI "int \fBeuler_flag\fP"
.br
.ti -1c
.RI "int \fBomega_flag\fP"
.br
.ti -1c
.RI "\fBFOMType\fP \fBfom_tag\fP [\fBNFOM\fP]"
.br
.ti -1c
.RI "\fBBfield\fP * \fBfield\fP"
.br
.ti -1c
.RI "\fBBreconstruction\fP * \fBrec\fP"
.br
.ti -1c
.RI "\fBBparticle\fP * \fBclass_avg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 504 of file mg_processing\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bproject::Bproject ()\fC [inline]\fP"

.PP
Definition at line 534 of file mg_processing\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBparticle\fP* Bproject::class_avg"

.PP
Definition at line 533 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bproject::comment"

.PP
Definition at line 524 of file mg_processing\&.h\&.
.SS "int Bproject::euler_flag"

.PP
Definition at line 528 of file mg_processing\&.h\&.
.SS "\fBBfield\fP* Bproject::field"

.PP
Definition at line 531 of file mg_processing\&.h\&.
.SS "\fBBstring\fP Bproject::filename"

.PP
Definition at line 523 of file mg_processing\&.h\&.
.SS "\fBFOMType\fP Bproject::fom_tag[\fBNFOM\fP]"

.PP
Definition at line 530 of file mg_processing\&.h\&.
.SS "\fBBproject\fP* Bproject::next"

.PP
Definition at line 522 of file mg_processing\&.h\&.
.SS "int Bproject::omega_flag"

.PP
Definition at line 529 of file mg_processing\&.h\&.
.SS "\fBBreconstruction\fP* Bproject::rec"

.PP
Definition at line 532 of file mg_processing\&.h\&.
.SS "\fBBstring\fP* Bproject::reference"

.PP
Definition at line 526 of file mg_processing\&.h\&.
.SS "int Bproject::select"

.PP
Definition at line 527 of file mg_processing\&.h\&.
.SS "int Bproject::split"

.PP
Definition at line 525 of file mg_processing\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
