.TH "Bresidue" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bresidue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmolecule\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBresidue\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "char \fBinsert\fP [2]"
.br
.ti -1c
.RI "char \fBtype\fP [6]"
.br
.ti -1c
.RI "\fBBatom\fP * \fBatom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file rwmolecule\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBatom\fP* Bresidue::atom"

.PP
Definition at line 54 of file rwmolecule\&.h\&.
.SS "char Bresidue::insert[2]"

.PP
Definition at line 52 of file rwmolecule\&.h\&.
.SS "\fBBresidue\fP* Bresidue::next"

.PP
Definition at line 50 of file rwmolecule\&.h\&.
.SS "int Bresidue::num"

.PP
Definition at line 51 of file rwmolecule\&.h\&.
.SS "char Bresidue::type[6]"

.PP
Definition at line 53 of file rwmolecule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
