.TH "Bresidue_matrix" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bresidue_matrix
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwresprop\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBc\fP"
.br
.ti -1c
.RI "float * \fBm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file rwresprop\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBstring\fP Bresidue_matrix::c"

.PP
Definition at line 46 of file rwresprop\&.h\&.
.SS "float* Bresidue_matrix::m"

.PP
Definition at line 47 of file rwresprop\&.h\&.
.SS "int Bresidue_matrix::n"

.PP
Definition at line 45 of file rwresprop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
