.TH "Bresidue_type" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bresidue_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwresprop\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBresidue_type\fP * \fBnext\fP"
.br
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "char \fBcod\fP [3]"
.br
.ti -1c
.RI "float \fBmass\fP"
.br
.ti -1c
.RI "float \fBvol\fP"
.br
.ti -1c
.RI "float \fBext\fP"
.br
.ti -1c
.RI "float \fBextsd\fP"
.br
.ti -1c
.RI "float \fBcharge\fP"
.br
.ti -1c
.RI "float \fBhphob\fP"
.br
.ti -1c
.RI "float \fBcomp\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file rwresprop\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char Bresidue_type::c"

.PP
Definition at line 24 of file rwresprop\&.h\&.
.SS "float Bresidue_type::charge"

.PP
Definition at line 30 of file rwresprop\&.h\&.
.SS "char Bresidue_type::cod[3]"

.PP
Definition at line 25 of file rwresprop\&.h\&.
.SS "float Bresidue_type::comp[5]"

.PP
Definition at line 32 of file rwresprop\&.h\&.
.SS "float Bresidue_type::ext"

.PP
Definition at line 28 of file rwresprop\&.h\&.
.SS "float Bresidue_type::extsd"

.PP
Definition at line 29 of file rwresprop\&.h\&.
.SS "float Bresidue_type::hphob"

.PP
Definition at line 31 of file rwresprop\&.h\&.
.SS "float Bresidue_type::mass"

.PP
Definition at line 26 of file rwresprop\&.h\&.
.SS "\fBBresidue_type\fP* Bresidue_type::next"

.PP
Definition at line 23 of file rwresprop\&.h\&.
.SS "float Bresidue_type::vol"

.PP
Definition at line 27 of file rwresprop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
