.TH "Bsecondary" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bsecondary
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwmolecule\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBsecondary\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBSecondaryType\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "char \fBid\fP [4]"
.br
.ti -1c
.RI "int \fBsense\fP"
.br
.ti -1c
.RI "int \fBnstrands\fP"
.br
.ti -1c
.RI "\fBBresidue\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBBresidue\fP * \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file rwmolecule\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBresidue\fP* Bsecondary::first"

.PP
Definition at line 94 of file rwmolecule\&.h\&.
.SS "char Bsecondary::id[4]"

.PP
Definition at line 91 of file rwmolecule\&.h\&.
.SS "\fBBresidue\fP* Bsecondary::last"

.PP
Definition at line 95 of file rwmolecule\&.h\&.
.SS "\fBBsecondary\fP* Bsecondary::next"

.PP
Definition at line 88 of file rwmolecule\&.h\&.
.SS "int Bsecondary::nstrands"

.PP
Definition at line 93 of file rwmolecule\&.h\&.
.SS "int Bsecondary::num"

.PP
Definition at line 90 of file rwmolecule\&.h\&.
.SS "int Bsecondary::sense"

.PP
Definition at line 92 of file rwmolecule\&.h\&.
.SS "\fBSecondaryType\fP Bsecondary::type"

.PP
Definition at line 89 of file rwmolecule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
