.TH "Bstar" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bstar \- Overall STAR class to hold all data blocks and options for I/O\&.\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwstar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsplit\fP"
.br
.ti -1c
.RI "int \fBline_length\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBcomment\fP"
.br
.ti -1c
.RI "\fBBstar_block\fP * \fBblock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Overall STAR class to hold all data blocks and options for I/O\&.\&. 


.PP
.nf
The split flag allows the user to output data blocks in separate files
in stead of one big file.
The line length field allows the user to output long lines without
wrapping it around.
The comments are ignored but output to the a new file - this can be used
to document the history of the file.
The STAR database is a hierarchy consisting of blocks, each with a set
of items.

.fi
.PP
 
.PP
Definition at line 78 of file rwstar\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBstar_block\fP* Bstar::block"

.PP
Definition at line 82 of file rwstar\&.h\&.
.SS "\fBBstring\fP Bstar::comment"

.PP
Definition at line 81 of file rwstar\&.h\&.
.SS "int Bstar::line_length"

.PP
Definition at line 80 of file rwstar\&.h\&.
.SS "int Bstar::split"

.PP
Definition at line 79 of file rwstar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
