.TH "Bstar_item" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bstar_item
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwstar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBstar_item\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBStarType\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBloop\fP"
.br
.ti -1c
.RI "int \fBmaxlen\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBcomment\fP"
.br
.ti -1c
.RI "\fBBstring\fP * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file rwstar\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBstring\fP Bstar_item::comment"

.PP
Definition at line 42 of file rwstar\&.h\&.
.SS "\fBBstring\fP* Bstar_item::data"

.PP
Definition at line 43 of file rwstar\&.h\&.
.SS "int Bstar_item::loop"

.PP
Definition at line 40 of file rwstar\&.h\&.
.SS "int Bstar_item::maxlen"

.PP
Definition at line 41 of file rwstar\&.h\&.
.SS "\fBBstar_item\fP* Bstar_item::next"

.PP
Definition at line 37 of file rwstar\&.h\&.
.SS "\fBBstring\fP Bstar_item::tag"

.PP
Definition at line 38 of file rwstar\&.h\&.
.SS "\fBStarType\fP Bstar_item::type"

.PP
Definition at line 39 of file rwstar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
