.TH "Bstar_block" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bstar_block \- Structure for a data block with multiple items in a STAR database\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwstar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBstar_block\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBcomment\fP"
.br
.ti -1c
.RI "\fBBstring\fP \fBfilename\fP"
.br
.ti -1c
.RI "\fBBstar_item\fP * \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for a data block with multiple items in a STAR database\&. 


.PP
.nf
Each data block contains a set set of unique items defined by tags 
and with the associate data as single or multiple values.
The order of the items in the data block are important and preserved.

.fi
.PP
 
.PP
Definition at line 55 of file rwstar\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBstring\fP Bstar_block::comment"

.PP
Definition at line 59 of file rwstar\&.h\&.
.SS "\fBBstring\fP Bstar_block::filename"

.PP
Definition at line 60 of file rwstar\&.h\&.
.SS "\fBBstar_item\fP* Bstar_block::item"

.PP
Definition at line 61 of file rwstar\&.h\&.
.SS "\fBBstar_block\fP* Bstar_block::next"

.PP
Definition at line 56 of file rwstar\&.h\&.
.SS "int Bstar_block::number"

.PP
Definition at line 57 of file rwstar\&.h\&.
.SS "\fBBstring\fP Bstar_block::tag"

.PP
Definition at line 58 of file rwstar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
