.TH "Bsymop" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bsymop
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <symmetry\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBsymop\fP ()"
.br
.ti -1c
.RI "\fBBsymop\fP (double x, double y, double z, int nn, double a)"
.br
.ti -1c
.RI "void \fBorder\fP (int i)"
.br
.ti -1c
.RI "int \fBorder\fP ()"
.br
.ti -1c
.RI "void \fBangle\fP (double a)"
.br
.ti -1c
.RI "double \fBangle\fP ()"
.br
.ti -1c
.RI "void \fBshift\fP (double s)"
.br
.ti -1c
.RI "double \fBshift\fP ()"
.br
.ti -1c
.RI "void \fBaxis\fP (\fBVector3\fP< double > a)"
.br
.ti -1c
.RI "void \fBaxis\fP (double x, double y, double z)"
.br
.ti -1c
.RI "\fBVector3\fP< double > & \fBaxis\fP ()"
.br
.ti -1c
.RI "double \fBnormalize\fP ()"
.br
.ti -1c
.RI "\fBMatrix3\fP \fBmatrix\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file symmetry\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bsymop::Bsymop ()\fC [inline]\fP"

.PP
Definition at line 36 of file symmetry\&.h\&.
.SS "Bsymop::Bsymop (double x, double y, double z, int nn, double a)\fC [inline]\fP"

.PP
Definition at line 37 of file symmetry\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double Bsymop::angle ()\fC [inline]\fP"

.PP
Definition at line 42 of file symmetry\&.h\&.
.SS "void Bsymop::angle (double a)\fC [inline]\fP"

.PP
Definition at line 41 of file symmetry\&.h\&.
.SS "\fBVector3\fP<double>& Bsymop::axis ()\fC [inline]\fP"

.PP
Definition at line 47 of file symmetry\&.h\&.
.SS "void Bsymop::axis (double x, double y, double z)\fC [inline]\fP"

.PP
Definition at line 46 of file symmetry\&.h\&.
.SS "void Bsymop::axis (\fBVector3\fP< double > a)\fC [inline]\fP"

.PP
Definition at line 45 of file symmetry\&.h\&.
.SS "\fBMatrix3\fP Bsymop::matrix ()\fC [inline]\fP"

.PP
Definition at line 49 of file symmetry\&.h\&.
.SS "double Bsymop::normalize ()\fC [inline]\fP"

.PP
Definition at line 48 of file symmetry\&.h\&.
.SS "int Bsymop::order ()\fC [inline]\fP"

.PP
Definition at line 40 of file symmetry\&.h\&.
.SS "void Bsymop::order (int i)\fC [inline]\fP"

.PP
Definition at line 39 of file symmetry\&.h\&.
.SS "double Bsymop::shift ()\fC [inline]\fP"

.PP
Definition at line 44 of file symmetry\&.h\&.
.SS "void Bsymop::shift (double s)\fC [inline]\fP"

.PP
Definition at line 43 of file symmetry\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
