.TH "/Users/bernard/b20/bsoft/src/btube.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/btube.cpp \- Symmetrizes helical tubes with hexagonal lattices\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Symmetrizes helical tubes with hexagonal lattices\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20131022 
.PP
Modified: 20131028 
.RE
.PP

.PP
Definition in file \fBbtube\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 47 of file btube\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
" ",
"Usage: btube [options] input\&.img output\&.img",
"-------------------------------------------",
"Symmetrizes helical tubes with hexagonal lattices\&.",
" ",
"Actions:",
"-lattice 5,9             Lattice parameters (units along u and v vectors)\&.",
"-normalize               Normalize symmetrized output, use for maps close to symmetry (default not)\&.",
"-background              Calculate new background values\&.",
"-rescale -0\&.1,5\&.2        Rescale data to average and standard deviation\&.",
" ",
"Parameters:",
"-verbose 1               Verbosity of output\&.",
"-datatype u              Force writing of a new data type\&.",
"-sampling 1\&.5,1\&.5,1\&.5    Sampling (A/pixel; a single value can be given)\&.",
"-origin 110,50,44        Origin for tube (default 0,0,0 or from image)\&.",
"-constant 95             Lattice constant: distance between units in angstrom (default 1)\&.",
"-zlimits 8,47            Range of slices along the helical axis to use (default 0,inf)\&.",
"-radius 22               Radial limit for symmetrization in pixels (default from image)\&.",
" ",



NULL
}
.fi
.PP
Definition at line 20 of file btube\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
