.TH "CameraDefects" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraDefects
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GainDefectCorrect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBDefectPixel\fP > \fBpixelDefects\fP"
.br
.ti -1c
.RI "std::vector< \fBDefectLines\fP > \fBvLineDefects\fP"
.br
.ti -1c
.RI "std::vector< \fBDefectLines\fP > \fBhLineDefects\fP"
.br
.ti -1c
.RI "std::vector< \fBDefectArea\fP > \fBareaDefects\fP"
.br
.ti -1c
.RI "unsigned \fBnPixelsDefect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file GainDefectCorrect\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBDefectArea\fP> CameraDefects::areaDefects"

.PP
Definition at line 48 of file GainDefectCorrect\&.h\&.
.SS "std::vector<\fBDefectLines\fP> CameraDefects::hLineDefects"

.PP
Definition at line 47 of file GainDefectCorrect\&.h\&.
.SS "unsigned CameraDefects::nPixelsDefect"

.PP
Definition at line 50 of file GainDefectCorrect\&.h\&.
.SS "std::vector<\fBDefectPixel\fP> CameraDefects::pixelDefects"

.PP
Definition at line 45 of file GainDefectCorrect\&.h\&.
.SS "std::vector<\fBDefectLines\fP> CameraDefects::vLineDefects"

.PP
Definition at line 46 of file GainDefectCorrect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
