.TH "CameraDefectNeighborInformation" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraDefectNeighborInformation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DefectMaskingEER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraDefectNeighborInformation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBdefectNeighborInfo_t\fP > \fBneighborSpec\fP"
.br
.ti -1c
.RI "const float * \fBgainImage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file DefectMaskingEER\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CameraDefectNeighborInformation::CameraDefectNeighborInformation ()\fC [inline]\fP"

.PP
Definition at line 31 of file DefectMaskingEER\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const float* CameraDefectNeighborInformation::gainImage"

.PP
Definition at line 29 of file DefectMaskingEER\&.h\&.
.SS "std::vector<\fBdefectNeighborInfo_t\fP> CameraDefectNeighborInformation::neighborSpec"

.PP
Definition at line 28 of file DefectMaskingEER\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
