.TH "ChunkHeader" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkHeader\fP ()"
.br
.ti -1c
.RI "\fBChunkHeader\fP (int s, int o, long l)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsig\fP"
.br
.ti -1c
.RI "int \fBoff\fP"
.br
.ti -1c
.RI "long \fBlen\fP"
.br
.ti -1c
.RI "string \fBtag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file rwND2\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChunkHeader::ChunkHeader ()\fC [inline]\fP"

.PP
Definition at line 26 of file rwND2\&.cpp\&.
.SS "ChunkHeader::ChunkHeader (int s, int o, long l)\fC [inline]\fP"

.PP
Definition at line 27 of file rwND2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "long ChunkHeader::len"

.PP
Definition at line 24 of file rwND2\&.cpp\&.
.SS "int ChunkHeader::off"

.PP
Definition at line 23 of file rwND2\&.cpp\&.
.SS "int ChunkHeader::sig"

.PP
Definition at line 22 of file rwND2\&.cpp\&.
.SS "string ChunkHeader::tag"

.PP
Definition at line 25 of file rwND2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
