.TH "DefectElectronAdder" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefectElectronAdder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DefectMaskingEER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefectElectronAdder\fP ()"
.br
.ti -1c
.RI "unsigned \fBexecute\fP (\fBElectronPos\fP *pListPtr, unsigned nElect, const \fBCameraDefectNeighborInformation\fP &camDefectNeighborInfo)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file DefectMaskingEER\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DefectElectronAdder::DefectElectronAdder ()"

.PP
Definition at line 161 of file DefectMaskingEER\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned DefectElectronAdder::execute (\fBElectronPos\fP * pListPtr, unsigned nElect, const \fBCameraDefectNeighborInformation\fP & camDefectNeighborInfo)"

.PP
Definition at line 168 of file DefectMaskingEER\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
