.TH "DefectNeighborSpec" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefectNeighborSpec
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DefectMaskingEER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefectNeighborSpec\fP ()"
.br
.ti -1c
.RI "\fBDefectNeighborSpec\fP (\fBdefectNeighborInfo_t\fP t, float g)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefectNeighborInfo_t\fP \fBdefectInfo\fP"
.br
.ti -1c
.RI "float \fBgainCoefficient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file DefectMaskingEER\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DefectNeighborSpec::DefectNeighborSpec ()\fC [inline]\fP"

.PP
Definition at line 21 of file DefectMaskingEER\&.h\&.
.SS "DefectNeighborSpec::DefectNeighborSpec (\fBdefectNeighborInfo_t\fP t, float g)\fC [inline]\fP"

.PP
Definition at line 22 of file DefectMaskingEER\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBdefectNeighborInfo_t\fP DefectNeighborSpec::defectInfo"

.PP
Definition at line 18 of file DefectMaskingEER\&.h\&.
.SS "float DefectNeighborSpec::gainCoefficient"

.PP
Definition at line 19 of file DefectMaskingEER\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
