.TH "DefectArea" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefectArea
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GainDefectCorrect\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefectArea\fP (uint16_t bX, uint16_t bY, uint16_t eX, uint16_t eY)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBbeginX\fP"
.br
.ti -1c
.RI "uint16_t \fBbeginY\fP"
.br
.ti -1c
.RI "uint16_t \fBendX\fP"
.br
.ti -1c
.RI "uint16_t \fBendY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file GainDefectCorrect\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DefectArea::DefectArea (uint16_t bX, uint16_t bY, uint16_t eX, uint16_t eY)\fC [inline]\fP"

.PP
Definition at line 35 of file GainDefectCorrect\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t DefectArea::beginX"

.PP
Definition at line 37 of file GainDefectCorrect\&.h\&.
.SS "uint16_t DefectArea::beginY"

.PP
Definition at line 37 of file GainDefectCorrect\&.h\&.
.SS "uint16_t DefectArea::endX"

.PP
Definition at line 38 of file GainDefectCorrect\&.h\&.
.SS "uint16_t DefectArea::endY"

.PP
Definition at line 38 of file GainDefectCorrect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
