.TH "/Users/bernard/b20/bsoft/src/dhand.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/dhand.cpp \- Compare projections of two oppositely handed reconstructions to images of tilted specimens\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_hand\&.h'\fP
.br
\fC#include 'mg_tomography\&.h'\fP
.br
\fC#include 'mg_particle_select\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBhand_get_options_mgselect\fP (\fBBstring\fP &tag, \fBBstring\fP &tagvalue, int *mg_select, int *mg_index, double *mg_ang)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compare projections of two oppositely handed reconstructions to images of tilted specimens\&. 


.PP
\fBAuthor\fP
.RS 4
David Belnap 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20011003 
.PP
Modified: 20121013 (BH) 
.RE
.PP

.PP
Definition in file \fBdhand\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int hand_get_options_mgselect (\fBBstring\fP & tag, \fBBstring\fP & tagvalue, int * mg_select, int * mg_index, double * mg_ang)"

.PP
Definition at line 336 of file dhand\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 84 of file dhand\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 25 of file dhand\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
