.TH "/Users/bernard/b20/bsoft/src/dmerge.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/dmerge.cpp \- Merge images in a defocal or other series, align images before adding together\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_merge\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Merge images in a defocal or other series, align images before adding together\&. 


.PP
\fBAuthor\fP
.RS 4
David Belnap & Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20021004 
.PP
Modified: 20041124 (DB) 
.RE
.PP

.PP
Definition in file \fBdmerge\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 68 of file dmerge\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"

.PP
Definition at line 18 of file dmerge\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
