.TH "DMhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwDM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBendian\fP"
.br
.ti -1c
.RI "int \fBxSize\fP"
.br
.ti -1c
.RI "int \fBySize\fP"
.br
.ti -1c
.RI "int \fBzSize\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "\fBDMDataType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file rwDM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int DMhead::depth"

.PP
Definition at line 27 of file rwDM\&.h\&.
.SS "unsigned int DMhead::endian"

.PP
Definition at line 23 of file rwDM\&.h\&.
.SS "\fBDMDataType\fP DMhead::type"

.PP
Definition at line 28 of file rwDM\&.h\&.
.SS "int DMhead::xSize"

.PP
Definition at line 24 of file rwDM\&.h\&.
.SS "int DMhead::ySize"

.PP
Definition at line 25 of file rwDM\&.h\&.
.SS "int DMhead::zSize"

.PP
Definition at line 26 of file rwDM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
