.TH "ElectronPos" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElectronPos
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElectronCountedFramesDecompressor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElectronPos\fP (uint16_t \fBx\fP, uint16_t \fBy\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBx\fP"
.br
.ti -1c
.RI "uint16_t \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file ElectronCountedFramesDecompressor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ElectronPos::ElectronPos (uint16_t x, uint16_t y)\fC [inline]\fP"

.PP
Definition at line 35 of file ElectronCountedFramesDecompressor\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t ElectronPos::x"

.PP
Definition at line 32 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "uint16_t ElectronPos::y"

.PP
Definition at line 33 of file ElectronCountedFramesDecompressor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
