.TH "ElectronCountedFramesDecompressor" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElectronCountedFramesDecompressor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElectronCountedFramesDecompressor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElectronCountedFramesDecompressor\fP (const std::string &filename)"
.br
.ti -1c
.RI "void \fBgetSize\fP (unsigned &x, unsigned &y, unsigned &z)"
.br
.ti -1c
.RI "unsigned \fBgetNFrames\fP ()"
.br
.ti -1c
.RI "std::string \fBGetAcquisitionMetadata\fP ()"
.br
.ti -1c
.RI "size_t \fBgetFileSize\fP ()"
.br
.ti -1c
.RI "unsigned \fBgetNElectronsCounted\fP ()"
.br
.ti -1c
.RI "void \fBdecompressImage\fP (uint8_t *p, int superFactor=1, int frameNumber=\-1)"
.br
.RI "read entire image of specified size\&. "
.ti -1c
.RI "void \fBdecompressImage_AddTo\fP (uint8_t *p, int superFactor=1, int frameNumber=\-1)"
.br
.ti -1c
.RI "void \fBdecompressImage\fP (float *p, int superFactor=1, int frameNumber=\-1)"
.br
.ti -1c
.RI "void \fBdecompressImage_AddTo\fP (float *p, int superFactor=1, int frameNumber=\-1)"
.br
.ti -1c
.RI "unsigned \fBnElectronFractionUpperLimit\fP (int frameStart, int frameStop)"
.br
.ti -1c
.RI "unsigned \fBdecompressCoordinateList\fP (\fBElectronPos\fP *pList, int frameNumber=\-1)"
.br
.ti -1c
.RI "\fB~ElectronCountedFramesDecompressor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file ElectronCountedFramesDecompressor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ElectronCountedFramesDecompressor::ElectronCountedFramesDecompressor (const std::string & filename)"

.PP
Definition at line 220 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "ElectronCountedFramesDecompressor::~ElectronCountedFramesDecompressor ()"

.PP
Definition at line 415 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned ElectronCountedFramesDecompressor::decompressCoordinateList (\fBElectronPos\fP * pList, int frameNumber = \fC\-1\fP)"

.PP
Definition at line 366 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "void ElectronCountedFramesDecompressor::decompressImage (float * p, int superFactor = \fC1\fP, int frameNumber = \fC\-1\fP)"

.PP
Definition at line 315 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "void ElectronCountedFramesDecompressor::decompressImage (uint8_t * p, int superFactor = \fC1\fP, int frameNumber = \fC\-1\fP)"

.PP
read entire image of specified size\&. 
.PP
Definition at line 265 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "void ElectronCountedFramesDecompressor::decompressImage_AddTo (float * p, int superFactor = \fC1\fP, int frameNumber = \fC\-1\fP)"

.PP
Definition at line 321 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "void ElectronCountedFramesDecompressor::decompressImage_AddTo (uint8_t * p, int superFactor = \fC1\fP, int frameNumber = \fC\-1\fP)"

.PP
Definition at line 293 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "std::string ElectronCountedFramesDecompressor::GetAcquisitionMetadata ()"

.PP
Definition at line 260 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "size_t ElectronCountedFramesDecompressor::getFileSize ()\fC [inline]\fP"

.PP
Definition at line 49 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "unsigned ElectronCountedFramesDecompressor::getNElectronsCounted ()\fC [inline]\fP"

.PP
Definition at line 50 of file ElectronCountedFramesDecompressor\&.h\&.
.SS "unsigned ElectronCountedFramesDecompressor::getNFrames ()"

.PP
Definition at line 255 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "void ElectronCountedFramesDecompressor::getSize (unsigned & x, unsigned & y, unsigned & z)"

.PP
Definition at line 248 of file ElectronCountedFramesDecompressor\&.cpp\&.
.SS "unsigned ElectronCountedFramesDecompressor::nElectronFractionUpperLimit (int frameStart, int frameStop)"

.PP
Definition at line 350 of file ElectronCountedFramesDecompressor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
