.TH "EMhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EMhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwEM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBstamp\fP [4]"
.br
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "char \fBlabel\fP [80]"
.br
.ti -1c
.RI "int \fBvolt\fP"
.br
.ti -1c
.RI "int \fBCs\fP"
.br
.ti -1c
.RI "int \fBaperture\fP"
.br
.ti -1c
.RI "int \fBmag\fP"
.br
.ti -1c
.RI "int \fBpost_mag\fP"
.br
.ti -1c
.RI "int \fBexp_time\fP"
.br
.ti -1c
.RI "int \fBnsampling\fP"
.br
.ti -1c
.RI "int \fBpixel_size\fP"
.br
.ti -1c
.RI "int \fBpad1\fP"
.br
.ti -1c
.RI "int \fBfield_length\fP"
.br
.ti -1c
.RI "int \fBdefocus\fP"
.br
.ti -1c
.RI "int \fBastigmatism\fP"
.br
.ti -1c
.RI "int \fBast_angle\fP"
.br
.ti -1c
.RI "int \fBdrift\fP"
.br
.ti -1c
.RI "int \fBdrift_angle\fP"
.br
.ti -1c
.RI "int \fBdefocus_inc\fP"
.br
.ti -1c
.RI "int \fBpad2\fP"
.br
.ti -1c
.RI "int \fBpad3\fP"
.br
.ti -1c
.RI "int \fBtilt_angle\fP"
.br
.ti -1c
.RI "int \fBtilt_dir\fP"
.br
.ti -1c
.RI "char \fBextra\fP [336]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwEM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int EMhead::aperture"

.PP
Definition at line 23 of file rwEM\&.h\&.
.SS "int EMhead::ast_angle"

.PP
Definition at line 33 of file rwEM\&.h\&.
.SS "int EMhead::astigmatism"

.PP
Definition at line 32 of file rwEM\&.h\&.
.SS "int EMhead::Cs"

.PP
Definition at line 22 of file rwEM\&.h\&.
.SS "int EMhead::defocus"

.PP
Definition at line 31 of file rwEM\&.h\&.
.SS "int EMhead::defocus_inc"

.PP
Definition at line 36 of file rwEM\&.h\&.
.SS "int EMhead::drift"

.PP
Definition at line 34 of file rwEM\&.h\&.
.SS "int EMhead::drift_angle"

.PP
Definition at line 35 of file rwEM\&.h\&.
.SS "int EMhead::exp_time"

.PP
Definition at line 26 of file rwEM\&.h\&.
.SS "char EMhead::extra[336]"

.PP
Definition at line 41 of file rwEM\&.h\&.
.SS "int EMhead::field_length"

.PP
Definition at line 30 of file rwEM\&.h\&.
.SS "char EMhead::label[80]"

.PP
Definition at line 20 of file rwEM\&.h\&.
.SS "int EMhead::mag"

.PP
Definition at line 24 of file rwEM\&.h\&.
.SS "int EMhead::nsampling"

.PP
Definition at line 27 of file rwEM\&.h\&.
.SS "int EMhead::nx"

.PP
Definition at line 17 of file rwEM\&.h\&.
.SS "int EMhead::ny"

.PP
Definition at line 18 of file rwEM\&.h\&.
.SS "int EMhead::nz"

.PP
Definition at line 19 of file rwEM\&.h\&.
.SS "int EMhead::pad1"

.PP
Definition at line 29 of file rwEM\&.h\&.
.SS "int EMhead::pad2"

.PP
Definition at line 37 of file rwEM\&.h\&.
.SS "int EMhead::pad3"

.PP
Definition at line 38 of file rwEM\&.h\&.
.SS "int EMhead::pixel_size"

.PP
Definition at line 28 of file rwEM\&.h\&.
.SS "int EMhead::post_mag"

.PP
Definition at line 25 of file rwEM\&.h\&.
.SS "char EMhead::stamp[4]"

.PP
Definition at line 16 of file rwEM\&.h\&.
.SS "int EMhead::tilt_angle"

.PP
Definition at line 39 of file rwEM\&.h\&.
.SS "int EMhead::tilt_dir"

.PP
Definition at line 40 of file rwEM\&.h\&.
.SS "int EMhead::volt"

.PP
Definition at line 21 of file rwEM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
