.TH "Fei::Acquisition::EerReader" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fei::Acquisition::EerReader
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBitmap\fP"
.br
.ti -1c
.RI "class \fBEerFile\fP"
.br
.ti -1c
.RI "class \fBEerFrame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
