.TH "Fei::Acquisition::EerReader::EerFrame" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fei::Acquisition::EerReader::EerFrame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EerFrame\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEerFrame\fP (TIFF *tiff)"
.br
.ti -1c
.RI "uint32_t \fBGetWidth\fP () const"
.br
.ti -1c
.RI "uint32_t \fBGetLength\fP () const"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBGetEerData\fP () const"
.br
.ti -1c
.RI "int \fBGetEncodingVersion\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file EerFrame\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fei::Acquisition::EerReader::EerFrame::EerFrame (TIFF * tiff)"

.PP
Definition at line 16 of file EerFrame\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< unsigned char > Fei::Acquisition::EerReader::EerFrame::GetEerData () const"

.PP
Definition at line 51 of file EerFrame\&.cpp\&.
.SS "int Fei::Acquisition::EerReader::EerFrame::GetEncodingVersion () const"

.PP
Definition at line 56 of file EerFrame\&.cpp\&.
.SS "uint32_t Fei::Acquisition::EerReader::EerFrame::GetLength () const"

.PP
Definition at line 46 of file EerFrame\&.cpp\&.
.SS "uint32_t Fei::Acquisition::EerReader::EerFrame::GetWidth () const"

.PP
Definition at line 41 of file EerFrame\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
