.TH "FSI_Kernel" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSI_Kernel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FSI_Kernel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFSI_Kernel\fP ()"
.br
.ti -1c
.RI "\fBFSI_Kernel\fP (long kernel_width, long kernel_power)"
.br
.RI "Calculates a reciprocal space interpolation lookup table\&. "
.ti -1c
.RI "long \fBwidth\fP ()"
.br
.ti -1c
.RI "long \fBhalf_width\fP ()"
.br
.ti -1c
.RI "long \fBdivisions\fP ()"
.br
.ti -1c
.RI "double \fBoperator[]\fP (long i) const"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file FSI_Kernel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FSI_Kernel::FSI_Kernel ()\fC [inline]\fP"

.PP
Definition at line 22 of file FSI_Kernel\&.h\&.
.SS "FSI_Kernel::FSI_Kernel (long kernel_width, long kernel_power)\fC [inline]\fP"

.PP
Calculates a reciprocal space interpolation lookup table\&. 
.PP
\fBParameters\fP
.RS 4
\fIkernel_width\fP table width\&. 
.br
\fIkernel_power\fP interpolation power\&. 
.RE
.PP
\fBReturns\fP
.RS 4
FSI_Kernel* new lookup table\&. 
.RE
.PP

.PP
Definition at line 29 of file FSI_Kernel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "long FSI_Kernel::divisions ()\fC [inline]\fP"

.PP
Definition at line 72 of file FSI_Kernel\&.h\&.
.SS "long FSI_Kernel::half_width ()\fC [inline]\fP"

.PP
Definition at line 71 of file FSI_Kernel\&.h\&.
.SS "double FSI_Kernel::operator[] (long i) const\fC [inline]\fP"

.PP
Definition at line 73 of file FSI_Kernel\&.h\&.
.SS "void FSI_Kernel::show ()\fC [inline]\fP"

.PP
Definition at line 74 of file FSI_Kernel\&.h\&.
.SS "long FSI_Kernel::width ()\fC [inline]\fP"

.PP
Definition at line 70 of file FSI_Kernel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
