.TH "/Users/bernard/b20/bsoft/eer/GainDefectCorrect.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/GainDefectCorrect.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'GainDefectCorrect\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreduce16k_to_4k\fP (const float *gain16k, float *gain4k)"
.br
.ti -1c
.RI "\fBCameraDefects\fP \fBPrepareGainImage_ExtractDefects\fP (float *gainImageFull, unsigned gainImSize, unsigned w, unsigned h, double deadThreshold)"
.br
.ti -1c
.RI "template<typename T > void \fBDefectCorrect\fP (T *img, const \fBCameraDefects\fP &def, unsigned w, unsigned h)"
.br
.ti -1c
.RI "template void \fBDefectCorrect< float >\fP (float *img, const \fBCameraDefects\fP &def, unsigned w, unsigned h)"
.br
.ti -1c
.RI "template void \fBDefectCorrect< uint8_t >\fP (uint8_t *img, const \fBCameraDefects\fP &def, unsigned w, unsigned h)"
.br
.ti -1c
.RI "template void \fBDefectCorrect< uint16_t >\fP (uint16_t *img, const \fBCameraDefects\fP &def, unsigned w, unsigned h)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > void DefectCorrect (T * img, const \fBCameraDefects\fP & def, unsigned w, unsigned h)"

.PP
Definition at line 202 of file GainDefectCorrect\&.cpp\&.
.SS "template void \fBDefectCorrect\fP< float > (float * img, const \fBCameraDefects\fP & def, unsigned w, unsigned h)"

.SS "template void \fBDefectCorrect\fP< uint16_t > (uint16_t * img, const \fBCameraDefects\fP & def, unsigned w, unsigned h)"

.SS "template void \fBDefectCorrect\fP< uint8_t > (uint8_t * img, const \fBCameraDefects\fP & def, unsigned w, unsigned h)"

.SS "\fBCameraDefects\fP PrepareGainImage_ExtractDefects (float * gainImageFull, unsigned gainImSize, unsigned w, unsigned h, double deadThreshold)"

.PP
Definition at line 37 of file GainDefectCorrect\&.cpp\&.
.SS "void reduce16k_to_4k (const float * gain16k, float * gain4k)"

.PP
Definition at line 19 of file GainDefectCorrect\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
