.TH "/Users/bernard/b20/bsoft/eer/GainDefectCorrect.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/eer/GainDefectCorrect.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDefectPixel\fP"
.br
.ti -1c
.RI "struct \fBDefectLines\fP"
.br
.ti -1c
.RI "struct \fBDefectArea\fP"
.br
.ti -1c
.RI "struct \fBCameraDefects\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCameraDefects\fP \fBPrepareGainImage_ExtractDefects\fP (float *gainImage, unsigned gainImSize, unsigned w=4096, unsigned h=4096, double deadThreshold=0\&.05)"
.br
.ti -1c
.RI "template<typename T > void \fBDefectCorrect\fP (T *img, const \fBCameraDefects\fP &def, unsigned w=4096, unsigned h=4096)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > void DefectCorrect (T * img, const \fBCameraDefects\fP & def, unsigned w = \fC4096\fP, unsigned h = \fC4096\fP)"

.PP
Definition at line 202 of file GainDefectCorrect\&.cpp\&.
.SS "\fBCameraDefects\fP PrepareGainImage_ExtractDefects (float * gainImage, unsigned gainImSize, unsigned w = \fC4096\fP, unsigned h = \fC4096\fP, double deadThreshold = \fC0\&.05\fP)"

.PP
Definition at line 37 of file GainDefectCorrect\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
