.TH "GRDhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GRDhead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwGRD\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmagic\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBdoffset\fP"
.br
.ti -1c
.RI "int \fBnx\fP"
.br
.ti -1c
.RI "int \fBny\fP"
.br
.ti -1c
.RI "int \fBnz\fP"
.br
.ti -1c
.RI "int \fBnn\fP"
.br
.ti -1c
.RI "int \fBchannels\fP"
.br
.ti -1c
.RI "int \fBslowest\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "float \fBamin\fP"
.br
.ti -1c
.RI "float \fBamax\fP"
.br
.ti -1c
.RI "float \fBamean\fP"
.br
.ti -1c
.RI "float \fBarms\fP"
.br
.ti -1c
.RI "float \fBux\fP"
.br
.ti -1c
.RI "float \fBuy\fP"
.br
.ti -1c
.RI "float \fBuz\fP"
.br
.ti -1c
.RI "float \fBbkg\fP"
.br
.ti -1c
.RI "float \fBox\fP"
.br
.ti -1c
.RI "float \fBoy\fP"
.br
.ti -1c
.RI "float \fBoz\fP"
.br
.ti -1c
.RI "float \fBvx\fP"
.br
.ti -1c
.RI "float \fBvy\fP"
.br
.ti -1c
.RI "float \fBvz\fP"
.br
.ti -1c
.RI "float \fBva\fP"
.br
.ti -1c
.RI "long \fBrle\fP"
.br
.ti -1c
.RI "float \fBextra\fP [31]"
.br
.ti -1c
.RI "char \fBdatetime\fP [16]"
.br
.ti -1c
.RI "char \fBsymmetry\fP [32]"
.br
.ti -1c
.RI "char \fBlabel\fP [208]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwGRD\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float GRDhead::a"

.PP
Definition at line 26 of file rwGRD\&.h\&.
.SS "float GRDhead::alpha"

.PP
Definition at line 29 of file rwGRD\&.h\&.
.SS "float GRDhead::amax"

.PP
Definition at line 33 of file rwGRD\&.h\&.
.SS "float GRDhead::amean"

.PP
Definition at line 34 of file rwGRD\&.h\&.
.SS "float GRDhead::amin"

.PP
Definition at line 32 of file rwGRD\&.h\&.
.SS "float GRDhead::arms"

.PP
Definition at line 35 of file rwGRD\&.h\&.
.SS "float GRDhead::b"

.PP
Definition at line 27 of file rwGRD\&.h\&.
.SS "float GRDhead::beta"

.PP
Definition at line 30 of file rwGRD\&.h\&.
.SS "float GRDhead::bkg"

.PP
Definition at line 39 of file rwGRD\&.h\&.
.SS "float GRDhead::c"

.PP
Definition at line 28 of file rwGRD\&.h\&.
.SS "int GRDhead::channels"

.PP
Definition at line 24 of file rwGRD\&.h\&.
.SS "char GRDhead::datetime[16]"

.PP
Definition at line 49 of file rwGRD\&.h\&.
.SS "int GRDhead::doffset"

.PP
Definition at line 19 of file rwGRD\&.h\&.
.SS "float GRDhead::extra[31]"

.PP
Definition at line 48 of file rwGRD\&.h\&.
.SS "float GRDhead::gamma"

.PP
Definition at line 31 of file rwGRD\&.h\&.
.SS "char GRDhead::label[208]"

.PP
Definition at line 51 of file rwGRD\&.h\&.
.SS "int GRDhead::magic"

.PP
Definition at line 16 of file rwGRD\&.h\&.
.SS "int GRDhead::mode"

.PP
Definition at line 18 of file rwGRD\&.h\&.
.SS "int GRDhead::nn"

.PP
Definition at line 23 of file rwGRD\&.h\&.
.SS "int GRDhead::nx"

.PP
Definition at line 20 of file rwGRD\&.h\&.
.SS "int GRDhead::ny"

.PP
Definition at line 21 of file rwGRD\&.h\&.
.SS "int GRDhead::nz"

.PP
Definition at line 22 of file rwGRD\&.h\&.
.SS "float GRDhead::ox"

.PP
Definition at line 40 of file rwGRD\&.h\&.
.SS "float GRDhead::oy"

.PP
Definition at line 41 of file rwGRD\&.h\&.
.SS "float GRDhead::oz"

.PP
Definition at line 42 of file rwGRD\&.h\&.
.SS "long GRDhead::rle"

.PP
Definition at line 47 of file rwGRD\&.h\&.
.SS "int GRDhead::slowest"

.PP
Definition at line 25 of file rwGRD\&.h\&.
.SS "char GRDhead::symmetry[32]"

.PP
Definition at line 50 of file rwGRD\&.h\&.
.SS "float GRDhead::ux"

.PP
Definition at line 36 of file rwGRD\&.h\&.
.SS "float GRDhead::uy"

.PP
Definition at line 37 of file rwGRD\&.h\&.
.SS "float GRDhead::uz"

.PP
Definition at line 38 of file rwGRD\&.h\&.
.SS "float GRDhead::va"

.PP
Definition at line 46 of file rwGRD\&.h\&.
.SS "int GRDhead::version"

.PP
Definition at line 17 of file rwGRD\&.h\&.
.SS "float GRDhead::vx"

.PP
Definition at line 43 of file rwGRD\&.h\&.
.SS "float GRDhead::vy"

.PP
Definition at line 44 of file rwGRD\&.h\&.
.SS "float GRDhead::vz"

.PP
Definition at line 45 of file rwGRD\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
