.TH "GSedge" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GSedge \- Graph segmentation edge\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bgraphseg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGSedge\fP ()"
.br
.ti -1c
.RI "\fBGSedge\fP (long start, long end, double \fBweight\fP)"
.br
.ti -1c
.RI "long \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "void \fBweight\fP (double val)"
.br
.ti -1c
.RI "double \fBweight\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graph segmentation edge\&. 
.PP
Definition at line 19 of file Bgraphseg\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GSedge::GSedge ()\fC [inline]\fP"

.PP
Definition at line 24 of file Bgraphseg\&.h\&.
.SS "GSedge::GSedge (long start, long end, double weight)\fC [inline]\fP"

.PP
Definition at line 25 of file Bgraphseg\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "long GSedge::operator[] (int i)\fC [inline]\fP"

.PP
Definition at line 26 of file Bgraphseg\&.h\&.
.SS "double GSedge::weight () const\fC [inline]\fP"

.PP
Definition at line 28 of file Bgraphseg\&.h\&.
.SS "void GSedge::weight (double val)\fC [inline]\fP"

.PP
Definition at line 27 of file Bgraphseg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
