.TH "GSvoxel" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GSvoxel \- Graph segmentation region\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bgraphseg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGSvoxel\fP ()"
.br
.ti -1c
.RI "\fBGSvoxel\fP (long \fBindex\fP, long nj, long nv, double avg)"
.br
.ti -1c
.RI "void \fBindex\fP (long i)"
.br
.ti -1c
.RI "long \fBindex\fP ()"
.br
.ti -1c
.RI "void \fBjoins\fP (int i)"
.br
.ti -1c
.RI "int \fBjoins\fP ()"
.br
.ti -1c
.RI "void \fBincrement_joins\fP ()"
.br
.ti -1c
.RI "void \fBvoxels\fP (int i)"
.br
.ti -1c
.RI "int \fBvoxels\fP ()"
.br
.ti -1c
.RI "void \fBincrement_voxels\fP ()"
.br
.ti -1c
.RI "void \fBadd_to_voxels\fP (int i)"
.br
.ti -1c
.RI "void \fBaverage\fP (double d)"
.br
.ti -1c
.RI "double \fBaverage\fP ()"
.br
.ti -1c
.RI "void \fBadd_to_average\fP (double d)"
.br
.ti -1c
.RI "void \fBdivide_average_by_voxels\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graph segmentation region\&. 
.PP
Definition at line 36 of file Bgraphseg\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GSvoxel::GSvoxel ()\fC [inline]\fP"

.PP
Definition at line 43 of file Bgraphseg\&.h\&.
.SS "GSvoxel::GSvoxel (long index, long nj, long nv, double avg)\fC [inline]\fP"

.PP
Definition at line 44 of file Bgraphseg\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void GSvoxel::add_to_average (double d)\fC [inline]\fP"

.PP
Definition at line 56 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::add_to_voxels (int i)\fC [inline]\fP"

.PP
Definition at line 53 of file Bgraphseg\&.h\&.
.SS "double GSvoxel::average ()\fC [inline]\fP"

.PP
Definition at line 55 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::average (double d)\fC [inline]\fP"

.PP
Definition at line 54 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::clear ()\fC [inline]\fP"

.PP
Definition at line 58 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::divide_average_by_voxels ()\fC [inline]\fP"

.PP
Definition at line 57 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::increment_joins ()\fC [inline]\fP"

.PP
Definition at line 49 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::increment_voxels ()\fC [inline]\fP"

.PP
Definition at line 52 of file Bgraphseg\&.h\&.
.SS "long GSvoxel::index ()\fC [inline]\fP"

.PP
Definition at line 46 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::index (long i)\fC [inline]\fP"

.PP
Definition at line 45 of file Bgraphseg\&.h\&.
.SS "int GSvoxel::joins ()\fC [inline]\fP"

.PP
Definition at line 48 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::joins (int i)\fC [inline]\fP"

.PP
Definition at line 47 of file Bgraphseg\&.h\&.
.SS "int GSvoxel::voxels ()\fC [inline]\fP"

.PP
Definition at line 51 of file Bgraphseg\&.h\&.
.SS "void GSvoxel::voxels (int i)\fC [inline]\fP"

.PP
Definition at line 50 of file Bgraphseg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
