.TH "IMAGIChead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMAGIChead
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rwIMAGIC\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBimn\fP"
.br
.ti -1c
.RI "int \fBifn\fP"
.br
.ti -1c
.RI "int \fBierror\fP"
.br
.ti -1c
.RI "int \fBnhfr\fP"
.br
.ti -1c
.RI "int \fBndate\fP"
.br
.ti -1c
.RI "int \fBnmonth\fP"
.br
.ti -1c
.RI "int \fBnyear\fP"
.br
.ti -1c
.RI "int \fBnhour\fP"
.br
.ti -1c
.RI "int \fBnminut\fP"
.br
.ti -1c
.RI "int \fBnsec\fP"
.br
.ti -1c
.RI "int \fBnpix2\fP"
.br
.ti -1c
.RI "int \fBnpixel\fP"
.br
.ti -1c
.RI "int \fBixlp\fP"
.br
.ti -1c
.RI "int \fBiylp\fP"
.br
.ti -1c
.RI "char \fBtype\fP [4]"
.br
.ti -1c
.RI "int \fBixold\fP"
.br
.ti -1c
.RI "int \fBiyold\fP"
.br
.ti -1c
.RI "float \fBavdens\fP"
.br
.ti -1c
.RI "float \fBsigma\fP"
.br
.ti -1c
.RI "float \fBvarian\fP"
.br
.ti -1c
.RI "float \fBoldavd\fP"
.br
.ti -1c
.RI "float \fBdensmax\fP"
.br
.ti -1c
.RI "float \fBdensmin\fP"
.br
.ti -1c
.RI "int \fBcomplex\fP"
.br
.ti -1c
.RI "float \fBcxlength\fP"
.br
.ti -1c
.RI "float \fBcylength\fP"
.br
.ti -1c
.RI "float \fBczlength\fP"
.br
.ti -1c
.RI "float \fBcalpha\fP"
.br
.ti -1c
.RI "float \fBcbeta\fP"
.br
.ti -1c
.RI "char \fBname\fP [80]"
.br
.ti -1c
.RI "float \fBcgamma\fP"
.br
.ti -1c
.RI "int \fBmapc\fP"
.br
.ti -1c
.RI "int \fBmapr\fP"
.br
.ti -1c
.RI "int \fBmaps\fP"
.br
.ti -1c
.RI "int \fBispg\fP"
.br
.ti -1c
.RI "int \fBnxstart\fP"
.br
.ti -1c
.RI "int \fBnystart\fP"
.br
.ti -1c
.RI "int \fBnzstart\fP"
.br
.ti -1c
.RI "int \fBnxintv\fP"
.br
.ti -1c
.RI "int \fBnyintv\fP"
.br
.ti -1c
.RI "int \fBnzintv\fP"
.br
.ti -1c
.RI "int \fBizlp\fP"
.br
.ti -1c
.RI "int \fBi4lp\fP"
.br
.ti -1c
.RI "int \fBi5lp\fP"
.br
.ti -1c
.RI "int \fBi6lp\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBbeta\fP"
.br
.ti -1c
.RI "float \fBgamma\fP"
.br
.ti -1c
.RI "int \fBimavers\fP"
.br
.ti -1c
.RI "int \fBrealtype\fP"
.br
.ti -1c
.RI "int \fBbuffer\fP [29]"
.br
.ti -1c
.RI "int \fBronly\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBrcp\fP"
.br
.ti -1c
.RI "int \fBixpeak\fP"
.br
.ti -1c
.RI "int \fBiypeak\fP"
.br
.ti -1c
.RI "float \fBccc\fP"
.br
.ti -1c
.RI "float \fBerrar\fP"
.br
.ti -1c
.RI "float \fBerr3d\fP"
.br
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "float \fBclassno\fP"
.br
.ti -1c
.RI "float \fBlocold\fP"
.br
.ti -1c
.RI "float \fBoldavd2\fP"
.br
.ti -1c
.RI "float \fBoldsigma\fP"
.br
.ti -1c
.RI "float \fBxshift\fP"
.br
.ti -1c
.RI "float \fByshift\fP"
.br
.ti -1c
.RI "float \fBnumcls\fP"
.br
.ti -1c
.RI "float \fBovqual\fP"
.br
.ti -1c
.RI "float \fBeangle\fP"
.br
.ti -1c
.RI "float \fBexshift\fP"
.br
.ti -1c
.RI "float \fBeyshift\fP"
.br
.ti -1c
.RI "float \fBcmtotvar\fP"
.br
.ti -1c
.RI "float \fBinformat\fP"
.br
.ti -1c
.RI "int \fBnumeigen\fP"
.br
.ti -1c
.RI "int \fBniactive\fP"
.br
.ti -1c
.RI "float \fBresolx\fP"
.br
.ti -1c
.RI "float \fBresoly\fP"
.br
.ti -1c
.RI "float \fBresolz\fP"
.br
.ti -1c
.RI "float \fBalpha2\fP"
.br
.ti -1c
.RI "float \fBbeta2\fP"
.br
.ti -1c
.RI "float \fBgamma2\fP"
.br
.ti -1c
.RI "float \fBnmetric\fP"
.br
.ti -1c
.RI "float \fBactmsa\fP"
.br
.ti -1c
.RI "float \fBcoosmsa\fP [69]"
.br
.ti -1c
.RI "char \fBhistory\fP [228]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rwIMAGIC\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float IMAGIChead::actmsa"

.PP
Definition at line 98 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::alpha"

.PP
Definition at line 61 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::alpha2"

.PP
Definition at line 94 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::angle"

.PP
Definition at line 68 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::avdens"

.PP
Definition at line 33 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::beta"

.PP
Definition at line 62 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::beta2"

.PP
Definition at line 95 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::buffer[29]"

.PP
Definition at line 66 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::calpha"

.PP
Definition at line 43 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::cbeta"

.PP
Definition at line 44 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::ccc"

.PP
Definition at line 72 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::cgamma"

.PP
Definition at line 46 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::classno"

.PP
Definition at line 76 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::cmtotvar"

.PP
Definition at line 87 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::complex"

.PP
Definition at line 39 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::coosmsa[69]"

.PP
Definition at line 99 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::cxlength"

.PP
Definition at line 40 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::cylength"

.PP
Definition at line 41 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::czlength"

.PP
Definition at line 42 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::densmax"

.PP
Definition at line 37 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::densmin"

.PP
Definition at line 38 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::eangle"

.PP
Definition at line 84 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::err3d"

.PP
Definition at line 74 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::errar"

.PP
Definition at line 73 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::exshift"

.PP
Definition at line 85 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::eyshift"

.PP
Definition at line 86 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::gamma"

.PP
Definition at line 63 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::gamma2"

.PP
Definition at line 96 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead::history[228]"

.PP
Definition at line 100 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::i4lp"

.PP
Definition at line 58 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::i5lp"

.PP
Definition at line 59 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::i6lp"

.PP
Definition at line 60 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ierror"

.PP
Definition at line 18 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ifn"

.PP
Definition at line 17 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::imavers"

.PP
Definition at line 64 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::imn"

.PP
Definition at line 16 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::informat"

.PP
Definition at line 88 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ispg"

.PP
Definition at line 50 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ixlp"

.PP
Definition at line 28 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ixold"

.PP
Definition at line 31 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ixpeak"

.PP
Definition at line 70 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::iylp"

.PP
Definition at line 29 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::iyold"

.PP
Definition at line 32 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::iypeak"

.PP
Definition at line 71 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::izlp"

.PP
Definition at line 57 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::locold"

.PP
Definition at line 77 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::mapc"

.PP
Definition at line 47 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::mapr"

.PP
Definition at line 48 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::maps"

.PP
Definition at line 49 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead::name[80]"

.PP
Definition at line 45 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ndate"

.PP
Definition at line 20 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nhfr"

.PP
Definition at line 19 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nhour"

.PP
Definition at line 23 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::niactive"

.PP
Definition at line 90 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::nmetric"

.PP
Definition at line 97 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nminut"

.PP
Definition at line 24 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nmonth"

.PP
Definition at line 21 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::npix2"

.PP
Definition at line 26 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::npixel"

.PP
Definition at line 27 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nsec"

.PP
Definition at line 25 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::numcls"

.PP
Definition at line 82 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::numeigen"

.PP
Definition at line 89 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nxintv"

.PP
Definition at line 54 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nxstart"

.PP
Definition at line 51 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nyear"

.PP
Definition at line 22 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nyintv"

.PP
Definition at line 55 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nystart"

.PP
Definition at line 52 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nzintv"

.PP
Definition at line 56 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::nzstart"

.PP
Definition at line 53 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::oldavd"

.PP
Definition at line 36 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::oldavd2"

.PP
Definition at line 78 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::oldsigma"

.PP
Definition at line 79 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::ovqual"

.PP
Definition at line 83 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::rcp"

.PP
Definition at line 69 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::realtype"

.PP
Definition at line 65 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ref"

.PP
Definition at line 75 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::resolx"

.PP
Definition at line 91 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::resoly"

.PP
Definition at line 92 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::resolz"

.PP
Definition at line 93 of file rwIMAGIC\&.h\&.
.SS "int IMAGIChead::ronly"

.PP
Definition at line 67 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::sigma"

.PP
Definition at line 34 of file rwIMAGIC\&.h\&.
.SS "char IMAGIChead::type[4]"

.PP
Definition at line 30 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::varian"

.PP
Definition at line 35 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::xshift"

.PP
Definition at line 80 of file rwIMAGIC\&.h\&.
.SS "float IMAGIChead::yshift"

.PP
Definition at line 81 of file rwIMAGIC\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
