.TH "/Users/bernard/b20/bsoft/include/json.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/json.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJSvalue\fP"
.br
.ti -1c
.RI "class \fBJSparser\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJStype\fP { \fBJSstring\fP, \fBJSbool\fP, \fBJSinteger\fP, \fBJSreal\fP, \fBJSobject\fP, \fBJSarray\fP, \fBJSnull\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBJStype\fP t)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBJSvalue\fP &jsv)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
20160409 - 20191219 
.RE
.PP

.PP
Definition in file \fBjson\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJStype\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIJSstring \fP\fP
.TP
\fB\fIJSbool \fP\fP
.TP
\fB\fIJSinteger \fP\fP
.TP
\fB\fIJSreal \fP\fP
.TP
\fB\fIJSobject \fP\fP
.TP
\fB\fIJSarray \fP\fP
.TP
\fB\fIJSnull \fP\fP
.PP
Definition at line 22 of file json\&.h\&.
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & output, \fBJStype\fP t)"

.PP
Definition at line 10 of file json\&.cpp\&.
.SS "ostream& operator<< (ostream & output, \fBJSvalue\fP & jsv)"

.PP
Definition at line 30 of file json\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
