.TH "JSparser" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSparser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSparser\fP ()"
.br
.ti -1c
.RI "\fBJSparser\fP (string filename)"
.br
.ti -1c
.RI "\fBJSparser\fP (const char *buf, size_t n)"
.br
.ti -1c
.RI "\fBJSvalue\fP \fBparse\fP ()"
.br
.ti -1c
.RI "\fBJSvalue\fP \fBparse\fP (string filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 387 of file json\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JSparser::JSparser ()\fC [inline]\fP"

.PP
Definition at line 414 of file json\&.h\&.
.SS "JSparser::JSparser (string filename)\fC [inline]\fP"

.PP
Definition at line 415 of file json\&.h\&.
.SS "JSparser::JSparser (const char * buf, size_t n)\fC [inline]\fP"

.PP
Definition at line 416 of file json\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBJSvalue\fP JSparser::parse ()\fC [inline]\fP"

.PP
Definition at line 417 of file json\&.h\&.
.SS "\fBJSvalue\fP JSparser::parse (string filename)\fC [inline]\fP"

.PP
Definition at line 427 of file json\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
