.TH "Latom" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Latom
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mol_util\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLatom\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBBatom\fP * \fBatom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file mol_util\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBatom\fP* Latom::atom"

.PP
Definition at line 24 of file mol_util\&.h\&.
.SS "\fBLatom\fP* Latom::next"

.PP
Definition at line 23 of file mol_util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
