.TH "Matrix::Row" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix::Row
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Matrix\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRow\fP (long len, double *row)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (long i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file Matrix\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Matrix::Row::Row (long len, double * row)\fC [inline]\fP"

.PP
Definition at line 119 of file Matrix\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double& Matrix::Row::operator[] (long i)\fC [inline]\fP"

.PP
Definition at line 120 of file Matrix\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
