.TH "/Users/bernard/b20/bsoft/src/util/Matrix3.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/util/Matrix3.cpp \- \fBMatrix\fP manipulation functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Matrix3\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &output, \fBMatrix3\fP &m)"
.br
.ti -1c
.RI "int \fBmatrix3_show_hp\fP (\fBMatrix3\fP &mat)"
.br
.RI "Print out a matrix\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMatrix\fP manipulation functions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000501 
.PP
Modified: 20150111 
.RE
.PP

.PP
Definition in file \fBMatrix3\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int matrix3_show_hp (\fBMatrix3\fP & mat)"

.PP
Print out a matrix\&. 
.PP
\fBParameters\fP
.RS 4
\fImat\fP 3x3 matrix\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.PP
.nf
Matrix elements less than 1e-6 are set to zero for display.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 31 of file Matrix3\&.cpp\&.
.SS "ostream& operator<< (ostream & output, \fBMatrix3\fP & m)"

.PP
Definition at line 15 of file Matrix3\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
