.TH "MDOCparser" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MDOCparser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mdoc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMDOCparser\fP ()"
.br
.ti -1c
.RI "\fBMDOCparser\fP (string filename)"
.br
.ti -1c
.RI "\fBJSvalue\fP \fBparse\fP ()"
.br
.ti -1c
.RI "\fBJSvalue\fP \fBparse\fP (string filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file mdoc\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MDOCparser::MDOCparser ()\fC [inline]\fP"

.PP
Definition at line 86 of file mdoc\&.h\&.
.SS "MDOCparser::MDOCparser (string filename)\fC [inline]\fP"

.PP
Definition at line 87 of file mdoc\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBJSvalue\fP MDOCparser::parse ()\fC [inline]\fP"

.PP
Definition at line 88 of file mdoc\&.h\&.
.SS "\fBJSvalue\fP MDOCparser::parse (string filename)\fC [inline]\fP"

.PP
Definition at line 92 of file mdoc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
