.TH "/Users/bernard/b20/bsoft/include/mg_hand.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/mg_hand.h \- Author: David Belnap\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBproject_get_handedness\fP (\fBBimage\fP *penantiomer, \fBBproject\fP *\fBproject\fP, double *mg_ang, int *mg_index, int *mg_select, double rad_min, double rad_max, double res_min, double res_max, double AmB_min, double AB_min, int diff_out, int origins2, \fBBstring\fP outimg)"
.br
.RI "Determines handedness for all selected particles (sel > 0) in a project\&. "
.ti -1c
.RI "int \fBhand_select_consist\fP (\fBBproject\fP *\fBproject\fP, double *mg_ang, int *mg_index, int *mg_select, int sel_consist)"
.br
.RI "Sets consistent selection values in all (including unused) micrographs\&. "
.in -1c
.SH "Detailed Description"
.PP 
Author: David Belnap\&. 


.PP
\fBDate\fP
.RS 4
Created: 20011003 
.PP
Modified: 20050906 
.RE
.PP

.PP
Definition in file \fBmg_hand\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int hand_select_consist (\fBBproject\fP * project, double * mg_ang, int * mg_index, int * mg_select, int sel_consist)"

.PP
Sets consistent selection values in all (including unused) micrographs\&. 
.PP
\fBParameters\fP
.RS 4
\fI*project\fP Project structure 
.br
\fI*mg_ang\fP angles for micrograph selection, views 1 & 2 
.br
\fI*mg_index\fP indices for micrograph selection, views 1 & 2 
.br
\fI*mg_select\fP micrograph selection criteria, views 1 & 2 
.br
\fIsel_consist\fP 1 or 2, set other selection values to those of this view 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.PP
.nf
If a field-of-view contains more than two micrographs, the user can
only use two of them to do the handedness determination.  The unused
micrographs may need their selection values set to the same as those
in the used micrographs (views 1 and 2).  In addition, there may be
differences in the initial selection values for views 1 and 2.  This 
routine loops through the micrographs in a field-of-view and sets all
selection values to those of view 1 or 2.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 898 of file mg_hand\&.cpp\&.
.SS "int project_get_handedness (\fBBimage\fP * mapA, \fBBproject\fP * project, double * mg_ang, int * mg_index, int * mg_select, double rad_min, double rad_max, double res_min, double res_max, double AmB_min, double AB_min, int diff_out, int origins2, \fBBstring\fP outimg)"

.PP
Determines handedness for all selected particles (sel > 0) in a project\&. 
.PP
\fBParameters\fP
.RS 4
\fI*mapA\fP 3D map (hand A) 
.br
\fI*project\fP Project structure 
.br
\fI*mg_ang\fP angles for micrograph selection, views 1 & 2 
.br
\fI*mg_index\fP indices for micrograph selection, views 1 & 2 
.br
\fI*mg_select\fP micrograph selection criteria, views 1 & 2 
.br
\fIrad_min\fP minimum radius for FOM calculation (pixels) 
.br
\fIrad_max\fP maximum radius for FOM calculation (pixels) 
.br
\fIres_min\fP minimum resolution for FOM calculation (angs\&.) 
.br
\fIres_max\fP maximum resolution for FOM calculation (angs\&.) 
.br
\fIAmB_min\fP |FOMA - FOMB| must be this value or greater 
.br
\fIAB_min\fP min\&. acceptable value for FOM of correct hand 
.br
\fIdiff_out\fP output difference of measured & predicted orientations 
.br
\fIorigins2\fP flag to determine origins for second view 
.br
\fIoutimg\fP prefix & suffix for output projection files 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.PP
.nf
Gets tilt-axis direction and rotation angle for a micrograph pair.
Then, loops through the selected particles in pair.  Sends data to
function get_handedness_from_tilt_pair, where handedness is
determined.  Statistics are calculated for each pair and sums for
global statistics are tabulated.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 114 of file mg_hand\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
