.TH "/Users/bernard/b20/bsoft/src/model/model_plane.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/model/model_plane.cpp \- Library routines used for plane models\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'model_create\&.h'\fP
.br
\fC#include 'model_transform\&.h'\fP
.br
\fC#include 'model_views\&.h'\fP
.br
\fC#include 'model_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBVector3\fP< double > \fBmodel_fit_plane\fP (\fBBmodel\fP *\fBmodel\fP)"
.br
.RI "Fits a plane through a model\&. "
.ti -1c
.RI "double \fBmodel_distance_to_guide\fP (\fBVector3\fP< double > loc, \fBVector3\fP< double > vec, \fBBmodel\fP *guide, double sigma2)"
.br
.RI "Calculates the distance between a location and the local guide model\&. "
.ti -1c
.RI "int \fBmodel_adjust_to_guide\fP (\fBBmodel\fP *\fBmodel\fP, \fBBmodel\fP *gmod, double sigma)"
.br
.RI "Adjusts a shell model to the faces of a polyhedral guide model\&. "
.ti -1c
.RI "\fBBmodel\fP * \fBmodel_generate_from_plane_guide\fP (\fBBmodel\fP *guide, double separation, double sigma)"
.br
.RI "Generates a plane model and fits a plane through it\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines used for plane models\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20140925 
.PP
Modified: 20141008 
.RE
.PP

.PP
Definition in file \fBmodel_plane\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int model_adjust_to_guide (\fBBmodel\fP * model, \fBBmodel\fP * gmod, double sigma)"

.PP
Adjusts a shell model to the faces of a polyhedral guide model\&. 
.PP
.nf
For each component, it is determined whether it is located inside or 
outside the appropriate polyhedral face, and its coordinates adjust
closer to the face by the indicated fraction.

.fi
.PP
 
.PP
\fBParameters\fP
.RS 4
\fI*model\fP shell model\&. 
.br
\fI*gmod\fP guide polyhedron model\&. 
.br
\fIsigma\fP smoothness of model\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.RE
.PP

.PP
Definition at line 136 of file model_plane\&.cpp\&.
.SS "double model_distance_to_guide (\fBVector3\fP< double > loc, \fBVector3\fP< double > vec, \fBBmodel\fP * guide, double sigma2)"

.PP
Calculates the distance between a location and the local guide model\&. 
.PP
.nf
Each guide component is used to calculate a distance of the location
to the guide plane and a lateral distance to the guide component.
The lateral distance is used to calculate a gaussian distributed weight
which in turn is used to calculate a weighted average of the distance
to the guide plane.

.fi
.PP
 
.PP
\fBParameters\fP
.RS 4
\fIloc\fP location to be tested\&. 
.br
\fIvec\fP direction vector associated with the location\&. 
.br
\fI*guide\fP guide model\&. 
.br
\fIsigma2\fP smoothness weighting parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* new circle model\&. 
.RE
.PP

.PP
Definition at line 102 of file model_plane\&.cpp\&.
.SS "\fBVector3\fP<double> model_fit_plane (\fBBmodel\fP * model)"

.PP
Fits a plane through a model\&. 
.PP
.nf
A plane is fit through the components and the normal calculated from:
    n•p = d
where n is the normal vector, p is a point in the plane, and d is the offset.
Only the first model is fit.

.fi
.PP
 
.PP
\fBParameters\fP
.RS 4
\fI*model\fP model structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBVector3<double>\fP plane normal\&. 
.RE
.PP

.PP
Definition at line 30 of file model_plane\&.cpp\&.
.SS "\fBBmodel\fP* model_generate_from_plane_guide (\fBBmodel\fP * guide, double separation, double sigma)"

.PP
Generates a plane model and fits a plane through it\&. 
.PP
\fBParameters\fP
.RS 4
\fI*guide\fP model structure\&. 
.br
\fIseparation\fP separation between components for new model\&. 
.br
\fIsigma\fP smoothness of model\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* new model based on input model\&. 
.PP
.nf
The principal axes of a planar model are calculated and a new plane model
generated with the given separation between components.
The components of the new model are then adjusted to fit the guide model.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 186 of file model_plane\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
