.TH "/Users/bernard/b20/bsoft/include/model_tags.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/model_tags.h \- All STAR and XML file format tags for models\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMMENT\fP   'comment'"
.br
.ti -1c
.RI "#define \fBID\fP   'id'"
.br
.ti -1c
.RI "#define \fBMODEL\fP   'model'"
.br
.ti -1c
.RI "#define \fBMODEL_ID\fP   'model\&.id'"
.br
.ti -1c
.RI "#define \fBMODEL_TYPE\fP   'model\&.type_id'"
.br
.ti -1c
.RI "#define \fBMODEL_HAND\fP   'model\&.hand'"
.br
.ti -1c
.RI "#define \fBMODEL_SYM\fP   'model\&.point_group'"
.br
.ti -1c
.RI "#define \fBMODEL_MAP_FILENAME\fP   'model\&.map_file_name'"
.br
.ti -1c
.RI "#define \fBMODEL_MAP_NUMBER\fP   'model\&.map_number'"
.br
.ti -1c
.RI "#define \fBMODEL_FOM\fP   'model\&.fom'"
.br
.ti -1c
.RI "#define \fBMODEL_SELECT\fP   'model\&.select'"
.br
.ti -1c
.RI "#define \fBCOMPONENT\fP   'component'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_ID\fP   'component\&.id'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_TYPE_ID\fP   'component\&.type_id'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_X\fP   'component\&.x'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_Y\fP   'component\&.y'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_Z\fP   'component\&.z'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_VIEW_X\fP   'component\&.view_x'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_VIEW_Y\fP   'component\&.view_y'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_VIEW_Z\fP   'component\&.view_z'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_VIEW_ANGLE\fP   'component\&.view_angle'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_RADIUS\fP   'component\&.radius'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_RED\fP   'component\&.red'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_GREEN\fP   'component\&.green'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_BLUE\fP   'component\&.blue'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_ALPHA\fP   'component\&.alpha'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_DENSITY\fP   'component\&.density'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_FOM\fP   'component\&.fom'"
.br
.ti -1c
.RI "#define \fBCOMPONENT_SELECT\fP   'component\&.select'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE\fP   'component_type'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_ID\fP   'component_type\&.id'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_FILENAME\fP   'component_type\&.file_name'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_MAP_NUMBER\fP   'component_type\&.map_number'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_NUMBER\fP   'component_type\&.number'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_MASS\fP   'component_type\&.mass'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_FOM\fP   'component_type\&.fom'"
.br
.ti -1c
.RI "#define \fBCOMPTYPE_SELECT\fP   'component_type\&.select'"
.br
.ti -1c
.RI "#define \fBCOMPLINK\fP   'component_link'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_ID\fP   'component_link\&.id'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_1\fP   'component_link\&.component_1'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_2\fP   'component_link\&.component_2'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_ANGLE\fP   'component_link\&.rotation_angle'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_RADIUS\fP   'component_link\&.radius'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_LENGTH\fP   'component_link\&.length'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_RED\fP   'component_link\&.red'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_GREEN\fP   'component_link\&.green'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_BLUE\fP   'component_link\&.blue'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_ALPHA\fP   'component_link\&.alpha'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_FOM\fP   'component_link\&.fom'"
.br
.ti -1c
.RI "#define \fBCOMPLINK_SELECT\fP   'component_link\&.select'"
.br
.ti -1c
.RI "#define \fBLINKTYPE\fP   'link_type'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_ID1\fP   'link_type\&.component_1'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_ID2\fP   'link_type\&.component_2'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_LENGTH\fP   'link_type\&.length'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_DISTANCE\fP   'link_type\&.distance'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_KLENGTH\fP   'link_type\&.Klength'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_KDISTANCE\fP   'link_type\&.Kdistance'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_FOM\fP   'link_type\&.fom'"
.br
.ti -1c
.RI "#define \fBLINKTYPE_SELECT\fP   'link_type\&.select'"
.br
.ti -1c
.RI "#define \fBANGLETYPE\fP   'angle_type'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_ID1\fP   'angle_type\&.component_1'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_ID2\fP   'angle_type\&.component_2'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_ID3\fP   'angle_type\&.component_3'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_ANGLE\fP   'angle_type\&.angle'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_KANGLE\fP   'angle_type\&.Kangle'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_FOM\fP   'angle_type\&.fom'"
.br
.ti -1c
.RI "#define \fBANGLETYPE_SELECT\fP   'angle_type\&.select'"
.br
.in -1c
.SH "Detailed Description"
.PP 
All STAR and XML file format tags for models\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000419 
.PP
Modified: 20210219 
.RE
.PP

.PP
Definition in file \fBmodel_tags\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANGLETYPE   'angle_type'"

.PP
Definition at line 84 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_ANGLE   'angle_type\&.angle'"

.PP
Definition at line 88 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_FOM   'angle_type\&.fom'"

.PP
Definition at line 90 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_ID1   'angle_type\&.component_1'"

.PP
Definition at line 85 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_ID2   'angle_type\&.component_2'"

.PP
Definition at line 86 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_ID3   'angle_type\&.component_3'"

.PP
Definition at line 87 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_KANGLE   'angle_type\&.Kangle'"

.PP
Definition at line 89 of file model_tags\&.h\&.
.SS "#define ANGLETYPE_SELECT   'angle_type\&.select'"

.PP
Definition at line 91 of file model_tags\&.h\&.
.SS "#define COMMENT   'comment'"

.PP
Definition at line 13 of file model_tags\&.h\&.
.SS "#define COMPLINK   'component_link'"

.PP
Definition at line 58 of file model_tags\&.h\&.
.SS "#define COMPLINK_1   'component_link\&.component_1'"

.PP
Definition at line 60 of file model_tags\&.h\&.
.SS "#define COMPLINK_2   'component_link\&.component_2'"

.PP
Definition at line 61 of file model_tags\&.h\&.
.SS "#define COMPLINK_ALPHA   'component_link\&.alpha'"

.PP
Definition at line 68 of file model_tags\&.h\&.
.SS "#define COMPLINK_ANGLE   'component_link\&.rotation_angle'"

.PP
Definition at line 62 of file model_tags\&.h\&.
.SS "#define COMPLINK_BLUE   'component_link\&.blue'"

.PP
Definition at line 67 of file model_tags\&.h\&.
.SS "#define COMPLINK_FOM   'component_link\&.fom'"

.PP
Definition at line 69 of file model_tags\&.h\&.
.SS "#define COMPLINK_GREEN   'component_link\&.green'"

.PP
Definition at line 66 of file model_tags\&.h\&.
.SS "#define COMPLINK_ID   'component_link\&.id'"

.PP
Definition at line 59 of file model_tags\&.h\&.
.SS "#define COMPLINK_LENGTH   'component_link\&.length'"

.PP
Definition at line 64 of file model_tags\&.h\&.
.SS "#define COMPLINK_RADIUS   'component_link\&.radius'"

.PP
Definition at line 63 of file model_tags\&.h\&.
.SS "#define COMPLINK_RED   'component_link\&.red'"

.PP
Definition at line 65 of file model_tags\&.h\&.
.SS "#define COMPLINK_SELECT   'component_link\&.select'"

.PP
Definition at line 70 of file model_tags\&.h\&.
.SS "#define COMPONENT   'component'"

.PP
Definition at line 28 of file model_tags\&.h\&.
.SS "#define COMPONENT_ALPHA   'component\&.alpha'"

.PP
Definition at line 42 of file model_tags\&.h\&.
.SS "#define COMPONENT_BLUE   'component\&.blue'"

.PP
Definition at line 41 of file model_tags\&.h\&.
.SS "#define COMPONENT_DENSITY   'component\&.density'"

.PP
Definition at line 43 of file model_tags\&.h\&.
.SS "#define COMPONENT_FOM   'component\&.fom'"

.PP
Definition at line 44 of file model_tags\&.h\&.
.SS "#define COMPONENT_GREEN   'component\&.green'"

.PP
Definition at line 40 of file model_tags\&.h\&.
.SS "#define COMPONENT_ID   'component\&.id'"

.PP
Definition at line 29 of file model_tags\&.h\&.
.SS "#define COMPONENT_RADIUS   'component\&.radius'"

.PP
Definition at line 38 of file model_tags\&.h\&.
.SS "#define COMPONENT_RED   'component\&.red'"

.PP
Definition at line 39 of file model_tags\&.h\&.
.SS "#define COMPONENT_SELECT   'component\&.select'"

.PP
Definition at line 45 of file model_tags\&.h\&.
.SS "#define COMPONENT_TYPE_ID   'component\&.type_id'"

.PP
Definition at line 30 of file model_tags\&.h\&.
.SS "#define COMPONENT_VIEW_ANGLE   'component\&.view_angle'"

.PP
Definition at line 37 of file model_tags\&.h\&.
.SS "#define COMPONENT_VIEW_X   'component\&.view_x'"

.PP
Definition at line 34 of file model_tags\&.h\&.
.SS "#define COMPONENT_VIEW_Y   'component\&.view_y'"

.PP
Definition at line 35 of file model_tags\&.h\&.
.SS "#define COMPONENT_VIEW_Z   'component\&.view_z'"

.PP
Definition at line 36 of file model_tags\&.h\&.
.SS "#define COMPONENT_X   'component\&.x'"

.PP
Definition at line 31 of file model_tags\&.h\&.
.SS "#define COMPONENT_Y   'component\&.y'"

.PP
Definition at line 32 of file model_tags\&.h\&.
.SS "#define COMPONENT_Z   'component\&.z'"

.PP
Definition at line 33 of file model_tags\&.h\&.
.SS "#define COMPTYPE   'component_type'"

.PP
Definition at line 48 of file model_tags\&.h\&.
.SS "#define COMPTYPE_FILENAME   'component_type\&.file_name'"

.PP
Definition at line 50 of file model_tags\&.h\&.
.SS "#define COMPTYPE_FOM   'component_type\&.fom'"

.PP
Definition at line 54 of file model_tags\&.h\&.
.SS "#define COMPTYPE_ID   'component_type\&.id'"

.PP
Definition at line 49 of file model_tags\&.h\&.
.SS "#define COMPTYPE_MAP_NUMBER   'component_type\&.map_number'"

.PP
Definition at line 51 of file model_tags\&.h\&.
.SS "#define COMPTYPE_MASS   'component_type\&.mass'"

.PP
Definition at line 53 of file model_tags\&.h\&.
.SS "#define COMPTYPE_NUMBER   'component_type\&.number'"

.PP
Definition at line 52 of file model_tags\&.h\&.
.SS "#define COMPTYPE_SELECT   'component_type\&.select'"

.PP
Definition at line 55 of file model_tags\&.h\&.
.SS "#define ID   'id'"

.PP
Definition at line 14 of file model_tags\&.h\&.
.SS "#define LINKTYPE   'link_type'"

.PP
Definition at line 73 of file model_tags\&.h\&.
.SS "#define LINKTYPE_DISTANCE   'link_type\&.distance'"

.PP
Definition at line 77 of file model_tags\&.h\&.
.SS "#define LINKTYPE_FOM   'link_type\&.fom'"

.PP
Definition at line 80 of file model_tags\&.h\&.
.SS "#define LINKTYPE_ID1   'link_type\&.component_1'"

.PP
Definition at line 74 of file model_tags\&.h\&.
.SS "#define LINKTYPE_ID2   'link_type\&.component_2'"

.PP
Definition at line 75 of file model_tags\&.h\&.
.SS "#define LINKTYPE_KDISTANCE   'link_type\&.Kdistance'"

.PP
Definition at line 79 of file model_tags\&.h\&.
.SS "#define LINKTYPE_KLENGTH   'link_type\&.Klength'"

.PP
Definition at line 78 of file model_tags\&.h\&.
.SS "#define LINKTYPE_LENGTH   'link_type\&.length'"

.PP
Definition at line 76 of file model_tags\&.h\&.
.SS "#define LINKTYPE_SELECT   'link_type\&.select'"

.PP
Definition at line 81 of file model_tags\&.h\&.
.SS "#define MODEL   'model'"

.PP
Definition at line 17 of file model_tags\&.h\&.
.SS "#define MODEL_FOM   'model\&.fom'"

.PP
Definition at line 24 of file model_tags\&.h\&.
.SS "#define MODEL_HAND   'model\&.hand'"

.PP
Definition at line 20 of file model_tags\&.h\&.
.SS "#define MODEL_ID   'model\&.id'"

.PP
Definition at line 18 of file model_tags\&.h\&.
.SS "#define MODEL_MAP_FILENAME   'model\&.map_file_name'"

.PP
Definition at line 22 of file model_tags\&.h\&.
.SS "#define MODEL_MAP_NUMBER   'model\&.map_number'"

.PP
Definition at line 23 of file model_tags\&.h\&.
.SS "#define MODEL_SELECT   'model\&.select'"

.PP
Definition at line 25 of file model_tags\&.h\&.
.SS "#define MODEL_SYM   'model\&.point_group'"

.PP
Definition at line 21 of file model_tags\&.h\&.
.SS "#define MODEL_TYPE   'model\&.type_id'"

.PP
Definition at line 19 of file model_tags\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
