.TH "/Users/bernard/b20/bsoft/include/mol_tags.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/mol_tags.h \- All STAR file format tags for molecules and molecular parameters\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCELL_A\fP   'cell\&.length_a'"
.br
.ti -1c
.RI "#define \fBCELL_B\fP   'cell\&.length_b'"
.br
.ti -1c
.RI "#define \fBCELL_C\fP   'cell\&.length_c'"
.br
.ti -1c
.RI "#define \fBCELL_ALPHA\fP   'cell\&.angle_alpha'"
.br
.ti -1c
.RI "#define \fBCELL_BETA\fP   'cell\&.angle_beta'"
.br
.ti -1c
.RI "#define \fBCELL_GAMMA\fP   'cell\&.angle_gamma'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE\fP   'atom_type'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SYMBOL\fP   'atom_type\&.symbol'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_NUMBER\fP   'atom_type\&.atom_number'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_OXIDATION\fP   'atom_type\&.oxidation_number'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_MASS\fP   'atom_type\&.mass'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_RADIUS_BOND\fP   'atom_type\&.radius_bond'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_RADIUS_VDW\fP   'atom_type\&.radius_contact'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_A1\fP   'atom_type\&.scat_Cromer_Mann_a1'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_A2\fP   'atom_type\&.scat_Cromer_Mann_a2'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_A3\fP   'atom_type\&.scat_Cromer_Mann_a3'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_A4\fP   'atom_type\&.scat_Cromer_Mann_a4'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_A5\fP   'atom_type\&.scat_Cromer_Mann_a5'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_B1\fP   'atom_type\&.scat_Cromer_Mann_b1'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_B2\fP   'atom_type\&.scat_Cromer_Mann_b2'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_B3\fP   'atom_type\&.scat_Cromer_Mann_b3'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_B4\fP   'atom_type\&.scat_Cromer_Mann_b4'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_B5\fP   'atom_type\&.scat_Cromer_Mann_b5'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_SCAT_C\fP   'atom_type\&.scat_Cromer_Mann_c'"
.br
.ti -1c
.RI "#define \fBATOM_TYPE_COUNT\fP   'atom_type\&.count'"
.br
.ti -1c
.RI "#define \fBBOND_RULE_SYMBOL\fP   'bond_rule\&.symbol'"
.br
.ti -1c
.RI "#define \fBBOND_RULE_BONDS\fP   'bond_rule\&.bonds'"
.br
.ti -1c
.RI "#define \fBBOND_TYPE_SYMBOL1\fP   'bond_type\&.symbol1'"
.br
.ti -1c
.RI "#define \fBBOND_TYPE_SYMBOL2\fP   'bond_type\&.symbol2'"
.br
.ti -1c
.RI "#define \fBBOND_TYPE_LENGTH\fP   'bond_type\&.length'"
.br
.ti -1c
.RI "#define \fBBOND_TYPE_VDWDIST\fP   'bond_type\&.VdW_distance'"
.br
.ti -1c
.RI "#define \fBANGLE_TYPE_SYMBOL1\fP   'angle_type\&.symbol1'"
.br
.ti -1c
.RI "#define \fBANGLE_TYPE_SYMBOL2\fP   'angle_type\&.symbol2'"
.br
.ti -1c
.RI "#define \fBANGLE_TYPE_SYMBOL3\fP   'angle_type\&.symbol3'"
.br
.ti -1c
.RI "#define \fBANGLE_TYPE_ANGLE\fP   'angle_type\&.angle'"
.br
.ti -1c
.RI "#define \fBATOM_PDB\fP   'atom_site\&.group_PDB'"
.br
.ti -1c
.RI "#define \fBATOM_RESNUMBER\fP   'atom_site\&.label_seq_id'"
.br
.ti -1c
.RI "#define \fBATOM_RESINSERT\fP   'atom_site\&.pdbx_PDB_ins_code'"
.br
.ti -1c
.RI "#define \fBATOM_NUMBER\fP   'atom_site\&.id'"
.br
.ti -1c
.RI "#define \fBATOM_SEGMENT\fP   'atom_site\&.auth_asym_id'"
.br
.ti -1c
.RI "#define \fBATOM_LABEL\fP   'atom_site\&.group_PDB'"
.br
.ti -1c
.RI "#define \fBATOM_SYMBOL\fP   'atom_site\&.type_symbol'"
.br
.ti -1c
.RI "#define \fBATOM_TOPTYPE\fP   'atom_site\&.label_atom_id'"
.br
.ti -1c
.RI "#define \fBATOM_RESIDUE\fP   'atom_site\&.label_comp_id'"
.br
.ti -1c
.RI "#define \fBATOM_CHAIN\fP   'atom_site\&.label_asym_id'"
.br
.ti -1c
.RI "#define \fBATOM_ENTITY\fP   'atom_site\&.label_entity_id'"
.br
.ti -1c
.RI "#define \fBATOM_X\fP   'atom_site\&.Cartn_x'"
.br
.ti -1c
.RI "#define \fBATOM_Y\fP   'atom_site\&.Cartn_y'"
.br
.ti -1c
.RI "#define \fBATOM_Z\fP   'atom_site\&.Cartn_z'"
.br
.ti -1c
.RI "#define \fBATOM_FRACT_X\fP   'atom_site\&.fract_x'"
.br
.ti -1c
.RI "#define \fBATOM_FRACT_Y\fP   'atom_site\&.fract_y'"
.br
.ti -1c
.RI "#define \fBATOM_FRACT_Z\fP   'atom_site\&.fract_z'"
.br
.ti -1c
.RI "#define \fBATOM_OCCUPANCY\fP   'atom_site\&.occupancy'"
.br
.ti -1c
.RI "#define \fBATOM_BFACTOR\fP   'atom_site\&.B_iso_or_equiv'"
.br
.ti -1c
.RI "#define \fBATOM_CHARGE\fP   'atom_site\&.charge'"
.br
.ti -1c
.RI "#define \fBATOM_FOOTNOTE_ID\fP   'atom_site\&.footnote_id'"
.br
.ti -1c
.RI "#define \fBRESPROP_CODON\fP   'residue_property\&.codon'"
.br
.ti -1c
.RI "#define \fBRESPROP_CODE1\fP   'residue_property\&.code1'"
.br
.ti -1c
.RI "#define \fBRESPROP_CODE3\fP   'residue_property\&.code3'"
.br
.ti -1c
.RI "#define \fBRESPROP_MASS\fP   'residue_property\&.mass'"
.br
.ti -1c
.RI "#define \fBRESPROP_VOLUME\fP   'residue_property\&.volume'"
.br
.ti -1c
.RI "#define \fBRESPROP_EXTENSION\fP   'residue_property\&.extension'"
.br
.ti -1c
.RI "#define \fBRESPROP_EXTSTDEV\fP   'residue_property\&.extstdev'"
.br
.ti -1c
.RI "#define \fBRESPROP_HYDROPHOBICITY\fP   'residue_property\&.hydrophobicity'"
.br
.ti -1c
.RI "#define \fBRESPROP_CHARGE\fP   'residue_property\&.charge'"
.br
.ti -1c
.RI "#define \fBRESPROP_H\fP   'residue_property\&.H'"
.br
.ti -1c
.RI "#define \fBRESPROP_C\fP   'residue_property\&.C'"
.br
.ti -1c
.RI "#define \fBRESPROP_N\fP   'residue_property\&.N'"
.br
.ti -1c
.RI "#define \fBRESPROP_O\fP   'residue_property\&.O'"
.br
.ti -1c
.RI "#define \fBRESPROP_S\fP   'residue_property\&.S'"
.br
.ti -1c
.RI "#define \fBRESMATRIX1_CODE1\fP   'residue1_matrix\&.code1'"
.br
.ti -1c
.RI "#define \fBRESMATRIX2_CODE1\fP   'residue2_matrix\&.code1'"
.br
.ti -1c
.RI "#define \fBRESMATRIX_SUBSTITUTION\fP   'residue_matrix\&.substitution'"
.br
.ti -1c
.RI "#define \fBRESCOIL_CODE1\fP   'residue_coil\&.code1'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_A\fP   'residue_coil\&.position_a'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_B\fP   'residue_coil\&.position_b'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_C\fP   'residue_coil\&.position_c'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_D\fP   'residue_coil\&.position_d'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_E\fP   'residue_coil\&.position_e'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_F\fP   'residue_coil\&.position_f'"
.br
.ti -1c
.RI "#define \fBRESCOIL_POS_G\fP   'residue_coil\&.position_g'"
.br
.ti -1c
.RI "#define \fBMOLECULE_NAME\fP   'molecule\&.name'"
.br
.ti -1c
.RI "#define \fBMOLECULE_LENGTH\fP   'molecule\&.length'"
.br
.ti -1c
.RI "#define \fBMOLECULE_SEQUENCE\fP   'molecule\&.sequence'"
.br
.ti -1c
.RI "#define \fBMOLECULE_FILENAME\fP   'molecule\&.file_name'"
.br
.ti -1c
.RI "#define \fBMOLECULE_MAP_FILE\fP   'molecule\&.map_file_name'"
.br
.ti -1c
.RI "#define \fBMOLECULE_MAP_NUMBER\fP   'molecule\&.map_number'"
.br
.ti -1c
.RI "#define \fBMOLECULE_X\fP   'molecule\&.x'"
.br
.ti -1c
.RI "#define \fBMOLECULE_Y\fP   'molecule\&.y'"
.br
.ti -1c
.RI "#define \fBMOLECULE_Z\fP   'molecule\&.z'"
.br
.ti -1c
.RI "#define \fBMOLECULE_VIEW_X\fP   'molecule\&.view_x'"
.br
.ti -1c
.RI "#define \fBMOLECULE_VIEW_Y\fP   'molecule\&.view_y'"
.br
.ti -1c
.RI "#define \fBMOLECULE_VIEW_Z\fP   'molecule\&.view_z'"
.br
.ti -1c
.RI "#define \fBMOLECULE_VIEW_ANGLE\fP   'molecule\&.view_angle'"
.br
.ti -1c
.RI "#define \fBMOLECULE_FOM\fP   'molecule\&.fom'"
.br
.ti -1c
.RI "#define \fBMOLECULE_SELECT\fP   'molecule\&.select'"
.br
.in -1c
.SH "Detailed Description"
.PP 
All STAR file format tags for molecules and molecular parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000419 
.PP
Modified: 20190603 
.RE
.PP

.PP
Definition in file \fBmol_tags\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANGLE_TYPE_ANGLE   'angle_type\&.angle'"

.PP
Definition at line 56 of file mol_tags\&.h\&.
.SS "#define ANGLE_TYPE_SYMBOL1   'angle_type\&.symbol1'"

.PP
Definition at line 53 of file mol_tags\&.h\&.
.SS "#define ANGLE_TYPE_SYMBOL2   'angle_type\&.symbol2'"

.PP
Definition at line 54 of file mol_tags\&.h\&.
.SS "#define ANGLE_TYPE_SYMBOL3   'angle_type\&.symbol3'"

.PP
Definition at line 55 of file mol_tags\&.h\&.
.SS "#define ATOM_BFACTOR   'atom_site\&.B_iso_or_equiv'"

.PP
Definition at line 77 of file mol_tags\&.h\&.
.SS "#define ATOM_CHAIN   'atom_site\&.label_asym_id'"

.PP
Definition at line 68 of file mol_tags\&.h\&.
.SS "#define ATOM_CHARGE   'atom_site\&.charge'"

.PP
Definition at line 78 of file mol_tags\&.h\&.
.SS "#define ATOM_ENTITY   'atom_site\&.label_entity_id'"

.PP
Definition at line 69 of file mol_tags\&.h\&.
.SS "#define ATOM_FOOTNOTE_ID   'atom_site\&.footnote_id'"

.PP
Definition at line 79 of file mol_tags\&.h\&.
.SS "#define ATOM_FRACT_X   'atom_site\&.fract_x'"

.PP
Definition at line 73 of file mol_tags\&.h\&.
.SS "#define ATOM_FRACT_Y   'atom_site\&.fract_y'"

.PP
Definition at line 74 of file mol_tags\&.h\&.
.SS "#define ATOM_FRACT_Z   'atom_site\&.fract_z'"

.PP
Definition at line 75 of file mol_tags\&.h\&.
.SS "#define ATOM_LABEL   'atom_site\&.group_PDB'"

.PP
Definition at line 64 of file mol_tags\&.h\&.
.SS "#define ATOM_NUMBER   'atom_site\&.id'"

.PP
Definition at line 62 of file mol_tags\&.h\&.
.SS "#define ATOM_OCCUPANCY   'atom_site\&.occupancy'"

.PP
Definition at line 76 of file mol_tags\&.h\&.
.SS "#define ATOM_PDB   'atom_site\&.group_PDB'"

.PP
Definition at line 59 of file mol_tags\&.h\&.
.SS "#define ATOM_RESIDUE   'atom_site\&.label_comp_id'"

.PP
Definition at line 67 of file mol_tags\&.h\&.
.SS "#define ATOM_RESINSERT   'atom_site\&.pdbx_PDB_ins_code'"

.PP
Definition at line 61 of file mol_tags\&.h\&.
.SS "#define ATOM_RESNUMBER   'atom_site\&.label_seq_id'"

.PP
Definition at line 60 of file mol_tags\&.h\&.
.SS "#define ATOM_SEGMENT   'atom_site\&.auth_asym_id'"

.PP
Definition at line 63 of file mol_tags\&.h\&.
.SS "#define ATOM_SYMBOL   'atom_site\&.type_symbol'"

.PP
Definition at line 65 of file mol_tags\&.h\&.
.SS "#define ATOM_TOPTYPE   'atom_site\&.label_atom_id'"

.PP
Definition at line 66 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE   'atom_type'"

.PP
Definition at line 22 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_COUNT   'atom_type\&.count'"

.PP
Definition at line 40 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_MASS   'atom_type\&.mass'"

.PP
Definition at line 26 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_NUMBER   'atom_type\&.atom_number'"

.PP
Definition at line 24 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_OXIDATION   'atom_type\&.oxidation_number'"

.PP
Definition at line 25 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_RADIUS_BOND   'atom_type\&.radius_bond'"

.PP
Definition at line 27 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_RADIUS_VDW   'atom_type\&.radius_contact'"

.PP
Definition at line 28 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_A1   'atom_type\&.scat_Cromer_Mann_a1'"

.PP
Definition at line 29 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_A2   'atom_type\&.scat_Cromer_Mann_a2'"

.PP
Definition at line 30 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_A3   'atom_type\&.scat_Cromer_Mann_a3'"

.PP
Definition at line 31 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_A4   'atom_type\&.scat_Cromer_Mann_a4'"

.PP
Definition at line 32 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_A5   'atom_type\&.scat_Cromer_Mann_a5'"

.PP
Definition at line 33 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_B1   'atom_type\&.scat_Cromer_Mann_b1'"

.PP
Definition at line 34 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_B2   'atom_type\&.scat_Cromer_Mann_b2'"

.PP
Definition at line 35 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_B3   'atom_type\&.scat_Cromer_Mann_b3'"

.PP
Definition at line 36 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_B4   'atom_type\&.scat_Cromer_Mann_b4'"

.PP
Definition at line 37 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_B5   'atom_type\&.scat_Cromer_Mann_b5'"

.PP
Definition at line 38 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SCAT_C   'atom_type\&.scat_Cromer_Mann_c'"

.PP
Definition at line 39 of file mol_tags\&.h\&.
.SS "#define ATOM_TYPE_SYMBOL   'atom_type\&.symbol'"

.PP
Definition at line 23 of file mol_tags\&.h\&.
.SS "#define ATOM_X   'atom_site\&.Cartn_x'"

.PP
Definition at line 70 of file mol_tags\&.h\&.
.SS "#define ATOM_Y   'atom_site\&.Cartn_y'"

.PP
Definition at line 71 of file mol_tags\&.h\&.
.SS "#define ATOM_Z   'atom_site\&.Cartn_z'"

.PP
Definition at line 72 of file mol_tags\&.h\&.
.SS "#define BOND_RULE_BONDS   'bond_rule\&.bonds'"

.PP
Definition at line 44 of file mol_tags\&.h\&.
.SS "#define BOND_RULE_SYMBOL   'bond_rule\&.symbol'"

.PP
Definition at line 43 of file mol_tags\&.h\&.
.SS "#define BOND_TYPE_LENGTH   'bond_type\&.length'"

.PP
Definition at line 49 of file mol_tags\&.h\&.
.SS "#define BOND_TYPE_SYMBOL1   'bond_type\&.symbol1'"

.PP
Definition at line 47 of file mol_tags\&.h\&.
.SS "#define BOND_TYPE_SYMBOL2   'bond_type\&.symbol2'"

.PP
Definition at line 48 of file mol_tags\&.h\&.
.SS "#define BOND_TYPE_VDWDIST   'bond_type\&.VdW_distance'"

.PP
Definition at line 50 of file mol_tags\&.h\&.
.SS "#define CELL_A   'cell\&.length_a'"

.PP
Definition at line 14 of file mol_tags\&.h\&.
.SS "#define CELL_ALPHA   'cell\&.angle_alpha'"

.PP
Definition at line 17 of file mol_tags\&.h\&.
.SS "#define CELL_B   'cell\&.length_b'"

.PP
Definition at line 15 of file mol_tags\&.h\&.
.SS "#define CELL_BETA   'cell\&.angle_beta'"

.PP
Definition at line 18 of file mol_tags\&.h\&.
.SS "#define CELL_C   'cell\&.length_c'"

.PP
Definition at line 16 of file mol_tags\&.h\&.
.SS "#define CELL_GAMMA   'cell\&.angle_gamma'"

.PP
Definition at line 19 of file mol_tags\&.h\&.
.SS "#define MOLECULE_FILENAME   'molecule\&.file_name'"

.PP
Definition at line 114 of file mol_tags\&.h\&.
.SS "#define MOLECULE_FOM   'molecule\&.fom'"

.PP
Definition at line 124 of file mol_tags\&.h\&.
.SS "#define MOLECULE_LENGTH   'molecule\&.length'"

.PP
Definition at line 110 of file mol_tags\&.h\&.
.SS "#define MOLECULE_MAP_FILE   'molecule\&.map_file_name'"

.PP
Definition at line 115 of file mol_tags\&.h\&.
.SS "#define MOLECULE_MAP_NUMBER   'molecule\&.map_number'"

.PP
Definition at line 116 of file mol_tags\&.h\&.
.SS "#define MOLECULE_NAME   'molecule\&.name'"

.PP
Definition at line 109 of file mol_tags\&.h\&.
.SS "#define MOLECULE_SELECT   'molecule\&.select'"

.PP
Definition at line 125 of file mol_tags\&.h\&.
.SS "#define MOLECULE_SEQUENCE   'molecule\&.sequence'"

.PP
Definition at line 111 of file mol_tags\&.h\&.
.SS "#define MOLECULE_VIEW_ANGLE   'molecule\&.view_angle'"

.PP
Definition at line 123 of file mol_tags\&.h\&.
.SS "#define MOLECULE_VIEW_X   'molecule\&.view_x'"

.PP
Definition at line 120 of file mol_tags\&.h\&.
.SS "#define MOLECULE_VIEW_Y   'molecule\&.view_y'"

.PP
Definition at line 121 of file mol_tags\&.h\&.
.SS "#define MOLECULE_VIEW_Z   'molecule\&.view_z'"

.PP
Definition at line 122 of file mol_tags\&.h\&.
.SS "#define MOLECULE_X   'molecule\&.x'"

.PP
Definition at line 117 of file mol_tags\&.h\&.
.SS "#define MOLECULE_Y   'molecule\&.y'"

.PP
Definition at line 118 of file mol_tags\&.h\&.
.SS "#define MOLECULE_Z   'molecule\&.z'"

.PP
Definition at line 119 of file mol_tags\&.h\&.
.SS "#define RESCOIL_CODE1   'residue_coil\&.code1'"

.PP
Definition at line 99 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_A   'residue_coil\&.position_a'"

.PP
Definition at line 100 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_B   'residue_coil\&.position_b'"

.PP
Definition at line 101 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_C   'residue_coil\&.position_c'"

.PP
Definition at line 102 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_D   'residue_coil\&.position_d'"

.PP
Definition at line 103 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_E   'residue_coil\&.position_e'"

.PP
Definition at line 104 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_F   'residue_coil\&.position_f'"

.PP
Definition at line 105 of file mol_tags\&.h\&.
.SS "#define RESCOIL_POS_G   'residue_coil\&.position_g'"

.PP
Definition at line 106 of file mol_tags\&.h\&.
.SS "#define RESMATRIX1_CODE1   'residue1_matrix\&.code1'"

.PP
Definition at line 96 of file mol_tags\&.h\&.
.SS "#define RESMATRIX2_CODE1   'residue2_matrix\&.code1'"

.PP
Definition at line 97 of file mol_tags\&.h\&.
.SS "#define RESMATRIX_SUBSTITUTION   'residue_matrix\&.substitution'"

.PP
Definition at line 98 of file mol_tags\&.h\&.
.SS "#define RESPROP_C   'residue_property\&.C'"

.PP
Definition at line 92 of file mol_tags\&.h\&.
.SS "#define RESPROP_CHARGE   'residue_property\&.charge'"

.PP
Definition at line 90 of file mol_tags\&.h\&.
.SS "#define RESPROP_CODE1   'residue_property\&.code1'"

.PP
Definition at line 83 of file mol_tags\&.h\&.
.SS "#define RESPROP_CODE3   'residue_property\&.code3'"

.PP
Definition at line 84 of file mol_tags\&.h\&.
.SS "#define RESPROP_CODON   'residue_property\&.codon'"

.PP
Definition at line 82 of file mol_tags\&.h\&.
.SS "#define RESPROP_EXTENSION   'residue_property\&.extension'"

.PP
Definition at line 87 of file mol_tags\&.h\&.
.SS "#define RESPROP_EXTSTDEV   'residue_property\&.extstdev'"

.PP
Definition at line 88 of file mol_tags\&.h\&.
.SS "#define RESPROP_H   'residue_property\&.H'"

.PP
Definition at line 91 of file mol_tags\&.h\&.
.SS "#define RESPROP_HYDROPHOBICITY   'residue_property\&.hydrophobicity'"

.PP
Definition at line 89 of file mol_tags\&.h\&.
.SS "#define RESPROP_MASS   'residue_property\&.mass'"

.PP
Definition at line 85 of file mol_tags\&.h\&.
.SS "#define RESPROP_N   'residue_property\&.N'"

.PP
Definition at line 93 of file mol_tags\&.h\&.
.SS "#define RESPROP_O   'residue_property\&.O'"

.PP
Definition at line 94 of file mol_tags\&.h\&.
.SS "#define RESPROP_S   'residue_property\&.S'"

.PP
Definition at line 95 of file mol_tags\&.h\&.
.SS "#define RESPROP_VOLUME   'residue_property\&.volume'"

.PP
Definition at line 86 of file mol_tags\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
