.TH "/Users/bernard/b20/bsoft/include/ps_tree.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/ps_tree.h \- Header file for writing a tree into a postcsript file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwtree\&.h'\fP
.br
\fC#include 'ps_plot\&.h'\fP
.br
\fC#include 'Bstring\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBps_draw_tree\fP (\fBBstring\fP &filename, \fBBnode\fP *root, float scale)"
.br
.RI "Draws a tree into a postscript file\&. "
.ti -1c
.RI "int \fBps_draw_node\fP (ofstream *fps, \fBBnode\fP *node, float scale, float x, float y)"
.br
.RI "Draws a tree node into a postscript file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for writing a tree into a postcsript file\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010722 
.PP
Modified: 20120416 
.RE
.PP

.PP
Definition in file \fBps_tree\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int ps_draw_node (ofstream * fps, \fBBnode\fP * node, float scale, float x, float y)"

.PP
Draws a tree node into a postscript file\&. 
.PP
\fBParameters\fP
.RS 4
\fI*fps\fP file pointer\&. 
.br
\fI*node\fP node\&. 
.br
\fIscale\fP scale for branch lengths 
.br
\fIx\fP x-coordinate for the node\&. 
.br
\fIy\fP y-coordinate for the node\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&.
.RE
.PP
Requirements: The tree must be well-formed, i\&.e\&., it must have branch lengths and angles defined\&. 
.PP
Definition at line 63 of file ps_tree\&.cpp\&.
.SS "int ps_draw_tree (\fBBstring\fP & filename, \fBBnode\fP * root, float scale)"

.PP
Draws a tree into a postscript file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP postscript file name\&. 
.br
\fI*root\fP root node\&. 
.br
\fIscale\fP scale for branch lengths\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&.
.RE
.PP
Requirements: The tree must be well-formed, i\&.e\&., it must have branch lengths and angles defined\&. 
.PP
Definition at line 28 of file ps_tree\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
