.TH "/Users/bernard/b20/bsoft/src/radonrecon.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/radonrecon.cpp \- Program to do radon transforms\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mg_processing\&.h'\fP
.br
\fC#include 'rwmg\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'img_radon\&.h'\fP
.br
\fC#include 'symmetry\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program to do radon transforms\&. 


.PP
\fBAuthor\fP
.RS 4
Salvatore Lanzavecchia, Francesca Cantele and Pier Luigi Bellon Dip\&. Chimica Strutturale e Stereochimica Inorganica, Via Venezian 21, 20133 Milano, Italy 
.PP
Bernard Heymann Rm 1515, 50 South Dr\&., NIH, Bethesda, MD, 20892, USA
.RE
.PP
\fBDate\fP
.RS 4
Created: 2003 07 04 
.PP
Modified: 20160728 (BH) 
.RE
.PP

.PP
Definition in file \fBradonrecon\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 50 of file radonrecon\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* use[]"
\fBInitial value:\fP
.PP
.nf
= {
  " ",
  "Usage: radonrecon [options] input\&.star [input\&.star]",
  "---------------------------------------------------",
  "Program to reconstruct a quarter (PI*PI) radon transform from projections\&.",
  "Projections must be square\&.",
  " ",
  "Parameters:",
  "-verbose 7               Verbosity of output",
  "-datatype u              Force writing of a new data type (default output floating point)",
  "-origin 32,32            Projections origin (default center of projections)",
  "-sampling 1\&.5,1\&.5,1\&.5    Sampling (A/pixel; a single value can be given)\&.",
  "-kernel 15,4             Kernel size and power (default 11,2)",
  "-threshold 19\&.4          Threshold for accepting a particle image (default 0)",
  "-symmetry D5             Number of symmetry equivalents (default 1)",
  " ",
  "Output:",
  "-output file\&.star        Output parameter file\&.",
  "-reconstruction rec\&.map  Reconstruction file name\&.",
  "-mask mask\&.map           Binary mask for POCS filter\&.",
  " ",
  NULL
}
.fi
.PP
Definition at line 25 of file radonrecon\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
