.TH "ResInfo" 3 "Mon Apr 12 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBres\fP [4]"
.br
.ti -1c
.RI "double \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file seq_analysis\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double ResInfo::info"

.PP
Definition at line 20 of file seq_analysis\&.cpp\&.
.SS "char ResInfo::res[4]"

.PP
Definition at line 20 of file seq_analysis\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
