.TH "resprop" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resprop
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcode\fP"
.br
.ti -1c
.RI "float \fBmass\fP"
.br
.ti -1c
.RI "float \fBvol\fP"
.br
.ti -1c
.RI "float \fBext\fP"
.br
.ti -1c
.RI "float \fBextsd\fP"
.br
.ti -1c
.RI "float \fBcharge\fP"
.br
.ti -1c
.RI "float \fBhphob\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file rwresprop\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "float resprop::charge"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.
.SS "char resprop::code"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.
.SS "float resprop::ext"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.
.SS "float resprop::extsd"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.
.SS "float resprop::hphob"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.
.SS "float resprop::mass"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.
.SS "float resprop::vol"

.PP
Definition at line 36 of file rwresprop\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
