.TH "RGB< Type >" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB< Type >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Color\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRGB\fP ()"
.br
.ti -1c
.RI "\fBRGB\fP (const \fBRGB\fP &c)"
.br
.ti -1c
.RI "\fBRGB\fP (const double d[3])"
.br
.ti -1c
.RI "\fBRGB\fP (const double rr, const double gg, const double bb)"
.br
.ti -1c
.RI "\fBRGB\fP \fBoperator=\fP (const \fBRGB\fP &c)"
.br
.ti -1c
.RI "\fBRGB\fP \fBoperator\-\fP (const \fBRGB\fP &c)"
.br
.ti -1c
.RI "Type & \fBoperator[]\fP (const unsigned int i)"
.br
.ti -1c
.RI "Type \fBr\fP ()"
.br
.ti -1c
.RI "Type \fBg\fP ()"
.br
.ti -1c
.RI "Type \fBb\fP ()"
.br
.ti -1c
.RI "void \fBred\fP ()"
.br
.ti -1c
.RI "template<typename T2 > \fBRGB\fP \fBoperator=\fP (\fBRGBA\fP< T2 > &c)"
.br
.ti -1c
.RI "template<typename T2 > \fBoperator RGB< T2 >\fP () const"
.br
.ti -1c
.RI "\fBRGB\fP (\fBRGBA\fP< Type > &c)"
.br
.ti -1c
.RI "\fBRGB\fP (\fBCMYK\fP< Type > &cmyk)"
.br
.ti -1c
.RI "\fBRGB\fP (\fBBstring\fP &\fBhex\fP)"
.br
.ti -1c
.RI "\fBBstring\fP \fBhex\fP ()"
.br
.ti -1c
.RI "double \fBaverage\fP ()"
.br
.ti -1c
.RI "double \fBrms\fP ()"
.br
.ti -1c
.RI "void \fBspectrum\fP (double value, double cmin, double cmax)"
.br
.ti -1c
.RI "void \fBphase\fP (double phi, double amp_ratio)"
.br
.ti -1c
.RI "void \fBrandom_color\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Type>
.br
class RGB< Type >"

.PP
Definition at line 24 of file Color\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP ()\fC [inline]\fP"

.PP
Definition at line 28 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP (const \fBRGB\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 29 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP (const double d[3])\fC [inline]\fP"

.PP
Definition at line 30 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP (const double rr, const double gg, const double bb)\fC [inline]\fP"

.PP
Definition at line 31 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP (\fBRGBA\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 56 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP (\fBCMYK\fP< Type > & cmyk)\fC [inline]\fP"

.PP
Definition at line 57 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP< Type >::\fBRGB\fP (\fBBstring\fP & hex)\fC [inline]\fP"

.PP
Definition at line 73 of file Color\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Type > double \fBRGB\fP< Type >::average ()\fC [inline]\fP"

.PP
Definition at line 87 of file Color\&.h\&.
.SS "template<typename Type > Type \fBRGB\fP< Type >::b ()\fC [inline]\fP"

.PP
Definition at line 47 of file Color\&.h\&.
.SS "template<typename Type > Type \fBRGB\fP< Type >::g ()\fC [inline]\fP"

.PP
Definition at line 46 of file Color\&.h\&.
.SS "template<typename Type > \fBBstring\fP \fBRGB\fP< Type >::hex ()\fC [inline]\fP"

.PP
Definition at line 80 of file Color\&.h\&.
.SS "template<typename Type > template<typename T2 > \fBRGB\fP< Type >::operator \fBRGB\fP< T2 > () const\fC [inline]\fP"

.PP
Definition at line 53 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP \fBRGB\fP< Type >::operator\- (const \fBRGB\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 37 of file Color\&.h\&.
.SS "template<typename Type > \fBRGB\fP \fBRGB\fP< Type >::operator= (const \fBRGB\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 33 of file Color\&.h\&.
.SS "template<typename Type > template<typename T2 > \fBRGB\fP \fBRGB\fP< Type >::operator= (\fBRGBA\fP< T2 > & c)\fC [inline]\fP"

.PP
Definition at line 49 of file Color\&.h\&.
.SS "template<typename Type > Type& \fBRGB\fP< Type >::operator[] (const unsigned int i)\fC [inline]\fP"

.PP
Definition at line 41 of file Color\&.h\&.
.SS "template<typename Type > void \fBRGB\fP< Type >::phase (double phi, double amp_ratio)\fC [inline]\fP"

.PP
Definition at line 114 of file Color\&.h\&.
.SS "template<typename Type > Type \fBRGB\fP< Type >::r ()\fC [inline]\fP"

.PP
Definition at line 45 of file Color\&.h\&.
.SS "template<typename Type > void \fBRGB\fP< Type >::random_color ()\fC [inline]\fP"

.PP
Definition at line 140 of file Color\&.h\&.
.SS "template<typename Type > void \fBRGB\fP< Type >::red ()\fC [inline]\fP"

.PP
Definition at line 48 of file Color\&.h\&.
.SS "template<typename Type > double \fBRGB\fP< Type >::rms ()\fC [inline]\fP"

.PP
Definition at line 88 of file Color\&.h\&.
.SS "template<typename Type > void \fBRGB\fP< Type >::spectrum (double value, double cmin, double cmax)\fC [inline]\fP"

.PP
Definition at line 89 of file Color\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
