.TH "RGBA< Type >" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBA< Type >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Color\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRGBA\fP ()"
.br
.ti -1c
.RI "\fBRGBA\fP (const \fBRGBA\fP &c)"
.br
.ti -1c
.RI "\fBRGBA\fP (const double d[4])"
.br
.ti -1c
.RI "\fBRGBA\fP (const double rr, const double gg, const double bb)"
.br
.ti -1c
.RI "\fBRGBA\fP (const double rr, const double gg, const double bb, const double aa)"
.br
.ti -1c
.RI "\fBRGBA\fP \fBoperator=\fP (const \fBRGBA\fP &c)"
.br
.ti -1c
.RI "template<typename T2 > \fBRGBA\fP \fBoperator=\fP (\fBRGB\fP< T2 > &c)"
.br
.ti -1c
.RI "template<typename T2 > \fBoperator RGBA< T2 >\fP () const"
.br
.ti -1c
.RI "\fBRGBA\fP \fBoperator+\fP (const \fBRGBA\fP &c)"
.br
.ti -1c
.RI "\fBRGBA\fP \fBoperator/\fP (const double d)"
.br
.ti -1c
.RI "\fBRGBA\fP (\fBRGB\fP< Type > &c)"
.br
.ti -1c
.RI "\fBRGBA\fP (\fBCMYK\fP< Type > &cmyk)"
.br
.ti -1c
.RI "Type & \fBoperator[]\fP (const unsigned int i)"
.br
.ti -1c
.RI "Type \fBr\fP ()"
.br
.ti -1c
.RI "Type \fBg\fP ()"
.br
.ti -1c
.RI "Type \fBb\fP ()"
.br
.ti -1c
.RI "Type \fBa\fP ()"
.br
.ti -1c
.RI "void \fBred\fP ()"
.br
.ti -1c
.RI "\fBRGBA\fP (\fBBstring\fP &\fBhex\fP)"
.br
.ti -1c
.RI "\fBBstring\fP \fBhex\fP ()"
.br
.ti -1c
.RI "void \fBspectrum\fP (double value, double cmin, double cmax)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Type>
.br
class RGBA< Type >"

.PP
Definition at line 162 of file Color\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP ()\fC [inline]\fP"

.PP
Definition at line 166 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (const \fBRGBA\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 167 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (const double d[4])\fC [inline]\fP"

.PP
Definition at line 168 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (const double rr, const double gg, const double bb)\fC [inline]\fP"

.PP
Definition at line 169 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (const double rr, const double gg, const double bb, const double aa)\fC [inline]\fP"

.PP
Definition at line 171 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (\fBRGB\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 190 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (\fBCMYK\fP< Type > & cmyk)\fC [inline]\fP"

.PP
Definition at line 191 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP< Type >::\fBRGBA\fP (\fBBstring\fP & hex)\fC [inline]\fP"

.PP
Definition at line 205 of file Color\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Type > Type \fBRGBA\fP< Type >::a ()\fC [inline]\fP"

.PP
Definition at line 203 of file Color\&.h\&.
.SS "template<typename Type > Type \fBRGBA\fP< Type >::b ()\fC [inline]\fP"

.PP
Definition at line 202 of file Color\&.h\&.
.SS "template<typename Type > Type \fBRGBA\fP< Type >::g ()\fC [inline]\fP"

.PP
Definition at line 201 of file Color\&.h\&.
.SS "template<typename Type > \fBBstring\fP \fBRGBA\fP< Type >::hex ()\fC [inline]\fP"

.PP
Definition at line 214 of file Color\&.h\&.
.SS "template<typename Type > template<typename T2 > \fBRGBA\fP< Type >::operator \fBRGBA\fP< T2 > () const\fC [inline]\fP"

.PP
Definition at line 181 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP \fBRGBA\fP< Type >::operator+ (const \fBRGBA\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 184 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP \fBRGBA\fP< Type >::operator/ (const double d)\fC [inline]\fP"

.PP
Definition at line 187 of file Color\&.h\&.
.SS "template<typename Type > \fBRGBA\fP \fBRGBA\fP< Type >::operator= (const \fBRGBA\fP< Type > & c)\fC [inline]\fP"

.PP
Definition at line 173 of file Color\&.h\&.
.SS "template<typename Type > template<typename T2 > \fBRGBA\fP \fBRGBA\fP< Type >::operator= (\fBRGB\fP< T2 > & c)\fC [inline]\fP"

.PP
Definition at line 177 of file Color\&.h\&.
.SS "template<typename Type > Type& \fBRGBA\fP< Type >::operator[] (const unsigned int i)\fC [inline]\fP"

.PP
Definition at line 196 of file Color\&.h\&.
.SS "template<typename Type > Type \fBRGBA\fP< Type >::r ()\fC [inline]\fP"

.PP
Definition at line 200 of file Color\&.h\&.
.SS "template<typename Type > void \fBRGBA\fP< Type >::red ()\fC [inline]\fP"

.PP
Definition at line 204 of file Color\&.h\&.
.SS "template<typename Type > void \fBRGBA\fP< Type >::spectrum (double value, double cmin, double cmax)\fC [inline]\fP"

.PP
Definition at line 221 of file Color\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
