.TH "/Users/bernard/b20/bsoft/src/rwimg/rwASCII.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwASCII.cpp \- Functions for reading and writing ASCII files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwASCII\&.h'\fP
.br
\fC#include 'Complex\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadASCII\fP (\fBBimage\fP *p, int readdata)"
.br
.RI "Reading an ASCII or text image format\&. "
.ti -1c
.RI "int \fBwriteASCII\fP (\fBBimage\fP *p)"
.br
.RI "Writing an ASCII or text image format\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing ASCII files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000318 
.PP
Modified: 20120211 
.RE
.PP

.PP
Definition in file \fBrwASCII\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readASCII (\fBBimage\fP * p, int readdata)"

.PP
Reading an ASCII or text image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&.
.RE
.PP
This function reads an ASCII image file with up to five dimensions in the order: c (channels), x, y, z, n (number of images) Default data type is Float Data is given as real (R) or complex (R and I or A and P), and may include an optional FOM (F) Column labels: Images: C X Y Z N R I F Structure factors: H K L A P R I F 
.PP
Definition at line 34 of file rwASCII\&.cpp\&.
.SS "int writeASCII (\fBBimage\fP * p)"

.PP
Writing an ASCII or text image format\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&.
.RE
.PP
This function writes an ascii image file with up to five dimensions in the order: c (channels), x, y, z, n (number of images) Default data type is Float Data is given as real (R) or complex (R and I or A and P), and may include an optional FOM (F) Column labels: Images: C X Y Z N R I F Structure factors: H K L A P R I F 
.PP
Definition at line 279 of file rwASCII\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
