.TH "/Users/bernard/b20/bsoft/src/rwmol/rwEMBL.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwmol/rwEMBL.cpp \- Library routines to read and write EMBL sequence files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwEMBL\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadEMBL\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Reads EMBL format sequence files\&. "
.ti -1c
.RI "int \fBwriteEMBL\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Writes EMBL format sequence files\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write EMBL sequence files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990123 
.PP
Modified: 20210422 
.RE
.PP

.PP
Definition in file \fBrwEMBL\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readEMBL (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Reads EMBL format sequence files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP sequence file name\&. 
.br
\fI*molgroup\fP molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules read (<0 if reading failed)\&. 
.PP
.nf
EMBL format:
ID   AQP1_HUMAN
DE   AQP1_HUMAN, 527 bases, EB1B8D0 checksum.
SQ             527 BP
    ---------- ---------- ---------- ---------- ---------- ----MASEFK

.fi
.PP
 
.RE
.PP

.PP
Definition at line 29 of file rwEMBL\&.cpp\&.
.SS "int writeEMBL (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Writes EMBL format sequence files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP sequence file name\&. 
.br
\fI*molgroup\fP molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules written (<0 if writing failed)\&. 
.RE
.PP

.PP
Definition at line 102 of file rwEMBL\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
