.TH "/Users/bernard/b20/bsoft/src/rwparam/rwgencode.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwparam/rwgencode.cpp \- Library routines to read and write genetic codes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwgencode\&.h'\fP
.br
\fC#include 'star\&.h'\fP
.br
\fC#include 'mol_tags\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBstring\fP \fBread_gencode_star\fP (\fBBstring\fP &propfile)"
.br
.ti -1c
.RI "\fBBstring\fP \fBget_genetic_code\fP (\fBBstring\fP &filename)"
.br
.RI "Gets the genetic code from a parameter file\&. "
.ti -1c
.RI "int \fBwrite_genetic_code\fP (\fBBstring\fP &filename, \fBBstring\fP &gc)"
.br
.RI "Writing genetic code\&. "
.ti -1c
.RI "int \fBindex_from_codon\fP (const char codon[3])"
.br
.RI "Gets the index associated with a specific codon\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write genetic codes\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20030316 
.PP
Modified: 20210328 
.RE
.PP

.PP
Definition in file \fBrwgencode\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBstring\fP get_genetic_code (\fBBstring\fP & filename)"

.PP
Gets the genetic code from a parameter file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name (if empty, use a default file)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBBstring\fP 64 character array of residues (+1 0 termination character)\&. 
.RE
.PP

.PP
Definition at line 26 of file rwgencode\&.cpp\&.
.SS "int index_from_codon (const char codon[3])"

.PP
Gets the index associated with a specific codon\&. 
.PP
\fBParameters\fP
.RS 4
\fI*codon\fP the codon\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int index\&. 
.RE
.PP

.PP
Definition at line 110 of file rwgencode\&.cpp\&.
.SS "\fBBstring\fP read_gencode_star (\fBBstring\fP & propfile)"

.PP
Definition at line 67 of file rwgencode\&.cpp\&.
.SS "int write_genetic_code (\fBBstring\fP & filename, \fBBstring\fP & gc)"

.PP
Writing genetic code\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI&gc\fP 64-byte string with the genetic code\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.RE
.PP

.PP
Definition at line 61 of file rwgencode\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
