.TH "/Users/bernard/b20/bsoft/src/rwimg/rwGOODFORD.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwGOODFORD.cpp \- Functions for reading and writing Peter Goodford's GRID files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwGOODFORD\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadGOODFORD\fP (\fBBimage\fP *p, int readdata)"
.br
.RI "Reading Peter Goodford's GRID map image file format\&. A 3D image format used for electrostatic potential maps\&. Header size: 168 bytes (fixed)\&. File format extensions: \&.pot The data is packed as slices, each slice with a header of size 20 bytes\&. Byte order determination: File type and third dimension values must be less than 256*256\&. Data types: 1 = float\&. "
.ti -1c
.RI "int \fBwriteGOODFORD\fP (\fBBimage\fP *p)"
.br
.RI "Writing Peter Goodford's GRID map image file format\&. A 3D image format used for electrostatic potential maps\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing Peter Goodford's GRID files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000924 
.PP
Modified: 20120321 
.RE
.PP

.PP
Definition in file \fBrwGOODFORD\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readGOODFORD (\fBBimage\fP * p, int readdata)"

.PP
Reading Peter Goodford's GRID map image file format\&. A 3D image format used for electrostatic potential maps\&. Header size: 168 bytes (fixed)\&. File format extensions: \&.pot The data is packed as slices, each slice with a header of size 20 bytes\&. Byte order determination: File type and third dimension values must be less than 256*256\&. Data types: 1 = float\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 29 of file rwGOODFORD\&.cpp\&.
.SS "int writeGOODFORD (\fBBimage\fP * p)"

.PP
Writing Peter Goodford's GRID map image file format\&. A 3D image format used for electrostatic potential maps\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 103 of file rwGOODFORD\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
