.TH "/Users/bernard/b20/bsoft/src/rwmol/rwGROMACS.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwmol/rwGROMACS.cpp \- Library routines to read and write GROMACS coordinate files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwGROMACS\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadGROMACS\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Reads a Gromacs coordinate file\&. "
.ti -1c
.RI "int \fBwriteGROMACS\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Writes a Gromacs coordinate file\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library routines to read and write GROMACS coordinate files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19980822 
.PP
Modified: 20060121 
.RE
.PP

.PP
Definition in file \fBrwGROMACS\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readGROMACS (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Reads a Gromacs coordinate file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP coordinate file name\&. 
.br
\fI*molgroup\fP molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules read (<0 if reading failed)\&. 
.PP
.nf
Gromacs format:
01234567890123456789012345678901234567890123456789012345678901234567890
MD of 2 waters, t= 0.0
    6
    1WATER  OW1    1   0.126   1.624   1.679  0.1227 -0.0580  0.0434
    1WATER  HW2    2   0.190   1.661   1.747  0.8085  0.3191 -0.7791
    1WATER  HW3    3   0.177   1.568   1.613 -0.9045 -2.6469  1.3180

.fi
.PP
 
.RE
.PP

.PP
Definition at line 31 of file rwGROMACS\&.cpp\&.
.SS "int writeGROMACS (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Writes a Gromacs coordinate file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP coordinate file name\&. 
.br
\fI*molgroup\fP molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules written (<0 if writing failed)\&. 
.PP
.nf
Gromacs format:
01234567890123456789012345678901234567890123456789012345678901234567890
MD of 2 waters, t= 0.0
    6
    1WATER  OW1    1   0.126   1.624   1.679  0.1227 -0.0580  0.0434
    1WATER  HW2    2   0.190   1.661   1.747  0.8085  0.3191 -0.7791
    1WATER  HW3    3   0.177   1.568   1.613 -0.9045 -2.6469  1.3180

.fi
.PP
 
.RE
.PP

.PP
Definition at line 143 of file rwGROMACS\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
