.TH "/Users/bernard/b20/bsoft/src/rwimg/rwMIFF.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwMIFF.cpp \- Functions for reading and writing ImageMagick MIFF files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwMIFF\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadMIFF\fP (\fBBimage\fP *p, int readdata, int img_select)"
.br
.RI "Reading an Image Magick map image file format\&. A 2D image format used for X-windows display\&. The header is text of variable size ending in a colon, ':'\&. A binary colour table may follow the header\&. Files can be directly concatenated for a multi-image file\&. File format extensions: \&.miff Byte order determination: none\&. Data types: depth 8 = byte, depth 16 = short\&. "
.ti -1c
.RI "int \fBwriteMIFF\fP (\fBBimage\fP *p)"
.br
.RI "Writing an Image Magick map image file format\&. A 2D image format used for X-windows display\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing ImageMagick MIFF files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990321 
.PP
Modified: 20120211 
.RE
.PP

.PP
Definition in file \fBrwMIFF\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readMIFF (\fBBimage\fP * p, int readdata, int img_select)"

.PP
Reading an Image Magick map image file format\&. A 2D image format used for X-windows display\&. The header is text of variable size ending in a colon, ':'\&. A binary colour table may follow the header\&. Files can be directly concatenated for a multi-image file\&. File format extensions: \&.miff Byte order determination: none\&. Data types: depth 8 = byte, depth 16 = short\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIreaddata\fP flag to activate reading of image data\&. 
.br
\fIimg_select\fP image selection in multi-image file (-1 = all images)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.RE
.PP

.PP
Definition at line 30 of file rwMIFF\&.cpp\&.
.SS "int writeMIFF (\fBBimage\fP * p)"

.PP
Writing an Image Magick map image file format\&. A 2D image format used for X-windows display\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.RE
.PP

.PP
Definition at line 150 of file rwMIFF\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
