.TH "/Users/bernard/b20/bsoft/include/rwmodel_star.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmodel_star.h \- Header file for reading and writing STAR model parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "map< string, int > \fBcomptype_tags\fP ()"
.br
.ti -1c
.RI "map< string, int > \fBlinktype_tags\fP ()"
.br
.ti -1c
.RI "map< string, int > \fBangletype_tags\fP ()"
.br
.ti -1c
.RI "\fBBmodel\fP * \fBread_model_star\fP (\fBBstring\fP *\fBfile_list\fP)"
.br
.RI "Reads STAR model parameters\&. "
.ti -1c
.RI "int \fBwrite_model_star\fP (\fBBstring\fP &filename, \fBBmodel\fP *\fBmodel\fP, int \fBsplit\fP)"
.br
.RI "Writes STAR model parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing STAR model parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20060919 
.PP
Modified: 20210219 
.RE
.PP

.PP
Definition in file \fBrwmodel_star\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "map<string, int> angletype_tags ()"

.PP
Definition at line 49 of file rwmodel_star\&.cpp\&.
.SS "map<string, int> comptype_tags ()"

.PP
Definition at line 21 of file rwmodel_star\&.cpp\&.
.SS "map<string, int> linktype_tags ()"

.PP
Definition at line 34 of file rwmodel_star\&.cpp\&.
.SS "\fBBmodel\fP* read_model_star (\fBBstring\fP * file_list)"

.PP
Reads STAR model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI*file_list\fP list of model parameter file names\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* model parameters\&. 
.RE
.PP

.PP
Definition at line 110 of file rwmodel_star\&.cpp\&.
.SS "int write_model_star (\fBBstring\fP & filename, \fBBmodel\fP * model, int split)"

.PP
Writes STAR model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP model parameter file name\&. 
.br
\fI*model\fP model parameters\&. 
.br
\fIsplit\fP flag to split into data blocks\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int models written\&. 
.RE
.PP

.PP
Definition at line 250 of file rwmodel_star\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
