.TH "/Users/bernard/b20/bsoft/include/rwmodel_mol.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmodel_mol.h \- Header file for reading and writing molecular model parameters\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwmodel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBmodel\fP * \fBread_model_molecule\fP (\fBBstring\fP *\fBfile_list\fP, \fBBstring\fP &paramfile)"
.br
.RI "Reads molecular model parameters\&. "
.ti -1c
.RI "int \fBwrite_model_molecule\fP (\fBBstring\fP &filename, \fBBmodel\fP *\fBmodel\fP)"
.br
.RI "Writes molecular model parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing molecular model parameters\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20060919 
.PP
Modified: 20080408 
.RE
.PP

.PP
Definition in file \fBrwmodel_mol\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBBmodel\fP* read_model_molecule (\fBBstring\fP * file_list, \fBBstring\fP & paramfile)"

.PP
Reads molecular model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI*file_list\fP list of model parameter file names\&. 
.br
\fI&paramfile\fP parameter file\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bmodel* model parameters\&. 
.RE
.PP

.PP
Definition at line 25 of file rwmodel_mol\&.cpp\&.
.SS "int write_model_molecule (\fBBstring\fP & filename, \fBBmodel\fP * model)"

.PP
Writes molecular model parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP model parameter file name\&. 
.br
\fI*model\fP model parameters\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int models written\&. 
.RE
.PP

.PP
Definition at line 107 of file rwmodel_mol\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
