.TH "/Users/bernard/b20/bsoft/include/rwmol_text.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwmol_text.h \- Read and write molecules in plain text\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBread_mol_text\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Reads a molecule group from a text file\&. "
.ti -1c
.RI "int \fBwrite_mol_text\fP (\fBBstring\fP &filename, \fBBmolgroup\fP *molgroup)"
.br
.RI "Writes a molecule group to a text file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Read and write molecules in plain text\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20050419 
.PP
Modified: 20050419 
.RE
.PP

.PP
Definition in file \fBrwmol_text\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int read_mol_text (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Reads a molecule group from a text file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP the file name\&. 
.br
\fI*molgroup\fP the molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules read (<0 if reading failed)\&. 
.RE
.PP

.PP
Definition at line 22 of file rwmol_text\&.cpp\&.
.SS "int write_mol_text (\fBBstring\fP & filename, \fBBmolgroup\fP * molgroup)"

.PP
Writes a molecule group to a text file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP the file name\&. 
.br
\fI*molgroup\fP the molecule group\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int number of molecules written (<0 if writing failed)\&. 
.RE
.PP

.PP
Definition at line 87 of file rwmol_text\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
