.TH "/Users/bernard/b20/bsoft/src/rwimg/rwPNG.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwPNG.cpp \- Functions for reading and writing PNG files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwPNG\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadPNG\fP (\fBBimage\fP *p, int readdata)"
.br
.ti -1c
.RI "int \fBwritePNG\fP (\fBBimage\fP *p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing PNG files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20041223 
.PP
Modified: 20170317 
.RE
.PP

.PP
Definition in file \fBrwPNG\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readPNG (\fBBimage\fP * p, int readdata)"

.PP
Definition at line 373 of file rwPNG\&.cpp\&.
.SS "int writePNG (\fBBimage\fP * p)"

.PP
Definition at line 380 of file rwPNG\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
