.TH "/Users/bernard/b20/bsoft/include/rwRAW.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwRAW.h \- Header file for reading and writing Raw files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadRAW\fP (\fBBimage\fP *p, int img_select)"
.br
.RI "Reading a raw block of data in a file\&. "
.ti -1c
.RI "int \fBwriteRAW\fP (\fBBimage\fP *p)"
.br
.RI "Writing a raw block of data in a file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing Raw files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990724 
.PP
Modified: 20010410 
.PP
.nf
A Raw file is defined as consisting of only a block data with no additional info
Format: Generic customizable 3D image file format

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwRAW\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readRAW (\fBBimage\fP * p, int img_select)"

.PP
Reading a raw block of data in a file\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.br
\fIimg_select\fP image selection in multi-image file (-1 = all images)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. A 5D format for generalized access to data in Bsoft\&. File format extensions: \&.raw and # The special symbol '#' appended to a valid file name is taken to indicate that the file should be interpreted as a raw data block\&. To further specify how the data block should be read, several variable-value pairs can be appended, each pair started with a '#'\&. Variable-value pairs: h=header_size d=data_type x=size_x,size_y,size_z p=page_size_x,page_size_y,page_size_z a=padding_bytes_between_pages s=sampling_x,sampling_y,sampling_z c=number_of_channels n=number_of_images i=image_selected f=transform_type (n=NoTransform, s=Standard, c=Centered, h=Hermitian, q=CentHerm) b=1=swap_bytes v=1=vax_floating_point 
.RE
.PP

.PP
Definition at line 44 of file rwRAW\&.cpp\&.
.SS "int writeRAW (\fBBimage\fP * p)"

.PP
Writing a raw block of data in a file\&. 
.PP
\fBParameters\fP
.RS 4
\fI*p\fP the image structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. A 5D format for generalized access to data in Bsoft\&. 
.RE
.PP

.PP
Definition at line 192 of file rwRAW\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
