.TH "/Users/bernard/b20/bsoft/include/rwresprop.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwresprop.h \- Header file for reading residue property files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Bstring\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBresidue_type\fP"
.br
.ti -1c
.RI "struct \fBBresidue_matrix\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXRES\fP   25"
.br
.ti -1c
.RI "#define \fB_Brestype_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBresidue_type\fP * \fBget_residue_properties\fP (\fBBstring\fP &filename)"
.br
.RI "Reading residue properties from parameter files\&. "
.ti -1c
.RI "int \fBwrite_residue_properties\fP (\fBBstring\fP &filename, \fBBresidue_type\fP *rt)"
.br
.RI "Writing residue properties from a parameter file\&. "
.ti -1c
.RI "\fBBresidue_matrix\fP * \fBget_residue_matrix\fP (\fBBstring\fP &filename)"
.br
.RI "Reading a residue matrix from a file\&. "
.ti -1c
.RI "int \fBresidue_matrix_kill\fP (\fBBresidue_matrix\fP *resmat)"
.br
.RI "Deallocating a residue matrix\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading residue property files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19980822 
.PP
Modified: 20100916 
.RE
.PP

.PP
Definition in file \fBrwresprop\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _Brestype_"

.PP
Definition at line 50 of file rwresprop\&.h\&.
.SS "#define MAXRES   25"

.PP
Definition at line 12 of file rwresprop\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBBresidue_matrix\fP* get_residue_matrix (\fBBstring\fP & filename)"

.PP
Reading a residue matrix from a file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bresidue_matrix* residue matrix property structure, NULL on failure\&. 
.RE
.PP

.PP
Definition at line 164 of file rwresprop\&.cpp\&.
.SS "\fBBresidue_type\fP* get_residue_properties (\fBBstring\fP & filename)"

.PP
Reading residue properties from parameter files\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Bresidue_type* the residue property structure, NULL on failure\&. 
.RE
.PP

.PP
Definition at line 99 of file rwresprop\&.cpp\&.
.SS "int residue_matrix_kill (\fBBresidue_matrix\fP * resmat)"

.PP
Deallocating a residue matrix\&. 
.PP
\fBParameters\fP
.RS 4
\fI*resmat\fP the residue matrix property structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0\&. 
.RE
.PP

.PP
Definition at line 208 of file rwresprop\&.cpp\&.
.SS "int write_residue_properties (\fBBstring\fP & filename, \fBBresidue_type\fP * rt)"

.PP
Writing residue properties from a parameter file\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI*rt\fP the residue property structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 152 of file rwresprop\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
