.TH "/Users/bernard/b20/bsoft/include/rwSER.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwSER.h \- Header file for reading and writing FEI Ser files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwimg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadSER\fP (\fBBimage\fP *p, int readdata)"
.br
.ti -1c
.RI "int \fBwriteSER\fP (\fBBimage\fP *p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing FEI Ser files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20150130 
.PP
Modified: 20150204 
.PP
.nf
Format: 1D and 2D spectral and image format for electron microscopy.

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBrwSER\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readSER (\fBBimage\fP * p, int readdata)"

.PP
Definition at line 32 of file rwSER\&.cpp\&.
.SS "int writeSER (\fBBimage\fP * p)"

.PP
Definition at line 108 of file rwSER\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
