.TH "/Users/bernard/b20/bsoft/src/rwimg/rwSER.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwSER.cpp \- Reading FEI SER files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include 'rwSER\&.h'\fP
.br
\fC#include 'file_util\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBread_field\fP (ifstream *fimg, char *p, size_t n)"
.br
.ti -1c
.RI "int \fBreadSER\fP (\fBBimage\fP *p, int readdata)"
.br
.ti -1c
.RI "int \fBwriteSER\fP (\fBBimage\fP *p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reading FEI SER files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20150130 
.PP
Modified: 20150630 
.RE
.PP

.PP
Definition in file \fBrwSER\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int read_field (ifstream * fimg, char * p, size_t n)"

.PP
Definition at line 18 of file rwSER\&.cpp\&.
.SS "int readSER (\fBBimage\fP * p, int readdata)"

.PP
Definition at line 32 of file rwSER\&.cpp\&.
.SS "int writeSER (\fBBimage\fP * p)"

.PP
Definition at line 108 of file rwSER\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
