.TH "/Users/bernard/b20/bsoft/include/rwsymop.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/rwsymop.h \- Header file for reading and writing symmetry operators\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'symmetry\&.h'\fP
.br
\fC#include 'rwimg\&.h'\fP
.br
\fC#include 'View\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float * \fBread_symat\fP (\fBBstring\fP &filename, int spacegroup, int &nsym)"
.br
.RI "Reading crystallographic symmetry operators\&. "
.ti -1c
.RI "char * \fBread_symop\fP (\fBBstring\fP &filename, int spacegroup, int &nsym)"
.br
.RI "Reading crystallographic symmetry operators\&. "
.ti -1c
.RI "int \fBwrite_symat\fP (\fBBstring\fP &filename, int spacegroup)"
.br
.RI "Writing crystallographic symmetry operators\&. "
.ti -1c
.RI "int \fBwrite_pointgroup\fP (\fBBstring\fP &filename, \fBBstring\fP &symmetry_string, \fBView\fP ref_view)"
.br
.RI "Writing point group symmetry operators\&. "
.ti -1c
.RI "int \fBwrite_pointgroup\fP (\fBBstring\fP &filename, \fBBsymmetry\fP &sym, \fBView\fP ref_view)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for reading and writing symmetry operators\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990509 
.PP
Modified: 20070621 
.RE
.PP

.PP
Definition in file \fBrwsymop\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "float* read_symat (\fBBstring\fP & filename, int spacegroup, int & nsym)"

.PP
Reading crystallographic symmetry operators\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fIspacegroup\fP crystal space group number\&. 
.br
\fI&nsym\fP number of symmetry operators\&. 
.RE
.PP
\fBReturns\fP
.RS 4
float* set of 12-value symmetry matrices\&. 
.PP
.nf
The symmetry operators are encoded as a set of matrices.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 35 of file rwsymop\&.cpp\&.
.SS "char* read_symop (\fBBstring\fP & symopfile, int spacegroup, int & nsym)"

.PP
Reading crystallographic symmetry operators\&. 
.PP
\fBParameters\fP
.RS 4
\fI&symopfile\fP file name\&. 
.br
\fIspacegroup\fP crystal space group number\&. 
.br
\fI&nsym\fP number of symmetry operators\&. 
.RE
.PP
\fBReturns\fP
.RS 4
char* set of 12-value symmetry matrices\&. 
.PP
.nf
The symmetry operators are encoded as 80 character lines.

.fi
.PP
 
.RE
.PP

.PP
Definition at line 60 of file rwsymop\&.cpp\&.
.SS "int write_pointgroup (\fBBstring\fP & filename, \fBBstring\fP & symmetry_string, \fBView\fP ref_view)"

.PP
Writing point group symmetry operators\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fI&symmetry_string\fP symmetry string\&. 
.br
\fIref_view\fP reference view\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 122 of file rwsymop\&.cpp\&.
.SS "int write_pointgroup (\fBBstring\fP & filename, \fBBsymmetry\fP & sym, \fBView\fP ref_view)"

.PP
Definition at line 131 of file rwsymop\&.cpp\&.
.SS "int write_symat (\fBBstring\fP & filename, int spacegroup)"

.PP
Writing crystallographic symmetry operators\&. 
.PP
\fBParameters\fP
.RS 4
\fI&filename\fP file name\&. 
.br
\fIspacegroup\fP crystal space group number\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int error code (<0 means failure)\&. 
.RE
.PP

.PP
Definition at line 99 of file rwsymop\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
