.TH "/Users/bernard/b20/bsoft/src/rwimg/rwTIFF.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwimg/rwTIFF.cpp \- Functions for reading and writing TIFF files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'rwTIFF\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadTIFF\fP (\fBBimage\fP *p, int readdata, int img_select)"
.br
.ti -1c
.RI "int \fBwriteTIFF\fP (\fBBimage\fP *p, int istiled)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for reading and writing TIFF files\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 19990509 
.PP
Modified: 20210615 
.RE
.PP

.PP
Definition in file \fBrwTIFF\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readTIFF (\fBBimage\fP * p, int readdata, int img_select)"

.PP
Definition at line 853 of file rwTIFF\&.cpp\&.
.SS "int writeTIFF (\fBBimage\fP * p, int istiled)"

.PP
Definition at line 860 of file rwTIFF\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
