.TH "/Users/bernard/b20/bsoft/src/rwparam/rwxml.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/rwparam/rwxml.cpp \- Reads to and writes from XML structures\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Reads to and writes from XML structures\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20050920 
.PP
Modified: 20210615 
.RE
.PP

.PP
Definition in file \fBrwxml\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
