.TH "SERIhead" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SERIhead
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBtilt\fP"
.br
.ti -1c
.RI "short \fBstageX\fP"
.br
.ti -1c
.RI "short \fBstageY\fP"
.br
.ti -1c
.RI "short \fBmag\fP"
.br
.ti -1c
.RI "short \fBintensity\fP"
.br
.ti -1c
.RI "short \fBdose1\fP"
.br
.ti -1c
.RI "short \fBdose2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file rwMRC\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "short SERIhead::dose1"

.PP
Definition at line 27 of file rwMRC\&.cpp\&.
.SS "short SERIhead::dose2"

.PP
Definition at line 28 of file rwMRC\&.cpp\&.
.SS "short SERIhead::intensity"

.PP
Definition at line 26 of file rwMRC\&.cpp\&.
.SS "short SERIhead::mag"

.PP
Definition at line 25 of file rwMRC\&.cpp\&.
.SS "short SERIhead::stageX"

.PP
Definition at line 23 of file rwMRC\&.cpp\&.
.SS "short SERIhead::stageY"

.PP
Definition at line 24 of file rwMRC\&.cpp\&.
.SS "short SERIhead::tilt"

.PP
Definition at line 22 of file rwMRC\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
