.TH "/Users/bernard/b20/bsoft/src/util/simplex.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/util/simplex.cpp \- Nelder and Mead downhill simplex method for generalized parameter fitting\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'simplex\&.h'\fP
.br
\fC#include 'random_numbers\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nelder and Mead downhill simplex method for generalized parameter fitting\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20000426 
.PP
Modified: 20210729 
.PP
.nf
Adapted from Numerical Recipes, 2nd edition, Press et al. 1992

.fi
.PP
 
.RE
.PP

.PP
Definition in file \fBsimplex\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
