.TH "/Users/bernard/b20/bsoft/tcltk/tcltk_bxtal.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/tcltk_bxtal.h
.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br
\fC#include 'mg_processing\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdo_unitcell_vectors\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBdo_spot\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Tcl_Obj* do_spot (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 68 of file tcltk_bxtal\&.cpp\&.
.SS "int do_unitcell_vectors (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
