.TH "/Users/bernard/b20/bsoft/tcltk/tcltk_bxtal.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/tcltk/tcltk_bxtal.cpp \- A shared object to manage micrograph parameter files in TCL/Tk\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <tk\&.h>\fP
.br
\fC#include 'tcltk_bxtal\&.h'\fP
.br
\fC#include 'mg_xtal\&.h'\fP
.br
\fC#include 'linked_list\&.h'\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Tcl_Obj * \fBspot_count\fP (\fBBmicrograph\fP *mg)"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_ids\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_reindex\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_location\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_fom\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_select\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_move\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_create\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_delete\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_unitcell_vectors\fP (\fBBmicrograph\fP *mg, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_generate\fP (\fBBmicrograph\fP *mg, \fBBimage\fP *p, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBspot_mask\fP (\fBBmicrograph\fP *mg, \fBBimage\fP *p, int objc, Tcl_Obj *CONST objv[])"
.br
.ti -1c
.RI "Tcl_Obj * \fBdo_spot\fP (\fBBproject\fP *\fBproject\fP, int objc, Tcl_Obj *CONST objv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "\fBBimage\fP * \fBimglist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A shared object to manage micrograph parameter files in TCL/Tk\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20030813 
.PP
Modified: 20181030 
.RE
.PP

.PP
Definition in file \fBtcltk_bxtal\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "Tcl_Obj* do_spot (\fBBproject\fP * project, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 68 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_count (\fBBmicrograph\fP * mg)"

.PP
Definition at line 154 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_create (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 348 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_delete (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 384 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_fom (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 249 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_generate (\fBBmicrograph\fP * mg, \fBBimage\fP * p, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 428 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_ids (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 169 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_location (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 222 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_mask (\fBBmicrograph\fP * mg, \fBBimage\fP * p, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 446 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_move (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 314 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_reindex (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 189 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_select (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 273 of file tcltk_bxtal\&.cpp\&.
.SS "Tcl_Obj * spot_unitcell_vectors (\fBBmicrograph\fP * mg, int objc, Tcl_Obj *CONST objv[])"

.PP
Definition at line 419 of file tcltk_bxtal\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBBimage\fP* imglist\fC [extern]\fP"

.PP
Definition at line 32 of file bshow\&.cpp\&.
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
