.TH "/Users/bernard/b20/bsoft/src/util/timer.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/util/timer.cpp \- Utilities for timing functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include 'timer\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgetwalltime\fP ()"
.br
.RI "Returns the current time\&. "
.ti -1c
.RI "double \fBgetcputime\fP ()"
.br
.RI "Returns the clock time\&. "
.ti -1c
.RI "double \fBtimer_start\fP ()"
.br
.RI "Starts timer and prints the time\&. "
.ti -1c
.RI "double \fBtimer_report\fP (double lasttime)"
.br
.RI "Reports the time elapsed since a given time\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utilities for timing functions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010316 
.PP
Modified: 20100726 
.RE
.PP

.PP
Definition in file \fBtimer\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "double getcputime ()"

.PP
Returns the clock time\&. 
.PP
.nf
The time format is in clock seconds since the start of the process.

.fi
.PP
 
.PP
\fBParameters\fP
.RS 4
\fI\&.\fP 
.RE
.PP
\fBReturns\fP
.RS 4
double the clock time in seconds\&. 
.RE
.PP

.PP
Definition at line 49 of file timer\&.cpp\&.
.SS "double getwalltime ()"

.PP
Returns the current time\&. 
.PP
\fBReturns\fP
.RS 4
double the current time in seconds\&.
.RE
.PP
The time format is in seconds since Jan\&. 1, 1970, including microseconds\&. 
.PP
Definition at line 26 of file timer\&.cpp\&.
.SS "double timer_report (double lasttime)"

.PP
Reports the time elapsed since a given time\&. 
.PP
\fBParameters\fP
.RS 4
\fIlasttime\fP the given initial time\&. 
.RE
.PP
\fBReturns\fP
.RS 4
double the current time\&. 
.RE
.PP

.PP
Definition at line 76 of file timer\&.cpp\&.
.SS "double timer_start ()"

.PP
Starts timer and prints the time\&. 
.PP
\fBParameters\fP
.RS 4
\fI\&.\fP 
.RE
.PP
\fBReturns\fP
.RS 4
double the current time\&. 
.RE
.PP

.PP
Definition at line 61 of file timer\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
