.TH "/Users/bernard/b20/bsoft/src/util/UnitCell.cpp" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/src/util/UnitCell.cpp \- Unit cell functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'UnitCell\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Unit cell functions\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20010420 
.PP
Modified: 20150111 
.RE
.PP

.PP
Definition in file \fBUnitCell\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int verbose\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
