.TH "/Users/bernard/b20/bsoft/include/versions.h" 3 "Wed Sep 1 2021" "Version 2.1.0" "Bsoft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/bernard/b20/bsoft/include/versions.h \- Library functions to encode versions of all included packages\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'fft\&.h'\fP
.br
\fC#include 'tiffvers\&.h'\fP
.br
\fC#include 'jversion\&.h'\fP
.br
\fC#include 'png\&.h'\fP
.br
\fC#include <tk\&.h>\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_VERSIONS_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshow_library_versions\fP ()"
.br
.RI "Displaying library versions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Library functions to encode versions of all included packages\&. 


.PP
\fBAuthor\fP
.RS 4
Bernard Heymann 
.RE
.PP
\fBDate\fP
.RS 4
Created: 20200610 
.PP
Modified: 20200610 
.RE
.PP

.PP
Definition in file \fBversions\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _VERSIONS_"

.PP
Definition at line 35 of file versions\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int show_library_versions ()"

.PP
Displaying library versions\&. 
.PP
\fBReturns\fP
.RS 4
int 0 
.RE
.PP

.PP
Definition at line 22 of file versions\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bsoft from the source code\&.
