#!/usr/bin/env sh

# Script to create the brun link
# Bernard Heymann
# 20170511

BSOFT="/usr/local/bsoft"

cd /Applications/Brun.app/Contents/Resources/Scripts/

rm -f AppMain.tcl

ln -s $BSOFT/tcltk/brun AppMain.tcl

exit 0

